# generated by datamodel-codegen:
#   filename:  model/mixins/spin_polarization.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class SpinPolarization(Enum):
    collinear = "collinear"
    non_collinear = "non-collinear"


class SpinPolarizationMixin(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    spinPolarization: Optional[SpinPolarization] = None
