# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.91.2-v202512300114-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class TableDefinitionPreviewOutputV1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'column_definitions': 'list[ColumnDefinitionOutputV1]',
        'compute_results': 'dict(str, list[RowRulesResultV1])',
        'table': 'MaterializedTableV1'
    }

    attribute_map = {
        'column_definitions': 'columnDefinitions',
        'compute_results': 'computeResults',
        'table': 'table'
    }

    def __init__(self, column_definitions=None, compute_results=None, table=None):
        """
        TableDefinitionPreviewOutputV1 - a model defined in Swagger
        """

        self._column_definitions = None
        self._compute_results = None
        self._table = None

        if column_definitions is not None:
          self.column_definitions = column_definitions
        if compute_results is not None:
          self.compute_results = compute_results
        if table is not None:
          self.table = table

    @property
    def column_definitions(self):
        """
        Gets the column_definitions of this TableDefinitionPreviewOutputV1.
        All of the updated column definitions, including those created from the preview.

        :return: The column_definitions of this TableDefinitionPreviewOutputV1.
        :rtype: list[ColumnDefinitionOutputV1]
        """
        return self._column_definitions

    @column_definitions.setter
    def column_definitions(self, column_definitions):
        """
        Sets the column_definitions of this TableDefinitionPreviewOutputV1.
        All of the updated column definitions, including those created from the preview.

        :param column_definitions: The column_definitions of this TableDefinitionPreviewOutputV1.
        :type: list[ColumnDefinitionOutputV1]
        """
        if column_definitions is None:
            raise ValueError("Invalid value for `column_definitions`, must not be `None`")

        self._column_definitions = column_definitions

    @property
    def compute_results(self):
        """
        Gets the compute_results of this TableDefinitionPreviewOutputV1.
        The compute results for this table definition

        :return: The compute_results of this TableDefinitionPreviewOutputV1.
        :rtype: dict(str, list[RowRulesResultV1])
        """
        return self._compute_results

    @compute_results.setter
    def compute_results(self, compute_results):
        """
        Sets the compute_results of this TableDefinitionPreviewOutputV1.
        The compute results for this table definition

        :param compute_results: The compute_results of this TableDefinitionPreviewOutputV1.
        :type: dict(str, list[RowRulesResultV1])
        """
        if compute_results is None:
            raise ValueError("Invalid value for `compute_results`, must not be `None`")

        self._compute_results = compute_results

    @property
    def table(self):
        """
        Gets the table of this TableDefinitionPreviewOutputV1.

        :return: The table of this TableDefinitionPreviewOutputV1.
        :rtype: MaterializedTableV1
        """
        return self._table

    @table.setter
    def table(self, table):
        """
        Sets the table of this TableDefinitionPreviewOutputV1.

        :param table: The table of this TableDefinitionPreviewOutputV1.
        :type: MaterializedTableV1
        """
        if table is None:
            raise ValueError("Invalid value for `table`, must not be `None`")

        self._table = table

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TableDefinitionPreviewOutputV1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
