from amsdal_data.test_utils.constants import PG_TEST_HOST as PG_TEST_HOST, PG_TEST_PASSWORD as PG_TEST_PASSWORD, PG_TEST_PORT as PG_TEST_PORT, PG_TEST_USER as PG_TEST_USER

def create_postgres_database(database: str) -> None: ...
def drop_postgres_database(database: str) -> None: ...
def create_postgres_extension(database: str, extension: str) -> None: ...
