from flask import Blueprint, Flask

blueprint: Blueprint

def create_communities_api_blueprint(app: Flask) -> Blueprint: ...
def create_members_api_bp_from_app(app: Flask) -> Blueprint: ...
def create_subcommunities_api_blueprint(app: Flask) -> Blueprint: ...
