10 REM ====================================
20 REM    Time Warp Classic - Examples Menu
30 REM ====================================
40 CLS
50 PRINT "╔════════════════════════════════════════╗"
60 PRINT "║  TIME WARP CLASSIC - EXAMPLE PROGRAMS  ║"
70 PRINT "╚════════════════════════════════════════╝"
80 PRINT ""
90 PRINT "Available examples:"
100 PRINT ""
110 PRINT "1. BASIC     - hello_basic.bas"
120 PRINT "             Classic BASIC with loops & graphics"
130 PRINT ""
140 PRINT "2. Logo      - spiral_logo.logo"
150 PRINT "             Colorful turtle graphics spiral"
160 PRINT ""
170 PRINT "3. PILOT     - quiz_pilot.pilot"
180 PRINT "             Interactive educational quiz"
190 PRINT ""
200 PRINT "4. Pascal    - hello_pascal.pas"
210 PRINT "             Structured programming demo"
220 PRINT ""
230 PRINT "5. Prolog    - facts_prolog.pl"
240 PRINT "             Logic programming with facts & rules"
250 PRINT ""
260 PRINT "6. Forth     - stack_forth.fth"
270 PRINT "             Stack-based RPN programming"
280 PRINT ""
290 PRINT "7. Perl      - patterns_perl.pl"
300 PRINT "             Text processing & regex"
310 PRINT ""
320 PRINT "8. Python    - modern_python.py"
330 PRINT "             Modern Python features"
340 PRINT ""
350 PRINT "9. JavaScript - interactive_javascript.js"
360 PRINT "              Modern web programming"
370 PRINT ""
380 PRINT "════════════════════════════════════════"
390 PRINT ""
400 PRINT "To load an example:"
410 PRINT "  File → Open → examples → [choose file]"
420 PRINT ""
430 PRINT "Or use Program menu:"
440 PRINT "  Program → Load Example → [choose language]"
450 PRINT ""
460 PRINT "See examples/README.md for full documentation"
470 END
