# coding: utf-8

"""
    Red Rover API

    Access Red Rover data via this REST API for Organizations that have granted you access.  # Authentication The API is protected by HTTP Basic Authentication.   Each application that connects to the API has a unique username and password that it must supply with every request.  This value needs to be supplied as an HTTP Header: `Authorization=BASIC [hash]`. The value of [hash] is the string username:password base64 encoded.  Endpoints marked for Basic Auth can be used with the Basic Auth username and password that you have been assigned.  # API Information ## Api Key Each Red Rover organization that has authorized your application has a unique API Key for your application.  To retrieve the API Key, you can use the Organization endpoint (`api/v1/organization`) which returns an ApiKey uniquely used for each Organization.  You must supply this as an HTTP Header when accessing that organization: `apiKey=[apiKey]`. The domains that require this `ApiKey` header are labeled as 'Requires an ApiKey'.  ## Identifier Where an `Identifier` can be specified in the route, you may either supply the Red Rover Id of the object (numeric) or the External Id (alpha-numeric). When specifying an External Id, you will need to prepend the External Id with the pipe character`|` (e.g. `|ABC123`). Please note that this is only the case when the External Id is within the route. If the External Id is contained within the body of the request, do not append the pipe character.  ## Rate Limiting Requests are rate limited at a default rate of 100 requests per minute  ## Transaction Id Each request can be supplied with a `TransactionId` GUID which will be logged with the request. The `Transaction Id` can be supplied as an HTTP Header: `TransactionId=[transactionId]`. If no `Transaction Id` is supplied, one will be generated for you. Please use a distinct TransactionId for each request.

    The version of the OpenAPI document: v1
    Contact: integrations@redroverk12.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from redrover_api.models.vacancy_detail_response import VacancyDetailResponse

class TestVacancyDetailResponse(unittest.TestCase):
    """VacancyDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VacancyDetailResponse:
        """Test VacancyDetailResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VacancyDetailResponse`
        """
        model = VacancyDetailResponse()
        if include_optional:
            return VacancyDetailResponse(
                id = 56,
                admin_only_notes = '',
                assignment_id = 56,
                substitute = redrover_api.models.user.User(
                    id = 56, 
                    external_id = '', 
                    secondary_identifier = '', 
                    first_name = '', 
                    middle_name = '', 
                    last_name = '', 
                    source_organization = redrover_api.models.simple_class.SimpleClass(
                        name = '', 
                        external_id = '', 
                        id = 56, ), ),
                external_assignment_number = '',
                assignment_is_long_term = True,
                assignment_notes = '',
                location = redrover_api.models.simple_class.SimpleClass(
                    code = '', 
                    name = '', 
                    external_id = '', 
                    id = 56, ),
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                actual_duration_minutes = 56,
                accounting_codes = [
                    redrover_api.models.accounting_code_allocation.AccountingCodeAllocation(
                        accounting_code = redrover_api.models.accounting_code_light.AccountingCodeLight(
                            code = '', 
                            name = '', 
                            external_id = '', 
                            id = 56, ), 
                        allocation = 1.337, )
                    ],
                pay_duration = 1.337,
                pay_unit = '',
                pay_code = redrover_api.models.pay_code.PayCode(
                    code = '', 
                    hourly_rate = 1.337, 
                    unit_rate = 1.337, 
                    half_day_rate = 1.337, 
                    full_day_rate = 1.337, 
                    valid_until_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    external_id = '', 
                    id = 56, ),
                vacancy_reason = redrover_api.models.simple_class.SimpleClass(
                    name = '', 
                    external_id = '', 
                    id = 56, ),
                verified = True,
                verified_at_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verify_comment = '',
                verified_by = redrover_api.models.simple_class.SimpleClass(
                    name = '', 
                    external_id = '', 
                    id = 56, ),
                approval_status = '',
                approval_status_id = 56,
                needs_replacement = True
            )
        else:
            return VacancyDetailResponse(
        )
        """

    def testVacancyDetailResponse(self):
        """Test VacancyDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
