
import subprocess
import pathlib
import os
import argparse
import pysam
import multiprocessing as mp
import pathlib
from tqdm import tqdm


def extract_name_from_fastx(fpath):
    names = set()
    with pysam.FastxFile(filename=fpath) as fastx_file:
        for record in fastx_file:
            name = record.name
            smc_name = name.rsplit("_", maxsplit=2)[0]
            names.add(smc_name)

    return names


def extract_channel_id_from_smc_name(smc_names):
    channel_ids = set()
    for name in smc_names:
        id = int(name.split("/")[1])
        channel_ids.add(id)
    return channel_ids


def asts_alignment(query_bam: str, target_bam: str, np_thr: int, rq_thr: float):
    o_dir = os.path.dirname(target_bam)
    o_name = "{}-TO-{}.align".format(pathlib.Path(query_bam).stem,
                                     pathlib.Path(target_bam).stem)
    o_prefix = f"{o_dir}/{o_name}"

    o_name = f"{o_prefix}.bam"

    if os.path.exists(o_name):
        return o_name

    cmd = f"asts -q {query_bam} -t {target_bam} -p {o_prefix} --np-range {np_thr}:10000000 --rq-range {rq_thr}:1.1"
    subprocess.check_call(cmd, shell=True)
    return o_name


def filter_bam(bam_path: str, channel_ids, infix="subset"):
    p = pathlib.Path(bam_path)
    stem = p.stem
    parent = p.parent
    tmp_bam_path = parent.joinpath(f"{stem}.{infix}.bam")

    with pysam.AlignmentFile(bam_path, mode="rb", check_sq=False, threads=mp.cpu_count() // 2) as bam_file:
        with pysam.AlignmentFile(str(tmp_bam_path), mode="wb", check_sq=False, threads=mp.cpu_count() // 2, header=bam_file.header) as bam_out:
            for record in tqdm(bam_file.fetch(until_eof=True), desc=f"{bam_path} -> {str(tmp_bam_path)}"):
                ch = int(record.get_tag("ch"))
                if ch in channel_ids:
                    bam_out.write(record)

    return str(tmp_bam_path)


def main():
    """

    docker run -it -v/data1:/data1 192.168.3.38:5000/algo/adacus:smc5.5.0_adapter_demux0.0.4_barcode_remover1.0.3_smicing0.4.4_bmi_0.1.4 \
        adapter_demux \
            --input_file ??_called.bam \
            --pattern /data1/adapter_bcs/Adapters-10.all.fasta \
            --output_file ??.bam \
            --initial_pattern /data1/adapter_bcs/short/Adapters-10.all-short.fasta  \
            --save_adapter \
            --common_adapter_file /data1/adapter_bcs/A-Common.fasta

    1. extract Q30 channels from fwd_rev.bam(--byStrand=True) & dump them into a file
    2. dump Q30 channels from origin.bam(--byStrand=False)
    3. seperate Q30 channels in fwd_rev.bam into fwd.bam & rev.bam
    4. alignment
        1. align fwd_rev.q30.bam to origin.q30.bam
        2. align sbr.bam to fwd.q30.bam and and rev.q30.bam
    5. using pileup to analysis result    
    """
    # parser = argparse.ArgumentParser()
    # parser.add_argument("--smc-bam", type=str, required=True,
    #                     dest="smc_bam", help="byStrand=False bam file")
    # parser.add_argument("--sbr-bam", type=str, required=True,
    #                     dest="sbr_bam", help="subreads bam file")
    # parser.add_argument("--np-thr", type=int, dest="np_thr", default=14,
    #                     help="only the channel that np≥np_thr will be processed")
    # parser.add_argument("--rq-thr", type=float, dest="rq_thr",
    #                     default=0.95,
    #                     help="only the channel that rq≥rq_thr will be processed")

    # args = parser.parse_args()
    # smc_bam = args.smc_bam
    # sbr_bam = args.sbr_bam

    rq_thr = 0.99
    np_thr = 7

    fastx_file_path = "/data1/ccs_data/20251216-aidikang/Barcode10_q20.fastq"
    smc_bam_path = "/data1/ccs_data/20251216-aidikang/20251216_250214YJ006_Run0006.smc_all_reads.bam"
    subreads_bam_path = "/data1/ccs_data/20251216-aidikang/20251216_250214YJ006_Run0006_adapter.bam"
    smc_names = extract_name_from_fastx(fastx_file_path)

    channel_ids = extract_channel_id_from_smc_name(smc_names)

    infix = f"B10-Q20"
    smc_bam_subset = filter_bam(smc_bam_path, channel_ids, infix=infix)
    adapter_bam_subset = filter_bam(
        subreads_bam_path, channel_ids, infix=infix)

    # return

    sbr2smc_alignment = asts_alignment(
        adapter_bam_subset, smc_bam_subset, np_thr=np_thr, rq_thr=rq_thr)

    cmd = f"base_mismatch_identification v2 --smc-bam {smc_bam_subset} --sbr2smc-bam {sbr2smc_alignment} --origin-bam-rq-thr {rq_thr} --origin-bam-np-thr {np_thr}"
    subprocess.check_call(cmd, shell=True)
    if os.path.exists(sbr2smc_alignment):
        os.remove(sbr2smc_alignment)

    pass


if __name__ == "__main__":
    main()


# GGGGAAACCCCTTTTGAGAGAGATGTCATCATCATGCCACTTCCCAATTCCCCTACAACTTTACAACCACATTCATGTCCACAGCCTCCTCCCACTTTCCTTCCTGCAGCTTCAGCTCTAACAATCTCAAACTTACCTTCTTTTTCAGGATGGGATTCACAAGGGCCCTTGGTGTCTGAAGCACCAAACTGAACGCAGGCCTCGGATGATCAAGACGGTCCCCACCACAATGCCCACGAGGCCCACAGACAAACCCCAGGGCACAGACCACAGTCTCTGTGAGCTCTGACATAGGTGCTGGAATCTCAGGCTCTGTGGAAGTGAAGTTGTTGAGGTCAGAATGCAGAGTGTGCTCATGTGCATGTGTGAGGGATGGGATGGGGTGGAGGGTTGGCTCTGCAAAGACTCAAGGCCCCTGGCTCAGGGAGGAGAGTGAAGTCTGTTATTAGAAACCCATGAAGTGGCAGGCCTGCTCCCACCCGTGGAGTGTACTTTCTTTTTTAATAATCTGTGCTTTTGTTGCTTAATTCTTTCAAAAAAAAAAAAAGATAAAAGAAACTCATGAAGTGTGGAAAACAAGTTTTGGGACATAGAGTAAAAGGCAGGAAGTTCTGAACTTGACAGACAAGAAAGCATCAAAAAATGGTGAAACTCATCCTTACCCCAGTGATTCAGAAGAGGCTCATCCAGGCCCCAGTGCTCCACCTTGCAGTCATAATCTTCATCAGCAGAAGGGAGAAAGGTGAGGTAACTGATCTGAAGAAGGAATGATCACTCTTGGAGAGGAAGCTGGTCTCAGAAACACCTTCTGTGACTGAGTGCCCATTGCTCAGCCAGGTGATGTTGACCACAGGAGGAAAGATGTGTCCACAAGACAGATGAGGGTGTTGGGCTGACCCAGTGTCACGGAGACTTGGAAAACACTGTGACCTCAGGAACCTCTATGGTGAGGAAACAGCACTGGTGTGAAGTGTGAATAGCTCTGCCCTGAGCTTCTGCATTACATCCTGGAAGAGTCTTCCTACCAGCATTTCCTCTCCTGCTGGTCAAAGAGGCCTTATTTACCTTCTACTTGGGAGCAATGACACATTGCCTCTGCTTTACTCCTGTGCCCTTCTCTCTGTGGGCATGTTTAATAAAGTAGGAGGTTGATGAGACCTCTCCTAGAATGATTTAATGAATGCATAATGGAAAGACCCTTGTATTACATGGGGATATGTGATTTTATGAGATGAGAAATGATAAAATTTCAGCAATTGCCATGAGAAGATCTGGGGACCTCTTGAAAGAAAATAATGAAACTTGGTATAAAGGGATAGATCAGTAAAGAAAGGCAGAATGGTGGACACATACCATTGGTAGCAGCGGTAGAGTTGGAGCGTTTAATCAGGATGTTCAAGTTATGTTTTAGCACAGCGATGTTTGTCAGTGCAAATTGCGGGTCAAATCTAAGTCTGTGGAACAGAGGGCAACTTCCAGACAGTCTCCTTCCTCTCCAGGTCCACATAGAACTCCTCGTCTCCATCAATTCATGGGTGAACTGGCCAGAGGGACCGTAAGACTGGTACAAGTTTACACCGTAAGAGGCAACGTGGTCAGCTGATGAGTGAAGATGACAAGCAGGAAGGCAGAGAACAGGAGAATAAAAAACCTTAATACACAAAATGATGGAAGAACTGACTTTCAAATATTATGGGCTTTGTCTTTGGCAAAGTCTGTGGACATTTCCAGCCCCTGCTTCCTCCCCTCTTCGTGTTGATAGTTGTCCAGTTAAAAGAGTGCACTTTCTTTCCCACTACAGTGTGTGCTACACAAGGGCAGAATATCGCGTGTCCGATTTTCACTATTTCCTGAGTGCCTGCAGCACATCATGGACTTGTGATTAAATAATGTAAATGAACAGAAGAAGGAATGAATGAGTTATCAGAGTACTTAACTTTCTTAGTCATAGATTAACTTCCCTCTGCTTCCTAAGGTTATCTTTCACTTAATTCTTTCATCAGTTAATAACAAATTGATTATACTTCCTTTCCTCTCAGGACTGGCTCAGAACGGACATTCTACACAGAGATCTTTCTTTTTTTAGAAAAAGGAAAAGCATGCAGGATCTTATTAATTTAAAATAATTTCTGCTAACAATGGTAGGTATAAGAAAGAGTATAACAAGAACGGTAATAACATTACAAAATATATGATAAATAAATAATGCTTCCTTCTAAGGTCTCTGTTTTGTTAATAGTAATGGTCCTTAGAGGAGAGTAACTGATTTCTTCTGAAATGAAAAGTGGAAGCTCTACTAGTTTTTGGATTTCTGTCATTCCCCCCACCCTTTTTTTCCTCTGAAGGAGGTTACTAAATGTCTGCAGTGTTCTGACTCACATTTATATTCACCCTTTTTCCTCTAATGGGCAGTGTGCTTCTCTGAGGATGCCAGAGCAGAATGGCAGCCATGCAGTATGACTCCAGCCAAATGAGCCAAACTGAACATTCTGGTCAGACATGTGTAAGCCTTTTACCATCGTATCTTTCCTTCCTTCCCCACTTTCTGAGCATCCACAAGTATCAGACATAGCAGGGGAAGTGTAAAACACCAATCAGGCATGGTCTACCATTAAGGAACAAACTGAATAGTGGAGAGTCAGGTAGGTAAGGGAGCAGATACAATGTACTGTAGTAAGTTCTGCGAGGAGGATATTGAGACAGCCTTACAGTCCAACATCTTTCACAGTATCTGCCAAGCAAACCAAACTACATTATCCTTTCATGTTCCTGGTCTTTGCAGTGGTCTGTTGTTTTCCTCCCTGAAATGAAATTATCTTTTAGGACTTCCTGGAGAAATCATAAAATCAATCCTTGAGGTTTCTGCTTAAGTTAACAACTTTGTAGCTAAGTCCTCTCATCAACATGTTTTTGACCACGTTATGACCTCCAGCTCCTCCATCTCAACATCTGGCCATCCAAGTTTGTCTATCCCTCTTCCAGCTCACCTTCTTCCCTATCCAGTATGACCACGCTGGATGGTCTTAACAGCCACCAACACAAGCCTCCTTATCCTTGCAATAAACCTTGACTCTTTGTTCAAACATAAATATATATGGAATATATGCAATCCTTCTTTTCGTCTGGTTATCCTGCTGGCCCAGCTGGAACCAAGTCACTTGTATAGTTTCAGCCTCTGCTGAGTCCACTGCCTGCTCAGCAATGGCCTTCTGCTTTCTTTCATCCCATACTGATTTCCATCACTAGTCTGAGCACCCTCTGCAGGGGAGACAGCATGACTTTTCATCTTTGAATCCTTAAAACTTAGCTCACTGGGTGCTCAAACATGTGTATTGAATGACAGTTGTTATATTTGAGGACCACATAGATTTTGGGGAAGACTGACAGGCACATAGTTAGCAGGAACCACACGAAGGTCAGGATCAGCCATGATCAGAGGATGCGTTCTGACATGTGAGCCCCAAGCACTCTTGCTTGTGTGGACGCCTTCCTCCATAAAAATATGGAAAATTATATTTTATGACTGAATTGGTATAAAGACAATATAAATATAGGCTGAATTAAAAGTTAAAACATTTTCTTAGGCTCTACAATTTCATTTTTTATAATTTTAAAAGGAGTTAAAACATTCTCATGTGGCTTTACAGTATGGAGGTTCCCCTGCACTGCCCACATTGTGCCTAATGGATGAGCTGAGCCTGACAGGGCACTCTGGTGTGAGGCTGAAGAAAGGAAATTTGGAACAAAGAAGCCAAGCGCTCTGGAGGAGAGGGTGAAACTTCCACTGCTGAACAAAATCAGAAATGGGAGCTGCCACGGTTAATAAGGTTGTGAAAAGTTTAGAGTACCTTCCAGTTTACTTCCCCTTTTAACTATCTGACTTTTCAACTTTTGTTTTACAAACTCATGTCCATCTCTATAAAGGAGCAGGGAGTCAGAGATGGATCCTGAAAGGGAAGAGGGAGAAAGGAATGCATGAAGAGAGGTGGGAAGAGATGGACGACAAAGGCAGAGGAGACTAAGAGACCAAATAATTAATCTGTGCTTCCTTCCTTCTGTTTTCTTTCTTTCTTTCTTCTTTCTTCCCTTCCCTTTCTCCTTCCTTGCTTCCTTCTTTCCTCTTTCCTTCCTTTCTCTCTTTCTGTTCCGCTTTCTTTTTGAGACAGGGTCTCTCTCTGTTGCCCTGGCTGGAGTGTAGTGGTGCCATCATAGGCTCACTGCAGCTTCCACCTCCTGGACTCAAGTGCTCCTCCCACTGCAGCCTTCTGAGTAGCTGGCACCACAGGCATGCACTACCATGCCTGGCTAATTTTTATTTTATTTTTTGGTAGAGATGAGGTCTTGCTGTGTTGCCCAGGCTGGTCTCAAACTCCCAGGCTCAAATGATCTCCTGCTTCGGCCTCCCAAAGTGCTGGGATTACAGGCATGAGCCACCATGTCTGGCCCACTTTTCTTTTTATAGGACTTTATTAGATGAGGTGAAGAACAGGTAATTTGGGTTGATAATTTGAGAATAAAATGATTAATTATACCAATTTTTTCTACTTCTCAATTTTAAACTAAAAGGATCCCTTATTTTGCTAAAGAAAGAAATGTGAAGCTATACCTGTAATAGAAATATGTAAAAACAATTGACATCCATGTTTTCACTATTTACAAAGCTTAGCTACATGCCCATTTTATTTGATTATTTGTGAGGTGACACATATGAGGCAGCTGAGAGTAAGTGAGGACCATGTGGTAAATGATTGTTGAAGGCATTCAGCCTGCTGGACTCCTTTACCTACTCCCCAACCTGTGCCAGTTCCCATGTGGAAATGTGAGTAAGTCTGAGAGAAAGAAACGGGCAACTTTTTTAATATCTATAGAGTATATAATTGATGGAACAGACCCCAAGATCTACTACAGGAGACATCCGAAAATCTTCAAAAGTTGTTCAGGGAAATTTGAGATGACACTTCATACATTTTTAATAATAAAAAATTATCCACTGATGGAAACCTCACTAATTATTGAGGCAATCATGATGGAATGACATAGAGACCTCCAGGCTGTAGTCACTGAATATAATATAAACAGATAGCATCCTTAGTGAACACAAAAGCATACATAACAAAAAGAGTAGGTTGGGGCTCTGGTTTCCTGAAGGAGGAACAGCTATAATTTTTAATTCTCTTAATACTGAAAGGGGTCTTAGGAAATCTCTACAATTTCTCTGCAAAATCGCTTTCTCTCTTTTCCTTCAATTTACTGTTTTTCAGCTCCAGAGAACATTCCTCACTCACGCACTCACCCACAATGTCTTCACCTCCACAAGGGCTCATCACGGTGGTCAGGGCGAGGGCCCCCAGCATCAGAGCTTTGTTTAGGATCATCTTCTTCCAAGGCAGCCTCAGCAGTTGCTGTTCTGAGCTGTAGAGTAATTGTGAGGACCTCAAGACAAGGAAATCTGAAGACACCCAAACCAAGACCCGCCAAGTCAGGTTTTGGCCAATTAGAAAAATCCCCCATGGTGACATCTCAGTTACTAGTTGAAGAGTTTTCTATTAAGAGCCCTGGAAGGAGACAGGGCAATCCCCTTGTTGTGATGCAGCCTCTACTCAGAGTGGACTTGAGGAATTGTTCTATGAAGAGAGGGAAGACACTAAATTGGAATCTTCTCTGGTGTGTGCATGTCTGATCTCTCTCAAAAGGGGTTTTCCC
# GGGGAAAACCCCTTTTGAGAGAGATGTCATCATCATGCCACTTCCCAATTCCCCTACAACTTTCAACCACATTCATGTCCACAGCCTCCTCCCACTTCCTTCCTGCAGCTTCAGCTCTACAAATCTCAAACTTACCTTCTTTTTCAGGATGGGATTCACAAGGGCCCTTGGTGTCTGAAGCACCAACTGAACGCAGGCCTCGGATGATCAAGACGGTCCCCACCCAATGCCCACGAGGCCCACAGACAACCCCAGGGCACAGACCACAGTCTCTGTGAGCTCTGACATAGGTGCTGGAATCTCAGGCTCTGTGGAAGTGAAGTTGTTGAGGTCAGAATGCAGAGTGTGCTCATGTGCATGTGTGAGGGATGGGATGGGTGGAGGGTTGGCTCTGCAAAGACTCAAGGCCCCTGGCTCAGGGAGGAGAGTGAAGTCTGTTATTAGAACCCATGAAGTGGCAGGCCTGCTCCACCCTGTGGAGTGTACTTTCTTTTTTAATAAATCTGTGCTTTTGTTGCTTATTCTTTCAAAAAAAAAAAAGATAAAAGAAACTCATGAAGTGTGGAAAACAAGTTTGGGACATAGAGTAAAAGGCAGGAAGTTCTGAACTTGACAGACAAGAAAGCATCAAAAAATGGTGAAACTCATCCTTACCCCAGTGTTTCAGAAGAGGCTCATCCAGGCCCAGTGCTCCACCTTGCAGTCATAAATCTCATCAGCAGAAGGGAGGAAGGTGAGGTAACTGATCTTGAAGAAGGAATGATCACTCTTGGAGAGGAAGCTGGTCTCAGAAACACCTTCTGTGACTGAGTGCCCATTGCTCAGCCAGGTGATGTTGACCACAGGAGGAAAGATGTTGTCCACAAGACAGATGAGGGTGTTGGCTGACCCAGTGTCACGGGAGACTTGGAAAACACTGTGACCTCAGGAACCTCTATGGTGAGGAAACAGCACTGGTGTGAAGTGTGAATAGCTCTGCCCTGAGCTTCTGCATTACATCCTGGAAGAGTCTTCCTACCAGCATTTCCTCTCCTGCTGGTCAAAGAGGCCTTATTTACCTTCTACTTGGGGCAATGACACATTGCCTCTGCTTTACTCCTGTGCCCTTCTCTCTGTGGGCATGTTTAATAAAGTAGGAGGTTGATGAGACCTCTCCTAGAATGATTTAATGAATGCATAATGGAAAAGACCCTTGTATTACATGGGGATATGTGATTTTAGAGATGAGAAATGATAAAATTTCAGCAATTGCCATGAGAAGATCTGGGGACCTCTTGGAAAGAAAATAATGAAACTTGGTATAAAGGGATAGATCAGTAAAGAAAGGCAGAATGGTGGACACATACCATGGTAGCAGCGGTAGAGTGGAGCGTTTAATCAGGATGTTCAAGTTATGTTTTAGCACAGCGATGTTTGTCAGTGCAAATTGCGGTGTCAAATCTAAGTCTGTGGAACAGAGGCAACTTCCAGACAGTCTCCTTCCTCTCCAGGTCCACTAGAACTCCTCGTCTCCATCAAATTCATGGGTGAACTGGCCAGAGGGACCGTAAGACTGGTACAAGTTTACACCGTAAGAGGCAACGTGGTCAGCTGGTGAGTGAAGATGACAAGCAGGAAGGCAGAGAACAGGAGAATAAAAAACCTTAATACACAAAATGATGGAAGAAACTGACTTTCAAATATTATGGGCTTTGTCTTTGGCAAAGTCTGTGGACATTTCCAGCCCTGCTTCCTCCCCTCTTCGGTGTTGATAGTTGTCCAGTTAAAAGTGCACTTTCTTTCCCACTACAGTGTGTGCTACACAAGGGCAGAATATCGCGTGTCCGATTTCACTATTTCCTGAGTGCCTGGCACATCATGGACTTGTGATTAAATAATGTAAATGAACAGAAGAAGGAATGAATGAGTTATCAGAGTACTTAACTTTCTTAGTCATAGATTAACTTCCCTCTGCTTCCTAAGGTTTATCTTTCACTAATTCTTTCATCAGTTAATAACAAAATTGATTATACTTCCTTTCCTCTCAGGACTGGCTCAGAACAGGACATTCTACACAGAGATCTTTCTTTTTTTAGAAAAAGGAAAAGCATGCAGGATCTTATTAATTTAAAATAATTTCTGCTAACAATGGTAGGGTATAAGAAAGAGTATAACAAGAACGGTAATAACATTACAAAATATATGATAAATAAATAATGCTTCCTTCTAAGGTCTCTGTTTTGTTAATAGTAATGGTCCTTAGAGGAGAGTAACTGATTTCTTCTGAAATGAAAAAGTGGAAGCTCTACTAGTTTTTGGATTTCTGTCATTCCCCCCACCCTTTTTTTTCCTCTGAAGGAGGTTACTAAATGTCTGCAGTGTTCTGACTCAACATTTATATTCACCCTTTTTCCTCTAATGGGCAGTGTGCTTCTCTGAGGATGCCAGAGCAGAATGGCAGCCATGCAGTATGACTCCAGCCAAATGAGCCAAACTGAACATTCTGGTCAAGACATGTGTAAGCCTTTTACCATCGTATCTTTCCTTCCTTCCCCACTTTCTGAGCATCCACAAGTATCAGACATAGCAGGGGAAGTGTAAAACACCAATCAGGCATGGTCTACTCATAAGGAACAAACTGAATAGTGGGAGAGTCAGGTAGGTAAGGGAGCAGATACAATGTACTGTAGTAAGTTCTGCGAGGAGGATATTGACAGCCTTACAGTCCAACATCTTTCACAAGTATCTGCCAAGCAAACCAAACTACATTATCCTTTCATGTTCCTGGTCTTTGCAGTGGTCTGTTGTTTTCCTCCCTGAAATGAAATTATCTTTTAGGACTTCCTGGAGAAATCATAAAATCAATCCTTGAGGTTTCTGCTTAAGTTAACAACTTTGTAGCTAAGTCCTCTCATCAACATGTTTTTGACCACGTTATGACCTCCAGTCCTCCATCTCAACATCTGGCCATCCAAGTTTGTCTATCCCTCTTCCAGCTCACCTTCTTCCCTATCCAGTATGACCACGCTGGATGGTCTTAACAGGCCACCAACAAAGCCTCCTTATCCTTGCATAAACCTTGACTCTTTGTTCAACATAAATATATATGGAATATATGCAATCCTTCTTTTCGTCTGGTTATCCTGCTGGCCCAGCTGGAACCAAGTCACTTGTATAGTTTCAGCCTCTGCTGAGTCCACTGCCTGCTCAGCAATGGCCTTCTGCTTTCTTTCATCCCATACTGTTCCATCACTAGTCTGAGCACCCTCTGCAGGGGAGACAGCATGACTTTTCATCTTGAATCCTTAAAACTTAGCTCACTGGGTGCTCAAACATGTGTATTGAATGACAGTTGTTATATTTGAGGACCACATAGATTTTGGGGAAGACTGACAGGCACATAGTTAGCAGAACCACACGAAGGTCAGGATCAGCCATGATCAGGGATGCGTTCTGACATGTGAGCCCCAAGCACTCTTGCTTGTGTGACGCCTTCCTCCATAAAAATATGGAAAATTATATTTTATGACTGAATTGGTATAAAGACAATATAATATAGGCTGAATTAAAAGTTAAAACATTTTCTTAGGCT
# CTACAATTTCATTTTTTTATAATTTTAAAAGGAGTTAAAACATTCTCATGTGGCTTTACAGTATGGAGGTTCCCCTGCACTGCCCACATTGTGCCTAATGGATGAAGCTGAGCCTGACCAGGGCACTCTGGTGTGAGGCTGAAGAAAGGAAATTTGGAACAAAGAAGCCAAGCGCTCTGGAGGAGAGGGTGAAACTTCCACTGCTGAACAAAATCAGAATGGGAGCTGCCACGGTTAATAAGGTTGTGAAAGTTTTAGAGTACCTTCCAGTTTACTTCCCCTTTTAACTATCTGACTTTTCAACTTTTGTTTTACAAACTCATGTCCATCTCTATAAAGGAGCAGGGAGTCAGAGATGGATCCTGAAAGGGAAGAGGGAGA
# AAGGAATGCATGAAGAGAGGTGGGAAGAGATGGACGACAAAGGCAGAGGAGACTAAGAGACCAAATAATTAATCTGTGCTTCCTTCCTTCTGTTTTTCTTTCTTTCTCTTTCCTCTCTTTCTTCCCT
# TCCCTTTCTCTCCTTCCTTGCTTCCTTCTTTCCTTCTTTCCTTCCTTTCTCTCTTTCTTTCCGCTTTCTTTTTGAGACAGGGTCTCTCTCTGTTGCCCTGGCTGGAGTGTAGTGGTGCCATCATGGCTCACTGCAGCTTCCACCTCCTGGACTCAAGTGCTCCTCCCACTGCAGCCTTCTGAGTAGCTGGCACCACAGGCATGCACTACCATGCCTGGCTAATTTTTATTTTATTTTTTGGTAGAGATGAGGTC
# TTGCTGTGTTGCCAGGCTGGTCTCAAACTCCCAGGCTCAAATGATCCTCCTGCTTCGGCCTCCCAAAGTGCTGGGATTACAGGCATGAGCCACCATGTCTGGCCCACTTTTCTTTTTATAGGACTTT
# ATTAGATGAGGTGAAGAACAGGTAATTTGGGTTGATAATTTGAGAATAAACATGATTTAATTTACCAATTTTTTCTACTTCTCAATTTTAAACTAAAAGGATCCCTTATTTTGCTAAAGAAAAATGTGAAGCTATACCTGTAATAGAAATATGTAAAAACAATTGACATCCATGTTTTCACTATTACAAAGCTTAGCTACATGCCCATTTTATTTGATTATTTGTGAGGTGACACATATGAGGCAGCTGAGAGT
# AAGTGAGGACCATGTGGTAAAATGATTGTTGAAGGCATTCAGCCTGCTGGACTCTTTACCCACTCCCCACCTGTGCCAGTTCCCATGTGGAAATGTGAGTAAGTCTGAGAGAAAGAAACGGGCAACT
# TTTTTAATATCTATAGAGTATATAATTGATGGAACGACCCCAAGATCTACTACAGGAGACATACGAAAAGCTTCAAAAGTTGTTCAGGGAAATTTGAGAATGACACTTCATACATTTTTAATAATAAAAAATTATCCACTGATGGAAACTTCACTAATTTTTGAGGCAATCATGACGGAACGACATAGAGACCTCCAGGCTGTTGTCACTGAATATAATATAAACAGAATAGCATCCTTAGTGAACACAAAAGC
# ATACATAACAAAAAGAGTAGGTTGGGGCTCTGGTTTCCTGAAGGAGGAACAGCTATAATTTTAATTCTCTTAATACTGAAAGGGGTCTTAGGAAATCTCTACAATTTCTCTGCAAATCGCTTTCTCT
# CTTTTCCTTCAATTTACTGTTTTTCAGCTCCAGAGAACATTCCTCACTCATGCACTCACCCACAATGTCTTCACCTCCACAAGGGTCGTCACGGTGGTCAGGGCGAGGGCCCCCAGCATCAGAGCTTTGTTTAGGATCATCCTCTTCCCAAGGCAGCCTCAGCAGTTGCTGTTCTGAGCTGTAGAGCAATTGTGAGGGCCTCAAGACAAGGAAATCTGAAGACACCCAAACCAAACCCTGCCAGGTCAGGTTTT
# GGCCAATTAGAAAAATCCCCCATGGTGACATCTCAGTTACTAGTTGAAGAGTTTGTATTAAGAGCCTGGAAGGAGACAGGGCAATCCCTTGTTGTGATGCAGCCTCTATCTCAGAGTGGACTTGAGG
# AATTGTTCTATGAACAGAGGCAGGACACTAAATTGGAATCTTCTCTGGTGTGTGCATGTCTGATCTCTCTCAAAAGGGGTTTTCCCC
