from invenio_communities.communities.records.models import CommunityFeatured
from invenio_db.uow import Operation, UnitOfWork

class CommunityFeaturedCommitOp(Operation):
    def __init__(self, featured_entry: CommunityFeatured) -> None: ...
    def on_register(self, uow: UnitOfWork) -> None: ...

class CommunityFeaturedDeleteOp(Operation):
    def __init__(self, featured_entry: CommunityFeatured) -> None: ...
    def on_register(self, uow: UnitOfWork) -> None: ...
