from collections.abc import Iterator, Mapping
from typing import Any, Self, overload

from invenio_records.systemfields import SystemField
from invenio_records_resources.records.api import FileRecord

class TransferFieldData(Mapping[str, Any]):
    _field: dict[str, Any]

    def __init__(self, field: dict[str, Any]) -> None: ...
    @property
    def transfer_type(self) -> str: ...
    @transfer_type.setter
    def transfer_type(self, value: str) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, values: dict[str, Any]) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class TransferField(SystemField):  # type: ignore[misc]
    @overload  # type: ignore[override]
    def __get__(self, instance: None, owner: type[FileRecord]) -> Self: ...  # type: ignore # keep typing tighter
    @overload
    def __get__(  # type: ignore # keep typing tighter
        self, instance: FileRecord, owner: type[FileRecord]
    ) -> TransferFieldData: ...
    def __set__(self, instance: FileRecord, value: TransferFieldData) -> None: ...  # type: ignore[override]
