from collections.abc import Callable, MutableMapping, Sequence
from types import NoneType
from typing import Any, NoReturn, overload

type NoReturnCall = Callable[..., NoReturn]
type FreezableTypes = dict | list | set
type ThawTypes = FrozenDict | tuple | frozenset

def is_primitive(obj: object) -> bool: ...
@overload
def freeze[K, V](obj: FrozenDict[K, V]) -> FrozenDict[K, V]: ...
@overload
def freeze[T](obj: tuple[T, ...]) -> tuple[T, ...]: ...
@overload
def freeze[T](obj: frozenset[T]) -> frozenset[T]: ...
@overload
def freeze[K, V](obj: dict[K, V]) -> FrozenDict[K, V]: ...
@overload
def freeze[T](obj: list[T]) -> tuple[T, ...]: ...
@overload
def freeze[T](obj: set[T]) -> frozenset[T]: ...
@overload
def freeze(obj: str) -> str: ...
@overload
def freeze(obj: bool) -> bool: ...
@overload
def freeze(obj: int) -> int: ...
@overload
def freeze(obj: float) -> float: ...
@overload
def freeze(obj: bytes) -> bytes: ...
@overload
def freeze(obj: NoneType) -> None: ...
@overload
def freeze(obj: object) -> object: ...
def freeze(
    obj: FreezableTypes | object,
) -> FrozenDict | tuple | frozenset | object: ...

class FrozenDict[K, V](dict[K, V]):
    data_size: int
    __frozen__: bool = True
    cacheable: bool = True
    def __init__(self, data: Sequence | MutableMapping[K, V]) -> None: ...
    def __getitem__(self, *args) -> Any: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self): ...
    def get_hash(self) -> int: ...
    def get(self, key: object, default: Any = None): ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    clear: NoReturnCall = ...
    setdefault: NoReturnCall = ...
    popitem: NoReturnCall = ...
    update: NoReturnCall = ...
    pop: NoReturnCall = ...
    __setitem__: NoReturnCall = ...
    __delitem__: NoReturnCall = ...
    def __hash__(self) -> int: ...  # pyright: ignore[reportIncompatibleVariableOverride]

class NullFrozenDict(FrozenDict[NoReturn, NoReturn]): ...

NULL_FROZEN_DICT: NullFrozenDict = ...
"""An empty NullFrozenDict constant."""
NULL_KEY: str = ...
NULL_TUPLE: tuple[str] = ...
NONE_TUPLE: tuple[NoneType] = ...
NONE_ITEMS_TUPLE: tuple[tuple[str, NoneType]] = ...
