"""Type stubs for scraper_rs.asyncio module."""

from __future__ import annotations

from . import Document, Element, ElementDict

class AsyncElement:
    tag: str
    text: str
    html: str
    attrs: dict[str, str]
    element: Element

    def __repr__(self) -> str: ...
    def attr(self, name: str) -> str | None: ...
    def get(self, name: str, default: str | None = ...) -> str | None: ...
    async def select(self, css: str) -> list[AsyncElement]: ...
    async def select_first(self, css: str) -> AsyncElement | None: ...
    async def find(self, css: str) -> AsyncElement | None: ...
    async def css(self, css: str) -> list[AsyncElement]: ...
    async def xpath(self, expr: str) -> list[AsyncElement]: ...
    async def xpath_first(self, expr: str) -> AsyncElement | None: ...
    def to_dict(self) -> ElementDict: ...

class AsyncDocument:
    html: str
    text: str
    document: Document

    async def select(self, css: str) -> list[AsyncElement]: ...
    async def select_first(self, css: str) -> AsyncElement | None: ...
    async def find(self, css: str) -> AsyncElement | None: ...
    async def css(self, css: str) -> list[AsyncElement]: ...
    async def xpath(self, expr: str) -> list[AsyncElement]: ...
    async def xpath_first(self, expr: str) -> AsyncElement | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> AsyncDocument: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback
    ) -> None: ...
    def __repr__(self) -> str: ...

async def parse(
    html: str,
    *,
    max_size_bytes: int | None = ...,
    truncate_on_limit: bool = False,
) -> AsyncDocument: ...
async def select(
    html: str,
    css: str,
    *,
    max_size_bytes: int | None = ...,
    truncate_on_limit: bool = False,
) -> list[AsyncElement]: ...
async def select_first(
    html: str,
    css: str,
    *,
    max_size_bytes: int | None = ...,
    truncate_on_limit: bool = False,
) -> AsyncElement | None: ...
async def first(
    html: str,
    css: str,
    *,
    max_size_bytes: int | None = ...,
    truncate_on_limit: bool = False,
) -> AsyncElement | None: ...
async def xpath(
    html: str,
    expr: str,
    *,
    max_size_bytes: int | None = ...,
    truncate_on_limit: bool = False,
) -> list[AsyncElement]: ...
async def xpath_first(
    html: str,
    expr: str,
    *,
    max_size_bytes: int | None = ...,
    truncate_on_limit: bool = False,
) -> AsyncElement | None: ...
