/** @type {import('codefetch').CodefetchConfig} */
export default {
  projectTree: 5,
  tokenLimiter: "truncated",
  defaultPromptFile: "default.md",
  excludeFiles: [
    "**/*.png",
    "**/*.lock",
    "**/*icon*.*",
    "**/*.coverage/**",
    "**/*.xml/**",
    "**/*.egg-info/**",
  ],
  excludeDirs: [
    "**/dist/**",
    "**/.taskmaster/**",
    "**/.cursor/**",
    "**/.clinerules/**",
    "**/.gemini/**",
    "**/codefetch/**",
    "**/.venv/**",
    "**/.archive/**",
    "**/__pycache__/**",
    ".pytest_cache",
    "**/.context/**",
    ".codex",
    "**/node_modules/**",
    "**/shared/**",
    "**/.codex/**",
    "**/coverage/**",
    "**/build/**",
  ],
};
