from numpy._core._dtype import (
    _aligned_offset as _aligned_offset,
    _byte_order_str as _byte_order_str,
    _construction_repr as _construction_repr,
    _datetime_metadata_str as _datetime_metadata_str,
    _is_packed as _is_packed,
    _isunsized as _isunsized,
    _kind_name as _kind_name,
    _kind_to_stem as _kind_to_stem,
    _name_get as _name_get,
    _name_includes_bit_suffix as _name_includes_bit_suffix,
    _scalar_str as _scalar_str,
    _struct_dict_str as _struct_dict_str,
    _struct_list_str as _struct_list_str,
    _struct_str as _struct_str,
    _subarray_str as _subarray_str,
    _unpack_field as _unpack_field,
)
