# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChatRoom(UniversalBaseModel):
    """
    A chat room
    """

    id: str = pydantic.Field()
    """
    Chat Room ID
    """

    inserted_at: dt.datetime = pydantic.Field()
    """
    Created At
    """

    task_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Associated Task ID
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Chat room title
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Updated At
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
