"""ONIX Code List 49: Region - based on ISO 3166-2."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "AU-CT": CodeListEntry(
        list_number=49,
        code="AU-CT",
        heading="Australian Capital Territory",
        added_version=1,
    ),
    "AU-NS": CodeListEntry(
        list_number=49,
        code="AU-NS",
        heading="New South Wales",
        added_version=1,
    ),
    "AU-NT": CodeListEntry(
        list_number=49,
        code="AU-NT",
        heading="Northern Territory",
        added_version=1,
    ),
    "AU-QL": CodeListEntry(
        list_number=49,
        code="AU-QL",
        heading="Queensland",
        added_version=1,
    ),
    "AU-SA": CodeListEntry(
        list_number=49,
        code="AU-SA",
        heading="South Australia",
        added_version=1,
    ),
    "AU-TS": CodeListEntry(
        list_number=49,
        code="AU-TS",
        heading="Tasmania",
        added_version=1,
    ),
    "AU-VI": CodeListEntry(
        list_number=49,
        code="AU-VI",
        heading="Victoria",
        added_version=1,
    ),
    "AU-WA": CodeListEntry(
        list_number=49,
        code="AU-WA",
        heading="Western Australia",
        added_version=1,
    ),
    "BE-BRU": CodeListEntry(
        list_number=49,
        code="BE-BRU",
        heading="Brussels-Capital Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=40,
    ),
    "BE-VLG": CodeListEntry(
        list_number=49,
        code="BE-VLG",
        heading="Flemish Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=40,
    ),
    "BE-WAL": CodeListEntry(
        list_number=49,
        code="BE-WAL",
        heading="Walloon Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=40,
    ),
    "CA-AB": CodeListEntry(
        list_number=49,
        code="CA-AB",
        heading="Alberta",
        added_version=2,
    ),
    "CA-BC": CodeListEntry(
        list_number=49,
        code="CA-BC",
        heading="British Columbia",
        added_version=2,
    ),
    "CA-MB": CodeListEntry(
        list_number=49,
        code="CA-MB",
        heading="Manitoba",
        added_version=2,
    ),
    "CA-NB": CodeListEntry(
        list_number=49,
        code="CA-NB",
        heading="New Brunswick",
        added_version=2,
    ),
    "CA-NL": CodeListEntry(
        list_number=49,
        code="CA-NL",
        heading="Newfoundland and Labrador",
        added_version=2,
    ),
    "CA-NS": CodeListEntry(
        list_number=49,
        code="CA-NS",
        heading="Nova Scotia",
        added_version=2,
    ),
    "CA-NT": CodeListEntry(
        list_number=49,
        code="CA-NT",
        heading="Northwest Territories",
        added_version=2,
    ),
    "CA-NU": CodeListEntry(
        list_number=49,
        code="CA-NU",
        heading="Nunavut",
        added_version=2,
    ),
    "CA-ON": CodeListEntry(
        list_number=49,
        code="CA-ON",
        heading="Ontario",
        added_version=2,
    ),
    "CA-PE": CodeListEntry(
        list_number=49,
        code="CA-PE",
        heading="Prince Edward Island",
        added_version=2,
    ),
    "CA-QC": CodeListEntry(
        list_number=49,
        code="CA-QC",
        heading="Quebec",
        added_version=2,
    ),
    "CA-SK": CodeListEntry(
        list_number=49,
        code="CA-SK",
        heading="Saskatchewan",
        added_version=2,
    ),
    "CA-YT": CodeListEntry(
        list_number=49,
        code="CA-YT",
        heading="Yukon Territory",
        added_version=2,
    ),
    "CN-BJ": CodeListEntry(
        list_number=49,
        code="CN-BJ",
        heading="Beijing Municipality",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-TJ": CodeListEntry(
        list_number=49,
        code="CN-TJ",
        heading="Tianjin Municipality",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-HE": CodeListEntry(
        list_number=49,
        code="CN-HE",
        heading="Hebei Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-SX": CodeListEntry(
        list_number=49,
        code="CN-SX",
        heading="Shanxi Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-NM": CodeListEntry(
        list_number=49,
        code="CN-NM",
        heading="Nei Mongol Autonomous Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-LN": CodeListEntry(
        list_number=49,
        code="CN-LN",
        heading="Liaoning Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-JL": CodeListEntry(
        list_number=49,
        code="CN-JL",
        heading="Jilin Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-HL": CodeListEntry(
        list_number=49,
        code="CN-HL",
        heading="Heilongjiang Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-SH": CodeListEntry(
        list_number=49,
        code="CN-SH",
        heading="Shanghai Municipality",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-JS": CodeListEntry(
        list_number=49,
        code="CN-JS",
        heading="Jiangsu Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-ZJ": CodeListEntry(
        list_number=49,
        code="CN-ZJ",
        heading="Zhejiang Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-AH": CodeListEntry(
        list_number=49,
        code="CN-AH",
        heading="Anhui Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-FJ": CodeListEntry(
        list_number=49,
        code="CN-FJ",
        heading="Fujian Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-JX": CodeListEntry(
        list_number=49,
        code="CN-JX",
        heading="Jiangxi Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-SD": CodeListEntry(
        list_number=49,
        code="CN-SD",
        heading="Shandong Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-HA": CodeListEntry(
        list_number=49,
        code="CN-HA",
        heading="Henan Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-HB": CodeListEntry(
        list_number=49,
        code="CN-HB",
        heading="Hubei Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-HN": CodeListEntry(
        list_number=49,
        code="CN-HN",
        heading="Hunan Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-GD": CodeListEntry(
        list_number=49,
        code="CN-GD",
        heading="Guangdong Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-GX": CodeListEntry(
        list_number=49,
        code="CN-GX",
        heading="Guangxi Zhuangzu Autonomous Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-HI": CodeListEntry(
        list_number=49,
        code="CN-HI",
        heading="Hainan Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-CQ": CodeListEntry(
        list_number=49,
        code="CN-CQ",
        heading="Chongqing Municipality",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-SC": CodeListEntry(
        list_number=49,
        code="CN-SC",
        heading="Sichuan Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-GZ": CodeListEntry(
        list_number=49,
        code="CN-GZ",
        heading="Guizhou Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-YN": CodeListEntry(
        list_number=49,
        code="CN-YN",
        heading="Yunnan Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-XZ": CodeListEntry(
        list_number=49,
        code="CN-XZ",
        heading="Tibet Autonomous Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-SN": CodeListEntry(
        list_number=49,
        code="CN-SN",
        heading="Shaanxi Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-GS": CodeListEntry(
        list_number=49,
        code="CN-GS",
        heading="Gansu Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-QH": CodeListEntry(
        list_number=49,
        code="CN-QH",
        heading="Qinghai Province",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-NX": CodeListEntry(
        list_number=49,
        code="CN-NX",
        heading="Ningxia Huizu Autonomous Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-XJ": CodeListEntry(
        list_number=49,
        code="CN-XJ",
        heading="Xinjiang Uygur Autonomous Region",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-TW": CodeListEntry(
        list_number=49,
        code="CN-TW",
        heading="Taiwan Province",
        notes="Prefer code TW (Taiwan, Province of China) from List 91. Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-HK": CodeListEntry(
        list_number=49,
        code="CN-HK",
        heading="Hong Kong Special Administrative Region",
        notes="Prefer code HK (Hong Kong) from List 91. Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-MO": CodeListEntry(
        list_number=49,
        code="CN-MO",
        heading="Macau Special Administrative Region",
        notes="Prefer code MO (Macao) from List 91. Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "CN-11": CodeListEntry(
        list_number=49,
        code="CN-11",
        heading="Beijing Municipality",
        notes="Deprecated in favor of CN-BJ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-12": CodeListEntry(
        list_number=49,
        code="CN-12",
        heading="Tianjin Municipality",
        notes="Deprecated in favor of CN-TJ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-13": CodeListEntry(
        list_number=49,
        code="CN-13",
        heading="Hebei Province",
        notes="Deprecated in favor of CN-HE",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-14": CodeListEntry(
        list_number=49,
        code="CN-14",
        heading="Shanxi Province",
        notes="Deprecated in favor of CN-SX",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-15": CodeListEntry(
        list_number=49,
        code="CN-15",
        heading="Inner Mongolia Autonomous Region",
        notes="Deprecated in favor of CN-NM",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-21": CodeListEntry(
        list_number=49,
        code="CN-21",
        heading="Liaoning Province",
        notes="Deprecated in favor of CN-LN",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-22": CodeListEntry(
        list_number=49,
        code="CN-22",
        heading="Jilin Province",
        notes="Deprecated in favor of CN-JL",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-23": CodeListEntry(
        list_number=49,
        code="CN-23",
        heading="Heilongjiang Province",
        notes="Deprecated in favor of CN-HL",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-31": CodeListEntry(
        list_number=49,
        code="CN-31",
        heading="Shanghai Municipality",
        notes="Deprecated in favor of CN-SH",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-32": CodeListEntry(
        list_number=49,
        code="CN-32",
        heading="Jiangsu Province",
        notes="Deprecated in favor of CN-JS",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-33": CodeListEntry(
        list_number=49,
        code="CN-33",
        heading="Zhejiang Province",
        notes="Deprecated in favor of CN-ZJ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-34": CodeListEntry(
        list_number=49,
        code="CN-34",
        heading="Anhui Province",
        notes="Deprecated in favor of CN-AH",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-35": CodeListEntry(
        list_number=49,
        code="CN-35",
        heading="Fujian Province",
        notes="Deprecated in favor of CN-FJ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-36": CodeListEntry(
        list_number=49,
        code="CN-36",
        heading="Jiangxi Province",
        notes="Deprecated in favor of CN-JX",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-37": CodeListEntry(
        list_number=49,
        code="CN-37",
        heading="Shandong Province",
        notes="Deprecated in favor of CN-SD",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-41": CodeListEntry(
        list_number=49,
        code="CN-41",
        heading="Henan Province",
        notes="Deprecated in favor of CN-HA",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-42": CodeListEntry(
        list_number=49,
        code="CN-42",
        heading="Hubei Province",
        notes="Deprecated in favor of CN-HB",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-43": CodeListEntry(
        list_number=49,
        code="CN-43",
        heading="Hunan Province",
        notes="Deprecated in favor of CN-HN",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-44": CodeListEntry(
        list_number=49,
        code="CN-44",
        heading="Guangdong Province",
        notes="Deprecated in favor of CN-GD",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-45": CodeListEntry(
        list_number=49,
        code="CN-45",
        heading="Guangxi Zhuang Autonomous Region",
        notes="Deprecated in favor of CN-GX",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-46": CodeListEntry(
        list_number=49,
        code="CN-46",
        heading="Hainan Province",
        notes="Deprecated in favor of CN-HI",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-50": CodeListEntry(
        list_number=49,
        code="CN-50",
        heading="Chongqing Municipality",
        notes="Deprecated in favor of CN-CQ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-51": CodeListEntry(
        list_number=49,
        code="CN-51",
        heading="Sichuan Province",
        notes="Deprecated in favor of CN-SC",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-52": CodeListEntry(
        list_number=49,
        code="CN-52",
        heading="Guizhou Province",
        notes="Deprecated in favor of CN-GZ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-53": CodeListEntry(
        list_number=49,
        code="CN-53",
        heading="Yunnan Province",
        notes="Deprecated in favor of CN-YN",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-54": CodeListEntry(
        list_number=49,
        code="CN-54",
        heading="Tibet Autonomous Region",
        notes="Deprecated in favor of CN-XZ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-61": CodeListEntry(
        list_number=49,
        code="CN-61",
        heading="Shaanxi Province",
        notes="Deprecated in favor of CN-SN",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-62": CodeListEntry(
        list_number=49,
        code="CN-62",
        heading="Gansu Province",
        notes="Deprecated in favor of CN-GS",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-63": CodeListEntry(
        list_number=49,
        code="CN-63",
        heading="Qinghai Province",
        notes="Deprecated in favor of CN-QH",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-64": CodeListEntry(
        list_number=49,
        code="CN-64",
        heading="Ningxia Hui Autonomous Region",
        notes="Deprecated in favor of CN-NX",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-65": CodeListEntry(
        list_number=49,
        code="CN-65",
        heading="Xinjiang Uyghur Autonomous Region",
        notes="Deprecated in favor of CN-XJ",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-71": CodeListEntry(
        list_number=49,
        code="CN-71",
        heading="Taiwan Province",
        notes="Deprecated in favor of CN-TW, but prefer code TW (Taiwan, Province of China) from List 91",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-91": CodeListEntry(
        list_number=49,
        code="CN-91",
        heading="Hong Kong Special Administrative Region",
        notes="Deprecated in favor of CN-HK, but prefer code HK (Hong Kong) from List 91",
        added_version=30,
        deprecated_version=44,
    ),
    "CN-92": CodeListEntry(
        list_number=49,
        code="CN-92",
        heading="Macau Special Administrative Region",
        notes="Deprecated in favor of CN-MO, but prefer code MO (Macao) from List 91",
        added_version=30,
        deprecated_version=44,
    ),
    "ES-CN": CodeListEntry(
        list_number=49,
        code="ES-CN",
        heading="Canary Islands",
        added_version=5,
    ),
    "FR-H": CodeListEntry(
        list_number=49,
        code="FR-H",
        heading="Corsica",
        added_version=36,
    ),
    "GB-AIR": CodeListEntry(
        list_number=49,
        code="GB-AIR",
        heading="UK airside",
        notes="Airside outlets at UK international airports only",
        added_version=1,
    ),
    "GB-APS": CodeListEntry(
        list_number=49,
        code="GB-APS",
        heading="UK airports",
        notes="All UK airports, including both airside and other outlets",
        added_version=3,
    ),
    "GB-CHA": CodeListEntry(
        list_number=49,
        code="GB-CHA",
        heading="Channel Islands",
        notes="Deprecated, replaced by country codes GG - Guernsey, and JE - Jersey from List 91",
        added_version=1,
        deprecated_version=13,
    ),
    "GB-ENG": CodeListEntry(
        list_number=49,
        code="GB-ENG",
        heading="England",
        added_version=1,
    ),
    "GB-EWS": CodeListEntry(
        list_number=49,
        code="GB-EWS",
        heading="England, Wales, Scotland",
        notes="UK excluding Northern Ireland. Deprecated - use separate region codes GB-ENG, GB-SCT, GB-WLS instead",
        added_version=1,
        deprecated_version=40,
    ),
    "GB-IOM": CodeListEntry(
        list_number=49,
        code="GB-IOM",
        heading="Isle of Man",
        notes="Deprecated, replaced by country code IM - Isle of Man from List 91",
        added_version=1,
        deprecated_version=13,
    ),
    "GB-NIR": CodeListEntry(
        list_number=49,
        code="GB-NIR",
        heading="Northern Ireland",
        added_version=1,
    ),
    "GB-SCT": CodeListEntry(
        list_number=49,
        code="GB-SCT",
        heading="Scotland",
        added_version=1,
    ),
    "GB-WLS": CodeListEntry(
        list_number=49,
        code="GB-WLS",
        heading="Wales",
        added_version=1,
    ),
    "IE-AIR": CodeListEntry(
        list_number=49,
        code="IE-AIR",
        heading="Ireland airside",
        notes="Airside outlets at Irish international airports only",
        added_version=23,
    ),
    "IT-AG": CodeListEntry(
        list_number=49,
        code="IT-AG",
        heading="Agrigento",
        added_version=24,
    ),
    "IT-AL": CodeListEntry(
        list_number=49,
        code="IT-AL",
        heading="Alessandria",
        added_version=24,
    ),
    "IT-AN": CodeListEntry(
        list_number=49,
        code="IT-AN",
        heading="Ancona",
        added_version=24,
    ),
    "IT-AO": CodeListEntry(
        list_number=49,
        code="IT-AO",
        heading="Aosta",
        added_version=24,
    ),
    "IT-AR": CodeListEntry(
        list_number=49,
        code="IT-AR",
        heading="Arezzo",
        added_version=24,
    ),
    "IT-AP": CodeListEntry(
        list_number=49,
        code="IT-AP",
        heading="Ascoli Piceno",
        added_version=24,
    ),
    "IT-AT": CodeListEntry(
        list_number=49,
        code="IT-AT",
        heading="Asti",
        added_version=24,
    ),
    "IT-AV": CodeListEntry(
        list_number=49,
        code="IT-AV",
        heading="Avellino",
        added_version=24,
    ),
    "IT-BA": CodeListEntry(
        list_number=49,
        code="IT-BA",
        heading="Bari",
        added_version=24,
    ),
    "IT-BT": CodeListEntry(
        list_number=49,
        code="IT-BT",
        heading="Barletta-Andria-Trani",
        added_version=24,
    ),
    "IT-BL": CodeListEntry(
        list_number=49,
        code="IT-BL",
        heading="Belluno",
        added_version=24,
    ),
    "IT-BN": CodeListEntry(
        list_number=49,
        code="IT-BN",
        heading="Benevento",
        added_version=24,
    ),
    "IT-BG": CodeListEntry(
        list_number=49,
        code="IT-BG",
        heading="Bergamo",
        added_version=24,
    ),
    "IT-BI": CodeListEntry(
        list_number=49,
        code="IT-BI",
        heading="Biella",
        added_version=24,
    ),
    "IT-BO": CodeListEntry(
        list_number=49,
        code="IT-BO",
        heading="Bologna",
        added_version=24,
    ),
    "IT-BZ": CodeListEntry(
        list_number=49,
        code="IT-BZ",
        heading="Bolzano",
        added_version=24,
    ),
    "IT-BS": CodeListEntry(
        list_number=49,
        code="IT-BS",
        heading="Brescia",
        added_version=24,
    ),
    "IT-BR": CodeListEntry(
        list_number=49,
        code="IT-BR",
        heading="Brindisi",
        added_version=24,
    ),
    "IT-CA": CodeListEntry(
        list_number=49,
        code="IT-CA",
        heading="Cagliari",
        added_version=24,
    ),
    "IT-CL": CodeListEntry(
        list_number=49,
        code="IT-CL",
        heading="Caltanissetta",
        added_version=24,
    ),
    "IT-CB": CodeListEntry(
        list_number=49,
        code="IT-CB",
        heading="Campobasso",
        added_version=24,
    ),
    "IT-CI": CodeListEntry(
        list_number=49,
        code="IT-CI",
        heading="Carbonia-Iglesias",
        added_version=24,
    ),
    "IT-CE": CodeListEntry(
        list_number=49,
        code="IT-CE",
        heading="Caserta",
        added_version=24,
    ),
    "IT-CT": CodeListEntry(
        list_number=49,
        code="IT-CT",
        heading="Catania",
        added_version=24,
    ),
    "IT-CZ": CodeListEntry(
        list_number=49,
        code="IT-CZ",
        heading="Catanzaro",
        added_version=24,
    ),
    "IT-CH": CodeListEntry(
        list_number=49,
        code="IT-CH",
        heading="Chieti",
        added_version=24,
    ),
    "IT-CO": CodeListEntry(
        list_number=49,
        code="IT-CO",
        heading="Como",
        added_version=24,
    ),
    "IT-CS": CodeListEntry(
        list_number=49,
        code="IT-CS",
        heading="Cosenza",
        added_version=24,
    ),
    "IT-CR": CodeListEntry(
        list_number=49,
        code="IT-CR",
        heading="Cremona",
        added_version=24,
    ),
    "IT-KR": CodeListEntry(
        list_number=49,
        code="IT-KR",
        heading="Crotone",
        added_version=24,
    ),
    "IT-CN": CodeListEntry(
        list_number=49,
        code="IT-CN",
        heading="Cuneo",
        added_version=24,
    ),
    "IT-EN": CodeListEntry(
        list_number=49,
        code="IT-EN",
        heading="Enna",
        added_version=24,
    ),
    "IT-FM": CodeListEntry(
        list_number=49,
        code="IT-FM",
        heading="Fermo",
        added_version=24,
    ),
    "IT-FE": CodeListEntry(
        list_number=49,
        code="IT-FE",
        heading="Ferrara",
        added_version=24,
    ),
    "IT-FI": CodeListEntry(
        list_number=49,
        code="IT-FI",
        heading="Firenze",
        added_version=24,
    ),
    "IT-FG": CodeListEntry(
        list_number=49,
        code="IT-FG",
        heading="Foggia",
        added_version=24,
    ),
    "IT-FC": CodeListEntry(
        list_number=49,
        code="IT-FC",
        heading="Forlì-Cesena",
        added_version=24,
    ),
    "IT-FR": CodeListEntry(
        list_number=49,
        code="IT-FR",
        heading="Frosinone",
        added_version=24,
    ),
    "IT-GE": CodeListEntry(
        list_number=49,
        code="IT-GE",
        heading="Genova",
        added_version=24,
    ),
    "IT-GO": CodeListEntry(
        list_number=49,
        code="IT-GO",
        heading="Gorizia",
        added_version=24,
    ),
    "IT-GR": CodeListEntry(
        list_number=49,
        code="IT-GR",
        heading="Grosseto",
        added_version=24,
    ),
    "IT-IM": CodeListEntry(
        list_number=49,
        code="IT-IM",
        heading="Imperia",
        added_version=24,
    ),
    "IT-IS": CodeListEntry(
        list_number=49,
        code="IT-IS",
        heading="Isernia",
        added_version=24,
    ),
    "IT-SP": CodeListEntry(
        list_number=49,
        code="IT-SP",
        heading="La Spezia",
        added_version=24,
    ),
    "IT-AQ": CodeListEntry(
        list_number=49,
        code="IT-AQ",
        heading="L’Aquila",
        added_version=24,
    ),
    "IT-LT": CodeListEntry(
        list_number=49,
        code="IT-LT",
        heading="Latina",
        added_version=24,
    ),
    "IT-LE": CodeListEntry(
        list_number=49,
        code="IT-LE",
        heading="Lecce",
        added_version=24,
    ),
    "IT-LC": CodeListEntry(
        list_number=49,
        code="IT-LC",
        heading="Lecco",
        added_version=24,
    ),
    "IT-LI": CodeListEntry(
        list_number=49,
        code="IT-LI",
        heading="Livorno",
        added_version=24,
    ),
    "IT-LO": CodeListEntry(
        list_number=49,
        code="IT-LO",
        heading="Lodi",
        added_version=24,
    ),
    "IT-LU": CodeListEntry(
        list_number=49,
        code="IT-LU",
        heading="Lucca",
        added_version=24,
    ),
    "IT-MC": CodeListEntry(
        list_number=49,
        code="IT-MC",
        heading="Macerata",
        added_version=24,
    ),
    "IT-MN": CodeListEntry(
        list_number=49,
        code="IT-MN",
        heading="Mantova",
        added_version=24,
    ),
    "IT-MS": CodeListEntry(
        list_number=49,
        code="IT-MS",
        heading="Massa-Carrara",
        added_version=24,
    ),
    "IT-MT": CodeListEntry(
        list_number=49,
        code="IT-MT",
        heading="Matera",
        added_version=24,
    ),
    "IT-VS": CodeListEntry(
        list_number=49,
        code="IT-VS",
        heading="Medio Campidano",
        added_version=24,
    ),
    "IT-ME": CodeListEntry(
        list_number=49,
        code="IT-ME",
        heading="Messina",
        added_version=24,
    ),
    "IT-MI": CodeListEntry(
        list_number=49,
        code="IT-MI",
        heading="Milano",
        added_version=24,
    ),
    "IT-MO": CodeListEntry(
        list_number=49,
        code="IT-MO",
        heading="Modena",
        added_version=24,
    ),
    "IT-MB": CodeListEntry(
        list_number=49,
        code="IT-MB",
        heading="Monza e Brianza",
        added_version=24,
    ),
    "IT-NA": CodeListEntry(
        list_number=49,
        code="IT-NA",
        heading="Napoli",
        added_version=24,
    ),
    "IT-NO": CodeListEntry(
        list_number=49,
        code="IT-NO",
        heading="Novara",
        added_version=24,
    ),
    "IT-NU": CodeListEntry(
        list_number=49,
        code="IT-NU",
        heading="Nuoro",
        added_version=24,
    ),
    "IT-OG": CodeListEntry(
        list_number=49,
        code="IT-OG",
        heading="Ogliastra",
        added_version=24,
    ),
    "IT-OT": CodeListEntry(
        list_number=49,
        code="IT-OT",
        heading="Olbia-Tempio",
        added_version=24,
    ),
    "IT-OR": CodeListEntry(
        list_number=49,
        code="IT-OR",
        heading="Oristano",
        added_version=24,
    ),
    "IT-PD": CodeListEntry(
        list_number=49,
        code="IT-PD",
        heading="Padova",
        added_version=24,
    ),
    "IT-PA": CodeListEntry(
        list_number=49,
        code="IT-PA",
        heading="Palermo",
        added_version=24,
    ),
    "IT-PR": CodeListEntry(
        list_number=49,
        code="IT-PR",
        heading="Parma",
        added_version=24,
    ),
    "IT-PV": CodeListEntry(
        list_number=49,
        code="IT-PV",
        heading="Pavia",
        added_version=24,
    ),
    "IT-PG": CodeListEntry(
        list_number=49,
        code="IT-PG",
        heading="Perugia",
        added_version=24,
    ),
    "IT-PU": CodeListEntry(
        list_number=49,
        code="IT-PU",
        heading="Pesaro e Urbino",
        added_version=24,
    ),
    "IT-PE": CodeListEntry(
        list_number=49,
        code="IT-PE",
        heading="Pescara",
        added_version=24,
    ),
    "IT-PC": CodeListEntry(
        list_number=49,
        code="IT-PC",
        heading="Piacenza",
        added_version=24,
    ),
    "IT-PI": CodeListEntry(
        list_number=49,
        code="IT-PI",
        heading="Pisa",
        added_version=24,
    ),
    "IT-PT": CodeListEntry(
        list_number=49,
        code="IT-PT",
        heading="Pistoia",
        added_version=24,
    ),
    "IT-PN": CodeListEntry(
        list_number=49,
        code="IT-PN",
        heading="Pordenone",
        added_version=24,
    ),
    "IT-PZ": CodeListEntry(
        list_number=49,
        code="IT-PZ",
        heading="Potenza",
        added_version=24,
    ),
    "IT-PO": CodeListEntry(
        list_number=49,
        code="IT-PO",
        heading="Prato",
        added_version=24,
    ),
    "IT-RG": CodeListEntry(
        list_number=49,
        code="IT-RG",
        heading="Ragusa",
        added_version=24,
    ),
    "IT-RA": CodeListEntry(
        list_number=49,
        code="IT-RA",
        heading="Ravenna",
        added_version=24,
    ),
    "IT-RC": CodeListEntry(
        list_number=49,
        code="IT-RC",
        heading="Reggio Calabria",
        added_version=24,
    ),
    "IT-RE": CodeListEntry(
        list_number=49,
        code="IT-RE",
        heading="Reggio Emilia",
        added_version=24,
    ),
    "IT-RI": CodeListEntry(
        list_number=49,
        code="IT-RI",
        heading="Rieti",
        added_version=24,
    ),
    "IT-RN": CodeListEntry(
        list_number=49,
        code="IT-RN",
        heading="Rimini",
        added_version=24,
    ),
    "IT-RM": CodeListEntry(
        list_number=49,
        code="IT-RM",
        heading="Roma",
        added_version=24,
    ),
    "IT-RO": CodeListEntry(
        list_number=49,
        code="IT-RO",
        heading="Rovigo",
        added_version=24,
    ),
    "IT-SA": CodeListEntry(
        list_number=49,
        code="IT-SA",
        heading="Salerno",
        added_version=24,
    ),
    "IT-SS": CodeListEntry(
        list_number=49,
        code="IT-SS",
        heading="Sassari",
        added_version=24,
    ),
    "IT-SV": CodeListEntry(
        list_number=49,
        code="IT-SV",
        heading="Savona",
        added_version=24,
    ),
    "IT-SI": CodeListEntry(
        list_number=49,
        code="IT-SI",
        heading="Siena",
        added_version=24,
    ),
    "IT-SR": CodeListEntry(
        list_number=49,
        code="IT-SR",
        heading="Siracusa",
        added_version=24,
    ),
    "IT-SO": CodeListEntry(
        list_number=49,
        code="IT-SO",
        heading="Sondrio",
        added_version=24,
    ),
    "IT-TA": CodeListEntry(
        list_number=49,
        code="IT-TA",
        heading="Taranto",
        added_version=24,
    ),
    "IT-TE": CodeListEntry(
        list_number=49,
        code="IT-TE",
        heading="Teramo",
        added_version=24,
    ),
    "IT-TR": CodeListEntry(
        list_number=49,
        code="IT-TR",
        heading="Terni",
        added_version=24,
    ),
    "IT-TO": CodeListEntry(
        list_number=49,
        code="IT-TO",
        heading="Torino",
        added_version=24,
    ),
    "IT-TP": CodeListEntry(
        list_number=49,
        code="IT-TP",
        heading="Trapani",
        added_version=24,
    ),
    "IT-TN": CodeListEntry(
        list_number=49,
        code="IT-TN",
        heading="Trento",
        added_version=24,
    ),
    "IT-TV": CodeListEntry(
        list_number=49,
        code="IT-TV",
        heading="Treviso",
        added_version=24,
    ),
    "IT-TS": CodeListEntry(
        list_number=49,
        code="IT-TS",
        heading="Trieste",
        added_version=24,
    ),
    "IT-UD": CodeListEntry(
        list_number=49,
        code="IT-UD",
        heading="Udine",
        added_version=24,
    ),
    "IT-VA": CodeListEntry(
        list_number=49,
        code="IT-VA",
        heading="Varese",
        added_version=24,
    ),
    "IT-VE": CodeListEntry(
        list_number=49,
        code="IT-VE",
        heading="Venezia",
        added_version=24,
    ),
    "IT-VB": CodeListEntry(
        list_number=49,
        code="IT-VB",
        heading="Verbano-Cusio-Ossola",
        added_version=24,
    ),
    "IT-VC": CodeListEntry(
        list_number=49,
        code="IT-VC",
        heading="Vercelli",
        added_version=24,
    ),
    "IT-VR": CodeListEntry(
        list_number=49,
        code="IT-VR",
        heading="Verona",
        added_version=24,
    ),
    "IT-VV": CodeListEntry(
        list_number=49,
        code="IT-VV",
        heading="Vibo Valentia",
        added_version=24,
    ),
    "IT-VI": CodeListEntry(
        list_number=49,
        code="IT-VI",
        heading="Vicenza",
        added_version=24,
    ),
    "IT-VT": CodeListEntry(
        list_number=49,
        code="IT-VT",
        heading="Viterbo",
        added_version=24,
    ),
    "RS-KM": CodeListEntry(
        list_number=49,
        code="RS-KM",
        heading="Kosovo-Metohija",
        added_version=28,
    ),
    "RS-VO": CodeListEntry(
        list_number=49,
        code="RS-VO",
        heading="Vojvodina",
        added_version=28,
    ),
    "RU-AD": CodeListEntry(
        list_number=49,
        code="RU-AD",
        heading="Republic of Adygeya",
        added_version=22,
    ),
    "RU-AL": CodeListEntry(
        list_number=49,
        code="RU-AL",
        heading="Republic of Altay",
        added_version=22,
    ),
    "RU-BA": CodeListEntry(
        list_number=49,
        code="RU-BA",
        heading="Republic of Bashkortostan",
        added_version=22,
    ),
    "RU-BU": CodeListEntry(
        list_number=49,
        code="RU-BU",
        heading="Republic of Buryatiya",
        added_version=22,
    ),
    "RU-CE": CodeListEntry(
        list_number=49,
        code="RU-CE",
        heading="Chechenskaya Republic",
        added_version=22,
    ),
    "RU-CU": CodeListEntry(
        list_number=49,
        code="RU-CU",
        heading="Chuvashskaya Republic",
        added_version=22,
    ),
    "RU-DA": CodeListEntry(
        list_number=49,
        code="RU-DA",
        heading="Republic of Dagestan",
        added_version=22,
    ),
    "RU-IN": CodeListEntry(
        list_number=49,
        code="RU-IN",
        heading="Republic of Ingushetiya",
        added_version=22,
    ),
    "RU-KB": CodeListEntry(
        list_number=49,
        code="RU-KB",
        heading="Kabardino-Balkarskaya Republic",
        added_version=22,
    ),
    "RU-KL": CodeListEntry(
        list_number=49,
        code="RU-KL",
        heading="Republic of Kalmykiya",
        added_version=22,
    ),
    "RU-KC": CodeListEntry(
        list_number=49,
        code="RU-KC",
        heading="Karachayevo-Cherkesskaya Republic",
        added_version=22,
    ),
    "RU-KR": CodeListEntry(
        list_number=49,
        code="RU-KR",
        heading="Republic of Kareliya",
        added_version=22,
    ),
    "RU-KK": CodeListEntry(
        list_number=49,
        code="RU-KK",
        heading="Republic of Khakasiya",
        added_version=22,
    ),
    "RU-KO": CodeListEntry(
        list_number=49,
        code="RU-KO",
        heading="Republic of Komi",
        added_version=22,
    ),
    "RU-ME": CodeListEntry(
        list_number=49,
        code="RU-ME",
        heading="Republic of Mariy El",
        added_version=22,
    ),
    "RU-MO": CodeListEntry(
        list_number=49,
        code="RU-MO",
        heading="Republic of Mordoviya",
        added_version=22,
    ),
    "RU-SA": CodeListEntry(
        list_number=49,
        code="RU-SA",
        heading="Republic of Sakha (Yakutiya)",
        added_version=22,
    ),
    "RU-SE": CodeListEntry(
        list_number=49,
        code="RU-SE",
        heading="Republic of Severnaya Osetiya-Alaniya",
        added_version=22,
    ),
    "RU-TA": CodeListEntry(
        list_number=49,
        code="RU-TA",
        heading="Republic of Tatarstan",
        added_version=22,
    ),
    "RU-TY": CodeListEntry(
        list_number=49,
        code="RU-TY",
        heading="Republic of Tyva (Tuva)",
        added_version=22,
    ),
    "RU-UD": CodeListEntry(
        list_number=49,
        code="RU-UD",
        heading="Udmurtskaya Republic",
        added_version=22,
    ),
    "RU-ALT": CodeListEntry(
        list_number=49,
        code="RU-ALT",
        heading="Altayskiy Administrative Territory",
        added_version=22,
    ),
    "RU-KAM": CodeListEntry(
        list_number=49,
        code="RU-KAM",
        heading="Kamchatskiy Administrative Territory",
        added_version=22,
    ),
    "RU-KHA": CodeListEntry(
        list_number=49,
        code="RU-KHA",
        heading="Khabarovskiy Administrative Territory",
        added_version=22,
    ),
    "RU-KDA": CodeListEntry(
        list_number=49,
        code="RU-KDA",
        heading="Krasnodarskiy Administrative Territory",
        added_version=22,
    ),
    "RU-KYA": CodeListEntry(
        list_number=49,
        code="RU-KYA",
        heading="Krasnoyarskiy Administrative Territory",
        added_version=22,
    ),
    "RU-PER": CodeListEntry(
        list_number=49,
        code="RU-PER",
        heading="Permskiy Administrative Territory",
        added_version=22,
    ),
    "RU-PRI": CodeListEntry(
        list_number=49,
        code="RU-PRI",
        heading="Primorskiy Administrative Territory",
        added_version=22,
    ),
    "RU-STA": CodeListEntry(
        list_number=49,
        code="RU-STA",
        heading="Stavropol’skiy Administrative Territory",
        added_version=22,
    ),
    "RU-ZAB": CodeListEntry(
        list_number=49,
        code="RU-ZAB",
        heading="Zabaykal’skiy Administrative Territory",
        added_version=22,
    ),
    "RU-AMU": CodeListEntry(
        list_number=49,
        code="RU-AMU",
        heading="Amurskaya Administrative Region",
        added_version=22,
    ),
    "RU-ARK": CodeListEntry(
        list_number=49,
        code="RU-ARK",
        heading="Arkhangel’skaya Administrative Region",
        added_version=22,
    ),
    "RU-AST": CodeListEntry(
        list_number=49,
        code="RU-AST",
        heading="Astrakhanskaya Administrative Region",
        added_version=22,
    ),
    "RU-BEL": CodeListEntry(
        list_number=49,
        code="RU-BEL",
        heading="Belgorodskaya Administrative Region",
        added_version=22,
    ),
    "RU-BRY": CodeListEntry(
        list_number=49,
        code="RU-BRY",
        heading="Bryanskaya Administrative Region",
        added_version=22,
    ),
    "RU-CHE": CodeListEntry(
        list_number=49,
        code="RU-CHE",
        heading="Chelyabinskaya Administrative Region",
        added_version=22,
    ),
    "RU-IRK": CodeListEntry(
        list_number=49,
        code="RU-IRK",
        heading="Irkutskaya Administrative Region",
        added_version=22,
    ),
    "RU-IVA": CodeListEntry(
        list_number=49,
        code="RU-IVA",
        heading="Ivanovskaya Administrative Region",
        added_version=22,
    ),
    "RU-KGD": CodeListEntry(
        list_number=49,
        code="RU-KGD",
        heading="Kaliningradskaya Administrative Region",
        added_version=22,
    ),
    "RU-KLU": CodeListEntry(
        list_number=49,
        code="RU-KLU",
        heading="Kaluzhskaya Administrative Region",
        added_version=22,
    ),
    "RU-KEM": CodeListEntry(
        list_number=49,
        code="RU-KEM",
        heading="Kemerovskaya Administrative Region",
        added_version=22,
    ),
    "RU-KIR": CodeListEntry(
        list_number=49,
        code="RU-KIR",
        heading="Kirovskaya Administrative Region",
        added_version=22,
    ),
    "RU-KOS": CodeListEntry(
        list_number=49,
        code="RU-KOS",
        heading="Kostromskaya Administrative Region",
        added_version=22,
    ),
    "RU-KGN": CodeListEntry(
        list_number=49,
        code="RU-KGN",
        heading="Kurganskaya Administrative Region",
        added_version=22,
    ),
    "RU-KRS": CodeListEntry(
        list_number=49,
        code="RU-KRS",
        heading="Kurskaya Administrative Region",
        added_version=22,
    ),
    "RU-LEN": CodeListEntry(
        list_number=49,
        code="RU-LEN",
        heading="Leningradskaya Administrative Region",
        added_version=22,
    ),
    "RU-LIP": CodeListEntry(
        list_number=49,
        code="RU-LIP",
        heading="Lipetskaya Administrative Region",
        added_version=22,
    ),
    "RU-MAG": CodeListEntry(
        list_number=49,
        code="RU-MAG",
        heading="Magadanskaya Administrative Region",
        added_version=22,
    ),
    "RU-MOS": CodeListEntry(
        list_number=49,
        code="RU-MOS",
        heading="Moskovskaya Administrative Region",
        added_version=22,
    ),
    "RU-MUR": CodeListEntry(
        list_number=49,
        code="RU-MUR",
        heading="Murmanskaya Administrative Region",
        added_version=22,
    ),
    "RU-NIZ": CodeListEntry(
        list_number=49,
        code="RU-NIZ",
        heading="Nizhegorodskaya Administrative Region",
        added_version=22,
    ),
    "RU-NGR": CodeListEntry(
        list_number=49,
        code="RU-NGR",
        heading="Novgorodskaya Administrative Region",
        added_version=22,
    ),
    "RU-NVS": CodeListEntry(
        list_number=49,
        code="RU-NVS",
        heading="Novosibirskaya Administrative Region",
        added_version=22,
    ),
    "RU-OMS": CodeListEntry(
        list_number=49,
        code="RU-OMS",
        heading="Omskaya Administrative Region",
        added_version=22,
    ),
    "RU-ORE": CodeListEntry(
        list_number=49,
        code="RU-ORE",
        heading="Orenburgskaya Administrative Region",
        added_version=22,
    ),
    "RU-ORL": CodeListEntry(
        list_number=49,
        code="RU-ORL",
        heading="Orlovskaya Administrative Region",
        added_version=22,
    ),
    "RU-PNZ": CodeListEntry(
        list_number=49,
        code="RU-PNZ",
        heading="Penzenskaya Administrative Region",
        added_version=22,
    ),
    "RU-PSK": CodeListEntry(
        list_number=49,
        code="RU-PSK",
        heading="Pskovskaya Administrative Region",
        added_version=22,
    ),
    "RU-ROS": CodeListEntry(
        list_number=49,
        code="RU-ROS",
        heading="Rostovskaya Administrative Region",
        added_version=22,
    ),
    "RU-RYA": CodeListEntry(
        list_number=49,
        code="RU-RYA",
        heading="Ryazanskaya Administrative Region",
        added_version=22,
    ),
    "RU-SAK": CodeListEntry(
        list_number=49,
        code="RU-SAK",
        heading="Sakhalinskaya Administrative Region",
        added_version=22,
    ),
    "RU-SAM": CodeListEntry(
        list_number=49,
        code="RU-SAM",
        heading="Samarskaya Administrative Region",
        added_version=22,
    ),
    "RU-SAR": CodeListEntry(
        list_number=49,
        code="RU-SAR",
        heading="Saratovskaya Administrative Region",
        added_version=22,
    ),
    "RU-SMO": CodeListEntry(
        list_number=49,
        code="RU-SMO",
        heading="Smolenskaya Administrative Region",
        added_version=22,
    ),
    "RU-SVE": CodeListEntry(
        list_number=49,
        code="RU-SVE",
        heading="Sverdlovskaya Administrative Region",
        added_version=22,
    ),
    "RU-TAM": CodeListEntry(
        list_number=49,
        code="RU-TAM",
        heading="Tambovskaya Administrative Region",
        added_version=22,
    ),
    "RU-TOM": CodeListEntry(
        list_number=49,
        code="RU-TOM",
        heading="Tomskaya Administrative Region",
        added_version=22,
    ),
    "RU-TUL": CodeListEntry(
        list_number=49,
        code="RU-TUL",
        heading="Tul’skaya Administrative Region",
        added_version=22,
    ),
    "RU-TVE": CodeListEntry(
        list_number=49,
        code="RU-TVE",
        heading="Tverskaya Administrative Region",
        added_version=22,
    ),
    "RU-TYU": CodeListEntry(
        list_number=49,
        code="RU-TYU",
        heading="Tyumenskaya Administrative Region",
        added_version=22,
    ),
    "RU-ULY": CodeListEntry(
        list_number=49,
        code="RU-ULY",
        heading="Ul’yanovskaya Administrative Region",
        added_version=22,
    ),
    "RU-VLA": CodeListEntry(
        list_number=49,
        code="RU-VLA",
        heading="Vladimirskaya Administrative Region",
        added_version=22,
    ),
    "RU-VGG": CodeListEntry(
        list_number=49,
        code="RU-VGG",
        heading="Volgogradskaya Administrative Region",
        added_version=22,
    ),
    "RU-VLG": CodeListEntry(
        list_number=49,
        code="RU-VLG",
        heading="Vologodskaya Administrative Region",
        added_version=22,
    ),
    "RU-VOR": CodeListEntry(
        list_number=49,
        code="RU-VOR",
        heading="Voronezhskaya Administrative Region",
        added_version=22,
    ),
    "RU-YAR": CodeListEntry(
        list_number=49,
        code="RU-YAR",
        heading="Yaroslavskaya Administrative Region",
        added_version=22,
    ),
    "RU-MOW": CodeListEntry(
        list_number=49,
        code="RU-MOW",
        heading="Moskva City",
        added_version=22,
    ),
    "RU-SPE": CodeListEntry(
        list_number=49,
        code="RU-SPE",
        heading="Sankt-Peterburg City",
        added_version=22,
    ),
    "RU-YEV": CodeListEntry(
        list_number=49,
        code="RU-YEV",
        heading="Yevreyskaya Autonomous Administrative Region",
        added_version=22,
    ),
    "RU-CHU": CodeListEntry(
        list_number=49,
        code="RU-CHU",
        heading="Chukotskiy Autonomous District",
        added_version=22,
    ),
    "RU-KHM": CodeListEntry(
        list_number=49,
        code="RU-KHM",
        heading="Khanty-Mansiyskiy Autonomous District",
        added_version=22,
    ),
    "RU-NEN": CodeListEntry(
        list_number=49,
        code="RU-NEN",
        heading="Nenetskiy Autonomous District",
        added_version=22,
    ),
    "RU-YAN": CodeListEntry(
        list_number=49,
        code="RU-YAN",
        heading="Yamalo-Nenetskiy Autonomous District",
        added_version=22,
    ),
    "US-AK": CodeListEntry(
        list_number=49,
        code="US-AK",
        heading="Alaska",
        added_version=9,
    ),
    "US-AL": CodeListEntry(
        list_number=49,
        code="US-AL",
        heading="Alabama",
        added_version=9,
    ),
    "US-AR": CodeListEntry(
        list_number=49,
        code="US-AR",
        heading="Arkansas",
        added_version=9,
    ),
    "US-AZ": CodeListEntry(
        list_number=49,
        code="US-AZ",
        heading="Arizona",
        added_version=9,
    ),
    "US-CA": CodeListEntry(
        list_number=49,
        code="US-CA",
        heading="California",
        added_version=9,
    ),
    "US-CO": CodeListEntry(
        list_number=49,
        code="US-CO",
        heading="Colorado",
        added_version=9,
    ),
    "US-CT": CodeListEntry(
        list_number=49,
        code="US-CT",
        heading="Connecticut",
        added_version=9,
    ),
    "US-DC": CodeListEntry(
        list_number=49,
        code="US-DC",
        heading="District of Columbia",
        added_version=9,
    ),
    "US-DE": CodeListEntry(
        list_number=49,
        code="US-DE",
        heading="Delaware",
        added_version=9,
    ),
    "US-FL": CodeListEntry(
        list_number=49,
        code="US-FL",
        heading="Florida",
        added_version=9,
    ),
    "US-GA": CodeListEntry(
        list_number=49,
        code="US-GA",
        heading="Georgia",
        added_version=9,
    ),
    "US-HI": CodeListEntry(
        list_number=49,
        code="US-HI",
        heading="Hawaii",
        added_version=9,
    ),
    "US-IA": CodeListEntry(
        list_number=49,
        code="US-IA",
        heading="Iowa",
        added_version=9,
    ),
    "US-ID": CodeListEntry(
        list_number=49,
        code="US-ID",
        heading="Idaho",
        added_version=9,
    ),
    "US-IL": CodeListEntry(
        list_number=49,
        code="US-IL",
        heading="Illinois",
        added_version=9,
    ),
    "US-IN": CodeListEntry(
        list_number=49,
        code="US-IN",
        heading="Indiana",
        added_version=9,
    ),
    "US-KS": CodeListEntry(
        list_number=49,
        code="US-KS",
        heading="Kansas",
        added_version=9,
    ),
    "US-KY": CodeListEntry(
        list_number=49,
        code="US-KY",
        heading="Kentucky",
        added_version=9,
    ),
    "US-LA": CodeListEntry(
        list_number=49,
        code="US-LA",
        heading="Louisiana",
        added_version=9,
    ),
    "US-MA": CodeListEntry(
        list_number=49,
        code="US-MA",
        heading="Massachusetts",
        added_version=9,
    ),
    "US-MD": CodeListEntry(
        list_number=49,
        code="US-MD",
        heading="Maryland",
        added_version=9,
    ),
    "US-ME": CodeListEntry(
        list_number=49,
        code="US-ME",
        heading="Maine",
        added_version=9,
    ),
    "US-MI": CodeListEntry(
        list_number=49,
        code="US-MI",
        heading="Michigan",
        added_version=9,
    ),
    "US-MN": CodeListEntry(
        list_number=49,
        code="US-MN",
        heading="Minnesota",
        added_version=9,
    ),
    "US-MO": CodeListEntry(
        list_number=49,
        code="US-MO",
        heading="Missouri",
        added_version=9,
    ),
    "US-MS": CodeListEntry(
        list_number=49,
        code="US-MS",
        heading="Mississippi",
        added_version=9,
    ),
    "US-MT": CodeListEntry(
        list_number=49,
        code="US-MT",
        heading="Montana",
        added_version=9,
    ),
    "US-NC": CodeListEntry(
        list_number=49,
        code="US-NC",
        heading="North Carolina",
        added_version=9,
    ),
    "US-ND": CodeListEntry(
        list_number=49,
        code="US-ND",
        heading="North Dakota",
        added_version=9,
    ),
    "US-NE": CodeListEntry(
        list_number=49,
        code="US-NE",
        heading="Nebraska",
        added_version=9,
    ),
    "US-NH": CodeListEntry(
        list_number=49,
        code="US-NH",
        heading="New Hampshire",
        added_version=9,
    ),
    "US-NJ": CodeListEntry(
        list_number=49,
        code="US-NJ",
        heading="New Jersey",
        added_version=9,
    ),
    "US-NM": CodeListEntry(
        list_number=49,
        code="US-NM",
        heading="New Mexico",
        added_version=9,
    ),
    "US-NV": CodeListEntry(
        list_number=49,
        code="US-NV",
        heading="Nevada",
        added_version=9,
    ),
    "US-NY": CodeListEntry(
        list_number=49,
        code="US-NY",
        heading="New York",
        added_version=9,
    ),
    "US-OH": CodeListEntry(
        list_number=49,
        code="US-OH",
        heading="Ohio",
        added_version=9,
    ),
    "US-OK": CodeListEntry(
        list_number=49,
        code="US-OK",
        heading="Oklahoma",
        added_version=9,
    ),
    "US-OR": CodeListEntry(
        list_number=49,
        code="US-OR",
        heading="Oregon",
        added_version=9,
    ),
    "US-PA": CodeListEntry(
        list_number=49,
        code="US-PA",
        heading="Pennsylvania",
        added_version=9,
    ),
    "US-RI": CodeListEntry(
        list_number=49,
        code="US-RI",
        heading="Rhode Island",
        added_version=9,
    ),
    "US-SC": CodeListEntry(
        list_number=49,
        code="US-SC",
        heading="South Carolina",
        added_version=9,
    ),
    "US-SD": CodeListEntry(
        list_number=49,
        code="US-SD",
        heading="South Dakota",
        added_version=9,
    ),
    "US-TN": CodeListEntry(
        list_number=49,
        code="US-TN",
        heading="Tennessee",
        added_version=9,
    ),
    "US-TX": CodeListEntry(
        list_number=49,
        code="US-TX",
        heading="Texas",
        added_version=9,
    ),
    "US-UT": CodeListEntry(
        list_number=49,
        code="US-UT",
        heading="Utah",
        added_version=9,
    ),
    "US-VA": CodeListEntry(
        list_number=49,
        code="US-VA",
        heading="Virginia",
        added_version=9,
    ),
    "US-VT": CodeListEntry(
        list_number=49,
        code="US-VT",
        heading="Vermont",
        added_version=9,
    ),
    "US-WA": CodeListEntry(
        list_number=49,
        code="US-WA",
        heading="Washington",
        added_version=9,
    ),
    "US-WI": CodeListEntry(
        list_number=49,
        code="US-WI",
        heading="Wisconsin",
        added_version=9,
    ),
    "US-WV": CodeListEntry(
        list_number=49,
        code="US-WV",
        heading="West Virginia",
        added_version=9,
    ),
    "US-WY": CodeListEntry(
        list_number=49,
        code="US-WY",
        heading="Wyoming",
        added_version=9,
    ),
    "ECZ": CodeListEntry(
        list_number=49,
        code="ECZ",
        heading="Eurozone",
        notes="Countries geographically within continental Europe which use the Euro as their sole currency. At the time of writing, this is a synonym for ‘AT BE CY EE FI FR DE ES GR HR IE IT LT LU LV MT NL PT SI SK’ (the official Eurozone 20), plus ‘AD MC SM VA ME’ and Kosovo (other Euro-using countries in continental Europe). Note some other territories using the Euro, but outside continental Europe are excluded from this list, and may need to be specified separately. ONLY valid in ONIX 3.0, and ONLY within P.26 - and this use is itself Deprecated. Use of an explicit list of countries instead of ECZ is strongly encouraged",
        added_version=13,
        deprecated_version=35,
    ),
    "WORLD": CodeListEntry(
        list_number=49,
        code="WORLD",
        heading="World",
        notes="In ONIX 3.0 and later, may ONLY be used in <RegionsIncluded>",
        added_version=1,
    ),
}

List49 = CodeList(
    number=49,
    heading="Region - based on ISO 3166-2",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
RegionBasedOnIso31662 = List49
RegionCode = List49  # Shorter alias
