"""ONIX Code List 150: Product form."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "00": CodeListEntry(
        list_number=150,
        code="00",
        heading="Undefined",
    ),
    "AA": CodeListEntry(
        list_number=150,
        code="AA",
        heading="Audio",
        notes="Audio recording - detail unspecified. Use only when the form is unknown and no further detail can be provided. Prefer AZ plus <ProductFormDescription> if detail is available but no other A* code applies",
    ),
    "AB": CodeListEntry(
        list_number=150,
        code="AB",
        heading="Audio cassette",
        notes="Audio cassette (analogue)",
    ),
    "AC": CodeListEntry(
        list_number=150,
        code="AC",
        heading="CD-Audio",
        notes="Audio compact disc: use for ‘Red book’ discs (conventional audio CD) and SACD, and use coding in <ProductFormDetail> to specify the format, if required",
        added_version=8,
    ),
    "AD": CodeListEntry(
        list_number=150,
        code="AD",
        heading="DAT",
        notes="Digital audio tape cassette",
    ),
    "AE": CodeListEntry(
        list_number=150,
        code="AE",
        heading="Audio disc",
        notes="Audio disc (excluding CD-Audio): use for ‘Yellow book’ (CD-Rom-style) discs, including for example mp3 CDs, and use coding in <ProductFormDetail> to specify the format of the data on the disc",
    ),
    "AF": CodeListEntry(
        list_number=150,
        code="AF",
        heading="Audio tape",
        notes="Audio tape (analogue open reel tape)",
    ),
    "AG": CodeListEntry(
        list_number=150,
        code="AG",
        heading="MiniDisc",
        notes="Sony MiniDisc format",
        added_version=2,
    ),
    "AH": CodeListEntry(
        list_number=150,
        code="AH",
        heading="CD-Extra",
        notes="Audio compact disc with part CD-ROM content, also termed CD-Plus or Enhanced-CD: use for ‘Blue book’ and ‘Yellow/Red book’ two-session discs",
        added_version=2,
    ),
    "AI": CodeListEntry(
        list_number=150,
        code="AI",
        heading="DVD Audio",
        added_version=2,
    ),
    "AJ": CodeListEntry(
        list_number=150,
        code="AJ",
        heading="Downloadable audio file",
        notes="Digital audio recording downloadable to the purchaser’s own device(s)",
        added_version=2,
    ),
    "AK": CodeListEntry(
        list_number=150,
        code="AK",
        heading="Pre-recorded digital audio player",
        notes="For example, Playaway audiobook and player: use coding in <ProductFormDetail> to specify the recording format, if required",
        added_version=11,
    ),
    "AL": CodeListEntry(
        list_number=150,
        code="AL",
        heading="Pre-recorded SD card",
        notes="For example, Audiofy audiobook chip",
        added_version=7,
    ),
    "AM": CodeListEntry(
        list_number=150,
        code="AM",
        heading="LP",
        notes="‘Long player’. Vinyl disc (analogue), typically 12 inches diameter and played at 33⅓rpm",
        added_version=38,
    ),
    "AN": CodeListEntry(
        list_number=150,
        code="AN",
        heading="Downloadable and online audio file",
        notes="Digital audio recording available both by download to the purchaser’s own device(s) and by online (eg streamed) access",
        added_version=39,
    ),
    "AO": CodeListEntry(
        list_number=150,
        code="AO",
        heading="Online audio file",
        notes="Digital audio recording available online (eg streamed), not downloadable to the purchaser’s own device(s)",
        added_version=39,
    ),
    "AZ": CodeListEntry(
        list_number=150,
        code="AZ",
        heading="Other audio format",
        notes="Other audio format not specified by AB to AO. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "BA": CodeListEntry(
        list_number=150,
        code="BA",
        heading="Book",
        notes="Book - detail unspecified. Use only when the form is unknown and no further detail can be provided. Prefer BZ plus <ProductFormDescription> if detail is available but no other B* code applies",
    ),
    "BB": CodeListEntry(
        list_number=150,
        code="BB",
        heading="Hardback",
        notes="Hardback or cased book",
    ),
    "BC": CodeListEntry(
        list_number=150,
        code="BC",
        heading="Paperback / softback",
        notes="Paperback or other softback book",
    ),
    "BD": CodeListEntry(
        list_number=150,
        code="BD",
        heading="Loose-leaf",
        notes="Loose-leaf book",
    ),
    "BE": CodeListEntry(
        list_number=150,
        code="BE",
        heading="Spiral bound",
        notes="Spiral, comb or coil bound book",
    ),
    "BF": CodeListEntry(
        list_number=150,
        code="BF",
        heading="Pamphlet",
        notes="Pamphlet, stapled (de: ‘geheftet’). Includes low-extent wire-stitched books bound without a distinct spine (eg many comic book ‘floppies’)",
    ),
    "BG": CodeListEntry(
        list_number=150,
        code="BG",
        heading="Leather / fine binding",
        notes="Use <ProductFormDetail> to provide additional description",
    ),
    "BH": CodeListEntry(
        list_number=150,
        code="BH",
        heading="Board book",
        notes="Child’s book with all pages printed on board",
    ),
    "BI": CodeListEntry(
        list_number=150,
        code="BI",
        heading="Rag book",
        notes="Child’s book with all pages printed on textile",
    ),
    "BJ": CodeListEntry(
        list_number=150,
        code="BJ",
        heading="Bath book",
        notes="Child’s book printed on waterproof material",
    ),
    "BK": CodeListEntry(
        list_number=150,
        code="BK",
        heading="Novelty book",
        notes="A book whose novelty consists wholly or partly in a format which cannot be described by any other available code - a ‘conventional’ format code is always to be preferred; one or more Product Form Detail codes, eg from the B2nn group, should be used whenever possible to provide additional description",
        added_version=2,
    ),
    "BL": CodeListEntry(
        list_number=150,
        code="BL",
        heading="Slide bound",
        notes="Slide bound book",
        added_version=2,
    ),
    "BM": CodeListEntry(
        list_number=150,
        code="BM",
        heading="Big book",
        notes="Extra-large format for teaching etc; this format and terminology may be specifically UK; required as a top-level differentiator",
        added_version=2,
    ),
    "BN": CodeListEntry(
        list_number=150,
        code="BN",
        heading="Part-work (fascículo)",
        notes="A part-work issued with its own ISBN and intended to be collected and bound into a complete book",
        added_version=6,
    ),
    "BO": CodeListEntry(
        list_number=150,
        code="BO",
        heading="Fold-out book or chart",
        notes="Concertina-folded booklet or chart, designed to fold to pocket or regular page size, and usually bound within distinct board or card covers (de: ‘Leporello’)",
        added_version=8,
    ),
    "BP": CodeListEntry(
        list_number=150,
        code="BP",
        heading="Foam book",
        notes="A children’s book whose cover and pages are made of foam",
        added_version=10,
    ),
    "BZ": CodeListEntry(
        list_number=150,
        code="BZ",
        heading="Other book format",
        notes="Other book format or binding not specified by BB to BP. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "CA": CodeListEntry(
        list_number=150,
        code="CA",
        heading="Sheet map",
        notes="Sheet map - detail unspecified. Use only when the form is unknown and no further detail can be provided. Prefer CZ plus <ProductFormDescription> if detail is available but no other C* code applies",
    ),
    "CB": CodeListEntry(
        list_number=150,
        code="CB",
        heading="Sheet map, folded",
    ),
    "CC": CodeListEntry(
        list_number=150,
        code="CC",
        heading="Sheet map, flat",
    ),
    "CD": CodeListEntry(
        list_number=150,
        code="CD",
        heading="Sheet map, rolled",
        notes="See <ProductPackaging> and Codelist 80 for ‘rolled in tube’",
    ),
    "CE": CodeListEntry(
        list_number=150,
        code="CE",
        heading="Globe",
        notes="Globe or planisphere",
    ),
    "CZ": CodeListEntry(
        list_number=150,
        code="CZ",
        heading="Other cartographic",
        notes="Other cartographic format not specified by CB to CE. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "DA": CodeListEntry(
        list_number=150,
        code="DA",
        heading="Digital (on physical carrier)",
        notes="Digital content delivered on a physical carrier (detail unspecified). Use only when the form is unknown and no further detail can be provided. Prefer DZ plus <ProductFormDescription> if detail is available but no other D* code applies",
    ),
    "DB": CodeListEntry(
        list_number=150,
        code="DB",
        heading="CD-ROM",
    ),
    "DC": CodeListEntry(
        list_number=150,
        code="DC",
        heading="CD-I",
        notes="CD interactive: use for ‘Green book’ discs",
    ),
    "DE": CodeListEntry(
        list_number=150,
        code="DE",
        heading="Game cartridge",
    ),
    "DF": CodeListEntry(
        list_number=150,
        code="DF",
        heading="Diskette",
        notes="AKA ‘floppy disc’",
    ),
    "DI": CodeListEntry(
        list_number=150,
        code="DI",
        heading="DVD-ROM",
        added_version=2,
    ),
    "DJ": CodeListEntry(
        list_number=150,
        code="DJ",
        heading="Secure Digital (SD) Memory Card",
        added_version=6,
    ),
    "DK": CodeListEntry(
        list_number=150,
        code="DK",
        heading="Compact Flash Memory Card",
        added_version=6,
    ),
    "DL": CodeListEntry(
        list_number=150,
        code="DL",
        heading="Memory Stick Memory Card",
        added_version=6,
    ),
    "DM": CodeListEntry(
        list_number=150,
        code="DM",
        heading="USB Flash Drive",
        added_version=6,
    ),
    "DN": CodeListEntry(
        list_number=150,
        code="DN",
        heading="Double-sided CD/DVD",
        notes="Double-sided disc, one side Audio CD/CD-ROM, other side DVD",
        added_version=7,
    ),
    "DO": CodeListEntry(
        list_number=150,
        code="DO",
        heading="BR-ROM",
        notes="(Blu Ray ROM)",
        added_version=51,
    ),
    "DZ": CodeListEntry(
        list_number=150,
        code="DZ",
        heading="Other digital carrier",
        notes="Other carrier of digital content not specified by DB to DO. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "EA": CodeListEntry(
        list_number=150,
        code="EA",
        heading="Digital (delivered electronically)",
        notes="Digital content delivered electronically (delivery method unspecified). Use only when the form and delivery method is unknown, or when no other E* code applies and the delivery method is described in <ProductFormDescription>. Note, use <ProductFormDetail> to specify file format",
        added_version=9,
    ),
    "EB": CodeListEntry(
        list_number=150,
        code="EB",
        heading="Digital download and online",
        notes="Digital content available both by download and by online access",
        added_version=9,
    ),
    "EC": CodeListEntry(
        list_number=150,
        code="EC",
        heading="Digital online",
        notes="Digital content accessed online only (eg streamed), not downloadable to the purchaser’s own device(s)",
        added_version=9,
    ),
    "ED": CodeListEntry(
        list_number=150,
        code="ED",
        heading="Digital download",
        notes="Digital content delivered by download only",
        added_version=9,
    ),
    "FA": CodeListEntry(
        list_number=150,
        code="FA",
        heading="Film or transparency",
        notes="Film or transparency - detail unspecified. Use only when the form is unknown and no further detail can be provided. Prefer FZ plus <ProductFormDescription> if detail is available but no other F* code applies",
    ),
    "FC": CodeListEntry(
        list_number=150,
        code="FC",
        heading="Slides",
        notes="Photographic transparencies mounted for projection",
    ),
    "FD": CodeListEntry(
        list_number=150,
        code="FD",
        heading="OHP transparencies",
        notes="Transparencies for overhead projector",
    ),
    "FE": CodeListEntry(
        list_number=150,
        code="FE",
        heading="Filmstrip",
        notes="Photographic transparencies, unmounted but cut into short multi-frame strips",
        added_version=2,
    ),
    "FF": CodeListEntry(
        list_number=150,
        code="FF",
        heading="Film",
        notes="Continuous movie film as opposed to filmstrip",
        added_version=2,
    ),
    "FZ": CodeListEntry(
        list_number=150,
        code="FZ",
        heading="Other film or transparency format",
        notes="Other film or transparency format not specified by FB to FF. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "LA": CodeListEntry(
        list_number=150,
        code="LA",
        heading="Digital product license",
        notes="Digital product license (delivery method unspecified). Use only when the form is unknown, or when no other L* code applies and the delivery method is described in <ProductFormDescription>",
        added_version=10,
    ),
    "LB": CodeListEntry(
        list_number=150,
        code="LB",
        heading="Digital product license key",
        notes="Digital product license delivered through the retail supply chain as a physical ‘key’, typically a card or booklet containing a code enabling the purchaser to download the associated product",
        added_version=10,
    ),
    "LC": CodeListEntry(
        list_number=150,
        code="LC",
        heading="Digital product license code",
        notes="Digital product license delivered by email or other electronic distribution, typically providing a code enabling the purchaser to activate, upgrade or extend the license supplied with the associated product",
        added_version=10,
    ),
    "MA": CodeListEntry(
        list_number=150,
        code="MA",
        heading="Microform",
        notes="Microform - detail unspecified. Use only when the form is unknown and no further detail can be provided. Prefer MZ plus <ProductFormDescription> if detail is available but no other M* code applies",
    ),
    "MB": CodeListEntry(
        list_number=150,
        code="MB",
        heading="Microfiche",
    ),
    "MC": CodeListEntry(
        list_number=150,
        code="MC",
        heading="Microfilm",
        notes="Roll microfilm",
    ),
    "MZ": CodeListEntry(
        list_number=150,
        code="MZ",
        heading="Other microform",
        notes="Other microform not specified by MB or MC. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "PA": CodeListEntry(
        list_number=150,
        code="PA",
        heading="Miscellaneous print",
        notes="Miscellaneous printed material - detail unspecified. Use only when the form is unknown and no further detail can be provided. Prefer PZ plus <ProductFormDescription> if detail is available but no other P* code applies",
    ),
    "PB": CodeListEntry(
        list_number=150,
        code="PB",
        heading="Address book",
        notes="May use <ProductFormDetail> codes P201 to P204 to specify binding",
    ),
    "PC": CodeListEntry(
        list_number=150,
        code="PC",
        heading="Calendar",
    ),
    "PD": CodeListEntry(
        list_number=150,
        code="PD",
        heading="Cards",
        notes="Cards, flash cards (eg for teaching reading), revision cards, divination, playing or trading cards",
    ),
    "PE": CodeListEntry(
        list_number=150,
        code="PE",
        heading="Copymasters",
        notes="Copymasters, photocopiable sheets",
    ),
    "PF": CodeListEntry(
        list_number=150,
        code="PF",
        heading="Diary or journal",
        notes="May use <ProductFormDetail> codes P201 to P204 to specify binding",
    ),
    "PG": CodeListEntry(
        list_number=150,
        code="PG",
        heading="Frieze",
        notes="Narrow strip-shaped printed sheet used mostly for education or children’s products (eg depicting alphabet, number line, procession of illustrated characters etc). Usually intended for horizontal display",
    ),
    "PH": CodeListEntry(
        list_number=150,
        code="PH",
        heading="Kit",
        notes="Parts for post-purchase assembly, including card, wood or plastic parts or model components, interlocking construction blocks, beads and other crafting materials etc",
    ),
    "PI": CodeListEntry(
        list_number=150,
        code="PI",
        heading="Sheet music",
        notes="May use <ProductFormDetail> codes P201 to P204 to specify binding",
    ),
    "PJ": CodeListEntry(
        list_number=150,
        code="PJ",
        heading="Postcard book or pack",
        notes="Including greeting cards and packs. For bound books (usually with perforated sheets to remove cards), may use <ProductFormDetail> codes P201 to P204 to specify binding",
    ),
    "PK": CodeListEntry(
        list_number=150,
        code="PK",
        heading="Poster",
        notes="Poster for retail sale - see also XF",
    ),
    "PL": CodeListEntry(
        list_number=150,
        code="PL",
        heading="Record book",
        notes="Record book (eg ‘birthday book’, ‘baby book’): binding unspecified; may use <ProductFormDetail> codes P201 to P204 to specify binding",
    ),
    "PM": CodeListEntry(
        list_number=150,
        code="PM",
        heading="Wallet or folder",
        notes="Wallet, folder or box (containing loose sheets etc, or empty): it is preferable to code the contents and treat ‘wallet’ (or folder / box) as packaging in <ProductPackaging> with Codelist 80, but if this is not possible (eg where the product is empty and intended for storing other loose items) the product as a whole may be coded as a ‘wallet’. For binders intended for loose leaf or partwork publications intended to be updateable, see codes BD, BN",
    ),
    "PN": CodeListEntry(
        list_number=150,
        code="PN",
        heading="Pictures or photographs",
    ),
    "PO": CodeListEntry(
        list_number=150,
        code="PO",
        heading="Wallchart",
    ),
    "PP": CodeListEntry(
        list_number=150,
        code="PP",
        heading="Stickers",
        added_version=2,
    ),
    "PQ": CodeListEntry(
        list_number=150,
        code="PQ",
        heading="Plate (lámina)",
        notes="A book-sized (as opposed to poster-sized) sheet, usually in color or high quality print",
        added_version=6,
    ),
    "PR": CodeListEntry(
        list_number=150,
        code="PR",
        heading="Notebook / blank book",
        notes="A book with all pages blank for the buyer’s own use; may use <ProductFormDetail> codes P201 to P204 to specify binding",
        added_version=8,
    ),
    "PS": CodeListEntry(
        list_number=150,
        code="PS",
        heading="Organizer",
        notes="May use <ProductFormDetail> codes P201 to P204 to specify binding",
        added_version=8,
    ),
    "PT": CodeListEntry(
        list_number=150,
        code="PT",
        heading="Bookmark",
        added_version=8,
    ),
    "PU": CodeListEntry(
        list_number=150,
        code="PU",
        heading="Leaflet",
        notes="Folded but unbound",
        added_version=42,
    ),
    "PV": CodeListEntry(
        list_number=150,
        code="PV",
        heading="Book plates",
        notes="Ex libris’ book labels and packs",
        added_version=48,
    ),
    "PZ": CodeListEntry(
        list_number=150,
        code="PZ",
        heading="Other printed item",
        notes="Other printed item not specified by PB to PQ. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "SA": CodeListEntry(
        list_number=150,
        code="SA",
        heading="Multiple-component retail product",
        notes="Presentation unspecified: format of product components must be given in <ProductPart>. Use only when the packaging of the product is unknown, or when no other S* code applies and the presentation is described in <ProductFormDescription>",
        added_version=9,
    ),
    "SB": CodeListEntry(
        list_number=150,
        code="SB",
        heading="Multiple-component retail product, boxed",
        notes="Format of product components must be given in <ProductPart>",
        added_version=9,
    ),
    "SC": CodeListEntry(
        list_number=150,
        code="SC",
        heading="Multiple-component retail product, slip-cased",
        notes="Format of product components must be given in <ProductPart>",
        added_version=9,
    ),
    "SD": CodeListEntry(
        list_number=150,
        code="SD",
        heading="Multiple-component retail product, shrink-wrapped",
        notes="Format of product components must be given in <ProductPart>. Use code XL for a shrink-wrapped pack for trade supply, where the retail items it contains are intended for sale individually",
        added_version=9,
    ),
    "SE": CodeListEntry(
        list_number=150,
        code="SE",
        heading="Multiple-component retail product, loose",
        notes="Format of product components must be given in <ProductPart>",
        added_version=9,
    ),
    "SF": CodeListEntry(
        list_number=150,
        code="SF",
        heading="Multiple-component retail product, part(s) enclosed",
        notes="Multiple component product where subsidiary product part(s) is/are supplied as enclosures to the primary part, eg a book with a CD packaged in a sleeve glued within the back cover. Format of product components must be given in <ProductPart>",
        added_version=9,
    ),
    "SG": CodeListEntry(
        list_number=150,
        code="SG",
        heading="Multiple-component retail product, entirely digital",
        notes="Multiple component product where all parts are digital, and delivered as separate files, eg a group of individual EPUB files, an EPUB with a PDF, an e-book with a license to access a range of online resources, etc. Format of product components must be given in <ProductPart>",
        added_version=60,
    ),
    "VA": CodeListEntry(
        list_number=150,
        code="VA",
        heading="Video",
        notes="Video - detail unspecified. Use only when the form is unknown and no further detail can be provided. Prefer VZ plus <ProductFormDescription> if detail is available but no other V* code applies",
    ),
    "VF": CodeListEntry(
        list_number=150,
        code="VF",
        heading="Videodisc",
        notes="eg Laserdisc",
    ),
    "VI": CodeListEntry(
        list_number=150,
        code="VI",
        heading="DVD video",
        notes="DVD video: specify TV standard in <ProductFormDetail>",
        added_version=2,
    ),
    "VJ": CodeListEntry(
        list_number=150,
        code="VJ",
        heading="VHS video",
        notes="VHS videotape: specify TV standard in <ProductFormDetail>",
        added_version=2,
    ),
    "VK": CodeListEntry(
        list_number=150,
        code="VK",
        heading="Betamax video",
        notes="Betamax videotape: specify TV standard in <ProductFormDetail>",
        added_version=2,
    ),
    "VL": CodeListEntry(
        list_number=150,
        code="VL",
        heading="VCD",
        notes="VideoCD",
        added_version=5,
    ),
    "VM": CodeListEntry(
        list_number=150,
        code="VM",
        heading="SVCD",
        notes="Super VideoCD",
        added_version=5,
    ),
    "VN": CodeListEntry(
        list_number=150,
        code="VN",
        heading="HD DVD",
        notes="High definition DVD disc, Toshiba HD DVD format",
        added_version=7,
    ),
    "VO": CodeListEntry(
        list_number=150,
        code="VO",
        heading="Blu-ray",
        notes="High definition DVD disc, Sony Blu-ray format",
        added_version=7,
    ),
    "VP": CodeListEntry(
        list_number=150,
        code="VP",
        heading="UMD Video",
        notes="Sony Universal Media disc",
        added_version=7,
    ),
    "VQ": CodeListEntry(
        list_number=150,
        code="VQ",
        heading="CBHD",
        notes="China Blue High-Definition, derivative of HD-DVD",
        added_version=23,
    ),
    "VZ": CodeListEntry(
        list_number=150,
        code="VZ",
        heading="Other video format",
        notes="Other video format not specified by VB to VQ. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "XA": CodeListEntry(
        list_number=150,
        code="XA",
        heading="Trade-only material",
        notes="Trade-only material (unspecified). Use only when the form is unknown and no further detail can be provided. Prefer XZ plus <ProductFormDescription> if detail is available but no other X* code applies",
    ),
    "XB": CodeListEntry(
        list_number=150,
        code="XB",
        heading="Dumpbin - empty",
    ),
    "XC": CodeListEntry(
        list_number=150,
        code="XC",
        heading="Dumpbin - filled",
        notes="Dumpbin with contents. ISBN (where applicable) and format of contained items must be given in <ProductPart>",
    ),
    "XD": CodeListEntry(
        list_number=150,
        code="XD",
        heading="Counterpack - empty",
    ),
    "XE": CodeListEntry(
        list_number=150,
        code="XE",
        heading="Counterpack - filled",
        notes="Counterpack with contents. ISBN (where applicable) and format of contained items must be given in <ProductPart>",
    ),
    "XF": CodeListEntry(
        list_number=150,
        code="XF",
        heading="Poster, promotional",
        notes="Promotional poster for display, not for sale - see also PK",
    ),
    "XG": CodeListEntry(
        list_number=150,
        code="XG",
        heading="Shelf strip",
    ),
    "XH": CodeListEntry(
        list_number=150,
        code="XH",
        heading="Window piece",
        notes="Promotional piece for shop window display",
    ),
    "XI": CodeListEntry(
        list_number=150,
        code="XI",
        heading="Streamer",
    ),
    "XJ": CodeListEntry(
        list_number=150,
        code="XJ",
        heading="Spinner - empty",
    ),
    "XK": CodeListEntry(
        list_number=150,
        code="XK",
        heading="Large book display",
        notes="Large scale facsimile of book for promotional display",
    ),
    "XL": CodeListEntry(
        list_number=150,
        code="XL",
        heading="Shrink-wrapped pack",
        notes="A quantity pack with its own product code, usually for trade supply only: the retail items it contains are intended for sale individually. ISBN (where applicable) and format of contained items must be given in <ProductPart>. For products or product bundles supplied individually shrink-wrapped for retail sale, use code SD",
    ),
    "XM": CodeListEntry(
        list_number=150,
        code="XM",
        heading="Boxed pack",
        notes="A quantity pack with its own product code, usually for trade supply only: the retail items it contains are intended for sale individually. ISBN (where applicable) and format of contained items must be given in <ProductPart>. For products or product bundles boxed individually for retail sale, use code SB",
        added_version=27,
    ),
    "XN": CodeListEntry(
        list_number=150,
        code="XN",
        heading="Pack (outer packaging unspecified)",
        notes="A quantity pack with its own product code, usually for trade supply only: the retail items it contains are intended for sale individually. ISBN (where applicable) and format of contained items must be given in <ProductPart>. Use only when the pack is neither shrinp-wrapped nor boxed",
        added_version=49,
    ),
    "XO": CodeListEntry(
        list_number=150,
        code="XO",
        heading="Spinner - filled",
        notes="Spinner with contents. ISBN(s) (where applicable) and detail of contained items must be given in <ProductPart>",
        added_version=51,
    ),
    "XY": CodeListEntry(
        list_number=150,
        code="XY",
        heading="Other point of sale - including retail product",
        notes="Other point of sale material not specified by XB to XO, supplied with included product(s) for retail sale. The retail product(s) must be described in <ProductPart>. Further detail of the POS material is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
        added_version=51,
    ),
    "XZ": CodeListEntry(
        list_number=150,
        code="XZ",
        heading="Other point of sale",
        notes="Other point of sale material not specified by XB to XY, promotional or decorative. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
    "ZA": CodeListEntry(
        list_number=150,
        code="ZA",
        heading="General merchandise",
        notes="General merchandise, book accessories and non-book products - unspecified. Use only when the form is unknown and no further detail can be provided. Prefer ZX, ZY or ZZ, plus <ProductFormDescription> if detail is available but no other Z* code applies",
    ),
    "ZB": CodeListEntry(
        list_number=150,
        code="ZB",
        heading="Doll or figure",
        notes="Including action figures, figurines",
    ),
    "ZC": CodeListEntry(
        list_number=150,
        code="ZC",
        heading="Soft toy",
        notes="Soft or plush toy",
    ),
    "ZD": CodeListEntry(
        list_number=150,
        code="ZD",
        heading="Toy",
        notes="Including educational toys (where no other code is relevant)",
    ),
    "ZE": CodeListEntry(
        list_number=150,
        code="ZE",
        heading="Game",
        notes="Board game, or other game (except computer game: see DE and other D* codes)",
    ),
    "ZF": CodeListEntry(
        list_number=150,
        code="ZF",
        heading="T-shirt",
    ),
    "ZG": CodeListEntry(
        list_number=150,
        code="ZG",
        heading="E-book reader",
        notes="Dedicated e-book reading device, typically with mono screen",
        added_version=21,
    ),
    "ZH": CodeListEntry(
        list_number=150,
        code="ZH",
        heading="Tablet computer",
        notes="General purpose tablet computer, typically with color screen",
        added_version=21,
    ),
    "ZI": CodeListEntry(
        list_number=150,
        code="ZI",
        heading="Audiobook player",
        notes="Dedicated audiobook player device, typically including book-related features like bookmarking",
        added_version=25,
    ),
    "ZJ": CodeListEntry(
        list_number=150,
        code="ZJ",
        heading="Jigsaw",
        notes="Jigsaw or similar ‘shapes’ puzzle",
        added_version=25,
    ),
    "ZK": CodeListEntry(
        list_number=150,
        code="ZK",
        heading="Mug",
        notes="For example, branded, promotional or tie-in drinking mug, cup etc",
        added_version=34,
    ),
    "ZL": CodeListEntry(
        list_number=150,
        code="ZL",
        heading="Tote bag",
        notes="For example, branded, promotional or tie-in bag",
        added_version=34,
    ),
    "ZM": CodeListEntry(
        list_number=150,
        code="ZM",
        heading="Tableware",
        notes="For example, branded, promotional or tie-in plates, bowls etc (note for mugs and cups, use code ZK)",
        added_version=38,
    ),
    "ZN": CodeListEntry(
        list_number=150,
        code="ZN",
        heading="Umbrella",
        notes="For example, branded, promotional or tie-in umbrella",
        added_version=38,
    ),
    "ZO": CodeListEntry(
        list_number=150,
        code="ZO",
        heading="Paints, crayons, pencils",
        notes="Coloring set, including pens, chalks, etc",
        added_version=51,
    ),
    "ZP": CodeListEntry(
        list_number=150,
        code="ZP",
        heading="Handicraft kit",
        notes="Handicraft kit or set, eg sewing, crochet, weaving, basketry, beadwork, leather, wood or metalworking, pottery and glassworking, candlemaking etc",
        added_version=60,
    ),
    "ZX": CodeListEntry(
        list_number=150,
        code="ZX",
        heading="Other toy/game accessories",
        notes="Other toy, game and puzzle items not specified by ZB to ZQ, generally accessories to other products etc. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
        added_version=50,
    ),
    "ZY": CodeListEntry(
        list_number=150,
        code="ZY",
        heading="Other apparel",
        notes="Other apparel items not specified by ZB to ZQ, including branded, promotional or tie-in scarves, caps, aprons, dress-up costumes etc. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
        added_version=25,
    ),
    "ZZ": CodeListEntry(
        list_number=150,
        code="ZZ",
        heading="Other merchandise",
        notes="Other branded, promotional or tie-in merchandise not specified by ZB to ZY. Further detail is expected in <ProductFormDescription>, as <ProductFormDetail> and <ProductFormFeature> are unlikely to be sufficient",
    ),
}

List150 = CodeList(
    number=150,
    heading="Product form",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
ProductForm = List150
