"""ONIX Code List 147: Unit of usage."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "01": CodeListEntry(
        list_number=147,
        code="01",
        heading="Copies",
        notes="Maximum number of copies that may be made of a permitted extract",
        added_version=9,
    ),
    "02": CodeListEntry(
        list_number=147,
        code="02",
        heading="Characters",
        notes="Maximum number of characters in a permitted extract for a specified usage",
        added_version=9,
    ),
    "03": CodeListEntry(
        list_number=147,
        code="03",
        heading="Words",
        notes="Maximum number of words in a permitted extract for a specified usage",
        added_version=9,
    ),
    "04": CodeListEntry(
        list_number=147,
        code="04",
        heading="Pages",
        notes="Maximum number of pages in a permitted extract for a specified usage",
        added_version=9,
    ),
    "05": CodeListEntry(
        list_number=147,
        code="05",
        heading="Percentage",
        notes="Maximum percentage of total content in a permitted extract for a specified usage",
        added_version=9,
    ),
    "06": CodeListEntry(
        list_number=147,
        code="06",
        heading="Devices",
        notes="Maximum number of devices in ‘share group’",
        added_version=9,
    ),
    "07": CodeListEntry(
        list_number=147,
        code="07",
        heading="Concurrent users",
        notes="Maximum number of concurrent users. NB where the number of concurrent users is specifically not limited, set the number of concurrent users to zero",
        added_version=9,
    ),
    "15": CodeListEntry(
        list_number=147,
        code="15",
        heading="Users",
        notes="Maximum number of licensed individual users, independent of concurrency of use",
        added_version=40,
    ),
    "19": CodeListEntry(
        list_number=147,
        code="19",
        heading="Concurrent classes",
        notes="Maximum number of licensed concurrent classes of user. A ‘class’ is a group of learners attending a specific course or lesson and generally taught as a group",
        added_version=45,
    ),
    "20": CodeListEntry(
        list_number=147,
        code="20",
        heading="Classes",
        notes="Maximum number of licensed classes of learners, independent of concurrency of use and the number of users per class",
        added_version=45,
    ),
    "31": CodeListEntry(
        list_number=147,
        code="31",
        heading="Institutions",
        notes="Maximum number of licensed institutions, independent of concurrency of use and the number of classes or individuals per institution",
        added_version=53,
    ),
    "08": CodeListEntry(
        list_number=147,
        code="08",
        heading="Percentage per time period",
        notes="Maximum percentage of total content which may be used in a specified usage per time period; the time period being specified as another <EpubUsageLimit> Quantity",
        added_version=11,
    ),
    "09": CodeListEntry(
        list_number=147,
        code="09",
        heading="Days",
        notes="Maximum time period in days (beginning from product purchase or activation)",
        added_version=11,
    ),
    "13": CodeListEntry(
        list_number=147,
        code="13",
        heading="Weeks",
        notes="Maximum time period in weeks",
        added_version=17,
    ),
    "14": CodeListEntry(
        list_number=147,
        code="14",
        heading="Months",
        notes="Maximum time period in months",
        added_version=17,
    ),
    "16": CodeListEntry(
        list_number=147,
        code="16",
        heading="Hours minutes and seconds",
        notes="Maximum amount of time in hours, minutes and seconds allowed in a permitted extract for a specified usage, in the format HHHMMSS (7 digits, with leading zeros if necessary)",
        added_version=42,
    ),
    "27": CodeListEntry(
        list_number=147,
        code="27",
        heading="Days (fixed start)",
        notes="Maximum time period in days (beginning from the product publication date). In effect, this defines a fixed end date for the license independent of the purchase or activation date",
        added_version=36,
    ),
    "28": CodeListEntry(
        list_number=147,
        code="28",
        heading="Weeks (fixed start)",
        notes="Maximum time period in weeks",
        added_version=36,
    ),
    "29": CodeListEntry(
        list_number=147,
        code="29",
        heading="Months (fixed start)",
        notes="Maximum time period in months",
        added_version=36,
    ),
    "10": CodeListEntry(
        list_number=147,
        code="10",
        heading="Times",
        notes="Maximum number of times a specified usage event may occur (in the lifetime of the product)",
        added_version=11,
    ),
    "22": CodeListEntry(
        list_number=147,
        code="22",
        heading="Times per day",
        notes="Maximum frequency a specified usage event may occur (per day)",
        added_version=36,
    ),
    "23": CodeListEntry(
        list_number=147,
        code="23",
        heading="Times per month",
        notes="Maximum frequency a specified usage event may occur (per month)",
        added_version=35,
    ),
    "24": CodeListEntry(
        list_number=147,
        code="24",
        heading="Times per year",
        notes="Maximum frequency a specified usage event may occur (per year)",
        added_version=35,
    ),
    "21": CodeListEntry(
        list_number=147,
        code="21",
        heading="Dots per inch",
        notes="Maximum resolution of printed or copy/pasted extracts",
        added_version=28,
    ),
    "26": CodeListEntry(
        list_number=147,
        code="26",
        heading="Dots per cm",
        notes="Maximum resolution of printed or copy/pasted extracts",
        added_version=36,
    ),
    "11": CodeListEntry(
        list_number=147,
        code="11",
        heading="Allowed usage start page",
        notes="Page number where allowed usage begins. <Quantity> should contain an absolute page number, counting the cover as page 1. (This type of page numbering should not be used where the e-publication has no fixed pagination). Use with (max number of) Pages, Percentage of content, or End page to specify pages allowed in Preview",
        added_version=14,
    ),
    "12": CodeListEntry(
        list_number=147,
        code="12",
        heading="Allowed usage end page",
        notes="Page number at which allowed usage ends. <Quantity> should contain an absolute page number, counting the cover as page 1. (This type of page numbering should not be used where the e-publication has no fixed pagination). Use with Start page to specify pages allowed in a preview",
        added_version=14,
    ),
    "17": CodeListEntry(
        list_number=147,
        code="17",
        heading="Allowed usage start time",
        notes="Time at which allowed usage begins. <Quantity> should contain an absolute time, counting from the beginning of an audio or video product, in the format HHHMMSS or HHHMMSScc. Use with Time, Percentage of content, or End time to specify time-based extract allowed in Preview",
        added_version=42,
    ),
    "18": CodeListEntry(
        list_number=147,
        code="18",
        heading="Allowed usage end time",
        notes="Time at which allowed usage ends. <Quantity> should contain an absolute time, counting from the beginning of an audio or video product, in the format HHHMMSS or HHHMMSScc. Use with Start time to specify time-based extract allowed in Preview",
        added_version=42,
    ),
    "98": CodeListEntry(
        list_number=147,
        code="98",
        heading="Valid from",
        notes="The date from which the usage constraint applies. <Quantity> is in the format YYYYMMDD",
        added_version=46,
    ),
    "99": CodeListEntry(
        list_number=147,
        code="99",
        heading="Valid to",
        notes="The date until which the usage constraint applies. <Quantity> is in the format YYYYMMDD",
        added_version=46,
    ),
}

List147 = CodeList(
    number=147,
    heading="Unit of usage",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
UnitOfUsage = List147
