"""ONIX Code List 44: Name identifier type."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "01": CodeListEntry(
        list_number=44,
        code="01",
        heading="Proprietary name ID scheme",
        notes="For example, a publisher’s own name, contributor or imprint ID scheme. Note that a distinctive <IDTypeName> is required with proprietary identifiers",
        added_version=10,
    ),
    "02": CodeListEntry(
        list_number=44,
        code="02",
        heading="Proprietary",
        notes="Deprecated - use code 01",
        deprecated_version=10,
    ),
    "03": CodeListEntry(
        list_number=44,
        code="03",
        heading="DNB publisher identifier",
        notes="Deutsche Nationalbibliothek publisher identifier",
        added_version=1,
    ),
    "04": CodeListEntry(
        list_number=44,
        code="04",
        heading="Börsenverein Verkehrsnummer",
        notes="(de: Verkehrsnummer ded Börsenverein des deutschen Buchhandels)",
        added_version=1,
    ),
    "05": CodeListEntry(
        list_number=44,
        code="05",
        heading="German ISBN Agency publisher identifier",
        notes="(de: MVB-Kennnummer)",
        added_version=1,
    ),
    "06": CodeListEntry(
        list_number=44,
        code="06",
        heading="GLN",
        notes="GS1 global location number (formerly EAN location number)",
        added_version=1,
    ),
    "07": CodeListEntry(
        list_number=44,
        code="07",
        heading="SAN",
        notes="Book trade Standard Address Number - US, UK etc",
        added_version=1,
    ),
    "08": CodeListEntry(
        list_number=44,
        code="08",
        heading="MARC organization code",
        notes="MARC code list for organizations - see http://www.loc.gov/marc/organizations/orgshome.html",
        added_version=28,
    ),
    "10": CodeListEntry(
        list_number=44,
        code="10",
        heading="Centraal Boekhuis Relatie ID",
        notes="Trading party identifier used in the Netherlands",
        added_version=4,
    ),
    "12": CodeListEntry(
        list_number=44,
        code="12",
        heading="Distributeurscode Boekenbank",
        notes="Flemish supplier code. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "13": CodeListEntry(
        list_number=44,
        code="13",
        heading="Fondscode Boekenbank",
        notes="Flemish publisher code",
        added_version=7,
    ),
    "15": CodeListEntry(
        list_number=44,
        code="15",
        heading="Y-tunnus",
        notes="Business Identity Code (Finland). See http://www.ytj.fi/ (in Finnish)",
        added_version=8,
    ),
    "16": CodeListEntry(
        list_number=44,
        code="16",
        heading="ISNI",
        notes="International Standard Name Identifier. A sixteen digit number. Usually presented with spaces or hyphens dividing the number into four groups of four digits, but in ONIX the spaces or hyphens should be omitted. See https://isni.org/",
        added_version=10,
    ),
    "17": CodeListEntry(
        list_number=44,
        code="17",
        heading="PND",
        notes="Personennamendatei - person name authority file used by Deutsche Nationalbibliothek and in other German-speaking countries. See http://www.dnb.de/standardisierung/normdateien/pnd.htm (German) or http://www.dnb.de/eng/standardisierung/normdateien/pnd.htm (English). Deprecated in favor of the GND",
        added_version=10,
        deprecated_version=18,
    ),
    "18": CodeListEntry(
        list_number=44,
        code="18",
        heading="NACO",
        notes="A control number assigned to a Library of Congress Control Number (LCCN) Name Authority / NACO record",
        added_version=10,
    ),
    "19": CodeListEntry(
        list_number=44,
        code="19",
        heading="Japanese Publisher identifier",
        notes="Publisher identifier administered by Japanese ISBN Agency",
        added_version=12,
    ),
    "20": CodeListEntry(
        list_number=44,
        code="20",
        heading="GKD",
        notes="Gemeinsame Körperschaftsdatei - Corporate Body Authority File in the German-speaking countries. See http://www.dnb.de/standardisierung/normdateien/gkd.htm (German) or http://www.dnb.de/eng/standardisierung/normdateien/gkd.htm (English). Deprecated in favor of the GND",
        added_version=13,
        deprecated_version=18,
    ),
    "21": CodeListEntry(
        list_number=44,
        code="21",
        heading="ORCID",
        notes="Open Researcher and Contributor ID. A sixteen digit number. Usually presented with hyphens dividing the number into four groups of four digits, but in ONIX the hyphens should be omitted. See http://www.orcid.org/",
        added_version=13,
    ),
    "22": CodeListEntry(
        list_number=44,
        code="22",
        heading="GAPP Publisher Identifier",
        notes="Publisher identifier maintained by the Chinese ISBN Agency (GAPP)",
        added_version=15,
    ),
    "23": CodeListEntry(
        list_number=44,
        code="23",
        heading="VAT Identity Number",
        notes="Identifier for a business organization for VAT purposes, eg within the EU’s VIES system. See http://ec.europa.eu/taxation_customs/vies/faqvies.do for EU VAT ID formats, which vary from country to country. Generally these consist of a two-letter country code followed by the 8-12 digits of the national VAT ID. Some countries include one or two letters within their VAT ID. See http://en.wikipedia.org/wiki/VAT_identification_number for non-EU countries that maintain similar identifiers. Spaces, dashes etc should be omitted",
        added_version=16,
    ),
    "24": CodeListEntry(
        list_number=44,
        code="24",
        heading="JP Distribution Identifier",
        notes="4-digit business organization identifier controlled by the Japanese Publication Wholesalers Association",
        added_version=17,
    ),
    "25": CodeListEntry(
        list_number=44,
        code="25",
        heading="GND",
        notes="Gemeinsame Normdatei - Joint Authority File in the German-speaking countries. See http://www.dnb.de/EN/gnd (English). Combines the PND, SWD and GKD into a single authority file, and should be used in preference",
        added_version=18,
    ),
    "26": CodeListEntry(
        list_number=44,
        code="26",
        heading="DUNS",
        notes="Dunn and Bradstreet Universal Numbering System, see http://www.dnb.co.uk/dandb-duns-number",
        added_version=22,
    ),
    "27": CodeListEntry(
        list_number=44,
        code="27",
        heading="Ringgold ID",
        notes="Ringgold organizational identifier, see http://www.ringgold.com/identify.html",
        added_version=22,
    ),
    "28": CodeListEntry(
        list_number=44,
        code="28",
        heading="Identifiant Editeur Electre",
        notes="French Electre publisher identifier",
        added_version=24,
    ),
    "29": CodeListEntry(
        list_number=44,
        code="29",
        heading="EIDR Party ID",
        notes="Entertainment Identifier Registry party identifier (a DOI beginning ‘10.5237/’ with a suffix of 8 hexadecimal digits and one hyphen, and without the https://doi.org/ or the older http://dx.doi.org/), for example ‘10.5237/C9F6-F41F’ (Sam Raimi). See http://eidr.org",
        added_version=29,
    ),
    "30": CodeListEntry(
        list_number=44,
        code="30",
        heading="Identifiant Marque Electre",
        notes="French Electre imprint Identifier",
        added_version=24,
    ),
    "31": CodeListEntry(
        list_number=44,
        code="31",
        heading="VIAF ID",
        notes="Virtual Internet Authority File. <IDValue> should be a number. The URI form of the identifier can be created by prefixing the number with ‘https://viaf.org/viaf/’. See https://viaf.org",
        added_version=29,
    ),
    "32": CodeListEntry(
        list_number=44,
        code="32",
        heading="FundRef DOI",
        notes="DOI used in CrossRef’s Open Funder Registry list of academic research funding bodies, for example ‘10.13039/100010269’ (Wellcome Trust). Use of RORs for funder identifiers is now preferred. See https://www.crossref.org/services/funder-registry/",
        added_version=27,
    ),
    "33": CodeListEntry(
        list_number=44,
        code="33",
        heading="BNE CN",
        notes="Control number assigned to a Name Authority record by the Biblioteca Nacional de España",
        added_version=35,
    ),
    "34": CodeListEntry(
        list_number=44,
        code="34",
        heading="BNF Control Number",
        notes="Numéro de la notice de personne BNF",
        added_version=36,
    ),
    "35": CodeListEntry(
        list_number=44,
        code="35",
        heading="ARK",
        notes="Archival Resource Key, as a URL (including the address of the ARK resolver provided by eg a national library)",
        added_version=36,
    ),
    "36": CodeListEntry(
        list_number=44,
        code="36",
        heading="Nasjonalt autoritetsregister",
        notes="Nasjonalt autoritetsregister for navn - Norwegian national authority file for personal and corporate names. Only for use in ONIX 3.0 or later",
        added_version=37,
    ),
    "37": CodeListEntry(
        list_number=44,
        code="37",
        heading="GRID",
        notes="Global Research Identifier Database ID (see https://www.grid.ac). Only for use in ONIX 3.0 or later. Deprecated - ROR is now generally preferred",
        added_version=39,
        deprecated_version=60,
    ),
    "38": CodeListEntry(
        list_number=44,
        code="38",
        heading="IDRef",
        notes="Party ID from Identifiers and Standards for Higher Education and Research (fr: Identifiants et Référentiels pour l’enseignement supérieur et la recherche). Only for use in ONIX 3.0 or later. See https://www.idref.fr",
        added_version=52,
    ),
    "39": CodeListEntry(
        list_number=44,
        code="39",
        heading="IPI",
        notes="Party ID from CISAC’s proprietary Interested Party Information scheme, used primarily in rights and royalties administration. Only for use in ONIX 3.0 or later",
        added_version=57,
    ),
    "40": CodeListEntry(
        list_number=44,
        code="40",
        heading="ROR",
        notes="Research organization registry identifier (see https://ror.org), leading 0 followed by 8 alphanumeric characters (including 2-digit checksum). Only for use in ONIX 3.0 or later",
        added_version=58,
    ),
    "41": CodeListEntry(
        list_number=44,
        code="41",
        heading="EORI",
        notes="Economic Operators Registration and Identification, identifier for businesses that import into or export from the EU. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "42": CodeListEntry(
        list_number=44,
        code="42",
        heading="LEI",
        notes="Legal Entity Identifier, administered by the Global LEI Foundation, as 20 alphanumeric characters without spaces or hyphens. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "43": CodeListEntry(
        list_number=44,
        code="43",
        heading="SIREN",
        notes="French business identifier, issued by the National Institute of Statistics and Economic Studies (INSEE). 9 digits, without spaces. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "44": CodeListEntry(
        list_number=44,
        code="44",
        heading="SIRET",
        notes="French business and location identifier, issued by the National Institute of Statistics and Economic Studies (INSEE). 14 digits (the SIREN plus a further five digits), without spaces, or occasionally an alphanumeric code. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "45": CodeListEntry(
        list_number=44,
        code="45",
        heading="Chinese Participant identifier",
        notes="Chinese Participant identifier on the Publishing and distribution public service platform. 12-digits (or 11 digits plus X), usually presented with a / and hyphens dividing the number into groups of three, four and four digits plus a check digit, but in ONIX the / and hyphens should be omitted. Only for use in ONIX 3.0 or later",
        added_version=68,
    ),
}

List44 = CodeList(
    number=44,
    heading="Name identifier type",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
NameIdentifierType = List44
