"""ONIX Code List 73: Website role."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "00": CodeListEntry(
        list_number=73,
        code="00",
        heading="Unspecified, see website description",
        added_version=5,
    ),
    "01": CodeListEntry(
        list_number=73,
        code="01",
        heading="Publisher’s corporate website",
        notes="See also codes 17 and 18",
        added_version=5,
    ),
    "02": CodeListEntry(
        list_number=73,
        code="02",
        heading="Publisher’s website for a specified work",
        notes="A publisher’s informative and/or promotional webpage relating to a specified work (book, journal, online resource or other publication type)",
        added_version=5,
    ),
    "03": CodeListEntry(
        list_number=73,
        code="03",
        heading="Online hosting service home page",
        notes="A webpage giving access to an online content hosting service as a whole",
        added_version=5,
    ),
    "04": CodeListEntry(
        list_number=73,
        code="04",
        heading="Journal home page",
        notes="A webpage giving general information about a serial, in print or electronic format or both",
        added_version=5,
    ),
    "05": CodeListEntry(
        list_number=73,
        code="05",
        heading="Online resource ‘available content’ page",
        notes="A webpage giving direct access to the content that is available online for a specified resource version. Generally used for content available online under subscription terms",
        added_version=5,
    ),
    "06": CodeListEntry(
        list_number=73,
        code="06",
        heading="Contributor’s own website",
        notes="A webpage maintained by an author or other contributor about their publications and personal background",
        added_version=5,
    ),
    "07": CodeListEntry(
        list_number=73,
        code="07",
        heading="Publisher’s website relating to specified contributor",
        notes="A publisher’s webpage devoted to a specific author or other contributor",
        added_version=5,
    ),
    "08": CodeListEntry(
        list_number=73,
        code="08",
        heading="Other publisher’s website relating to specified contributor",
        notes="A webpage devoted to a specific author or other contributor, and maintained by a publisher other than the publisher of the item described in the ONIX record",
        added_version=5,
    ),
    "09": CodeListEntry(
        list_number=73,
        code="09",
        heading="Third-party website relating to specified contributor",
        notes="A webpage devoted to a specific author or other contributor, and maintained by a third party (eg a fan site)",
        added_version=5,
    ),
    "10": CodeListEntry(
        list_number=73,
        code="10",
        heading="Contributor’s own website for specified work",
        notes="A webpage maintained by an author or other contributor and specific to an individual work",
        added_version=5,
    ),
    "11": CodeListEntry(
        list_number=73,
        code="11",
        heading="Other publisher’s website relating to specified work",
        notes="A webpage devoted to an individual work, and maintained by a publisher other than the publisher of the item described in the ONIX record",
        added_version=5,
    ),
    "12": CodeListEntry(
        list_number=73,
        code="12",
        heading="Third-party website relating to specified work",
        notes="A webpage devoted to an individual work, and maintained by a third party (eg a fan site)",
        added_version=5,
    ),
    "13": CodeListEntry(
        list_number=73,
        code="13",
        heading="Contributor’s own website for group or series of works",
        notes="A webpage maintained by an author or other contributor and specific to a group or series of works",
        added_version=5,
    ),
    "14": CodeListEntry(
        list_number=73,
        code="14",
        heading="Publisher’s website relating to group or series of works",
        notes="A publisher’s webpage devoted to a group or series of works",
        added_version=5,
    ),
    "15": CodeListEntry(
        list_number=73,
        code="15",
        heading="Other publisher’s website relating to group or series of works",
        notes="A webpage devoted to a group or series of works, and maintained by a publisher other than the publisher of the item described in the ONIX record",
        added_version=5,
    ),
    "16": CodeListEntry(
        list_number=73,
        code="16",
        heading="Third-party website relating to group or series of works (eg a fan site)",
        notes="A webpage devoted to a group or series of works, and maintained by a third party (eg a fan site)",
        added_version=5,
    ),
    "17": CodeListEntry(
        list_number=73,
        code="17",
        heading="Publisher’s B2B website",
        notes="Use instead of code 01 to specify a publisher’s website for trade users",
        added_version=5,
    ),
    "18": CodeListEntry(
        list_number=73,
        code="18",
        heading="Publisher’s B2C website",
        notes="Use instead of code 01 to specify a publisher’s website for end customers (consumers)",
        added_version=5,
    ),
    "23": CodeListEntry(
        list_number=73,
        code="23",
        heading="Author blog",
        notes="For example, a Blogger or Tumblr URL, a Wordpress website or other blog URL",
        added_version=8,
    ),
    "24": CodeListEntry(
        list_number=73,
        code="24",
        heading="Web page for author presentation / commentary",
        added_version=8,
    ),
    "25": CodeListEntry(
        list_number=73,
        code="25",
        heading="Web page for author interview",
        added_version=8,
    ),
    "26": CodeListEntry(
        list_number=73,
        code="26",
        heading="Web page for author reading",
        added_version=8,
    ),
    "27": CodeListEntry(
        list_number=73,
        code="27",
        heading="Web page for cover material",
        added_version=8,
    ),
    "28": CodeListEntry(
        list_number=73,
        code="28",
        heading="Web page for sample content",
        added_version=8,
    ),
    "29": CodeListEntry(
        list_number=73,
        code="29",
        heading="Web page for full content",
        notes="Use this value in the <Website> composite (typically within <Publisher> or <SupplyDetail>) when sending a link to a webpage at which a digital product is available for download and/or online access",
        added_version=8,
    ),
    "30": CodeListEntry(
        list_number=73,
        code="30",
        heading="Web page for other commentary / discussion",
        notes="For example a subscribable podcast hosting site, social media message, newsletter issue, other commentary",
        added_version=8,
    ),
    "31": CodeListEntry(
        list_number=73,
        code="31",
        heading="Transfer-URL",
        notes="URL needed by the German National Library for direct access, harvesting and storage of an electronic resource",
        added_version=9,
    ),
    "32": CodeListEntry(
        list_number=73,
        code="32",
        heading="DOI Website Link",
        notes="Link needed by German Books in Print (VLB) for DOI registration and ONIX DOI conversion",
        added_version=9,
    ),
    "33": CodeListEntry(
        list_number=73,
        code="33",
        heading="Supplier’s corporate website",
        notes="A corporate website operated by a distributor or other supplier (not the publisher)",
        added_version=10,
    ),
    "34": CodeListEntry(
        list_number=73,
        code="34",
        heading="Supplier’s B2B website",
        notes="A website operated by a distributor or other supplier (not the publisher) and aimed at trade customers",
        added_version=10,
    ),
    "35": CodeListEntry(
        list_number=73,
        code="35",
        heading="Supplier’s B2C website",
        notes="A website operated by a distributor or other supplier (not the publisher) and aimed at consumers",
        added_version=10,
    ),
    "36": CodeListEntry(
        list_number=73,
        code="36",
        heading="Supplier’s website for a specified work",
        notes="A distributor or supplier’s webpage describing a specified work",
        added_version=10,
    ),
    "37": CodeListEntry(
        list_number=73,
        code="37",
        heading="Supplier’s B2B website for a specified work",
        notes="A distributor or supplier’s webpage describing a specified work, and aimed at trade customers",
        added_version=10,
    ),
    "38": CodeListEntry(
        list_number=73,
        code="38",
        heading="Supplier’s B2C website for a specified work",
        notes="A distributor or supplier’s webpage describing a specified work, and aimed at consumers",
        added_version=10,
    ),
    "39": CodeListEntry(
        list_number=73,
        code="39",
        heading="Supplier’s website for a group or series of works",
        notes="A distributor or supplier’s webpage describing a group or series of works",
        added_version=10,
    ),
    "40": CodeListEntry(
        list_number=73,
        code="40",
        heading="URL of full metadata description",
        notes="For example an ONIX or MARC record for the product, available online",
        added_version=14,
    ),
    "41": CodeListEntry(
        list_number=73,
        code="41",
        heading="Social networking URL for specific work or product",
        notes="For example, a Facebook, Instagram, Youtube, Pinterest, Tiktok (including Booktok), Twitter (latterly, X) or similar URL for the product or work",
        added_version=16,
    ),
    "42": CodeListEntry(
        list_number=73,
        code="42",
        heading="Author’s social networking URL",
        notes="For example, a Facebook, Instagram, Youtube, Pinterest, Tiktok (including Booktok), Twitter (latterly, X) or similar page for the contributor",
        added_version=16,
    ),
    "43": CodeListEntry(
        list_number=73,
        code="43",
        heading="Publisher’s social networking URL",
        notes="For example, a Facebook, Instagram, Youtube, Pinterest, Tiktok (including Booktok), Twitter (latterly, X) or similar page",
        added_version=16,
    ),
    "44": CodeListEntry(
        list_number=73,
        code="44",
        heading="Social networking URL for specific article, chapter or content item",
        notes="For example, a Facebook, Instagram, Youtube, Pinterest, Tiktok (including Booktok), Twitter (latterly, X) or similar page. Use only in the context of a specific content item (eg within <ContentItem>)",
        added_version=17,
    ),
    "45": CodeListEntry(
        list_number=73,
        code="45",
        heading="Publisher’s or third party website for permissions requests",
        notes="For example, a service offering click-through licensing of extracts",
        added_version=29,
    ),
    "46": CodeListEntry(
        list_number=73,
        code="46",
        heading="Publisher’s or third party website for privacy statement",
        notes="For example, a page providing details related to GDPR. Only for use in ONIX 3.0 or later",
        added_version=43,
    ),
    "47": CodeListEntry(
        list_number=73,
        code="47",
        heading="Publisher’s website for digital preservation",
        notes="The URL of the publisher’s preservation service, or a more specific URL for access to its preservation metadata, to provide confirmation of the preservation status of the product. <WebsiteDescription> may contain the name of the service. Only for use in ONIX 3.0 or later",
        added_version=52,
    ),
    "48": CodeListEntry(
        list_number=73,
        code="48",
        heading="Third-party website for digital preservation",
        notes="The URL of the preservation service (eg https://clockss.org), or a more specific URL for access to its preservation metadata, to provide confirmation of the preservation status of the product. <WebsiteDescription> may contain the name of the service. Only for use in ONIX 3.0 or later",
        added_version=52,
    ),
    "49": CodeListEntry(
        list_number=73,
        code="49",
        heading="Product website for environmental responsibility statement",
        notes="The URL of a web page describing the environmental and sustainability policy, or carbon neutrality status, that applies to the specific product. Only for use in ONIX 3.0 or later",
        added_version=55,
    ),
    "50": CodeListEntry(
        list_number=73,
        code="50",
        heading="Organization’s website for environmental responsibility statement",
        notes="The URL of a web page describing the environmental and sustainability policies, carbon neutrality status, etc of the organization (publisher, supplier etc). For environmental sustainability of the product itself, see List 79. Only for use in ONIX 3.0 or later",
        added_version=55,
    ),
    "51": CodeListEntry(
        list_number=73,
        code="51",
        heading="Legal deposit website for digital preservation",
        notes="The URL of a digital legal deposit service (eg https://www.legaldeposit.org.uk), or a more specific URL for access to its preservation metadata, to provide confirmation of the digital legal deposit status of the product. <WebsiteDescription> may contain the name of the service. Only for use in ONIX 3.0 or later",
        added_version=64,
    ),
    "52": CodeListEntry(
        list_number=73,
        code="52",
        heading="Publisher’s or third party contact form",
        notes="For example, a web page providing an interactive contact form for safety-related issues. Only for use in ONIX 3.0 or later",
        added_version=68,
    ),
    "53": CodeListEntry(
        list_number=73,
        code="53",
        heading="Organization’s website for corporate social responsibility",
        notes="The URL of a web page describing the CSR policies, including corporate ethics, governance and human rights or modern slavery statements, of the organization, but see code 50 for sustainability. Only for use in ONIX 3.0 or later",
        added_version=69,
    ),
    "54": CodeListEntry(
        list_number=73,
        code="54",
        heading="Website for Indigenous statement or resource",
        notes="The URL of a web page providing a statement, protocol or resource relevant to indigenous publishing. This may include content hosted by the publisher, a contributor, or a third party. Examples include Reconciliation Action Plans (RAPs), Indigenous Cultural and Intellectual Property (ICIP) acknowledgements, cultural protocols, author guidelines, nation, community, or language resources, or contextual references such as Indigenous place names, territories, or treaties (eg native-land.ca). May be used at either organisational or product level, and additional specifics about the web page should be provided using <WebsiteDescription>. Only for use in ONIX 3.0 or later",
        added_version=71,
    ),
}

List73 = CodeList(
    number=73,
    heading="Website role",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
WebsiteRole = List73
