"""ONIX Code List 74: Language - based on ISO 639-2/B."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "abk": CodeListEntry(
        list_number=74,
        code="abk",
        heading="Abkhazian",
    ),
    "ace": CodeListEntry(
        list_number=74,
        code="ace",
        heading="Achinese",
    ),
    "ach": CodeListEntry(
        list_number=74,
        code="ach",
        heading="Acoli",
    ),
    "ada": CodeListEntry(
        list_number=74,
        code="ada",
        heading="Adangme",
    ),
    "ady": CodeListEntry(
        list_number=74,
        code="ady",
        heading="Adygei; Adyghe",
        notes="(West Circassian)",
    ),
    "aar": CodeListEntry(
        list_number=74,
        code="aar",
        heading="Afar",
    ),
    "afh": CodeListEntry(
        list_number=74,
        code="afh",
        heading="Afrihili",
        notes="Artificial language",
    ),
    "afr": CodeListEntry(
        list_number=74,
        code="afr",
        heading="Afrikaans",
    ),
    "afa": CodeListEntry(
        list_number=74,
        code="afa",
        heading="Afro-Asiatic languages",
        notes="Collective name",
    ),
    "ain": CodeListEntry(
        list_number=74,
        code="ain",
        heading="Ainu",
        added_version=5,
    ),
    "aka": CodeListEntry(
        list_number=74,
        code="aka",
        heading="Akan",
        notes="Macrolanguage. See also fat (Fanti), twi (Twi)",
    ),
    "akk": CodeListEntry(
        list_number=74,
        code="akk",
        heading="Akkadian",
    ),
    "alb": CodeListEntry(
        list_number=74,
        code="alb",
        heading="Albanian",
        notes="Macrolanguage",
    ),
    "ale": CodeListEntry(
        list_number=74,
        code="ale",
        heading="Aleut",
    ),
    "alg": CodeListEntry(
        list_number=74,
        code="alg",
        heading="Algonquian languages",
        notes="Collective name",
    ),
    "alq": CodeListEntry(
        list_number=74,
        code="alq",
        heading="Algonquin",
        notes="Alginkin. ONIX local code, equivalent to alq in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "tut": CodeListEntry(
        list_number=74,
        code="tut",
        heading="Altaic languages",
        notes="Collective name",
    ),
    "amh": CodeListEntry(
        list_number=74,
        code="amh",
        heading="Amharic",
    ),
    "anp": CodeListEntry(
        list_number=74,
        code="anp",
        heading="Angika",
        added_version=7,
    ),
    "apa": CodeListEntry(
        list_number=74,
        code="apa",
        heading="Apache languages",
        notes="Collective name",
    ),
    "ara": CodeListEntry(
        list_number=74,
        code="ara",
        heading="Arabic",
        notes="Macrolanguage",
    ),
    "arg": CodeListEntry(
        list_number=74,
        code="arg",
        heading="Aragonese",
    ),
    "qar": CodeListEntry(
        list_number=74,
        code="qar",
        heading="Aranés",
        notes="ONIX local code, distinct dialect of Occitan (not distinguished from oci by ISO 639-3)",
        added_version=6,
    ),
    "arp": CodeListEntry(
        list_number=74,
        code="arp",
        heading="Arapaho",
    ),
    "arw": CodeListEntry(
        list_number=74,
        code="arw",
        heading="Arawak",
    ),
    "arm": CodeListEntry(
        list_number=74,
        code="arm",
        heading="Armenian",
    ),
    "rup": CodeListEntry(
        list_number=74,
        code="rup",
        heading="Aromanian; Arumanian; Macedo-Romanian",
        added_version=5,
    ),
    "art": CodeListEntry(
        list_number=74,
        code="art",
        heading="Artificial languages",
        notes="Collective name",
    ),
    "asm": CodeListEntry(
        list_number=74,
        code="asm",
        heading="Assamese",
    ),
    "ast": CodeListEntry(
        list_number=74,
        code="ast",
        heading="Asturian; Bable; Leonese; Asturleonese",
    ),
    "ath": CodeListEntry(
        list_number=74,
        code="ath",
        heading="Athapascan languages",
        notes="Collective name",
    ),
    "atj": CodeListEntry(
        list_number=74,
        code="atj",
        heading="Atikamekw",
        notes="ONIX local code, equivalent to atj in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "aus": CodeListEntry(
        list_number=74,
        code="aus",
        heading="Australian languages",
        notes="Collective name",
    ),
    "aav": CodeListEntry(
        list_number=74,
        code="aav",
        heading="Austro-Asiatic languages",
        notes="Collective name, not related to Australian languages. ONIX local code, equivalent of aav in ISO 639-5. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "map": CodeListEntry(
        list_number=74,
        code="map",
        heading="Austronesian languages",
        notes="Collective name",
    ),
    "ava": CodeListEntry(
        list_number=74,
        code="ava",
        heading="Avaric",
    ),
    "ave": CodeListEntry(
        list_number=74,
        code="ave",
        heading="Avestan",
    ),
    "awa": CodeListEntry(
        list_number=74,
        code="awa",
        heading="Awadhi",
    ),
    "aym": CodeListEntry(
        list_number=74,
        code="aym",
        heading="Aymara",
        notes="Macrolanguage",
    ),
    "aze": CodeListEntry(
        list_number=74,
        code="aze",
        heading="Azerbaijani",
        notes="Macrolanguage",
    ),
    "ban": CodeListEntry(
        list_number=74,
        code="ban",
        heading="Balinese",
    ),
    "bat": CodeListEntry(
        list_number=74,
        code="bat",
        heading="Baltic languages",
        notes="Collective name",
    ),
    "bal": CodeListEntry(
        list_number=74,
        code="bal",
        heading="Baluchi",
        notes="Macrolanguage",
    ),
    "bam": CodeListEntry(
        list_number=74,
        code="bam",
        heading="Bambara",
    ),
    "bai": CodeListEntry(
        list_number=74,
        code="bai",
        heading="Bamileke languages",
        notes="Collective name",
    ),
    "bad": CodeListEntry(
        list_number=74,
        code="bad",
        heading="Banda languages",
        notes="Collective name",
    ),
    "bnt": CodeListEntry(
        list_number=74,
        code="bnt",
        heading="Bantu languages",
        notes="Collective name",
    ),
    "bas": CodeListEntry(
        list_number=74,
        code="bas",
        heading="Basa",
    ),
    "bak": CodeListEntry(
        list_number=74,
        code="bak",
        heading="Bashkir",
    ),
    "baq": CodeListEntry(
        list_number=74,
        code="baq",
        heading="Basque",
    ),
    "btk": CodeListEntry(
        list_number=74,
        code="btk",
        heading="Batak languages",
        notes="Collective name",
    ),
    "bej": CodeListEntry(
        list_number=74,
        code="bej",
        heading="Beja; Bedawiyet",
    ),
    "bel": CodeListEntry(
        list_number=74,
        code="bel",
        heading="Belarusian",
    ),
    "bem": CodeListEntry(
        list_number=74,
        code="bem",
        heading="Bemba",
    ),
    "ben": CodeListEntry(
        list_number=74,
        code="ben",
        heading="Bengali",
    ),
    "ber": CodeListEntry(
        list_number=74,
        code="ber",
        heading="Berber languages",
        notes="Collective name",
    ),
    "bho": CodeListEntry(
        list_number=74,
        code="bho",
        heading="Bhojpuri",
    ),
    "bih": CodeListEntry(
        list_number=74,
        code="bih",
        heading="Bihari languages",
        notes="Collective name",
    ),
    "bik": CodeListEntry(
        list_number=74,
        code="bik",
        heading="Bikol",
        notes="Macrolanguage",
    ),
    "bin": CodeListEntry(
        list_number=74,
        code="bin",
        heading="Bini; Edo",
    ),
    "bis": CodeListEntry(
        list_number=74,
        code="bis",
        heading="Bislama",
    ),
    "byn": CodeListEntry(
        list_number=74,
        code="byn",
        heading="Blin; Bilin",
        added_version=4,
    ),
    "zbl": CodeListEntry(
        list_number=74,
        code="zbl",
        heading="Blissymbols; Blissymbolics; Bliss",
        notes="Artificial language",
        added_version=8,
    ),
    "brx": CodeListEntry(
        list_number=74,
        code="brx",
        heading="Bodo (India)",
        notes="Boro. ONIX local code, equivalent to brx in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "bos": CodeListEntry(
        list_number=74,
        code="bos",
        heading="Bosnian",
    ),
    "bra": CodeListEntry(
        list_number=74,
        code="bra",
        heading="Braj",
    ),
    "bre": CodeListEntry(
        list_number=74,
        code="bre",
        heading="Breton",
    ),
    "bug": CodeListEntry(
        list_number=74,
        code="bug",
        heading="Buginese",
    ),
    "bul": CodeListEntry(
        list_number=74,
        code="bul",
        heading="Bulgarian",
    ),
    "bum": CodeListEntry(
        list_number=74,
        code="bum",
        heading="Bulu (Cameroon)",
        notes="ONIX local code, equivalent to bum in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "bua": CodeListEntry(
        list_number=74,
        code="bua",
        heading="Buriat",
        notes="Macrolanguage",
    ),
    "bur": CodeListEntry(
        list_number=74,
        code="bur",
        heading="Burmese",
    ),
    "cad": CodeListEntry(
        list_number=74,
        code="cad",
        heading="Caddo",
    ),
    "sro": CodeListEntry(
        list_number=74,
        code="sro",
        heading="Campidanese",
        notes="ONIX local code for Sardinian dialect, equivalent to sro in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "yue": CodeListEntry(
        list_number=74,
        code="yue",
        heading="Cantonese",
        notes="ONIX local code, equivalent to yue in ISO 639-3",
        added_version=35,
    ),
    "cat": CodeListEntry(
        list_number=74,
        code="cat",
        heading="Catalan",
        notes="See also qav (Valencian)",
    ),
    "cau": CodeListEntry(
        list_number=74,
        code="cau",
        heading="Caucasian languages",
        notes="Collective name",
    ),
    "cay": CodeListEntry(
        list_number=74,
        code="cay",
        heading="Cayuga",
        notes="ONIX local code, equivalent to cay in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "ceb": CodeListEntry(
        list_number=74,
        code="ceb",
        heading="Cebuano",
    ),
    "cel": CodeListEntry(
        list_number=74,
        code="cel",
        heading="Celtic languages",
        notes="Collective name",
    ),
    "cai": CodeListEntry(
        list_number=74,
        code="cai",
        heading="Central American Indian languages",
        notes="Collective name",
    ),
    "tzm": CodeListEntry(
        list_number=74,
        code="tzm",
        heading="Central Atlas Tamazight",
        notes="ONIX local code, equivalent to tzm in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=56,
    ),
    "khm": CodeListEntry(
        list_number=74,
        code="khm",
        heading="Central Khmer",
    ),
    "ckb": CodeListEntry(
        list_number=74,
        code="ckb",
        heading="Central Kurdish (Sorani)",
        notes="ONIX local code, equivalent to ckb in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "chg": CodeListEntry(
        list_number=74,
        code="chg",
        heading="Chagatai",
    ),
    "cmc": CodeListEntry(
        list_number=74,
        code="cmc",
        heading="Chamic languages",
        notes="Collective name",
    ),
    "cha": CodeListEntry(
        list_number=74,
        code="cha",
        heading="Chamorro",
    ),
    "che": CodeListEntry(
        list_number=74,
        code="che",
        heading="Chechen",
    ),
    "chr": CodeListEntry(
        list_number=74,
        code="chr",
        heading="Cherokee",
    ),
    "chy": CodeListEntry(
        list_number=74,
        code="chy",
        heading="Cheyenne",
    ),
    "chb": CodeListEntry(
        list_number=74,
        code="chb",
        heading="Chibcha",
    ),
    "nya": CodeListEntry(
        list_number=74,
        code="nya",
        heading="Chichewa; Chewa; Nyanja",
    ),
    "cic": CodeListEntry(
        list_number=74,
        code="cic",
        heading="Chickasaw",
        notes="ONIX local code, equivalent to cic in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "chi": CodeListEntry(
        list_number=74,
        code="chi",
        heading="Chinese",
        notes="Macrolanguage. See also cmn (Mandarin), yue (Cantonese)",
    ),
    "chn": CodeListEntry(
        list_number=74,
        code="chn",
        heading="Chinook jargon",
    ),
    "chp": CodeListEntry(
        list_number=74,
        code="chp",
        heading="Chipewyan; Dene Suline",
    ),
    "cho": CodeListEntry(
        list_number=74,
        code="cho",
        heading="Choctaw",
    ),
    "chu": CodeListEntry(
        list_number=74,
        code="chu",
        heading="Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    ),
    "chk": CodeListEntry(
        list_number=74,
        code="chk",
        heading="Chuukese (Truk)",
    ),
    "chv": CodeListEntry(
        list_number=74,
        code="chv",
        heading="Chuvash",
    ),
    "nwc": CodeListEntry(
        list_number=74,
        code="nwc",
        heading="Classical Newari; Old Newari; Classical Nepal Bhasa",
        added_version=4,
    ),
    "syc": CodeListEntry(
        list_number=74,
        code="syc",
        heading="Classical Syriac",
        added_version=8,
    ),
    "cop": CodeListEntry(
        list_number=74,
        code="cop",
        heading="Coptic",
    ),
    "cor": CodeListEntry(
        list_number=74,
        code="cor",
        heading="Cornish",
    ),
    "cos": CodeListEntry(
        list_number=74,
        code="cos",
        heading="Corsican",
    ),
    "cre": CodeListEntry(
        list_number=74,
        code="cre",
        heading="Cree",
        notes="Macrolanguage. See also crj (Southern East Cree), crk (plains Cree), crl (Northern East Cree), crm (Moose Cree), csw (Swampy Cree), cwd (Woods Cree)",
    ),
    "mus": CodeListEntry(
        list_number=74,
        code="mus",
        heading="Creek",
        notes="Seminole",
    ),
    "crp": CodeListEntry(
        list_number=74,
        code="crp",
        heading="Creoles and pidgins",
        notes="Collective name",
    ),
    "cpe": CodeListEntry(
        list_number=74,
        code="cpe",
        heading="Creoles and pidgins, English-based",
        notes="Collective name",
    ),
    "cpf": CodeListEntry(
        list_number=74,
        code="cpf",
        heading="Creoles and pidgins, French-based",
        notes="Collective name",
    ),
    "cpp": CodeListEntry(
        list_number=74,
        code="cpp",
        heading="Creoles and pidgins, Portuguese-based",
        notes="Collective name",
    ),
    "crh": CodeListEntry(
        list_number=74,
        code="crh",
        heading="Crimean Turkish; Crimean Tatar",
    ),
    "hrv": CodeListEntry(
        list_number=74,
        code="hrv",
        heading="Croatian",
        added_version=10,
    ),
    "scr": CodeListEntry(
        list_number=74,
        code="scr",
        heading="Croatian",
        notes="Deprecated - use hrv",
        deprecated_version=10,
    ),
    "cus": CodeListEntry(
        list_number=74,
        code="cus",
        heading="Cushitic languages",
        notes="Collective name",
    ),
    "cze": CodeListEntry(
        list_number=74,
        code="cze",
        heading="Czech",
    ),
    "dak": CodeListEntry(
        list_number=74,
        code="dak",
        heading="Dakota",
    ),
    "dan": CodeListEntry(
        list_number=74,
        code="dan",
        heading="Danish",
    ),
    "dar": CodeListEntry(
        list_number=74,
        code="dar",
        heading="Dargwa",
    ),
    "prs": CodeListEntry(
        list_number=74,
        code="prs",
        heading="Dari; Afghan Persian",
        notes="ONIX local code, equivalent to prs in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=39,
    ),
    "del": CodeListEntry(
        list_number=74,
        code="del",
        heading="Delaware",
        notes="Macrolanguage",
    ),
    "din": CodeListEntry(
        list_number=74,
        code="din",
        heading="Dinka",
        notes="Macrolanguage",
    ),
    "div": CodeListEntry(
        list_number=74,
        code="div",
        heading="Divehi; Dhivehi; Maldivian",
    ),
    "doi": CodeListEntry(
        list_number=74,
        code="doi",
        heading="Dogri",
        notes="Macrolanguage",
    ),
    "dgr": CodeListEntry(
        list_number=74,
        code="dgr",
        heading="Dogrib",
    ),
    "dra": CodeListEntry(
        list_number=74,
        code="dra",
        heading="Dravidian languages",
        notes="Collective name",
    ),
    "dua": CodeListEntry(
        list_number=74,
        code="dua",
        heading="Duala",
    ),
    "dum": CodeListEntry(
        list_number=74,
        code="dum",
        heading="Dutch, Middle (ca. 1050-1350)",
    ),
    "dut": CodeListEntry(
        list_number=74,
        code="dut",
        heading="Dutch; Flemish",
    ),
    "dyu": CodeListEntry(
        list_number=74,
        code="dyu",
        heading="Dyula",
    ),
    "dzo": CodeListEntry(
        list_number=74,
        code="dzo",
        heading="Dzongkha",
    ),
    "ike": CodeListEntry(
        list_number=74,
        code="ike",
        heading="Eastern Canadian Inuktitut",
        notes="ONIX local code, equivalent to ike in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "frs": CodeListEntry(
        list_number=74,
        code="frs",
        heading="Eastern Frisian",
        added_version=7,
    ),
    "efi": CodeListEntry(
        list_number=74,
        code="efi",
        heading="Efik",
    ),
    "egy": CodeListEntry(
        list_number=74,
        code="egy",
        heading="Egyptian (Ancient)",
    ),
    "eka": CodeListEntry(
        list_number=74,
        code="eka",
        heading="Ekajuk",
    ),
    "elx": CodeListEntry(
        list_number=74,
        code="elx",
        heading="Elamite",
    ),
    "egl": CodeListEntry(
        list_number=74,
        code="egl",
        heading="Emilian",
        notes="ONIX local code for Italian dialect, equivalent to egl in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "eng": CodeListEntry(
        list_number=74,
        code="eng",
        heading="English",
    ),
    "enm": CodeListEntry(
        list_number=74,
        code="enm",
        heading="English, Middle (1100-1500)",
    ),
    "ang": CodeListEntry(
        list_number=74,
        code="ang",
        heading="English, Old (ca. 450-1100)",
    ),
    "myv": CodeListEntry(
        list_number=74,
        code="myv",
        heading="Erzya",
        added_version=4,
    ),
    "esx": CodeListEntry(
        list_number=74,
        code="esx",
        heading="Eskaleut languages",
        notes="Inuit-Yupik-Unangan languages. Collective name. ONIX local code, equivalent of esx in ISO 639-5. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "epo": CodeListEntry(
        list_number=74,
        code="epo",
        heading="Esperanto",
        notes="Artificial language",
    ),
    "est": CodeListEntry(
        list_number=74,
        code="est",
        heading="Estonian",
        notes="Macrolanguage",
    ),
    "gez": CodeListEntry(
        list_number=74,
        code="gez",
        heading="Ethiopic (Ge’ez)",
    ),
    "ewe": CodeListEntry(
        list_number=74,
        code="ewe",
        heading="Ewe",
    ),
    "ewo": CodeListEntry(
        list_number=74,
        code="ewo",
        heading="Ewondo",
    ),
    "fan": CodeListEntry(
        list_number=74,
        code="fan",
        heading="Fang",
    ),
    "fat": CodeListEntry(
        list_number=74,
        code="fat",
        heading="Fanti",
    ),
    "fao": CodeListEntry(
        list_number=74,
        code="fao",
        heading="Faroese",
    ),
    "fij": CodeListEntry(
        list_number=74,
        code="fij",
        heading="Fijian",
    ),
    "fil": CodeListEntry(
        list_number=74,
        code="fil",
        heading="Filipino; Pilipino",
        added_version=4,
    ),
    "fin": CodeListEntry(
        list_number=74,
        code="fin",
        heading="Finnish",
    ),
    "fiu": CodeListEntry(
        list_number=74,
        code="fiu",
        heading="Finno-Ugrian languages",
        notes="Collective name",
    ),
    "fon": CodeListEntry(
        list_number=74,
        code="fon",
        heading="Fon",
    ),
    "fre": CodeListEntry(
        list_number=74,
        code="fre",
        heading="French",
    ),
    "frm": CodeListEntry(
        list_number=74,
        code="frm",
        heading="French, Middle (ca. 1400-1600)",
    ),
    "fro": CodeListEntry(
        list_number=74,
        code="fro",
        heading="French, Old (ca. 842-1400)",
        notes="See also qgl (Gallo)",
    ),
    "fur": CodeListEntry(
        list_number=74,
        code="fur",
        heading="Friulian",
    ),
    "ful": CodeListEntry(
        list_number=74,
        code="ful",
        heading="Fulah",
        notes="Macrolanguage",
    ),
    "gaa": CodeListEntry(
        list_number=74,
        code="gaa",
        heading="Gã",
    ),
    "car": CodeListEntry(
        list_number=74,
        code="car",
        heading="Galibi Carib",
    ),
    "glg": CodeListEntry(
        list_number=74,
        code="glg",
        heading="Galician",
    ),
    "qgl": CodeListEntry(
        list_number=74,
        code="qgl",
        heading="Gallo",
        notes="ONIX local code, distinct variant of langue d’oïl (old northern French), not distinguished from fro, or from frm, fre, nrf by ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=52,
    ),
    "sdn": CodeListEntry(
        list_number=74,
        code="sdn",
        heading="Gallurese",
        notes="ONIX local code for Sardinian dialect, equivalent to sdn in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "lug": CodeListEntry(
        list_number=74,
        code="lug",
        heading="Ganda",
    ),
    "grt": CodeListEntry(
        list_number=74,
        code="grt",
        heading="Garo",
        notes="ONIX local code, equivalent to grt in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=52,
    ),
    "gay": CodeListEntry(
        list_number=74,
        code="gay",
        heading="Gayo",
    ),
    "gba": CodeListEntry(
        list_number=74,
        code="gba",
        heading="Gbaya",
        notes="Macrolanguage",
    ),
    "geo": CodeListEntry(
        list_number=74,
        code="geo",
        heading="Georgian",
    ),
    "ger": CodeListEntry(
        list_number=74,
        code="ger",
        heading="German",
    ),
    "gmh": CodeListEntry(
        list_number=74,
        code="gmh",
        heading="German, Middle High (ca. 1050-1500)",
    ),
    "goh": CodeListEntry(
        list_number=74,
        code="goh",
        heading="German, Old High (ca. 750-1050)",
    ),
    "gem": CodeListEntry(
        list_number=74,
        code="gem",
        heading="Germanic languages",
        notes="Collective name",
    ),
    "gil": CodeListEntry(
        list_number=74,
        code="gil",
        heading="Gilbertese",
    ),
    "git": CodeListEntry(
        list_number=74,
        code="git",
        heading="Gitxsan",
        notes="ONIX local code, equivalent to git in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "gon": CodeListEntry(
        list_number=74,
        code="gon",
        heading="Gondi",
        notes="Macrolanguage",
    ),
    "gor": CodeListEntry(
        list_number=74,
        code="gor",
        heading="Gorontalo",
    ),
    "got": CodeListEntry(
        list_number=74,
        code="got",
        heading="Gothic",
    ),
    "grb": CodeListEntry(
        list_number=74,
        code="grb",
        heading="Grebo",
        notes="Macrolanguage",
    ),
    "grc": CodeListEntry(
        list_number=74,
        code="grc",
        heading="Greek, Ancient (to 1453)",
    ),
    "gre": CodeListEntry(
        list_number=74,
        code="gre",
        heading="Greek, Modern (1453-)",
    ),
    "grn": CodeListEntry(
        list_number=74,
        code="grn",
        heading="Guarani",
        notes="Macrolanguage",
    ),
    "nrf": CodeListEntry(
        list_number=74,
        code="nrf",
        heading="Guernésiais, Jèrriais",
        notes="ONIX local code, equivalent to nrf in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=46,
    ),
    "guj": CodeListEntry(
        list_number=74,
        code="guj",
        heading="Gujarati",
    ),
    "gwi": CodeListEntry(
        list_number=74,
        code="gwi",
        heading="Gwich’in",
    ),
    "hai": CodeListEntry(
        list_number=74,
        code="hai",
        heading="Haida",
        notes="Macrolanguage",
    ),
    "hat": CodeListEntry(
        list_number=74,
        code="hat",
        heading="Haitian; Haitian Creole",
    ),
    "hau": CodeListEntry(
        list_number=74,
        code="hau",
        heading="Hausa",
    ),
    "haw": CodeListEntry(
        list_number=74,
        code="haw",
        heading="Hawaiian",
    ),
    "heb": CodeListEntry(
        list_number=74,
        code="heb",
        heading="Hebrew",
    ),
    "her": CodeListEntry(
        list_number=74,
        code="her",
        heading="Herero",
    ),
    "hil": CodeListEntry(
        list_number=74,
        code="hil",
        heading="Hiligaynon",
    ),
    "him": CodeListEntry(
        list_number=74,
        code="him",
        heading="Himachali languages; Western Pahari languages",
        notes="Collective name",
    ),
    "hin": CodeListEntry(
        list_number=74,
        code="hin",
        heading="Hindi",
    ),
    "hmo": CodeListEntry(
        list_number=74,
        code="hmo",
        heading="Hiri Motu",
    ),
    "hit": CodeListEntry(
        list_number=74,
        code="hit",
        heading="Hittite",
    ),
    "hmx": CodeListEntry(
        list_number=74,
        code="hmx",
        heading="Hmong-Mien languages",
        notes="Collective name. ONIX local code, equivalent of hmx in ISO 639-5. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "hmn": CodeListEntry(
        list_number=74,
        code="hmn",
        heading="Hmong; Mong",
        notes="Macrolanguage",
    ),
    "hop": CodeListEntry(
        list_number=74,
        code="hop",
        heading="Hopi",
        notes="ONIX local code, equivalent to hop in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "hun": CodeListEntry(
        list_number=74,
        code="hun",
        heading="Hungarian",
    ),
    "hup": CodeListEntry(
        list_number=74,
        code="hup",
        heading="Hupa",
    ),
    "iba": CodeListEntry(
        list_number=74,
        code="iba",
        heading="Iban",
    ),
    "ice": CodeListEntry(
        list_number=74,
        code="ice",
        heading="Icelandic",
    ),
    "ido": CodeListEntry(
        list_number=74,
        code="ido",
        heading="Ido",
        notes="Artificial language",
    ),
    "ibo": CodeListEntry(
        list_number=74,
        code="ibo",
        heading="Igbo",
    ),
    "ijo": CodeListEntry(
        list_number=74,
        code="ijo",
        heading="Ijo languages",
        notes="Collective name",
    ),
    "ilo": CodeListEntry(
        list_number=74,
        code="ilo",
        heading="Iloko",
    ),
    "smn": CodeListEntry(
        list_number=74,
        code="smn",
        heading="Inari Sami",
    ),
    "inc": CodeListEntry(
        list_number=74,
        code="inc",
        heading="Indic languages",
        notes="Collective name",
    ),
    "ine": CodeListEntry(
        list_number=74,
        code="ine",
        heading="Indo-European languages",
        notes="Collective name",
    ),
    "ind": CodeListEntry(
        list_number=74,
        code="ind",
        heading="Indonesian",
    ),
    "inh": CodeListEntry(
        list_number=74,
        code="inh",
        heading="Ingush",
    ),
    "moe": CodeListEntry(
        list_number=74,
        code="moe",
        heading="Innu, Montagnais",
        notes="ONIX local code, equivalent to moe in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "ina": CodeListEntry(
        list_number=74,
        code="ina",
        heading="Interlingua (International Auxiliary Language Association)",
        notes="Artificial language",
    ),
    "ile": CodeListEntry(
        list_number=74,
        code="ile",
        heading="Interlingue; Occidental",
        notes="Artificial language",
    ),
    "ikt": CodeListEntry(
        list_number=74,
        code="ikt",
        heading="Inuinnaqtun",
        notes="Western Canadian Inuktitut. ONIX local code, equivalent to ikt in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "iku": CodeListEntry(
        list_number=74,
        code="iku",
        heading="Inuktitut",
        notes="Macrolanguage. See also ike (Eastern Canadian Inuktitut), ikt (Inuinnaqtun)",
    ),
    "ipk": CodeListEntry(
        list_number=74,
        code="ipk",
        heading="Inupiaq",
        notes="Macrolanguage",
    ),
    "qiv": CodeListEntry(
        list_number=74,
        code="qiv",
        heading="Inuvialuktun",
        notes="ONIX local code, distinct dialect of Inuktitut (not distinguished from iku, ike, ikt by ISO 639-3). Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "ira": CodeListEntry(
        list_number=74,
        code="ira",
        heading="Iranian languages",
        notes="Collective name",
    ),
    "pes": CodeListEntry(
        list_number=74,
        code="pes",
        heading="Iranian Persian; Parsi",
        notes="ONIX local code, equivalent to pes in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=39,
    ),
    "gle": CodeListEntry(
        list_number=74,
        code="gle",
        heading="Irish",
    ),
    "mga": CodeListEntry(
        list_number=74,
        code="mga",
        heading="Irish, Middle (ca. 1100-1550)",
    ),
    "sga": CodeListEntry(
        list_number=74,
        code="sga",
        heading="Irish, Old (to 1100)",
    ),
    "iro": CodeListEntry(
        list_number=74,
        code="iro",
        heading="Iroquoian languages",
        notes="Collective name",
    ),
    "ita": CodeListEntry(
        list_number=74,
        code="ita",
        heading="Italian",
    ),
    "jpn": CodeListEntry(
        list_number=74,
        code="jpn",
        heading="Japanese",
    ),
    "jpx": CodeListEntry(
        list_number=74,
        code="jpx",
        heading="Japanese languages",
        notes="Japonic. Collective name. ONIX local code, equivalent of jpx in ISO 639-5. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "jav": CodeListEntry(
        list_number=74,
        code="jav",
        heading="Javanese",
    ),
    "jow": CodeListEntry(
        list_number=74,
        code="jow",
        heading="Jowulu",
        notes="ONIX local code, equivalent to jow in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=57,
    ),
    "jrb": CodeListEntry(
        list_number=74,
        code="jrb",
        heading="Judeo-Arabic",
        notes="Macrolanguage",
    ),
    "jpr": CodeListEntry(
        list_number=74,
        code="jpr",
        heading="Judeo-Persian",
    ),
    "kbd": CodeListEntry(
        list_number=74,
        code="kbd",
        heading="Kabardian",
        notes="(East Circassian)",
    ),
    "kbp": CodeListEntry(
        list_number=74,
        code="kbp",
        heading="Kabiyè",
        notes="ONIX local code, equivalent to kbp in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=65,
    ),
    "kab": CodeListEntry(
        list_number=74,
        code="kab",
        heading="Kabyle",
    ),
    "kac": CodeListEntry(
        list_number=74,
        code="kac",
        heading="Kachin; Jingpho",
    ),
    "kal": CodeListEntry(
        list_number=74,
        code="kal",
        heading="Kalâtdlisut; Greenlandic",
    ),
    "xal": CodeListEntry(
        list_number=74,
        code="xal",
        heading="Kalmyk; Oirat",
    ),
    "kam": CodeListEntry(
        list_number=74,
        code="kam",
        heading="Kamba",
    ),
    "kan": CodeListEntry(
        list_number=74,
        code="kan",
        heading="Kannada",
    ),
    "kau": CodeListEntry(
        list_number=74,
        code="kau",
        heading="Kanuri",
        notes="Macrolanguage",
    ),
    "kaa": CodeListEntry(
        list_number=74,
        code="kaa",
        heading="Kara-Kalpak",
    ),
    "krc": CodeListEntry(
        list_number=74,
        code="krc",
        heading="Karachay-Balkar",
        added_version=4,
    ),
    "kdr": CodeListEntry(
        list_number=74,
        code="kdr",
        heading="Karaim",
        notes="ONIX local code, equivalent to kdr in ISO 639-3",
        added_version=32,
    ),
    "krl": CodeListEntry(
        list_number=74,
        code="krl",
        heading="Karelian",
        added_version=7,
    ),
    "kar": CodeListEntry(
        list_number=74,
        code="kar",
        heading="Karen languages",
        notes="Collective name",
    ),
    "kas": CodeListEntry(
        list_number=74,
        code="kas",
        heading="Kashmiri",
    ),
    "csb": CodeListEntry(
        list_number=74,
        code="csb",
        heading="Kashubian",
        added_version=4,
    ),
    "kaw": CodeListEntry(
        list_number=74,
        code="kaw",
        heading="Kawi",
    ),
    "kaz": CodeListEntry(
        list_number=74,
        code="kaz",
        heading="Kazakh",
    ),
    "kha": CodeListEntry(
        list_number=74,
        code="kha",
        heading="Khasi",
    ),
    "khi": CodeListEntry(
        list_number=74,
        code="khi",
        heading="Khoisan languages",
        notes="Collective name",
    ),
    "kho": CodeListEntry(
        list_number=74,
        code="kho",
        heading="Khotanese; Sakan",
    ),
    "xuu": CodeListEntry(
        list_number=74,
        code="xuu",
        heading="Khwedam, Kxoe",
        notes="ONIX local code, equivalent to xuu in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=42,
    ),
    "kik": CodeListEntry(
        list_number=74,
        code="kik",
        heading="Kikuyu; Gikuyu",
    ),
    "kmb": CodeListEntry(
        list_number=74,
        code="kmb",
        heading="Kimbundu",
    ),
    "kin": CodeListEntry(
        list_number=74,
        code="kin",
        heading="Kinyarwanda",
    ),
    "kir": CodeListEntry(
        list_number=74,
        code="kir",
        heading="Kirghiz; Kyrgyz",
    ),
    "kqs": CodeListEntry(
        list_number=74,
        code="kqs",
        heading="Kissi, Northern",
        notes="Kisi (Guinean language). ONIX local code, equivalent to kqs in ISO 639-3. Only for use in ONIX 3.0 or later. Do not confuse with Kisi (Tanzanian language)",
        added_version=64,
    ),
    "kss": CodeListEntry(
        list_number=74,
        code="kss",
        heading="Kissi, Southern",
        notes="Kisi (Liberian language). ONIX local code, equivalent to kss in ISO 639-3. Only for use in ONIX 3.0 or later. Do not confuse with Kisi (Tanzanian language)",
        added_version=64,
    ),
    "tlh": CodeListEntry(
        list_number=74,
        code="tlh",
        heading="Klingon; tlhIngan-Hol",
        notes="Artificial language",
        added_version=4,
    ),
    "kom": CodeListEntry(
        list_number=74,
        code="kom",
        heading="Komi",
        notes="Macrolanguage",
    ),
    "kon": CodeListEntry(
        list_number=74,
        code="kon",
        heading="Kongo",
        notes="Macrolanguage",
    ),
    "kok": CodeListEntry(
        list_number=74,
        code="kok",
        heading="Konkani",
        notes="Macrolanguage",
    ),
    "kor": CodeListEntry(
        list_number=74,
        code="kor",
        heading="Korean",
    ),
    "kpe": CodeListEntry(
        list_number=74,
        code="kpe",
        heading="Kpelle",
        notes="Macrolanguage",
    ),
    "kro": CodeListEntry(
        list_number=74,
        code="kro",
        heading="Kru languages",
        notes="Collective name",
    ),
    "kua": CodeListEntry(
        list_number=74,
        code="kua",
        heading="Kuanyama; Kwanyama",
    ),
    "kum": CodeListEntry(
        list_number=74,
        code="kum",
        heading="Kumyk",
    ),
    "kur": CodeListEntry(
        list_number=74,
        code="kur",
        heading="Kurdish",
        notes="Macrolanguage. See also ckb (Central Kurdish)",
    ),
    "kru": CodeListEntry(
        list_number=74,
        code="kru",
        heading="Kurukh",
    ),
    "kos": CodeListEntry(
        list_number=74,
        code="kos",
        heading="Kusaiean (Caroline Islands)",
    ),
    "kut": CodeListEntry(
        list_number=74,
        code="kut",
        heading="Kutenai",
    ),
    "fkv": CodeListEntry(
        list_number=74,
        code="fkv",
        heading="Kvensk",
        notes="ONIX local code, equivalent to fkv in ISO 639-3",
        added_version=24,
    ),
    "kwk": CodeListEntry(
        list_number=74,
        code="kwk",
        heading="Kwakiutl",
        notes="ONIX local code, equivalent to kwk in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "lad": CodeListEntry(
        list_number=74,
        code="lad",
        heading="Ladino",
    ),
    "lah": CodeListEntry(
        list_number=74,
        code="lah",
        heading="Lahnda",
        notes="Macrolanguage",
    ),
    "lkt": CodeListEntry(
        list_number=74,
        code="lkt",
        heading="Lakota",
        notes="Teton, Teton Sioux. ONIX local code, equivalent to lkt in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "lam": CodeListEntry(
        list_number=74,
        code="lam",
        heading="Lamba",
    ),
    "day": CodeListEntry(
        list_number=74,
        code="day",
        heading="Land Dayak languages",
        notes="Collective name",
    ),
    "lao": CodeListEntry(
        list_number=74,
        code="lao",
        heading="Lao",
    ),
    "lat": CodeListEntry(
        list_number=74,
        code="lat",
        heading="Latin",
    ),
    "lav": CodeListEntry(
        list_number=74,
        code="lav",
        heading="Latvian",
        notes="Macrolanguage",
    ),
    "qlk": CodeListEntry(
        list_number=74,
        code="qlk",
        heading="Lemko",
        notes="ONIX local code, distinct dialect of Rusyn (not distinguished from rue by ISO 639-3). Only for use in ONIX 3.0 or later",
        added_version=40,
    ),
    "lez": CodeListEntry(
        list_number=74,
        code="lez",
        heading="Lezgian",
    ),
    "lij": CodeListEntry(
        list_number=74,
        code="lij",
        heading="Ligurian",
        notes="ONIX local code for Italian dialect, equivalent to lij in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "lim": CodeListEntry(
        list_number=74,
        code="lim",
        heading="Limbergan; Limburger; Limburgish",
    ),
    "lin": CodeListEntry(
        list_number=74,
        code="lin",
        heading="Lingala",
    ),
    "lit": CodeListEntry(
        list_number=74,
        code="lit",
        heading="Lithuanian",
    ),
    "jbo": CodeListEntry(
        list_number=74,
        code="jbo",
        heading="Lojban",
        added_version=4,
    ),
    "lom": CodeListEntry(
        list_number=74,
        code="lom",
        heading="Loma (Liberia)",
        notes="ONIX local code for Liberian language, equivalent to lom in ISO 639-3. See also Toma for the closely-related Guinean variant. Only for use in ONIX 3.0 or later",
        added_version=68,
    ),
    "lmo": CodeListEntry(
        list_number=74,
        code="lmo",
        heading="Lombard",
        notes="ONIX local code for Italian dialect, equivalent to lmo in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "nds": CodeListEntry(
        list_number=74,
        code="nds",
        heading="Low German; Low Saxon",
    ),
    "dsb": CodeListEntry(
        list_number=74,
        code="dsb",
        heading="Lower Sorbian",
        added_version=4,
    ),
    "loz": CodeListEntry(
        list_number=74,
        code="loz",
        heading="Lozi",
    ),
    "lub": CodeListEntry(
        list_number=74,
        code="lub",
        heading="Luba-Katanga",
    ),
    "lua": CodeListEntry(
        list_number=74,
        code="lua",
        heading="Luba-Lulua",
    ),
    "lui": CodeListEntry(
        list_number=74,
        code="lui",
        heading="Luiseño",
    ),
    "smj": CodeListEntry(
        list_number=74,
        code="smj",
        heading="Lule Sami",
    ),
    "lun": CodeListEntry(
        list_number=74,
        code="lun",
        heading="Lunda",
    ),
    "luo": CodeListEntry(
        list_number=74,
        code="luo",
        heading="Luo (Kenya and Tanzania)",
    ),
    "lus": CodeListEntry(
        list_number=74,
        code="lus",
        heading="Lushai",
    ),
    "ltz": CodeListEntry(
        list_number=74,
        code="ltz",
        heading="Luxembourgish; Letzeburgesch",
    ),
    "mac": CodeListEntry(
        list_number=74,
        code="mac",
        heading="Macedonian",
    ),
    "mad": CodeListEntry(
        list_number=74,
        code="mad",
        heading="Madurese",
    ),
    "mag": CodeListEntry(
        list_number=74,
        code="mag",
        heading="Magahi",
    ),
    "mai": CodeListEntry(
        list_number=74,
        code="mai",
        heading="Maithili",
    ),
    "mak": CodeListEntry(
        list_number=74,
        code="mak",
        heading="Makasar",
    ),
    "mlg": CodeListEntry(
        list_number=74,
        code="mlg",
        heading="Malagasy",
        notes="Macrolanguage",
    ),
    "may": CodeListEntry(
        list_number=74,
        code="may",
        heading="Malay",
        notes="Macrolanguage",
    ),
    "mal": CodeListEntry(
        list_number=74,
        code="mal",
        heading="Malayalam",
    ),
    "poz": CodeListEntry(
        list_number=74,
        code="poz",
        heading="Malayo-Polynesian languages",
        notes="Collective name. ONIX local code, equivalent of poz in ISO 639-5. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "mlt": CodeListEntry(
        list_number=74,
        code="mlt",
        heading="Maltese",
    ),
    "mnc": CodeListEntry(
        list_number=74,
        code="mnc",
        heading="Manchu",
    ),
    "mdr": CodeListEntry(
        list_number=74,
        code="mdr",
        heading="Mandar",
    ),
    "cmn": CodeListEntry(
        list_number=74,
        code="cmn",
        heading="Mandarin",
        notes="ONIX local code, equivalent to cmn in ISO 639-3",
        added_version=35,
    ),
    "man": CodeListEntry(
        list_number=74,
        code="man",
        heading="Mandingo",
        notes="Macrolanguage",
    ),
    "mni": CodeListEntry(
        list_number=74,
        code="mni",
        heading="Manipuri",
    ),
    "mno": CodeListEntry(
        list_number=74,
        code="mno",
        heading="Manobo languages",
        notes="Collective name",
    ),
    "glv": CodeListEntry(
        list_number=74,
        code="glv",
        heading="Manx",
    ),
    "swb": CodeListEntry(
        list_number=74,
        code="swb",
        heading="Maore Comorian",
        notes="Shimaore. ONIX local code, equivalent to swb in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=66,
    ),
    "mao": CodeListEntry(
        list_number=74,
        code="mao",
        heading="Maori",
        notes="Māori",
    ),
    "arn": CodeListEntry(
        list_number=74,
        code="arn",
        heading="Mapudungun; Mapuche",
    ),
    "mar": CodeListEntry(
        list_number=74,
        code="mar",
        heading="Marathi",
    ),
    "chm": CodeListEntry(
        list_number=74,
        code="chm",
        heading="Mari",
        notes="Macrolanguage",
    ),
    "mah": CodeListEntry(
        list_number=74,
        code="mah",
        heading="Marshallese",
    ),
    "mwr": CodeListEntry(
        list_number=74,
        code="mwr",
        heading="Marwari",
        notes="Macrolanguage",
    ),
    "mas": CodeListEntry(
        list_number=74,
        code="mas",
        heading="Masai",
    ),
    "myn": CodeListEntry(
        list_number=74,
        code="myn",
        heading="Mayan languages",
        notes="Collective name",
    ),
    "fit": CodeListEntry(
        list_number=74,
        code="fit",
        heading="Meänkieli / Tornedalen Finnish",
        notes="ONIX local code, equivalent to fit in ISO 639-3",
        added_version=29,
    ),
    "men": CodeListEntry(
        list_number=74,
        code="men",
        heading="Mende",
    ),
    "mic": CodeListEntry(
        list_number=74,
        code="mic",
        heading="Mi’kmaq; Micmac; Mi’gmaw",
    ),
    "crg": CodeListEntry(
        list_number=74,
        code="crg",
        heading="Michif",
        notes="ONIX local code, equivalent to crg in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "gml": CodeListEntry(
        list_number=74,
        code="gml",
        heading="Middle Low German",
        notes="ONIX local code, equivalent to gml in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "min": CodeListEntry(
        list_number=74,
        code="min",
        heading="Minangkabau",
    ),
    "mwl": CodeListEntry(
        list_number=74,
        code="mwl",
        heading="Mirandese",
        added_version=4,
    ),
    "moh": CodeListEntry(
        list_number=74,
        code="moh",
        heading="Mohawk",
    ),
    "mdf": CodeListEntry(
        list_number=74,
        code="mdf",
        heading="Moksha",
        added_version=4,
    ),
    "mol": CodeListEntry(
        list_number=74,
        code="mol",
        heading="Moldavian; Moldovan",
        notes="Deprecated - use rum",
        deprecated_version=10,
    ),
    "mkh": CodeListEntry(
        list_number=74,
        code="mkh",
        heading="Mon-Khmer languages",
        notes="Collective name",
    ),
    "lol": CodeListEntry(
        list_number=74,
        code="lol",
        heading="Mongo-Nkundu",
    ),
    "mon": CodeListEntry(
        list_number=74,
        code="mon",
        heading="Mongolian",
        notes="Macrolanguage",
    ),
    "cnr": CodeListEntry(
        list_number=74,
        code="cnr",
        heading="Montenegrin",
        notes="Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "mos": CodeListEntry(
        list_number=74,
        code="mos",
        heading="Mooré; Mossi",
    ),
    "crm": CodeListEntry(
        list_number=74,
        code="crm",
        heading="Moose Cree",
        notes="ONIX local code, equivalent to crm in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "mun": CodeListEntry(
        list_number=74,
        code="mun",
        heading="Munda languages",
        notes="Collective name",
    ),
    "mwf": CodeListEntry(
        list_number=74,
        code="mwf",
        heading="Murrinh-Patha",
        notes="ONIX local code, equivalent to mwf in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "nqo": CodeListEntry(
        list_number=74,
        code="nqo",
        heading="N’Ko",
        added_version=7,
    ),
    "nah": CodeListEntry(
        list_number=74,
        code="nah",
        heading="Nahuatl languages",
        notes="Collective name",
    ),
    "nsk": CodeListEntry(
        list_number=74,
        code="nsk",
        heading="Naskapi",
        notes="ONIX local code, equivalent to nsk in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "nau": CodeListEntry(
        list_number=74,
        code="nau",
        heading="Nauruan",
    ),
    "nav": CodeListEntry(
        list_number=74,
        code="nav",
        heading="Navajo; Navaho",
    ),
    "nde": CodeListEntry(
        list_number=74,
        code="nde",
        heading="Ndebele, North",
    ),
    "nbl": CodeListEntry(
        list_number=74,
        code="nbl",
        heading="Ndebele, South",
    ),
    "ndo": CodeListEntry(
        list_number=74,
        code="ndo",
        heading="Ndonga",
    ),
    "nap": CodeListEntry(
        list_number=74,
        code="nap",
        heading="Neapolitan",
    ),
    "nep": CodeListEntry(
        list_number=74,
        code="nep",
        heading="Nepali",
        notes="Macrolanguage",
    ),
    "qls": CodeListEntry(
        list_number=74,
        code="qls",
        heading="Neutral Latin American Spanish",
        notes="ONIX local code, distinct and exclusively spoken variation of Spanish, not distinguished from spa (Spanish, Castilian) by ISO 639-3. Neutral Latin American Spanish should be considered a ‘shorthand’ for spa plus a ‘country code’ for Latin America - but prefer spa plus the relevant country code for specifically Mexican Spanish, Argentine (Rioplatense) Spanish, Puerto Rican Spanish etc. Neutral Latin American Spanish must only be used with audio material (including the audio tracks of TV, video and film) to indicate use of accent, vocabulary and construction suitable for broad use across Latin America. Only for use in ONIX 3.0 or later",
        added_version=43,
    ),
    "new": CodeListEntry(
        list_number=74,
        code="new",
        heading="Newari; Nepal Bhasa",
    ),
    "nia": CodeListEntry(
        list_number=74,
        code="nia",
        heading="Nias",
    ),
    "nic": CodeListEntry(
        list_number=74,
        code="nic",
        heading="Niger-Kordofanian languages",
        notes="Collective name",
    ),
    "ssa": CodeListEntry(
        list_number=74,
        code="ssa",
        heading="Nilo-Saharan languages",
        notes="Collective name",
    ),
    "niu": CodeListEntry(
        list_number=74,
        code="niu",
        heading="Niuean",
    ),
    "nog": CodeListEntry(
        list_number=74,
        code="nog",
        heading="Nogai",
    ),
    "qnf": CodeListEntry(
        list_number=74,
        code="qnf",
        heading="Norman French",
        notes="Normand, of which Guernésiais, Jèrriais are distinct dialects. ONIX local code (not distinguished from nrf in ISO 639-3). Only for use in ONIX 3.0 or later",
        added_version=64,
    ),
    "nai": CodeListEntry(
        list_number=74,
        code="nai",
        heading="North American Indian languages",
        notes="Collective name",
    ),
    "crl": CodeListEntry(
        list_number=74,
        code="crl",
        heading="Northern East Cree",
        notes="ONIX local code, equivalent to crl in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "frr": CodeListEntry(
        list_number=74,
        code="frr",
        heading="Northern Frisian",
        added_version=7,
    ),
    "sme": CodeListEntry(
        list_number=74,
        code="sme",
        heading="Northern Sami",
    ),
    "nor": CodeListEntry(
        list_number=74,
        code="nor",
        heading="Norwegian",
        notes="Macrolanguage. See also nob (Bokmål), nno (Nynorsk)",
    ),
    "nob": CodeListEntry(
        list_number=74,
        code="nob",
        heading="Norwegian Bokmål",
        added_version=5,
    ),
    "nno": CodeListEntry(
        list_number=74,
        code="nno",
        heading="Norwegian Nynorsk",
        added_version=5,
    ),
    "nub": CodeListEntry(
        list_number=74,
        code="nub",
        heading="Nubian languages",
        notes="Collective name",
    ),
    "nym": CodeListEntry(
        list_number=74,
        code="nym",
        heading="Nyamwezi",
    ),
    "nyn": CodeListEntry(
        list_number=74,
        code="nyn",
        heading="Nyankole",
    ),
    "nyo": CodeListEntry(
        list_number=74,
        code="nyo",
        heading="Nyoro",
    ),
    "nzi": CodeListEntry(
        list_number=74,
        code="nzi",
        heading="Nzima",
    ),
    "oci": CodeListEntry(
        list_number=74,
        code="oci",
        heading="Occitan (post-1500)",
        notes="See also qar (Aranés)",
    ),
    "arc": CodeListEntry(
        list_number=74,
        code="arc",
        heading="Official Aramaic; Imperial Aramaic (700-300 BCE)",
    ),
    "oji": CodeListEntry(
        list_number=74,
        code="oji",
        heading="Ojibwa",
        notes="Macrolanguage. See also ojs (Severn Ojibwa)",
    ),
    "oka": CodeListEntry(
        list_number=74,
        code="oka",
        heading="Okanagan; Nsyilxcn / Nsyilxcən",
        notes="Colville-Okanagan. ONIX local code, equivalent to oka in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=68,
    ),
    "odt": CodeListEntry(
        list_number=74,
        code="odt",
        heading="Old Dutch / Old Low Franconian (ca. 400-1050)",
        notes="ONIX local code, equivalent to odt in ISO 639-3",
        added_version=32,
    ),
    "non": CodeListEntry(
        list_number=74,
        code="non",
        heading="Old Norse",
    ),
    "peo": CodeListEntry(
        list_number=74,
        code="peo",
        heading="Old Persian (ca. 600-400 B.C.)",
    ),
    "ood": CodeListEntry(
        list_number=74,
        code="ood",
        heading="O’odham",
        notes="Tohono O’odham, Akimel Oʼodham. ONIX local code, equivalent to ood in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=70,
    ),
    "ori": CodeListEntry(
        list_number=74,
        code="ori",
        heading="Oriya",
        notes="Macrolanguage",
    ),
    "orm": CodeListEntry(
        list_number=74,
        code="orm",
        heading="Oromo",
        notes="Macrolanguage",
    ),
    "osa": CodeListEntry(
        list_number=74,
        code="osa",
        heading="Osage",
    ),
    "oss": CodeListEntry(
        list_number=74,
        code="oss",
        heading="Ossetian; Ossetic",
    ),
    "omq": CodeListEntry(
        list_number=74,
        code="omq",
        heading="Oto-Manguean languages",
        notes="ONIX local code, equivalent to omq in ISO 639-5. Collective name",
        added_version=32,
    ),
    "oto": CodeListEntry(
        list_number=74,
        code="oto",
        heading="Otomian languages",
        notes="Collective name",
    ),
    "pal": CodeListEntry(
        list_number=74,
        code="pal",
        heading="Pahlavi",
    ),
    "pau": CodeListEntry(
        list_number=74,
        code="pau",
        heading="Palauan",
    ),
    "pli": CodeListEntry(
        list_number=74,
        code="pli",
        heading="Pali",
    ),
    "pam": CodeListEntry(
        list_number=74,
        code="pam",
        heading="Pampanga; Kapampangan",
    ),
    "pag": CodeListEntry(
        list_number=74,
        code="pag",
        heading="Pangasinan",
    ),
    "pan": CodeListEntry(
        list_number=74,
        code="pan",
        heading="Panjabi",
    ),
    "pap": CodeListEntry(
        list_number=74,
        code="pap",
        heading="Papiamento",
    ),
    "paa": CodeListEntry(
        list_number=74,
        code="paa",
        heading="Papuan languages",
        notes="Collective name",
    ),
    "nso": CodeListEntry(
        list_number=74,
        code="nso",
        heading="Pedi; Sepedi; Northern Sotho",
    ),
    "per": CodeListEntry(
        list_number=74,
        code="per",
        heading="Persian",
        notes="Macrolanguage. See also pes (Iranian Persian, Farsi), prs (Dari)",
    ),
    "phi": CodeListEntry(
        list_number=74,
        code="phi",
        heading="Philippine languages",
        notes="Collective name",
    ),
    "phn": CodeListEntry(
        list_number=74,
        code="phn",
        heading="Phoenician",
    ),
    "pcd": CodeListEntry(
        list_number=74,
        code="pcd",
        heading="Picard",
        notes="ONIX local code, distinct variant of langue d’oïl (old northern French), equivalent to pcd in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=61,
    ),
    "qsp": CodeListEntry(
        list_number=74,
        code="qsp",
        heading="Picture Communication Symbols (PCS)",
        notes="ONIX local code for graphical symbols used in augmentative and alternative communication and education, not listed in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "pms": CodeListEntry(
        list_number=74,
        code="pms",
        heading="Piedmontese",
        notes="ONIX local code for Italian dialect, equivalent to pms in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "crk": CodeListEntry(
        list_number=74,
        code="crk",
        heading="Plains Cree",
        notes="ONIX local code, equivalent to crk in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "pol": CodeListEntry(
        list_number=74,
        code="pol",
        heading="Polish",
    ),
    "pon": CodeListEntry(
        list_number=74,
        code="pon",
        heading="Ponapeian",
    ),
    "por": CodeListEntry(
        list_number=74,
        code="por",
        heading="Portuguese",
    ),
    "pra": CodeListEntry(
        list_number=74,
        code="pra",
        heading="Prakrit languages",
        notes="Collective name",
    ),
    "pro": CodeListEntry(
        list_number=74,
        code="pro",
        heading="Provençal, Old (to 1500); Occitan, Old (to 1500)",
    ),
    "fuf": CodeListEntry(
        list_number=74,
        code="fuf",
        heading="Pular",
        notes="ONIX local code, equivalent to fuf in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=66,
    ),
    "pus": CodeListEntry(
        list_number=74,
        code="pus",
        heading="Pushto; Pashto",
        notes="Macrolanguage",
    ),
    "que": CodeListEntry(
        list_number=74,
        code="que",
        heading="Quechua",
        notes="Macrolanguage",
    ),
    "raj": CodeListEntry(
        list_number=74,
        code="raj",
        heading="Rajasthani",
        notes="Macrolanguage",
    ),
    "rjs": CodeListEntry(
        list_number=74,
        code="rjs",
        heading="Rajbanshi",
        notes="Tajpuria. ONIX local code, equivalent to rjs in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=70,
    ),
    "rkt": CodeListEntry(
        list_number=74,
        code="rkt",
        heading="Rangpuri",
        notes="Bahe. ONIX local code, equivalent to rkt in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=70,
    ),
    "rap": CodeListEntry(
        list_number=74,
        code="rap",
        heading="Rapanui",
    ),
    "rar": CodeListEntry(
        list_number=74,
        code="rar",
        heading="Rarotongan; Cook Islands Maori",
        notes="Māori Kūki ʻĀirani",
    ),
    "rcf": CodeListEntry(
        list_number=74,
        code="rcf",
        heading="Réunion Creole French",
        notes="ONIX local code, equivalent to rcf in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=46,
    ),
    "rgn": CodeListEntry(
        list_number=74,
        code="rgn",
        heading="Romagnol",
        notes="ONIX local code for Italian dialect, equivalent to rgl in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "roa": CodeListEntry(
        list_number=74,
        code="roa",
        heading="Romance languages",
        notes="Collective name",
    ),
    "rum": CodeListEntry(
        list_number=74,
        code="rum",
        heading="Romanian",
    ),
    "roh": CodeListEntry(
        list_number=74,
        code="roh",
        heading="Romansh",
    ),
    "rom": CodeListEntry(
        list_number=74,
        code="rom",
        heading="Romany",
        notes="Romani. Macrolanguage",
    ),
    "run": CodeListEntry(
        list_number=74,
        code="run",
        heading="Rundi",
    ),
    "rus": CodeListEntry(
        list_number=74,
        code="rus",
        heading="Russian",
    ),
    "sal": CodeListEntry(
        list_number=74,
        code="sal",
        heading="Salishan languages",
        notes="Collective name",
    ),
    "sam": CodeListEntry(
        list_number=74,
        code="sam",
        heading="Samaritan Aramaic",
    ),
    "smi": CodeListEntry(
        list_number=74,
        code="smi",
        heading="Sami languages",
        notes="Collective name",
    ),
    "smo": CodeListEntry(
        list_number=74,
        code="smo",
        heading="Samoan",
    ),
    "sad": CodeListEntry(
        list_number=74,
        code="sad",
        heading="Sandawe",
    ),
    "sag": CodeListEntry(
        list_number=74,
        code="sag",
        heading="Sango",
    ),
    "san": CodeListEntry(
        list_number=74,
        code="san",
        heading="Sanskrit",
    ),
    "sat": CodeListEntry(
        list_number=74,
        code="sat",
        heading="Santali",
    ),
    "srm": CodeListEntry(
        list_number=74,
        code="srm",
        heading="Saramaccan",
        notes="ONIX local code for Saramaccan language, equivalent to srm in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=54,
    ),
    "srd": CodeListEntry(
        list_number=74,
        code="srd",
        heading="Sardinian",
        notes="Macrolanguage. See also sdc (Sassarese), sdn (Gallurese), sro (Campidanese)",
    ),
    "sas": CodeListEntry(
        list_number=74,
        code="sas",
        heading="Sasak",
    ),
    "sdc": CodeListEntry(
        list_number=74,
        code="sdc",
        heading="Sassarese",
        notes="ONIX local code for Sardinian dialect, equivalent to sdc in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "sco": CodeListEntry(
        list_number=74,
        code="sco",
        heading="Scots",
    ),
    "gla": CodeListEntry(
        list_number=74,
        code="gla",
        heading="Scottish Gaelic",
    ),
    "sel": CodeListEntry(
        list_number=74,
        code="sel",
        heading="Selkup",
    ),
    "sem": CodeListEntry(
        list_number=74,
        code="sem",
        heading="Semitic languages",
        notes="Collective name",
    ),
    "scc": CodeListEntry(
        list_number=74,
        code="scc",
        heading="Serbian",
        notes="Deprecated - use srp",
        deprecated_version=10,
    ),
    "srp": CodeListEntry(
        list_number=74,
        code="srp",
        heading="Serbian",
        added_version=10,
    ),
    "srr": CodeListEntry(
        list_number=74,
        code="srr",
        heading="Serer",
    ),
    "ojs": CodeListEntry(
        list_number=74,
        code="ojs",
        heading="Severn Ojibwa",
        notes="ONIX local code, equivalent to ojs in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "shn": CodeListEntry(
        list_number=74,
        code="shn",
        heading="Shan",
    ),
    "sna": CodeListEntry(
        list_number=74,
        code="sna",
        heading="Shona",
    ),
    "shs": CodeListEntry(
        list_number=74,
        code="shs",
        heading="Shuswap",
        notes="ONIX local code, equivalent to shs in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "iii": CodeListEntry(
        list_number=74,
        code="iii",
        heading="Sichuan Yi; Nuosu",
    ),
    "scn": CodeListEntry(
        list_number=74,
        code="scn",
        heading="Sicilian",
        added_version=4,
    ),
    "sid": CodeListEntry(
        list_number=74,
        code="sid",
        heading="Sidamo",
    ),
    "sgn": CodeListEntry(
        list_number=74,
        code="sgn",
        heading="Sign languages",
        notes="Collective name",
    ),
    "bla": CodeListEntry(
        list_number=74,
        code="bla",
        heading="Siksika",
    ),
    "szl": CodeListEntry(
        list_number=74,
        code="szl",
        heading="Silesian",
        notes="ONIX local code, equivalent to szl in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "snd": CodeListEntry(
        list_number=74,
        code="snd",
        heading="Sindhi",
    ),
    "sin": CodeListEntry(
        list_number=74,
        code="sin",
        heading="Sinhala; Sinhalese",
    ),
    "zhx": CodeListEntry(
        list_number=74,
        code="zhx",
        heading="Sinitic languages",
        notes="Chinese (family) languages. Collective name. ONIX local code, equivalent of zhx in ISO 639-5. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "sit": CodeListEntry(
        list_number=74,
        code="sit",
        heading="Sino-Tibetan languages",
        notes="Collective name",
    ),
    "sio": CodeListEntry(
        list_number=74,
        code="sio",
        heading="Siouan languages",
        notes="Collective name",
    ),
    "sms": CodeListEntry(
        list_number=74,
        code="sms",
        heading="Skolt Sami",
    ),
    "den": CodeListEntry(
        list_number=74,
        code="den",
        heading="Slave (Athapascan)",
        notes="Macrolanguage",
    ),
    "sla": CodeListEntry(
        list_number=74,
        code="sla",
        heading="Slavic languages",
        notes="Collective name",
    ),
    "slo": CodeListEntry(
        list_number=74,
        code="slo",
        heading="Slovak",
    ),
    "slv": CodeListEntry(
        list_number=74,
        code="slv",
        heading="Slovenian",
    ),
    "sog": CodeListEntry(
        list_number=74,
        code="sog",
        heading="Sogdian",
    ),
    "som": CodeListEntry(
        list_number=74,
        code="som",
        heading="Somali",
    ),
    "son": CodeListEntry(
        list_number=74,
        code="son",
        heading="Songhai languages",
        notes="Collective name",
    ),
    "snk": CodeListEntry(
        list_number=74,
        code="snk",
        heading="Soninke",
    ),
    "wen": CodeListEntry(
        list_number=74,
        code="wen",
        heading="Sorbian languages",
        notes="Collective name",
    ),
    "sot": CodeListEntry(
        list_number=74,
        code="sot",
        heading="Sotho; Sesotho",
    ),
    "sai": CodeListEntry(
        list_number=74,
        code="sai",
        heading="South American Indian languages",
        notes="Collective name",
    ),
    "alt": CodeListEntry(
        list_number=74,
        code="alt",
        heading="Southern Altai",
        added_version=5,
    ),
    "crj": CodeListEntry(
        list_number=74,
        code="crj",
        heading="Southern East Cree",
        notes="ONIX local code, equivalent to crj in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "sma": CodeListEntry(
        list_number=74,
        code="sma",
        heading="Southern Sami",
    ),
    "spa": CodeListEntry(
        list_number=74,
        code="spa",
        heading="Spanish",
    ),
    "srn": CodeListEntry(
        list_number=74,
        code="srn",
        heading="Sranan Tongo",
        added_version=7,
    ),
    "zgh": CodeListEntry(
        list_number=74,
        code="zgh",
        heading="Standard Moroccan Tamazight",
        added_version=32,
    ),
    "sto": CodeListEntry(
        list_number=74,
        code="sto",
        heading="Stoney",
        notes="ONIX local code, equivalent to sto in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "suk": CodeListEntry(
        list_number=74,
        code="suk",
        heading="Sukuma",
    ),
    "sux": CodeListEntry(
        list_number=74,
        code="sux",
        heading="Sumerian",
    ),
    "sun": CodeListEntry(
        list_number=74,
        code="sun",
        heading="Sundanese",
    ),
    "sus": CodeListEntry(
        list_number=74,
        code="sus",
        heading="Susu",
    ),
    "swa": CodeListEntry(
        list_number=74,
        code="swa",
        heading="Swahili",
        notes="Macrolanguage",
    ),
    "csw": CodeListEntry(
        list_number=74,
        code="csw",
        heading="Swampy Cree",
        notes="ONIX local code, equivalent to csw in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "ssw": CodeListEntry(
        list_number=74,
        code="ssw",
        heading="Swazi; Swati",
    ),
    "swe": CodeListEntry(
        list_number=74,
        code="swe",
        heading="Swedish",
    ),
    "gsw": CodeListEntry(
        list_number=74,
        code="gsw",
        heading="Swiss German; Alemannic; Alsatian",
        added_version=7,
    ),
    "syr": CodeListEntry(
        list_number=74,
        code="syr",
        heading="Syriac",
        notes="Macrolanguage",
    ),
    "tgl": CodeListEntry(
        list_number=74,
        code="tgl",
        heading="Tagalog",
    ),
    "tah": CodeListEntry(
        list_number=74,
        code="tah",
        heading="Tahitian",
    ),
    "tai": CodeListEntry(
        list_number=74,
        code="tai",
        heading="Tai languages",
        notes="Collective name",
    ),
    "tgk": CodeListEntry(
        list_number=74,
        code="tgk",
        heading="Tajik; Tajiki Persian",
    ),
    "tmh": CodeListEntry(
        list_number=74,
        code="tmh",
        heading="Tamashek",
        notes="Macrolanguage",
    ),
    "tam": CodeListEntry(
        list_number=74,
        code="tam",
        heading="Tamil",
    ),
    "shi": CodeListEntry(
        list_number=74,
        code="shi",
        heading="Tashelhit; Shilha",
        notes="ONIX local code, equivalent to shi in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=56,
    ),
    "tat": CodeListEntry(
        list_number=74,
        code="tat",
        heading="Tatar",
    ),
    "tel": CodeListEntry(
        list_number=74,
        code="tel",
        heading="Telugu",
    ),
    "tem": CodeListEntry(
        list_number=74,
        code="tem",
        heading="Temne; Time",
    ),
    "ter": CodeListEntry(
        list_number=74,
        code="ter",
        heading="Terena",
    ),
    "tet": CodeListEntry(
        list_number=74,
        code="tet",
        heading="Tetum",
    ),
    "tha": CodeListEntry(
        list_number=74,
        code="tha",
        heading="Thai",
    ),
    "thp": CodeListEntry(
        list_number=74,
        code="thp",
        heading="Thompson",
        notes="Nla’kapamux. ONIX local code, equivalent to thp in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "tib": CodeListEntry(
        list_number=74,
        code="tib",
        heading="Tibetan",
    ),
    "tig": CodeListEntry(
        list_number=74,
        code="tig",
        heading="Tigré",
    ),
    "tir": CodeListEntry(
        list_number=74,
        code="tir",
        heading="Tigrinya",
    ),
    "tiv": CodeListEntry(
        list_number=74,
        code="tiv",
        heading="Tiv",
    ),
    "tli": CodeListEntry(
        list_number=74,
        code="tli",
        heading="Tlingit",
    ),
    "tpi": CodeListEntry(
        list_number=74,
        code="tpi",
        heading="Tok Pisin",
    ),
    "tkl": CodeListEntry(
        list_number=74,
        code="tkl",
        heading="Tokelauan",
    ),
    "tod": CodeListEntry(
        list_number=74,
        code="tod",
        heading="Toma",
        notes="ONIX local code for Guinean language, equivalent to tod in ISO 639-3. See also Loma for the closely-related Liberian variant. Only for use in ONIX 3.0 or later",
        added_version=68,
    ),
    "tog": CodeListEntry(
        list_number=74,
        code="tog",
        heading="Tonga (Nyasa)",
    ),
    "ton": CodeListEntry(
        list_number=74,
        code="ton",
        heading="Tongan",
    ),
    "rmg": CodeListEntry(
        list_number=74,
        code="rmg",
        heading="Traveler Norwegian",
        notes="ONIX local code for Norwegian Scandoromani variant, equivalent to rmg in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=64,
    ),
    "tsd": CodeListEntry(
        list_number=74,
        code="tsd",
        heading="Tsakonian",
        notes="ONIX local code, equivalent to tsd in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "tsi": CodeListEntry(
        list_number=74,
        code="tsi",
        heading="Tsimshian",
    ),
    "tso": CodeListEntry(
        list_number=74,
        code="tso",
        heading="Tsonga",
    ),
    "tsn": CodeListEntry(
        list_number=74,
        code="tsn",
        heading="Tswana",
        notes="AKA Setswana",
    ),
    "tum": CodeListEntry(
        list_number=74,
        code="tum",
        heading="Tumbuka",
    ),
    "tup": CodeListEntry(
        list_number=74,
        code="tup",
        heading="Tupi languages",
        notes="Collective name",
    ),
    "tur": CodeListEntry(
        list_number=74,
        code="tur",
        heading="Turkish",
    ),
    "ota": CodeListEntry(
        list_number=74,
        code="ota",
        heading="Turkish, Ottoman",
    ),
    "tuk": CodeListEntry(
        list_number=74,
        code="tuk",
        heading="Turkmen",
    ),
    "tvl": CodeListEntry(
        list_number=74,
        code="tvl",
        heading="Tuvaluan",
    ),
    "tyv": CodeListEntry(
        list_number=74,
        code="tyv",
        heading="Tuvinian",
    ),
    "twi": CodeListEntry(
        list_number=74,
        code="twi",
        heading="Twi",
    ),
    "tzo": CodeListEntry(
        list_number=74,
        code="tzo",
        heading="Tzotzil",
        notes="ONIX local code, equivalent to tzo in ISO 639-3",
        added_version=32,
    ),
    "udm": CodeListEntry(
        list_number=74,
        code="udm",
        heading="Udmurt",
    ),
    "uga": CodeListEntry(
        list_number=74,
        code="uga",
        heading="Ugaritic",
    ),
    "uig": CodeListEntry(
        list_number=74,
        code="uig",
        heading="Uighur; Uyghur",
    ),
    "ukr": CodeListEntry(
        list_number=74,
        code="ukr",
        heading="Ukrainian",
    ),
    "umb": CodeListEntry(
        list_number=74,
        code="umb",
        heading="Umbundu",
    ),
    "hsb": CodeListEntry(
        list_number=74,
        code="hsb",
        heading="Upper Sorbian",
        added_version=4,
    ),
    "urj": CodeListEntry(
        list_number=74,
        code="urj",
        heading="Uralic languages",
        notes="Collective name. ONIX local code, equivalent of urj in ISO 639-5. Only for use in ONIX 3.0 or later",
        added_version=60,
    ),
    "urd": CodeListEntry(
        list_number=74,
        code="urd",
        heading="Urdu",
    ),
    "uzb": CodeListEntry(
        list_number=74,
        code="uzb",
        heading="Uzbek",
        notes="Macrolanguage",
    ),
    "vai": CodeListEntry(
        list_number=74,
        code="vai",
        heading="Vai",
    ),
    "qav": CodeListEntry(
        list_number=74,
        code="qav",
        heading="Valencian",
        notes="ONIX local code, distinct dialect of Catalan (not distinguished from cat by ISO 639-3)",
        added_version=5,
    ),
    "ven": CodeListEntry(
        list_number=74,
        code="ven",
        heading="Venda",
    ),
    "vec": CodeListEntry(
        list_number=74,
        code="vec",
        heading="Venetian/Venetan",
        notes="ONIX local code for Italian dialect, equivalent to vec in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "vie": CodeListEntry(
        list_number=74,
        code="vie",
        heading="Vietnamese",
    ),
    "vol": CodeListEntry(
        list_number=74,
        code="vol",
        heading="Volapük",
        notes="Artificial language",
    ),
    "vot": CodeListEntry(
        list_number=74,
        code="vot",
        heading="Votic",
    ),
    "wak": CodeListEntry(
        list_number=74,
        code="wak",
        heading="Wakashan languages",
        notes="Collective name",
    ),
    "wls": CodeListEntry(
        list_number=74,
        code="wls",
        heading="Wallisian",
        notes="East Uvean. ONIX local code, equivalent to wls in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=58,
    ),
    "wln": CodeListEntry(
        list_number=74,
        code="wln",
        heading="Walloon",
    ),
    "war": CodeListEntry(
        list_number=74,
        code="war",
        heading="Waray",
    ),
    "was": CodeListEntry(
        list_number=74,
        code="was",
        heading="Washo",
    ),
    "guc": CodeListEntry(
        list_number=74,
        code="guc",
        heading="Wayuu",
        notes="Guajiro. ONIX local code, equivalent of guc in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=61,
    ),
    "wel": CodeListEntry(
        list_number=74,
        code="wel",
        heading="Welsh",
    ),
    "fry": CodeListEntry(
        list_number=74,
        code="fry",
        heading="Western Frisian",
        added_version=7,
    ),
    "qsw": CodeListEntry(
        list_number=74,
        code="qsw",
        heading="Widgit symbols",
        notes="ONIX local code for graphical symbols used in augmentative and alternative communication and education, not listed in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "wal": CodeListEntry(
        list_number=74,
        code="wal",
        heading="Wolaitta; Wolaytta",
    ),
    "wol": CodeListEntry(
        list_number=74,
        code="wol",
        heading="Wolof",
    ),
    "cwd": CodeListEntry(
        list_number=74,
        code="cwd",
        heading="Woods Cree",
        notes="ONIX local code, equivalent to cwd in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=63,
    ),
    "wym": CodeListEntry(
        list_number=74,
        code="wym",
        heading="Wymysorys",
        notes="Vilamovian. ONIX local code, equivalent to wym in ISO 639-3. Only for use in ONIX 3.0 or later",
        added_version=53,
    ),
    "xho": CodeListEntry(
        list_number=74,
        code="xho",
        heading="Xhosa",
    ),
    "sah": CodeListEntry(
        list_number=74,
        code="sah",
        heading="Yakut",
    ),
    "yao": CodeListEntry(
        list_number=74,
        code="yao",
        heading="Yao",
    ),
    "yap": CodeListEntry(
        list_number=74,
        code="yap",
        heading="Yapese",
    ),
    "yid": CodeListEntry(
        list_number=74,
        code="yid",
        heading="Yiddish",
        notes="Macrolanguage",
    ),
    "yor": CodeListEntry(
        list_number=74,
        code="yor",
        heading="Yoruba",
    ),
    "ypk": CodeListEntry(
        list_number=74,
        code="ypk",
        heading="Yupik languages",
        notes="Collective name",
    ),
    "znd": CodeListEntry(
        list_number=74,
        code="znd",
        heading="Zande languages",
        notes="Collective name",
    ),
    "zap": CodeListEntry(
        list_number=74,
        code="zap",
        heading="Zapotec",
        notes="Macrolanguage",
    ),
    "zza": CodeListEntry(
        list_number=74,
        code="zza",
        heading="Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
        notes="Macrolanguage",
        added_version=7,
    ),
    "zen": CodeListEntry(
        list_number=74,
        code="zen",
        heading="Zenaga",
    ),
    "zha": CodeListEntry(
        list_number=74,
        code="zha",
        heading="Zhuang; Chuang",
        notes="Macrolanguage",
    ),
    "zul": CodeListEntry(
        list_number=74,
        code="zul",
        heading="Zulu",
    ),
    "zun": CodeListEntry(
        list_number=74,
        code="zun",
        heading="Zuni",
    ),
    "mis": CodeListEntry(
        list_number=74,
        code="mis",
        heading="Uncoded language",
        notes="Use where no suitable code is available",
    ),
    "und": CodeListEntry(
        list_number=74,
        code="und",
        heading="Undetermined language",
    ),
    "mul": CodeListEntry(
        list_number=74,
        code="mul",
        heading="Multiple languages",
    ),
    "zxx": CodeListEntry(
        list_number=74,
        code="zxx",
        heading="No linguistic content",
        added_version=10,
    ),
}

List74 = CodeList(
    number=74,
    heading="Language - based on ISO 639-2/B",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
LanguageCode = List74
