"""ONIX Code List 81: Product content type."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "10": CodeListEntry(
        list_number=81,
        code="10",
        heading="Text",
        notes="Readable text of the main content: this value is required, together with applicable <ProductForm> and <ProductFormDetail> values, to designate an e-book or other digital or physical product whose primary content is text. Note ‘text’ is ‘text-as-text’, not ‘text as an image’ or images of text",
        added_version=9,
    ),
    "15": CodeListEntry(
        list_number=81,
        code="15",
        heading="Extensive links between internal content",
        notes="E-publication contains a significant number of actionable (clickable) cross-references, hyperlinked notes and annotations, or with other actionable links between largely textual elements (eg quiz/test questions, ‘choose your own ending’ etc)",
        added_version=13,
    ),
    "14": CodeListEntry(
        list_number=81,
        code="14",
        heading="Extensive links to external content",
        notes="E-publication contains a significant number of actionable (clickable) web links to external content, downloadable resources, supplementary material, etc",
        added_version=13,
    ),
    "51": CodeListEntry(
        list_number=81,
        code="51",
        heading="Links to external interactive content",
        notes="Publication contains actionable (clickable) links to external interactive content. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "16": CodeListEntry(
        list_number=81,
        code="16",
        heading="Additional text not part of main content",
        notes="Publication contains additional textual content such as an interview, feature article, essay, bibliography, quiz/test, other background material, or text that is not included in a primary or ‘unenhanced’ version. Note ‘text’ is ‘text-as-text’, not ‘text as an image’ or images of text",
        added_version=13,
    ),
    "45": CodeListEntry(
        list_number=81,
        code="45",
        heading="Text within images",
        notes="Including text-as-text embedded in diagrams, charts, or within images containing speech balloons, thought bubbles, captions etc. Note this does not include ‘text as an image’ or images of text (for which see code 49). Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "41": CodeListEntry(
        list_number=81,
        code="41",
        heading="Additional eye-readable links to external content",
        notes="Publication contains a significant number of web links (printed URLs, QR codes etc). Only for use in ONIX 3.0 or later",
        added_version=39,
    ),
    "17": CodeListEntry(
        list_number=81,
        code="17",
        heading="Promotional text for other book product",
        notes="Publication contains supplementary text as promotional content such as, for example, a teaser chapter",
        added_version=13,
    ),
    "11": CodeListEntry(
        list_number=81,
        code="11",
        heading="Musical notation",
        added_version=9,
    ),
    "07": CodeListEntry(
        list_number=81,
        code="07",
        heading="Still images / graphics",
        notes="Includes any type of illustrations. Use only when no more detailed specification is provided",
        added_version=2,
    ),
    "18": CodeListEntry(
        list_number=81,
        code="18",
        heading="Photographs",
        notes="Whether in a plate section / insert, or not",
        added_version=13,
    ),
    "19": CodeListEntry(
        list_number=81,
        code="19",
        heading="Figures, diagrams, charts, graphs",
        notes="Including other ‘mechanical’ (ie non-photographic) illustrations",
        added_version=13,
    ),
    "20": CodeListEntry(
        list_number=81,
        code="20",
        heading="Additional images / graphics not part of main work",
        notes="Publication is enhanced with additional images or graphical content such as supplementary photographs that are not included in a primary or ‘unenhanced’ version",
        added_version=13,
    ),
    "12": CodeListEntry(
        list_number=81,
        code="12",
        heading="Maps and/or other cartographic content",
        added_version=12,
    ),
    "47": CodeListEntry(
        list_number=81,
        code="47",
        heading="Chemical content",
        notes="Indicates that the publication contains chemical notations, formulae. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "48": CodeListEntry(
        list_number=81,
        code="48",
        heading="Mathematical content",
        notes="Indicates that the publication contains mathematical notation, equations, formulae. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "46": CodeListEntry(
        list_number=81,
        code="46",
        heading="Decorative images or graphics",
        notes="Publication contains visual content that is purely decorative and are not necessary to understanding of the content. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "42": CodeListEntry(
        list_number=81,
        code="42",
        heading="Assessment material",
        notes="eg Questions or student exercises, problems, quizzes or tests (as an integral part of the work). Only for use in ONIX 3.0 or later",
        added_version=40,
    ),
    "01": CodeListEntry(
        list_number=81,
        code="01",
        heading="Audiobook",
        notes="Audio recording of a reading of a book or other text",
        added_version=1,
    ),
    "02": CodeListEntry(
        list_number=81,
        code="02",
        heading="Performance - spoken word",
        notes="Audio recording of a drama or other spoken word performance",
        added_version=1,
    ),
    "13": CodeListEntry(
        list_number=81,
        code="13",
        heading="Other speech content",
        notes="eg an interview, speech, lecture or commentary / discussion, not a ‘reading’ or ‘performance’)",
        added_version=12,
    ),
    "03": CodeListEntry(
        list_number=81,
        code="03",
        heading="Music recording",
        notes="Audio recording of a music performance, including musical drama and opera",
        added_version=1,
    ),
    "04": CodeListEntry(
        list_number=81,
        code="04",
        heading="Other audio",
        notes="Audio recording of other sound, eg birdsong, sound effects, ASMR material",
        added_version=2,
    ),
    "49": CodeListEntry(
        list_number=81,
        code="49",
        heading="Images of text",
        notes="At least some text - including text within other images - is ‘text as an image’ (ie a picture of text). Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "21": CodeListEntry(
        list_number=81,
        code="21",
        heading="Partial performance - spoken word",
        notes="Audio recording of a reading, performance or dramatization of part of the work",
        added_version=13,
    ),
    "22": CodeListEntry(
        list_number=81,
        code="22",
        heading="Additional audio content not part of main content",
        notes="Product includes additional pre-recorded audio of any supplementary material such as full or partial reading, lecture, performance, dramatization, interview, background documentary or other audio content not included in the primary or ‘unenhanced’ version",
        added_version=13,
    ),
    "23": CodeListEntry(
        list_number=81,
        code="23",
        heading="Promotional audio for other book product",
        notes="eg Reading of teaser chapter",
        added_version=13,
    ),
    "06": CodeListEntry(
        list_number=81,
        code="06",
        heading="Video",
        notes="Includes Film, video, animation etc. Use only when no more detailed specification is provided. Formerly ‘Moving images’",
        added_version=2,
    ),
    "26": CodeListEntry(
        list_number=81,
        code="26",
        heading="Video recording of a reading",
        added_version=13,
    ),
    "50": CodeListEntry(
        list_number=81,
        code="50",
        heading="Video content without audio",
        notes="Publication contains video material with no audio recording or narration (but may have music or textual subtitles) . Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "27": CodeListEntry(
        list_number=81,
        code="27",
        heading="Performance - visual",
        notes="Video recording of a drama or other performance, including musical performance",
        added_version=13,
    ),
    "24": CodeListEntry(
        list_number=81,
        code="24",
        heading="Animated / interactive illustrations",
        notes="eg animated diagrams, charts, graphs or other illustrations (usually without sound)",
        added_version=13,
    ),
    "25": CodeListEntry(
        list_number=81,
        code="25",
        heading="Narrative animation",
        notes="eg cartoon, animatic or CGI animation (usually includes sound)",
        added_version=13,
    ),
    "28": CodeListEntry(
        list_number=81,
        code="28",
        heading="Other video",
        notes="Other video content eg interview, not a reading or performance",
        added_version=13,
    ),
    "29": CodeListEntry(
        list_number=81,
        code="29",
        heading="Partial performance - video",
        notes="Video recording of a reading, performance or dramatization of part of the work",
        added_version=13,
    ),
    "30": CodeListEntry(
        list_number=81,
        code="30",
        heading="Additional video content not part of main work",
        notes="E-publication is enhanced with video recording of full or partial reading, performance, dramatization, interview, background documentary or other content not included in the primary or ‘unenhanced’ version",
        added_version=13,
    ),
    "31": CodeListEntry(
        list_number=81,
        code="31",
        heading="Promotional video for other book product",
        notes="eg Book trailer",
        added_version=13,
    ),
    "05": CodeListEntry(
        list_number=81,
        code="05",
        heading="Game / Puzzle",
        notes="No multi-user functionality. Formerly just ‘Game’",
        added_version=2,
    ),
    "32": CodeListEntry(
        list_number=81,
        code="32",
        heading="Contest",
        notes="Includes some degree of multi-user functionality",
        added_version=13,
    ),
    "08": CodeListEntry(
        list_number=81,
        code="08",
        heading="Software",
        notes="Largely ‘content free’",
        added_version=2,
    ),
    "09": CodeListEntry(
        list_number=81,
        code="09",
        heading="Data",
        notes="Data files",
        added_version=2,
    ),
    "33": CodeListEntry(
        list_number=81,
        code="33",
        heading="Data set plus software",
        added_version=13,
    ),
    "34": CodeListEntry(
        list_number=81,
        code="34",
        heading="Blank pages or spaces",
        notes="Entire pages or blank spaces, forms, boxes, write-in pages etc, intended to be filled in by the reader",
        added_version=13,
    ),
    "35": CodeListEntry(
        list_number=81,
        code="35",
        heading="Advertising content",
        notes="Use only where type of advertising content is not stated",
        added_version=13,
    ),
    "37": CodeListEntry(
        list_number=81,
        code="37",
        heading="Advertising - first party",
        notes="‘Back ads’ - promotional content for other books (that does not include sample content of those books, cf codes 17, 23)",
        added_version=13,
    ),
    "36": CodeListEntry(
        list_number=81,
        code="36",
        heading="Advertising - coupons",
        notes="Eg to obtain discounts on other products",
        added_version=13,
    ),
    "38": CodeListEntry(
        list_number=81,
        code="38",
        heading="Advertising - third party display",
        added_version=13,
    ),
    "39": CodeListEntry(
        list_number=81,
        code="39",
        heading="Advertising - third party textual",
        added_version=13,
    ),
    "40": CodeListEntry(
        list_number=81,
        code="40",
        heading="Scripting",
        notes="E-publication contains microprograms written (eg) in JavaScript and executed within the reading system. Only for use in ONIX 3.0 or later",
        added_version=38,
    ),
    "43": CodeListEntry(
        list_number=81,
        code="43",
        heading="Scripted pop-ups",
        notes="E-publication contains pop-ups or other functionality offering (eg) term definitions, cross-links or glossary entries [Note this should not include (eg) dictionary functionality that is part of the reading system.] Only for use in ONIX 3.0 or later",
        added_version=52,
    ),
    "44": CodeListEntry(
        list_number=81,
        code="44",
        heading="Sequential art",
        notes="Or pictorial narrative, usually panel-based. Images displayed in a specific order for the purpose of graphic storytelling or giving information (eg graphic novels, comics and manga). May include text integrated into the image (as speech and thought bubbles, textual ‘sound’ effects, captions etc). Only for use in ONIX 3.0 or later",
        added_version=61,
    ),
}

List81 = CodeList(
    number=81,
    heading="Product content type",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
ProductContentType = List81
