"""ONIX Code List 17: Contributor role code."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "A01": CodeListEntry(
        list_number=17,
        code="A01",
        heading="By (author)",
        notes="Author of a textual work",
    ),
    "A02": CodeListEntry(
        list_number=17,
        code="A02",
        heading="With",
        notes="With or as told to: ‘ghost’ or secondary author of a literary work (for clarity, should not be used for true ‘ghost’ authors who are not credited on the book and whose existence is secret)",
    ),
    "A03": CodeListEntry(
        list_number=17,
        code="A03",
        heading="Screenplay by",
        notes="Writer of screenplay or script (film or video)",
    ),
    "A04": CodeListEntry(
        list_number=17,
        code="A04",
        heading="Libretto by",
        notes="Writer of libretto (opera): see also A31",
    ),
    "A05": CodeListEntry(
        list_number=17,
        code="A05",
        heading="Lyrics by",
        notes="Author of lyrics (song): see also A31",
    ),
    "A06": CodeListEntry(
        list_number=17,
        code="A06",
        heading="By (composer)",
        notes="Composer of music",
    ),
    "A07": CodeListEntry(
        list_number=17,
        code="A07",
        heading="By (artist)",
        notes="Visual artist when named as the primary creator of, eg, a book of reproductions of artworks",
    ),
    "A08": CodeListEntry(
        list_number=17,
        code="A08",
        heading="By (photographer)",
        notes="Photographer when named as the primary creator of, eg, a book of photographs",
    ),
    "A09": CodeListEntry(
        list_number=17,
        code="A09",
        heading="Created by",
        notes="For example of an editorial concept, of a board game, etc",
    ),
    "A10": CodeListEntry(
        list_number=17,
        code="A10",
        heading="From an idea by",
        notes="For example of a plot idea. Implies a less direct association or active participation than ‘created by’",
    ),
    "A11": CodeListEntry(
        list_number=17,
        code="A11",
        heading="Designed by",
        notes="Use for interior graphic design. See code A36 for cover design, code A12, A35 for interior illustrations or drawings",
    ),
    "A12": CodeListEntry(
        list_number=17,
        code="A12",
        heading="Illustrated by",
        notes="Artist when named as the creator of artwork which illustrates a text, or the originator (sometimes ‘penciller’ for collaborative art) of the artwork of a graphic novel or comic book",
    ),
    "A13": CodeListEntry(
        list_number=17,
        code="A13",
        heading="Photographs by",
        notes="Photographer when named as the creator of photographs which illustrate a text",
    ),
    "A14": CodeListEntry(
        list_number=17,
        code="A14",
        heading="Text by",
        notes="Author of text which accompanies art reproductions or photographs, or which is part of a graphic novel or comic book",
    ),
    "A15": CodeListEntry(
        list_number=17,
        code="A15",
        heading="Preface by",
        notes="Author of preface",
    ),
    "A16": CodeListEntry(
        list_number=17,
        code="A16",
        heading="Prologue by",
        notes="Author of prologue",
    ),
    "A17": CodeListEntry(
        list_number=17,
        code="A17",
        heading="Summary by",
        notes="Author of summary",
    ),
    "A18": CodeListEntry(
        list_number=17,
        code="A18",
        heading="Supplement by",
        notes="Author of supplement",
    ),
    "A19": CodeListEntry(
        list_number=17,
        code="A19",
        heading="Afterword by",
        notes="Author of afterword",
    ),
    "A20": CodeListEntry(
        list_number=17,
        code="A20",
        heading="Notes by",
        notes="Author of notes or annotations: see also A29",
    ),
    "A21": CodeListEntry(
        list_number=17,
        code="A21",
        heading="Commentaries by",
        notes="Author of commentaries on the main text",
    ),
    "A22": CodeListEntry(
        list_number=17,
        code="A22",
        heading="Epilogue by",
        notes="Author of epilogue",
    ),
    "A23": CodeListEntry(
        list_number=17,
        code="A23",
        heading="Foreword by",
        notes="Author of foreword",
    ),
    "A24": CodeListEntry(
        list_number=17,
        code="A24",
        heading="Introduction by",
        notes="Author of introduction: see also A29",
    ),
    "A25": CodeListEntry(
        list_number=17,
        code="A25",
        heading="Footnotes by",
        notes="Author/compiler of footnotes",
    ),
    "A26": CodeListEntry(
        list_number=17,
        code="A26",
        heading="Memoir by",
        notes="Author of memoir accompanying main text",
    ),
    "A27": CodeListEntry(
        list_number=17,
        code="A27",
        heading="Experiments by",
        notes="Person who carried out experiments reported in the text",
    ),
    "A28": CodeListEntry(
        list_number=17,
        code="A28",
        heading="Interpreted through",
        notes="Use with narratives drawn from an oral tradition, where no ‘ownership’ of the narrative is claimed. See also B33. Only for use in ONIX 3.0 or later",
        added_version=65,
    ),
    "A29": CodeListEntry(
        list_number=17,
        code="A29",
        heading="Introduction and notes by",
        notes="Author of introduction and notes: see also A20 and A24",
    ),
    "A30": CodeListEntry(
        list_number=17,
        code="A30",
        heading="Software written by",
        notes="Writer of computer programs ancillary to the text",
    ),
    "A31": CodeListEntry(
        list_number=17,
        code="A31",
        heading="Book and lyrics by",
        notes="Author of the textual content of a musical drama: see also A04 and A05",
    ),
    "A32": CodeListEntry(
        list_number=17,
        code="A32",
        heading="Contributions by",
        notes="Author of additional contributions to the text",
    ),
    "A33": CodeListEntry(
        list_number=17,
        code="A33",
        heading="Appendix by",
        notes="Author of appendix",
    ),
    "A34": CodeListEntry(
        list_number=17,
        code="A34",
        heading="Index by",
        notes="Compiler of index",
    ),
    "A35": CodeListEntry(
        list_number=17,
        code="A35",
        heading="Drawings by",
    ),
    "A36": CodeListEntry(
        list_number=17,
        code="A36",
        heading="Cover design or artwork by",
        notes="Use also for the cover artist of a graphic novel or comic book if named separately",
    ),
    "A37": CodeListEntry(
        list_number=17,
        code="A37",
        heading="Preliminary work by",
        notes="Responsible for preliminary work on which the work is based",
    ),
    "A38": CodeListEntry(
        list_number=17,
        code="A38",
        heading="Original author",
        notes="Author of the first edition (usually of a standard work) who is not an author of the current edition",
    ),
    "A39": CodeListEntry(
        list_number=17,
        code="A39",
        heading="Maps by",
        notes="Maps drawn or otherwise contributed by",
        added_version=4,
    ),
    "A40": CodeListEntry(
        list_number=17,
        code="A40",
        heading="Inked or colored by",
        notes="Use for secondary creators when separate persons are named as having respectively drawn and inked/colored/finished artwork, eg for a graphic novel or comic book. Use with A12 for ‘drawn by’. Use A40 for ‘finished by’, but prefer more specific codes A46 to A48 instead of A40 unless the more specific secondary roles are inappropriate, unclear or unavailable",
        added_version=5,
    ),
    "A41": CodeListEntry(
        list_number=17,
        code="A41",
        heading="Paper engineering by",
        notes="Designer or paper engineer of die-cuts, press-outs or of pop-ups in a pop-up book, who may be different from the illustrator",
        added_version=7,
    ),
    "A42": CodeListEntry(
        list_number=17,
        code="A42",
        heading="Continued by",
        notes="Use where a standard work is being continued by somebody other than the original author",
        added_version=7,
    ),
    "A43": CodeListEntry(
        list_number=17,
        code="A43",
        heading="Interviewer",
        added_version=7,
    ),
    "A44": CodeListEntry(
        list_number=17,
        code="A44",
        heading="Interviewee",
        added_version=7,
    ),
    "A45": CodeListEntry(
        list_number=17,
        code="A45",
        heading="Comic script by",
        notes="Writer of dialogue, captions in a comic book (following an outline by the primary writer)",
        added_version=29,
    ),
    "A46": CodeListEntry(
        list_number=17,
        code="A46",
        heading="Inker",
        notes="Renders final comic book line art based on work of the illustrator or penciller (code A12). Preferred to code A40",
        added_version=29,
    ),
    "A47": CodeListEntry(
        list_number=17,
        code="A47",
        heading="Colorist",
        notes="Provides comic book color art and effects. Preferred to code A40",
        added_version=29,
    ),
    "A48": CodeListEntry(
        list_number=17,
        code="A48",
        heading="Letterer",
        notes="Creates comic book text balloons and other text elements (where this is a distinct role from script writer and/or illustrator), or creates calligraphy in non-comic products",
        added_version=29,
    ),
    "A49": CodeListEntry(
        list_number=17,
        code="A49",
        heading="Cover inker",
        notes="Renders final comic book cover line art based on work of the cover designer (code A36), where different from the inker of the interior line art. Only for use in ONIX 3.0 or later",
        added_version=64,
    ),
    "A50": CodeListEntry(
        list_number=17,
        code="A50",
        heading="Cover colorist",
        notes="Provides comic book cover color art and effects, where different from the colorist of the interior art and effects. Only for use in ONIX 3.0 or later",
        added_version=64,
    ),
    "A51": CodeListEntry(
        list_number=17,
        code="A51",
        heading="Research by",
        notes="Person or organization responsible for performing research on which the work is based. Only for use in ONIX 3.0 or later",
        added_version=39,
    ),
    "A52": CodeListEntry(
        list_number=17,
        code="A52",
        heading="Original character design",
        notes="(for comic books). Only for use in ONIX 3.0 or later",
        added_version=64,
    ),
    "A99": CodeListEntry(
        list_number=17,
        code="A99",
        heading="Other primary creator",
        notes="Other type of primary creator not specified above",
    ),
    "B01": CodeListEntry(
        list_number=17,
        code="B01",
        heading="Edited by",
    ),
    "B02": CodeListEntry(
        list_number=17,
        code="B02",
        heading="Revised by",
    ),
    "B03": CodeListEntry(
        list_number=17,
        code="B03",
        heading="Retold by",
    ),
    "B04": CodeListEntry(
        list_number=17,
        code="B04",
        heading="Abridged by",
    ),
    "B05": CodeListEntry(
        list_number=17,
        code="B05",
        heading="Adapted by",
        notes="See also B22 (Dramatized by)",
    ),
    "B06": CodeListEntry(
        list_number=17,
        code="B06",
        heading="Translated by",
    ),
    "B07": CodeListEntry(
        list_number=17,
        code="B07",
        heading="As told by",
    ),
    "B08": CodeListEntry(
        list_number=17,
        code="B08",
        heading="Translated with commentary by",
        notes="This code applies where a translator has provided a commentary on issues relating to the translation. If the translator has also provided a commentary on the work itself, codes B06 and A21 should be used",
    ),
    "B09": CodeListEntry(
        list_number=17,
        code="B09",
        heading="Series edited by",
        notes="Name of a series editor when the product belongs to a series",
    ),
    "B10": CodeListEntry(
        list_number=17,
        code="B10",
        heading="Edited and translated by",
    ),
    "B11": CodeListEntry(
        list_number=17,
        code="B11",
        heading="Editor-in-chief",
    ),
    "B12": CodeListEntry(
        list_number=17,
        code="B12",
        heading="Guest editor",
    ),
    "B13": CodeListEntry(
        list_number=17,
        code="B13",
        heading="Volume editor",
    ),
    "B14": CodeListEntry(
        list_number=17,
        code="B14",
        heading="Editorial board member",
    ),
    "B15": CodeListEntry(
        list_number=17,
        code="B15",
        heading="Editorial coordination by",
    ),
    "B16": CodeListEntry(
        list_number=17,
        code="B16",
        heading="Managing editor",
    ),
    "B17": CodeListEntry(
        list_number=17,
        code="B17",
        heading="Founded by",
        notes="Usually the founder editor of a serial publication (de: Begruendet von)",
        added_version=1,
    ),
    "B18": CodeListEntry(
        list_number=17,
        code="B18",
        heading="Prepared for publication by",
        added_version=2,
    ),
    "B19": CodeListEntry(
        list_number=17,
        code="B19",
        heading="Associate editor",
        added_version=2,
    ),
    "B20": CodeListEntry(
        list_number=17,
        code="B20",
        heading="Consultant editor",
        notes="Use also for ‘advisory editor’, ‘series advisor’, ‘editorial consultant’ etc",
        added_version=2,
    ),
    "B21": CodeListEntry(
        list_number=17,
        code="B21",
        heading="General editor",
        added_version=2,
    ),
    "B22": CodeListEntry(
        list_number=17,
        code="B22",
        heading="Dramatized by",
        notes="See also B05 (Adapted by)",
        added_version=2,
    ),
    "B23": CodeListEntry(
        list_number=17,
        code="B23",
        heading="General rapporteur",
        notes="In Europe, an expert editor who takes responsibility for the legal content of a collaborative law volume",
        added_version=2,
    ),
    "B24": CodeListEntry(
        list_number=17,
        code="B24",
        heading="Literary editor",
        notes="Editor who is responsible for establishing the text used in an edition of a literary work, where this is recognized as a distinctive role (es: editor literario)",
        added_version=6,
    ),
    "B25": CodeListEntry(
        list_number=17,
        code="B25",
        heading="Arranged by (music)",
        added_version=7,
    ),
    "B26": CodeListEntry(
        list_number=17,
        code="B26",
        heading="Technical editor",
        notes="Responsible for the technical accuracy and language, may also be involved in coordinating and preparing technical material for publication",
        added_version=15,
    ),
    "B27": CodeListEntry(
        list_number=17,
        code="B27",
        heading="Thesis advisor or supervisor",
        added_version=23,
    ),
    "B28": CodeListEntry(
        list_number=17,
        code="B28",
        heading="Thesis examiner",
        added_version=23,
    ),
    "B29": CodeListEntry(
        list_number=17,
        code="B29",
        heading="Scientific editor",
        notes="Responsible overall for the scientific content of the publication",
        added_version=30,
    ),
    "B30": CodeListEntry(
        list_number=17,
        code="B30",
        heading="Historical advisor",
        notes="Only for use in ONIX 3.0 or later",
        added_version=37,
    ),
    "B31": CodeListEntry(
        list_number=17,
        code="B31",
        heading="Original editor",
        notes="Editor of the first edition (usually of a standard work) who is not an editor of the current edition. Only for use in ONIX 3.0 or later",
        added_version=37,
    ),
    "B32": CodeListEntry(
        list_number=17,
        code="B32",
        heading="Translation revised by",
        notes="Where possible, use with B06 for the original translator. Only for use in ONIX 3.0 or later",
        added_version=53,
    ),
    "B33": CodeListEntry(
        list_number=17,
        code="B33",
        heading="Transcribed by",
        notes="As told to. Use with narratives drawn from an oral tradition, and with B03 (Retold by), B07 (As told by) or A28 (Interpreted through). Only for use in ONIX 3.0 or later",
        added_version=65,
    ),
    "B34": CodeListEntry(
        list_number=17,
        code="B34",
        heading="Sensitivity reader / editor",
        notes="Reader or editor responsible for ensuring the text is free of offensive, potentially offensive or insensitive language, is inclusive and free from bias, and avoids stereotypical characterization. Only for use in ONIX 3.0 or later",
        added_version=66,
    ),
    "B35": CodeListEntry(
        list_number=17,
        code="B35",
        heading="Image descriptions by",
        notes="Creator of alternative image descriptions for accessibility purposes. Only for use in ONIX 3.0 or later",
        added_version=68,
    ),
    "B36": CodeListEntry(
        list_number=17,
        code="B36",
        heading="Text modernized or updated by",
        notes="Use for modernization or minor updating of language, but not for original contributions to the text",
        added_version=71,
    ),
    "B99": CodeListEntry(
        list_number=17,
        code="B99",
        heading="Other adaptation by",
        notes="Other type of adaptation or editing not specified above",
    ),
    "C01": CodeListEntry(
        list_number=17,
        code="C01",
        heading="Compiled by",
        notes="For puzzles, directories, statistics, etc",
    ),
    "C02": CodeListEntry(
        list_number=17,
        code="C02",
        heading="Selected by",
        notes="For textual material (eg for an anthology)",
    ),
    "C03": CodeListEntry(
        list_number=17,
        code="C03",
        heading="Non-text material selected by",
        notes="Eg for a collection of photographs etc",
        added_version=31,
    ),
    "C04": CodeListEntry(
        list_number=17,
        code="C04",
        heading="Curated by",
        notes="Eg for an exhibition",
        added_version=31,
    ),
    "C99": CodeListEntry(
        list_number=17,
        code="C99",
        heading="Other compilation by",
        notes="Other type of compilation not specified above",
    ),
    "D01": CodeListEntry(
        list_number=17,
        code="D01",
        heading="Producer",
        notes="Of a film, of a theatrical or multimedia production, of dramatized audio etc",
    ),
    "D02": CodeListEntry(
        list_number=17,
        code="D02",
        heading="Director",
        notes="Of a film, of a theatrical or multimedia production, of dramatized audio etc",
    ),
    "D03": CodeListEntry(
        list_number=17,
        code="D03",
        heading="Conductor",
        notes="Conductor of a musical performance",
    ),
    "D04": CodeListEntry(
        list_number=17,
        code="D04",
        heading="Choreographer",
        notes="Of a dance performance. Only for use in ONIX 3.0 or later",
        added_version=38,
    ),
    "D99": CodeListEntry(
        list_number=17,
        code="D99",
        heading="Other direction by",
        notes="Other type of direction not specified above",
    ),
    "E01": CodeListEntry(
        list_number=17,
        code="E01",
        heading="Actor",
        notes="Performer in a dramatized production (including a voice actor in an audio production)",
    ),
    "E02": CodeListEntry(
        list_number=17,
        code="E02",
        heading="Dancer",
    ),
    "E03": CodeListEntry(
        list_number=17,
        code="E03",
        heading="Narrator",
        notes="Where the narrator is a character in a dramatized production (including a voice actor in an audio production). For the ‘narrator’ of a non-dramatized audiobook, use code E07",
    ),
    "E04": CodeListEntry(
        list_number=17,
        code="E04",
        heading="Commentator",
    ),
    "E05": CodeListEntry(
        list_number=17,
        code="E05",
        heading="Vocal soloist",
        notes="Singer etc",
    ),
    "E06": CodeListEntry(
        list_number=17,
        code="E06",
        heading="Instrumental soloist",
    ),
    "E07": CodeListEntry(
        list_number=17,
        code="E07",
        heading="Read by",
        notes="Reader of recorded text, as in an audiobook",
    ),
    "E08": CodeListEntry(
        list_number=17,
        code="E08",
        heading="Performed by (orchestra, band, ensemble)",
        notes="Name of a musical group in a performing role",
    ),
    "E09": CodeListEntry(
        list_number=17,
        code="E09",
        heading="Speaker",
        notes="Of a speech, lecture etc",
        added_version=15,
    ),
    "E10": CodeListEntry(
        list_number=17,
        code="E10",
        heading="Presenter",
        notes="Introduces and links other contributors and material, eg within a documentary",
        added_version=32,
    ),
    "E11": CodeListEntry(
        list_number=17,
        code="E11",
        heading="Introduction read by",
        notes="Reader of recorded introduction (or other ‘front matter’) in an audiobook. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "E99": CodeListEntry(
        list_number=17,
        code="E99",
        heading="Performed by",
        notes="Other type of performer not specified above: use for a recorded performance which does not fit a category above, eg a performance by a stand-up comedian",
    ),
    "F01": CodeListEntry(
        list_number=17,
        code="F01",
        heading="Filmed/photographed by",
        notes="Cinematographer, etc",
    ),
    "F02": CodeListEntry(
        list_number=17,
        code="F02",
        heading="Editor (film or video)",
        added_version=25,
    ),
    "F99": CodeListEntry(
        list_number=17,
        code="F99",
        heading="Other recording by",
        notes="Other type of recording not specified above",
    ),
    "Z01": CodeListEntry(
        list_number=17,
        code="Z01",
        heading="Assisted by",
        notes="Contributor must follow another contributor with any contributor role, and placement should therefore be controlled by contributor sequence numbering to ensure the correct association",
        added_version=2,
    ),
    "Z02": CodeListEntry(
        list_number=17,
        code="Z02",
        heading="Honored/dedicated to",
        added_version=32,
    ),
    "Z03": CodeListEntry(
        list_number=17,
        code="Z03",
        heading="Enacting jurisdiction",
        notes="For publication of laws, regulations, rulings etc. Only for use in ONIX 3.0 or later",
        added_version=48,
    ),
    "Z04": CodeListEntry(
        list_number=17,
        code="Z04",
        heading="Peer reviewed",
        notes="Use with <UnnamedPersons> code 02 as a ‘flag’ to indicate the publication is anonymously peer-reviewed. Only for use in ONIX 3.0 or later",
        added_version=49,
    ),
    "Z05": CodeListEntry(
        list_number=17,
        code="Z05",
        heading="Posthumously completed by",
        notes="Contributor must follow another (posthumous) contributor with any contributor role, and placement should therefore be controlled by contributor sequence numbering to ensure the correct association. Only for use in ONIX 3.0 or later",
        added_version=64,
    ),
    "Z06": CodeListEntry(
        list_number=17,
        code="Z06",
        heading="In association with",
        notes="Contributor must follow another contributor with any contributor role, and placement should therefore be controlled by contributor sequence numbering to ensure the correct association. See also ‘published in association with’ in List 45. Only for use in ONIX 3.0 or later",
        added_version=67,
    ),
    "Z98": CodeListEntry(
        list_number=17,
        code="Z98",
        heading="(Various roles)",
        notes="For use ONLY with ‘et al’ or ‘Various’ within <UnnamedPersons>, where the roles of the multiple contributors vary",
        added_version=20,
    ),
    "Z99": CodeListEntry(
        list_number=17,
        code="Z99",
        heading="Other",
        notes="Other creative responsibility not falling within A to F above",
    ),
}

List17 = CodeList(
    number=17,
    heading="Contributor role code",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
ContributorRole = List17
