"""ONIX Code List 79: Product form feature type."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "01": CodeListEntry(
        list_number=79,
        code="01",
        heading="Color of cover",
        notes="For Product Form Feature values see code list 98",
        added_version=1,
    ),
    "26": CodeListEntry(
        list_number=79,
        code="26",
        heading="Color of spine",
        notes="Where it is different from the overall color of the cover (see code 01). For Product Form Feature values see code list 98. Only for use in ONIX 3.0 or later",
        added_version=59,
    ),
    "27": CodeListEntry(
        list_number=79,
        code="27",
        heading="Color of foil (on cover)",
        notes="On cover or spine. For Product form feature values see metallic colors from code list 98. If further detail is required, also use Product form feature description. Only for use in ONIX 3.0 or later",
        added_version=61,
    ),
    "59": CodeListEntry(
        list_number=79,
        code="59",
        heading="Color of foil (on jacket)",
        notes="On dustjacket. For Product Form Feature values see metallic colors from code list 98. If further detail is required, also use Product form feature description. Only for use in ONIX 3.0 or later",
        added_version=71,
    ),
    "02": CodeListEntry(
        list_number=79,
        code="02",
        heading="Color of page edges",
        notes="Sprayed / stained / gilded edges. For Product form feature values see code list 98. For patterned and illustrated page edges, also use Product form feature description or see List 158 code 54",
        added_version=1,
    ),
    "55": CodeListEntry(
        list_number=79,
        code="55",
        heading="Color of endpapers",
        notes="Or of inside front and back covers. For Product form feature values see Codelist 98. For patterned and illustrated endpapers, also use Product form feature description or see List 158 code 55. Only for use in ONIX 3.0 or later",
        added_version=69,
    ),
    "57": CodeListEntry(
        list_number=79,
        code="57",
        heading="Color of ribbon marker(s)",
        notes="Use also for color of elasticated strap. For Product Form Feature Values see Codelist 98, and with multicolored or multiple ribbons, also use Product Form Feature Description. Only for use in ONIX 3.0 or later",
        added_version=70,
    ),
    "58": CodeListEntry(
        list_number=79,
        code="58",
        heading="Color of head and tail bands",
        notes="Capital bands. For Product form feature values see codelist 98, and with multicolored (eg striped) bands, also use Product form feature description. Only for use in ONIX 3.0 or later",
        added_version=70,
    ),
    "03": CodeListEntry(
        list_number=79,
        code="03",
        heading="Text font",
        notes="The principal font used for body text, when this is a significant aspect of product description, eg for some Bibles, and for large print product. The accompanying <ProductFormFeatureDescription> is text specifying the typeface name. The font size may be specified with the font name, but is preferred separately (in points) in <ProductFormFeatureValue>",
        added_version=1,
    ),
    "04": CodeListEntry(
        list_number=79,
        code="04",
        heading="Special cover material",
        notes="For Product Form Feature values see code list 99",
        added_version=1,
    ),
    "05": CodeListEntry(
        list_number=79,
        code="05",
        heading="DVD region",
        notes="For Product Form Feature values see code list 76",
        added_version=2,
    ),
    "06": CodeListEntry(
        list_number=79,
        code="06",
        heading="Operating system requirements",
        notes="A computer or handheld device operating system required to use a digital product, with version detail if applicable. The accompanying Product Form Feature Value is a code from List 176. Version detail, when applicable, is carried in Product Form Feature Description",
        added_version=10,
    ),
    "07": CodeListEntry(
        list_number=79,
        code="07",
        heading="Other system requirements",
        notes="Other system requirements for a digital product, described by free text in Product Form Feature Description",
        added_version=10,
    ),
    "08": CodeListEntry(
        list_number=79,
        code="08",
        heading="‘Point and listen’ device compatibility",
        notes="Indicates compatibility with proprietary ‘point and listen’ devices such as Ting Pen (http://www.ting.eu), the iSmart Touch and Read Pen. These devices scan invisible codes specially printed on the page to identify the book and position of the word, and the word is then read aloud by the device. The name of the compatible device (or range of devices) should be given in <ProductFormFeatureDescription>",
        added_version=15,
    ),
    "09": CodeListEntry(
        list_number=79,
        code="09",
        heading="E-publication accessibility detail",
        notes="For <ProductFormFeatureValue> codes, see Codelist 196",
        added_version=15,
    ),
    "10": CodeListEntry(
        list_number=79,
        code="10",
        heading="E-publication format version",
        notes="For versioned e-book file formats (or in some cases, devices). <ProductFormFeatureValue> should contain the version number as a period-separated list of numbers (eg ‘7’, ‘1.5’ or ‘3.10.7’). Only for use in ONIX 3.0 or later - in ONIX 2.1, use <EpubTypeVersion> instead. For the most common file formats, code 15 and List 220 is strongly preferred",
        added_version=17,
    ),
    "12": CodeListEntry(
        list_number=79,
        code="12",
        heading="US CPSIA or other international hazard warning",
        notes="Hazard warning required by US Consumer Product Safety Improvement Act (CPSIA) of 2008 or other US or international legislation. Required, when applicable, for products sold in the US. The Product Form Feature Value is a code from List 143. Further explanation may be given in Product Form Feature Description",
        added_version=9,
    ),
    "13": CodeListEntry(
        list_number=79,
        code="13",
        heading="EU General Product Safety Regulation and Toy Safety Directive hazard warning",
        notes="Product carries hazard warning, conformity notice or other text required by EU General Product Safety Regulation or Toy Safety Directive. The Product Form Feature Value is a code from List 184, and (for some codes) the exact wording of the warning or text may be given in Product Form Feature Description",
        added_version=13,
    ),
    "14": CodeListEntry(
        list_number=79,
        code="14",
        heading="IATA Dangerous Goods warning",
        notes="Product Form Feature Description must give further details of the warning",
        added_version=21,
    ),
    "15": CodeListEntry(
        list_number=79,
        code="15",
        heading="E-publication format version code",
        notes="For common versioned e-book formats (or in some cases, devices) - for example EPUB 2.0.1 or EPUB 3.0. <ProductFormFeatureValue> is a code from list 220. Only for use in ONIX 3.0 or later",
        added_version=24,
    ),
    "16": CodeListEntry(
        list_number=79,
        code="16",
        heading="E-publication format validator version",
        notes="For common versioned e-book formats, the name and version of the validator used to check conformance. <ProductFormFeatureDescription> is the common name of the validator used (eg EpubCheck, Flightdeck), and <ProductFormFeatureValue> is the version number of the validator (eg 4.0.0a). Use with code 15 (or possibly code 10), or with <EpubTypeVersion>, to specify the version the e-publication conforms with",
        added_version=30,
    ),
    "17": CodeListEntry(
        list_number=79,
        code="17",
        heading="‘Point and watch’ device/app compatibility",
        notes="Indicates compatibility with proprietary ‘point and watch‘ devices or apps. These scan invisible codes specially printed on the page, or the whole page image, to identify the book and page position. Scanning can trigger display of (for example) an augmented reality view of the page. The name of the compatible app or device (or range of apps/devices) should be given in <ProductFormFeatureDescription>. Only for use in ONIX 3.0 or later",
        added_version=39,
    ),
    "18": CodeListEntry(
        list_number=79,
        code="18",
        heading="E-publication authentication and access control",
        notes="Requirement for user authentication prior to use, with detail of authentication method (user enrolment, and login passwords, location- or device-based recognition, authentication via third-party identity service etc) given in <ProductFormFeatureDescription>. Only for use in ONIX 3.0 or later",
        added_version=44,
    ),
    "19": CodeListEntry(
        list_number=79,
        code="19",
        heading="Battery type and safety",
        notes="Use to describe battery requirements, types, hazards and battery safety warnings. <ProductFormFeatureValue> is a code from List 242. Only for use in ONIX 3.0 or later",
        added_version=45,
    ),
    "20": CodeListEntry(
        list_number=79,
        code="20",
        heading="Battery capacity",
        notes="Total capacity (of batteries in the product) in Watt hours. <ProductFormFeatureValue> is an integer or decimal number (eg ‘45’, not ‘45Wh’). Only for use in ONIX 3.0 or later",
        added_version=45,
    ),
    "21": CodeListEntry(
        list_number=79,
        code="21",
        heading="Dangerous goods",
        notes="Use to describe regulation of the product for various purposes. <ProductFormFeatureValue> is a code from List 243. Only for use in ONIX 3.0 or later",
        added_version=45,
    ),
    "22": CodeListEntry(
        list_number=79,
        code="22",
        heading="Game pieces",
        notes="Number of pieces, eg for jigsaws, puzzles, kits, board games. <ProductFormFeatureValue> is an integer. Only for use in ONIX 3.0 or later. For pieces like cards in a pack, see <Extent> and code 00 from List 24",
        added_version=48,
    ),
    "23": CodeListEntry(
        list_number=79,
        code="23",
        heading="Game players",
        notes="Number of players, for board games, card games, videogames etc. <ProductFormFeatureValue> must be a required (exact) number as an integer OR a range (eg ‘2-6’), optionally accompanied by the number of players as text (eg ‘suitable for 2-6 players’) in <ProductFormFeatureDescription>. Only for use in ONIX 3.0 or later",
        added_version=48,
    ),
    "24": CodeListEntry(
        list_number=79,
        code="24",
        heading="Game play time",
        notes="Typical time to complete a game, for board games, card games, videogames etc, stated as an integer (in minutes) OR range (eg ‘60-90’) in <ProductFormFeatureValue>, optionally accompanied by the playing time as text (eg ‘typically 60-90 minutes’) in <ProductFormFeatureDescription>. Only for use in ONIX 3.0 or later",
        added_version=48,
    ),
    "25": CodeListEntry(
        list_number=79,
        code="25",
        heading="Personal data requirements",
        notes="Personal data required for registration or use of the product. This can be coded in <ProductFormFeatureValue> (for example using a URI from SCOLOM list 044 - see http://data.education.fr/voc/scolomfr/scolomfr-voc-044) - and/or described in <ProductFormFeatureDescription>. Only for use in ONIX 3.0 or later",
        added_version=53,
    ),
    "30": CodeListEntry(
        list_number=79,
        code="30",
        heading="Not FSC or PEFC certified",
        notes="Product does not carry FSC or PEFC logo. The Product Form Feature Value element is not used. The Product Form Feature Description element may carry free text indicating the grade or type of paper. The product record may also still carry a claimed Pre- and Post-Consumer Waste (PCW) percentage value (type code 37) in a separate repeat of the Product Form Feature composite",
        added_version=10,
    ),
    "31": CodeListEntry(
        list_number=79,
        code="31",
        heading="FSC certified - pure",
        notes="Product carries FSC logo (Pure, 100%). <ProductFormFeatureValue> is the Certification number (ie either a Chain Of Custody (COC) number or a Trademark License number) printed on the book. Format: Chain of Custody number is two to five letters-COC-six digits (the digits should include leading zeros if necessary), eg ‘AB-COC-001234’ or ‘ABCDE-COC-123456’; Trademark License number is C followed by six digits, eg ‘C005678’ (this would normally be prefixed by ‘FSC(R)’ when displayed). The Product Form Feature Description element may carry free text indicating the grade or type of paper. By definition, a product certified Pure does not contain Pre- or Post-Consumer-Waste (PCW), so type code 31 can only occur on its own. Certification numbers may be checked at https://info.fsc.org/",
        added_version=10,
    ),
    "32": CodeListEntry(
        list_number=79,
        code="32",
        heading="FSC certified - mixed sources",
        notes="Product carries FSC logo (Mixed sources, Mix). <ProductFormFeatureValue> is the Certification number (ie either a Chain Of Custody (COC) number or a Trademark License number) printed on the book. Format: Chain of Custody number is two to five letters-COC-six digits (the digits should include leading zeros if necessary), eg ‘AB-COC-001234’ or ‘ABCDE-COC-123456’; Trademark License number is C followed by six digits, eg ‘C005678’ (this would normally be prefixed by ‘FSC(R)’ when displayed). The Product Form Feature Description element may carry free text indicating the grade or type of paper. May be accompanied by a Pre- and Post-Consumer-Waste (PCW) percentage value, to be reported in another instance of <ProductFormFeature> with type code 36. Certification numbers may be checked at https://info.fsc.org/",
        added_version=10,
    ),
    "33": CodeListEntry(
        list_number=79,
        code="33",
        heading="FSC certified - recycled",
        notes="Product carries FSC logo (Recycled). <ProductFormFeatureValue> is the Certification number (ie either a Chain Of Custody (COC) number or a Trademark License number) printed on the book. Format: Chain of Custody number is two to five letters-COC-six digits (the digits should include leading zeroes if necessary), eg ‘AB-COC-001234’ or ‘ABCDE-COC-123456’; Trademark License number is C followed by six digits, eg ‘C005678’ (this would normally be prefixed by ‘FSC(R)’ when displayed). The Product Form Feature Description element may carry free text indicating the grade or type of paper. May be accompanied by a Pre- and Post-Consumer-Waste (PCW) percentage value, to be reported in another instance of <ProductFormFeature> with type code 36, but otherwise assumed to be 100% recycled. Certification numbers may be checked at https://info.fsc.org/",
        added_version=10,
    ),
    "34": CodeListEntry(
        list_number=79,
        code="34",
        heading="PEFC certified",
        notes="Product carries PEFC logo (certified) or equivalent from PEFC-endorsed national scheme. <ProductFormFeatureValue> is the Chain Of Custody (COC) number printed on the book. The Product Form Feature Description element may carry free text indicating the grade or type of paper. May be accompanied by a Post-Consumer Waste (PCW) percentage value, to be reported in another instance of <ProductFormFeature> with type code 36",
        added_version=10,
    ),
    "35": CodeListEntry(
        list_number=79,
        code="35",
        heading="PEFC recycled",
        notes="Product carries PEFC logo (recycled) or equivalent from PEFC-endorsed national scheme. <ProductFormFeatureValue> is the Chain Of Custody (COC) number printed on the book. The Product Form Feature Description element may carry free text indicating the grade or type of paper. Should be accompanied by a Post-Consumer-Waste (PCW) percentage value, to be reported in another instance of <ProductFormFeature> with type code 36",
        added_version=10,
    ),
    "36": CodeListEntry(
        list_number=79,
        code="36",
        heading="FSC or PEFC certified Pre- and Post-Consumer Waste (PCW) percentage",
        notes="The percentage of recycled Pre- and Post-Consumer-Waste (PCW) used in a product where the composition is certified by FSC, PEFC or PEFC-endorsed scheme. <ProductFormFeatureValue> is an integer. May occur together with type code 32, 33, 34 or 35",
        added_version=10,
    ),
    "37": CodeListEntry(
        list_number=79,
        code="37",
        heading="Claimed Pre- and Post-Consumer Waste (PCW) percentage",
        notes="The percentage of recycled Pre- and Post-Consumer Waste (PCW) claimed to be used in a product where the composition is not certified by FSC or PEFC. <Product FormFeatureValue> is an integer. <ProductFormFeatureDescription> may carry free text supporting the claim. Must be accompanied by type code 30",
        added_version=10,
    ),
    "38": CodeListEntry(
        list_number=79,
        code="38",
        heading="‘Green’ inks",
        notes="Vegetable-based or other environmentally-conscious inks and varnishes. <ProductFormFeatureDescription> may carry free text with a more detailed statement. Only for use in ONIX 3.0 or later",
        added_version=55,
    ),
    "39": CodeListEntry(
        list_number=79,
        code="39",
        heading="‘Green’ adhesives",
        notes="Product binding uses environmentally-conscious adhesives and other binding materials. <ProductFormFeatureDescription> may carry free text with a more detailed statement. Only for use in ONIX 3.0 or later",
        added_version=55,
    ),
    "40": CodeListEntry(
        list_number=79,
        code="40",
        heading="Paper produced by ‘green’ technology",
        notes="Product made from paper produced using environmentally-conscious technology. <ProductFormFeatureDescription> may carry free text with a more detailed statement",
        added_version=11,
    ),
    "41": CodeListEntry(
        list_number=79,
        code="41",
        heading="Carbon/GHG emission certification scheme",
        notes="<ProductFormFeatureValue> is a code from List 262 identifying the particular certification scheme. <ProductFormFeatureDescription> may be a descriptor for some part, schedule or annex of the certification scheme, where necessary. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "42": CodeListEntry(
        list_number=79,
        code="42",
        heading="Carbon/GHG emission certification / license number",
        notes="<ProductFormFeatureValue> is a code from List 262 identifying a particular certification scheme. <ProductFormFeatureDescription> is a certificate or license number used to certify compliance with the scheme. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "43": CodeListEntry(
        list_number=79,
        code="43",
        heading="Carbon/GHG emission certification URL",
        notes="<ProductFormFeatureValue> is a code from List 262 identifying a particular certification scheme. <ProductFormFeatureDescription> is a URL linking to a web page certifying compliance with the scheme. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "44": CodeListEntry(
        list_number=79,
        code="44",
        heading="Carbon/GHG Scope 3 certified Carbon dioxide equivalent emission",
        notes="<ProductFormFeatureValue> is a code from List 262 identifying a particular certification scheme. <ProductFormFeatureDescription> is a number specifying certified GHG emissions per copy of the product, measured in kilograms of Carbon dioxide equivalent (CO₂e) using the Scope 3 methodology of the scheme. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "45": CodeListEntry(
        list_number=79,
        code="45",
        heading="Carbon/GHG Scope 2 certified Carbon dioxide equivalent emission",
        notes="Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "46": CodeListEntry(
        list_number=79,
        code="46",
        heading="Carbon/GHG Scope 1 certified Carbon dioxide equivalent emission",
        notes="Scope 1 emission certifications are not recommended for use. Only for use in ONIX 3.0 or later",
        added_version=62,
    ),
    "47": CodeListEntry(
        list_number=79,
        code="47",
        heading="EUDR raw material location (interior or full product)",
        notes="For EU Deforestation regulations, location of raw material source plot (‘where the tree grew’) for the interior or main body of the product (or for the entire product, if the raw material source for the binding and other parts of the product cannot be differentiated). If there are multiple sources for the same raw material, repeat <ProductFormFeature> for each plot or use the ‘list of plots’ option below. Further repeats of <ProductFormFeature> may be used for multiple paper, card and board types. <ProductFormFeatureValue> is a country code from List 91 indicating the country in which the source plot is, optionally followed by a space and the name of the species, and optionally followed by a space and the date of harvest of the source plot (YYYY, YYYYMM or YYYYMMDD). A species name may itself consist of the binomial Latin name (the ‘scientific name’), or the binomial Latin name followed by a space plus the common name in parentheses. The common name may only be included if the Latin name is also present. Alternatively, a list of multiple species names from the same source plot may be listed, separated by commas. In such a list, all species names must include both scientific and common name, or all must include a scientific name only. Note there can be up to four types of data (country, a Latin name and a common name, or a comma-separated list of Latin names and common names, and a date), each space separated, but only the country is mandatory. <ProductFormFeatureDescription> is a list of points defining one or more plots from which the raw material was harvested, using GPS coordinates with 6 decimal places of precision (these are real numbers, ±90 for latitude [negative numbers indicate a latitude south of the equator], ±180 excluding -180 itself for longitude [negative numbers indicate a longitude west of the Prime Greenwich meridian]). Latitude and Longitude for each point are space-separated, and multiple points are comma-separated. Multiple plots are semicolon separated, and must be in the same country. (Any supplied species name and date must also apply to all plots in the list.) (Note these GPS coordinates use decimal parts of a degree, not minutes and seconds.) ONE point defines the center of a 4 hectare plot (200m × 200m). TWO points define a line joining opposite corners of a ‘square’ plot bounded by two lines of latitude and two of longitude. THREE or more points define a simple polygon outlining the plot. Plot types with one, two or multiple points must not be mixed in a list of multiple plots. Lines and polygon edges may not cross a national boundary or the 180° line of longitude. Polygon edges may not intersect. It is good practice to ensure the polygon is drawn clockwise and is ‘closed’ (that is, that the first and last points are identical, so that for example four points define a triangle). If not closed, the closing polygon edge is implied, and to avoid ambiguity, trailing zeros in the latitude and longitude should be explicit. Only for use in ONIX 3.0 or later",
        added_version=66,
    ),
    "48": CodeListEntry(
        list_number=79,
        code="48",
        heading="EUDR raw material location (binding)",
        notes="As code 47, but for endpaper, cover card or board, any other binding or covering material and any jacket (but not including any slipcase or other packaging). Only for use in ONIX 3.0 or later",
        added_version=66,
    ),
    "49": CodeListEntry(
        list_number=79,
        code="49",
        heading="EUDR raw material location (other)",
        notes="As code 47, but for any slipcase or box, retail packaging, supplementary material (but not including any packaging discarded before retail sale). Only for use in ONIX 3.0 or later",
        added_version=66,
    ),
    "50": CodeListEntry(
        list_number=79,
        code="50",
        heading="EUDR due diligence reference",
        notes="For EU Deforestation Regulations, <ProductFormFeatureValue> is the ‘Due Diligence Statement’ (DDS) document reference recorded by the publisher or other organization responsible for the product when a due diligence statement is uploaded to the EU’s portal, expected to be in a format like ‘24FRXVV3VOS991’ (with an optional suffix ‘+’ and a ‘verification code’ expected to be in a format like ‘A4B3C2D1’). This reference is the DDS for the product as a whole. There may also be a UUID acting as an internal or proprietary document reference, for which use <ProductFormFeatureDescription>. <ProductFormFeature> should be repeated if multiple DDSs apply to the product as a whole. Only for use in ONIX 3.0 or later. See https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en",
        added_version=66,
    ),
    "51": CodeListEntry(
        list_number=79,
        code="51",
        heading="EUDR associated due diligence references",
        notes="For EU Deforestation Regulation, <ProductFormFeatureValue> is a space-separated list of document references for DDSs (including optional verification code) created by upstream operators that are or may be referred to in the DDS for the product as a whole (ie the DDS specified using code 50)) - for example DDSs for the paper types used to manufacture the product. Only for use in ONIX 3.0 or later",
        added_version=67,
    ),
    "52": CodeListEntry(
        list_number=79,
        code="52",
        heading="EUDR compliant with national law attestation",
        notes="For EU Deforestation regulations, a ‘flag’ indicating that all raw materials were produced in accordance with legal requirements of one or more countries within each of which there are one or more source plots, and that documentation to verify this is available upon request. <ProductFormFeatureValue> is a space-separated list of country codes from List 91. Presence of code 52 and a country code acts as an positive attestation that the product’s raw materials sourced from the specified country are compliant with the national laws of that country, but the attestation is meaningful only if there is no pre-existing DDS for the product as a whole (presence of a DDS reference already attests the product is compliant with all national laws and that documentation is available). Only for use in ONIX 3.0 or later",
        added_version=67,
    ),
    "53": CodeListEntry(
        list_number=79,
        code="53",
        heading="EUDR deforestation-free attestation",
        notes="For EU Deforestation regulations, a ‘flag’ indicating that all raw materials used for the product are ‘deforestation-free’, and that documentation to verify this is available upon request. Presence of code 53 acts as a positive attestation that the product’s raw materials are deforestation-free, but the attestation is meaningful only if there is no pre-existing DDS for the product as a whole (presence of a DDS reference already attests the product is deforestation-free and that documentation is available). Only for use in ONIX 3.0 or later",
        added_version=67,
    ),
    "54": CodeListEntry(
        list_number=79,
        code="54",
        heading="EUDR stock present attestation",
        notes="For EU Deforestation regulations, a ‘flag’ indicating that no (in-EU) supplier has stock that was not physically present within the EU prior to the enforcement date of the Regulation, and that documentation to verify this is available upon request. Presence of code 54 acts as a positive attestation that all copies of the product held at distributors and wholesalers within the EU pre-dates the enforcement date, but the attestation is meaningful only if there is no pre-existing DDS for the product as a whole (presence of a DDS reference already attests the product is compliant with the regulation and that documentation is available). Only for use in ONIX 3.0 or later",
        added_version=68,
    ),
    "56": CodeListEntry(
        list_number=79,
        code="56",
        heading="EUDR beyond scope attestation",
        notes="For EU Deforestation regulations, a ‘flag’ indicating that the raw materials for the product are entirely outside the scope of the regulations for any reason, for example because a map - that would otherwise be required to conform - is printed on plastic rather than paper, or a book is made wholly of recycled raw materials (including the cover). <ProductClassification> may contain an additional TARIC exemption code. Ensure other Product form features agree, and that documentation is available. Only for use in ONIX 3.0 or later. No other EUDR metadata need be included",
        added_version=70,
    ),
    "60": CodeListEntry(
        list_number=79,
        code="60",
        heading="EUDR raw material location (interior or full product) URL",
        notes="As code 47, but <ProductFormFeatureDescription> is the URL of a GeoJSON file outlining the source plot. Only for use in ONIX 3.0 or later",
        added_version=71,
    ),
    "61": CodeListEntry(
        list_number=79,
        code="61",
        heading="EUDR raw material location (binding) URL",
        notes="As code 48, but <ProductFormFeatureDescription> is the URL of a GeoJSON file outlining the source plot. Only for use in ONIX 3.0 or later",
        added_version=71,
    ),
    "62": CodeListEntry(
        list_number=79,
        code="62",
        heading="EUDR raw material location (other) URL",
        notes="As code 49, but <ProductFormFeatureDescription> is the URL of a GeoJSON file outlining the source plot. Only for use in ONIX 3.0 or later",
        added_version=71,
    ),
}

List79 = CodeList(
    number=79,
    heading="Product form feature type",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
ProductFormFeatureType = List79
