"""ONIX Code List 96: Currency code - based on ISO 4217."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "AED": CodeListEntry(
        list_number=96,
        code="AED",
        heading="UAE Dirham",
        notes="United Arab Emirates",
    ),
    "AFA": CodeListEntry(
        list_number=96,
        code="AFA",
        heading="Afghani",
        notes="Afghanistan. Deprecated, replaced by AFN",
        deprecated_version=4,
    ),
    "AFN": CodeListEntry(
        list_number=96,
        code="AFN",
        heading="Afghani",
        notes="Afghanistan (prices normally quoted as integers)",
        added_version=4,
    ),
    "ALL": CodeListEntry(
        list_number=96,
        code="ALL",
        heading="Lek",
        notes="Albania (prices normally quoted as integers)",
    ),
    "AMD": CodeListEntry(
        list_number=96,
        code="AMD",
        heading="Armenian Dram",
        notes="Armenia (prices normally quoted as integers)",
    ),
    "ANG": CodeListEntry(
        list_number=96,
        code="ANG",
        heading="Netherlands Antillean Guilder",
        notes="Curaçao, Sint Maarten. Replaced by the Caribbean Guilder (XCG) from April 2025. Deprecated - use only for historical prices that pre-date withdrawal",
        deprecated_version=69,
    ),
    "AOA": CodeListEntry(
        list_number=96,
        code="AOA",
        heading="Kwanza",
        notes="Angola",
    ),
    "ARS": CodeListEntry(
        list_number=96,
        code="ARS",
        heading="Argentine Peso",
        notes="Argentina",
    ),
    "ATS": CodeListEntry(
        list_number=96,
        code="ATS",
        heading="Schilling",
        notes="Austria. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "AUD": CodeListEntry(
        list_number=96,
        code="AUD",
        heading="Australian Dollar",
        notes="Australia, Christmas Island, Cocos (Keeling) Islands, Heard Island and McDonald Islands, Kiribati, Nauru, Norfolk Island, Tuvalu",
    ),
    "AWG": CodeListEntry(
        list_number=96,
        code="AWG",
        heading="Aruban Florin",
        notes="Aruba",
    ),
    "AZN": CodeListEntry(
        list_number=96,
        code="AZN",
        heading="Azerbaijan Manat",
        notes="Azerbaijan",
        added_version=7,
    ),
    "BAM": CodeListEntry(
        list_number=96,
        code="BAM",
        heading="Convertible Marks",
        notes="Bosnia and Herzegovina",
    ),
    "BBD": CodeListEntry(
        list_number=96,
        code="BBD",
        heading="Barbados Dollar",
        notes="Barbados",
    ),
    "BDT": CodeListEntry(
        list_number=96,
        code="BDT",
        heading="Taka",
        notes="Bangladesh",
    ),
    "BEF": CodeListEntry(
        list_number=96,
        code="BEF",
        heading="Belgian Franc",
        notes="Belgium. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "BGL": CodeListEntry(
        list_number=96,
        code="BGL",
        heading="Bulgarian Lev",
        notes="Deprecated, replaced by BGN",
        deprecated_version=4,
    ),
    "BGN": CodeListEntry(
        list_number=96,
        code="BGN",
        heading="Bulgarian Lev",
        notes="Bulgaria",
        added_version=4,
    ),
    "BHD": CodeListEntry(
        list_number=96,
        code="BHD",
        heading="Bahraini Dinar",
        notes="Bahrain (prices normally quoted with 3 decimal places)",
    ),
    "BIF": CodeListEntry(
        list_number=96,
        code="BIF",
        heading="Burundi Franc",
        notes="Burundi (prices normally quoted as integers)",
    ),
    "BMD": CodeListEntry(
        list_number=96,
        code="BMD",
        heading="Bermudian Dollar",
        notes="Bermuda",
    ),
    "BND": CodeListEntry(
        list_number=96,
        code="BND",
        heading="Brunei Dollar",
        notes="Brunei Darussalam",
    ),
    "BOB": CodeListEntry(
        list_number=96,
        code="BOB",
        heading="Boliviano",
        notes="Bolivia",
    ),
    "BRL": CodeListEntry(
        list_number=96,
        code="BRL",
        heading="Brazilian Real",
        notes="Brazil",
    ),
    "BSD": CodeListEntry(
        list_number=96,
        code="BSD",
        heading="Bahamian Dollar",
        notes="Bahamas",
    ),
    "BTN": CodeListEntry(
        list_number=96,
        code="BTN",
        heading="Ngultrun",
        notes="Bhutan",
    ),
    "BWP": CodeListEntry(
        list_number=96,
        code="BWP",
        heading="Pula",
        notes="Botswana",
    ),
    "BYR": CodeListEntry(
        list_number=96,
        code="BYR",
        heading="(Old) Belarussian Ruble",
        notes="Belarus (prices normally quoted as integers). Deprecated - now replaced by new Belarussian Ruble (BYN): use only for historical prices that pre-date the introduction of the new Belarussian Ruble",
        deprecated_version=44,
    ),
    "BYN": CodeListEntry(
        list_number=96,
        code="BYN",
        heading="Belarussian Ruble",
        notes="Belarus",
        added_version=32,
    ),
    "BZD": CodeListEntry(
        list_number=96,
        code="BZD",
        heading="Belize Dollar",
        notes="Belize",
    ),
    "CAD": CodeListEntry(
        list_number=96,
        code="CAD",
        heading="Canadian Dollar",
        notes="Canada",
    ),
    "CDF": CodeListEntry(
        list_number=96,
        code="CDF",
        heading="Franc Congolais",
        notes="Congo (Democratic Republic of the)",
    ),
    "CHF": CodeListEntry(
        list_number=96,
        code="CHF",
        heading="Swiss Franc",
        notes="Switzerland, Liechtenstein",
    ),
    "CLP": CodeListEntry(
        list_number=96,
        code="CLP",
        heading="Chilean Peso",
        notes="Chile (prices normally quoted as integers)",
    ),
    "CNY": CodeListEntry(
        list_number=96,
        code="CNY",
        heading="Yuan Renminbi",
        notes="China",
    ),
    "COP": CodeListEntry(
        list_number=96,
        code="COP",
        heading="Colombian Peso",
        notes="Colombia (prices normally quoted as integers)",
    ),
    "CRC": CodeListEntry(
        list_number=96,
        code="CRC",
        heading="Costa Rican Colon",
        notes="Costa Rica (prices normally quoted as integers)",
    ),
    "CSD": CodeListEntry(
        list_number=96,
        code="CSD",
        heading="Serbian Dinar",
        notes="Deprecated, replaced by RSD",
        added_version=4,
        deprecated_version=17,
    ),
    "CUC": CodeListEntry(
        list_number=96,
        code="CUC",
        heading="Cuban Convertible Peso",
        notes="Cuba (alternative currency from 1994, withdrawn 2021). Deprecated - use only for historical prices that pre-date withdrawal",
        added_version=4,
        deprecated_version=69,
    ),
    "CUP": CodeListEntry(
        list_number=96,
        code="CUP",
        heading="Cuban Peso",
        notes="Cuba",
    ),
    "CVE": CodeListEntry(
        list_number=96,
        code="CVE",
        heading="Cabo Verde Escudo",
        notes="Cabo Verde (prices normally quoted as integers)",
    ),
    "CYP": CodeListEntry(
        list_number=96,
        code="CYP",
        heading="Cyprus Pound",
        notes="Cyprus. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "CZK": CodeListEntry(
        list_number=96,
        code="CZK",
        heading="Czech Koruna",
        notes="Czechia",
    ),
    "DEM": CodeListEntry(
        list_number=96,
        code="DEM",
        heading="Mark",
        notes="Germany. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "DJF": CodeListEntry(
        list_number=96,
        code="DJF",
        heading="Djibouti Franc",
        notes="Djibouti (prices normally quoted as integers)",
    ),
    "DKK": CodeListEntry(
        list_number=96,
        code="DKK",
        heading="Danish Krone",
        notes="Denmark, Faroe Islands, Greenland",
    ),
    "DOP": CodeListEntry(
        list_number=96,
        code="DOP",
        heading="Dominican Peso",
        notes="Dominican Republic",
    ),
    "DZD": CodeListEntry(
        list_number=96,
        code="DZD",
        heading="Algerian Dinar",
        notes="Algeria",
    ),
    "EEK": CodeListEntry(
        list_number=96,
        code="EEK",
        heading="Kroon",
        notes="Estonia. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "EGP": CodeListEntry(
        list_number=96,
        code="EGP",
        heading="Egyptian Pound",
        notes="Egypt",
    ),
    "ERN": CodeListEntry(
        list_number=96,
        code="ERN",
        heading="Nakfa",
        notes="Eritrea",
    ),
    "ESP": CodeListEntry(
        list_number=96,
        code="ESP",
        heading="Peseta",
        notes="Spain. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro (prices normally quoted as integers)",
        deprecated_version=42,
    ),
    "ETB": CodeListEntry(
        list_number=96,
        code="ETB",
        heading="Ethiopian Birr",
        notes="Ethiopia",
    ),
    "EUR": CodeListEntry(
        list_number=96,
        code="EUR",
        heading="Euro",
        notes="Eurozone: Andorra, Austria, Belgium, Croatia, Cyprus, Estonia, Finland, France, Fr Guiana, Fr S Territories, Germany, Greece, Guadeloupe, Holy See (Vatican City), Ireland, Italy, Latvia, Lithuania, Luxembourg, Martinique, Malta, Mayotte, Monaco, Montenegro, Netherlands, Portugal, Réunion, St Barthelemy, St Martin, St Pierre and Miquelon, San Marino, Slovakia, Slovenia, Spain",
        added_version=5,
    ),
    "FIM": CodeListEntry(
        list_number=96,
        code="FIM",
        heading="Markka",
        notes="Finland. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "FJD": CodeListEntry(
        list_number=96,
        code="FJD",
        heading="Fiji Dollar",
        notes="Fiji",
    ),
    "FKP": CodeListEntry(
        list_number=96,
        code="FKP",
        heading="Falkland Islands Pound",
        notes="Falkland Islands (Malvinas)",
    ),
    "FRF": CodeListEntry(
        list_number=96,
        code="FRF",
        heading="Franc",
        notes="France. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "GBP": CodeListEntry(
        list_number=96,
        code="GBP",
        heading="Pound Sterling",
        notes="United Kingdom, Isle of Man, Channel Islands, South Georgia, South Sandwich Islands, British Indian Ocean Territory (de jure)",
    ),
    "GEL": CodeListEntry(
        list_number=96,
        code="GEL",
        heading="Lari",
        notes="Georgia",
    ),
    "GHC": CodeListEntry(
        list_number=96,
        code="GHC",
        heading="Ghana Cedi",
        notes="Deprecated, replaced by GHS",
        deprecated_version=17,
    ),
    "GHS": CodeListEntry(
        list_number=96,
        code="GHS",
        heading="Ghana Cedi",
        notes="Ghana",
        added_version=17,
    ),
    "GIP": CodeListEntry(
        list_number=96,
        code="GIP",
        heading="Gibraltar Pound",
        notes="Gibraltar",
    ),
    "GMD": CodeListEntry(
        list_number=96,
        code="GMD",
        heading="Dalasi",
        notes="Gambia",
    ),
    "GNF": CodeListEntry(
        list_number=96,
        code="GNF",
        heading="Guinean Franc",
        notes="Guinea (prices normally quoted as integers)",
    ),
    "GRD": CodeListEntry(
        list_number=96,
        code="GRD",
        heading="Drachma",
        notes="Greece. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "GTQ": CodeListEntry(
        list_number=96,
        code="GTQ",
        heading="Quetzal",
        notes="Guatemala",
    ),
    "GWP": CodeListEntry(
        list_number=96,
        code="GWP",
        heading="Guinea-Bissau Peso",
        notes="Now replaced by the CFA Franc BCEAO XOF use only for historical prices that pre-date use of the CFA Franc",
    ),
    "GYD": CodeListEntry(
        list_number=96,
        code="GYD",
        heading="Guyana Dollar",
        notes="Guyana (prices normally quoted as integers)",
    ),
    "HKD": CodeListEntry(
        list_number=96,
        code="HKD",
        heading="Hong Kong Dollar",
        notes="Hong Kong",
    ),
    "HNL": CodeListEntry(
        list_number=96,
        code="HNL",
        heading="Lempira",
        notes="Honduras",
    ),
    "HRK": CodeListEntry(
        list_number=96,
        code="HRK",
        heading="Kuna",
        notes="Croatia. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=60,
    ),
    "HTG": CodeListEntry(
        list_number=96,
        code="HTG",
        heading="Gourde",
        notes="Haiti",
    ),
    "HUF": CodeListEntry(
        list_number=96,
        code="HUF",
        heading="Forint",
        notes="Hungary (prices normally quoted as integers)",
    ),
    "IDR": CodeListEntry(
        list_number=96,
        code="IDR",
        heading="Rupiah",
        notes="Indonesia (prices normally quoted as integers)",
    ),
    "IEP": CodeListEntry(
        list_number=96,
        code="IEP",
        heading="Punt",
        notes="Ireland. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "ILS": CodeListEntry(
        list_number=96,
        code="ILS",
        heading="New Israeli Sheqel",
        notes="Israel",
    ),
    "INR": CodeListEntry(
        list_number=96,
        code="INR",
        heading="Indian Rupee",
        notes="India, Bhutan (prices normally quoted as integers)",
    ),
    "IQD": CodeListEntry(
        list_number=96,
        code="IQD",
        heading="Iraqi Dinar",
        notes="Iraq (prices normally quoted as integers)",
    ),
    "IRR": CodeListEntry(
        list_number=96,
        code="IRR",
        heading="Iranian Rial",
        notes="Iran (Islamic Republic of) (prices normally quoted as integers)",
    ),
    "ISK": CodeListEntry(
        list_number=96,
        code="ISK",
        heading="Iceland Krona",
        notes="Iceland (prices normally quoted as integers)",
    ),
    "ITL": CodeListEntry(
        list_number=96,
        code="ITL",
        heading="Lira",
        notes="Italy. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro (prices normally quoted as integers)",
        deprecated_version=42,
    ),
    "JMD": CodeListEntry(
        list_number=96,
        code="JMD",
        heading="Jamaican Dollar",
        notes="Jamaica",
    ),
    "JOD": CodeListEntry(
        list_number=96,
        code="JOD",
        heading="Jordanian Dinar",
        notes="Jordan (prices normally quoted with 3 decimal places)",
    ),
    "JPY": CodeListEntry(
        list_number=96,
        code="JPY",
        heading="Yen",
        notes="Japan (prices normally quoted as integers)",
    ),
    "KES": CodeListEntry(
        list_number=96,
        code="KES",
        heading="Kenyan Shilling",
        notes="Kenya",
    ),
    "KGS": CodeListEntry(
        list_number=96,
        code="KGS",
        heading="Som",
        notes="Kyrgyzstan",
    ),
    "KHR": CodeListEntry(
        list_number=96,
        code="KHR",
        heading="Riel",
        notes="Cambodia",
    ),
    "KMF": CodeListEntry(
        list_number=96,
        code="KMF",
        heading="Comorian Franc",
        notes="Comoros (prices normally quoted as integers)",
    ),
    "KPW": CodeListEntry(
        list_number=96,
        code="KPW",
        heading="North Korean Won",
        notes="Korea (Democratic People’s Republic of) (prices normally quoted as integers)",
    ),
    "KRW": CodeListEntry(
        list_number=96,
        code="KRW",
        heading="Won",
        notes="Korea (Republic of) (prices normally quoted as integers)",
    ),
    "KWD": CodeListEntry(
        list_number=96,
        code="KWD",
        heading="Kuwaiti Dinar",
        notes="Kuwait (prices normally quoted with 3 decimal places)",
    ),
    "KYD": CodeListEntry(
        list_number=96,
        code="KYD",
        heading="Cayman Islands Dollar",
        notes="Cayman Islands",
    ),
    "KZT": CodeListEntry(
        list_number=96,
        code="KZT",
        heading="Tenge",
        notes="Kazakhstan",
    ),
    "LAK": CodeListEntry(
        list_number=96,
        code="LAK",
        heading="Lao Kip",
        notes="Lao People’s Democratic Republic (prices normally quoted as integers)",
    ),
    "LBP": CodeListEntry(
        list_number=96,
        code="LBP",
        heading="Lebanese Pound",
        notes="Lebanon (prices normally quoted as integers)",
    ),
    "LKR": CodeListEntry(
        list_number=96,
        code="LKR",
        heading="Sri Lanka Rupee",
        notes="Sri Lanka",
    ),
    "LRD": CodeListEntry(
        list_number=96,
        code="LRD",
        heading="Liberian Dollar",
        notes="Liberia",
    ),
    "LSL": CodeListEntry(
        list_number=96,
        code="LSL",
        heading="Loti",
        notes="Lesotho",
    ),
    "LTL": CodeListEntry(
        list_number=96,
        code="LTL",
        heading="Litus",
        notes="Lithuania. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "LUF": CodeListEntry(
        list_number=96,
        code="LUF",
        heading="Luxembourg Franc",
        notes="Luxembourg. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro (prices normally quoted as integers)",
        deprecated_version=42,
    ),
    "LVL": CodeListEntry(
        list_number=96,
        code="LVL",
        heading="Latvian Lats",
        notes="Latvia. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "LYD": CodeListEntry(
        list_number=96,
        code="LYD",
        heading="Libyan Dinar",
        notes="Libyan Arab Jamahiriya (prices normally quoted with 3 decimal places)",
    ),
    "MAD": CodeListEntry(
        list_number=96,
        code="MAD",
        heading="Moroccan Dirham",
        notes="Morocco, Western Sahara",
    ),
    "MDL": CodeListEntry(
        list_number=96,
        code="MDL",
        heading="Moldovan Leu",
        notes="Moldova, Republic of",
    ),
    "MGA": CodeListEntry(
        list_number=96,
        code="MGA",
        heading="Malagasy Ariary",
        notes="Madagascar (prices normally quoted with 0 or 1 decimal place - 1 iraimbilanja = Ar0.2)",
        added_version=4,
    ),
    "MGF": CodeListEntry(
        list_number=96,
        code="MGF",
        heading="Malagasy Franc",
        notes="Now replaced by the Ariary (MGA) (prices normally quoted as integers)",
    ),
    "MKD": CodeListEntry(
        list_number=96,
        code="MKD",
        heading="Denar",
        notes="North Macedonia (formerly FYR Macedonia)",
    ),
    "MMK": CodeListEntry(
        list_number=96,
        code="MMK",
        heading="Kyat",
        notes="Myanmar (prices normally quoted as integers)",
    ),
    "MNT": CodeListEntry(
        list_number=96,
        code="MNT",
        heading="Tugrik",
        notes="Mongolia (prices normally quoted as integers)",
    ),
    "MOP": CodeListEntry(
        list_number=96,
        code="MOP",
        heading="Pataca",
        notes="Macau",
    ),
    "MRO": CodeListEntry(
        list_number=96,
        code="MRO",
        heading="(Old) Ouguiya",
        notes="Mauritania (prices normally quoted with 0 or 1 decimal place - 1 khoums = UM0.2). Was interchangeable with MRU (New) Ouguiya at rate of 10:1 until June 2018. Deprecated, use MRU instead",
        deprecated_version=42,
    ),
    "MRU": CodeListEntry(
        list_number=96,
        code="MRU",
        heading="Ouguiya",
        notes="Mauritania (prices normally quoted with 0 or 1 decimal place - 1 khoums = UM0.2). Replaced MRO (old) Ouguiya at rate of 10:1 in June 2018. Only for use in ONIX 3.0 or later",
        added_version=40,
    ),
    "MTL": CodeListEntry(
        list_number=96,
        code="MTL",
        heading="Maltese Lira",
        notes="Malta. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "MUR": CodeListEntry(
        list_number=96,
        code="MUR",
        heading="Mauritius Rupee",
        notes="Mauritius (prices normally quoted as integers)",
    ),
    "MVR": CodeListEntry(
        list_number=96,
        code="MVR",
        heading="Rufiyaa",
        notes="Maldives",
    ),
    "MWK": CodeListEntry(
        list_number=96,
        code="MWK",
        heading="Malawi Kwacha",
        notes="Malawi",
    ),
    "MXN": CodeListEntry(
        list_number=96,
        code="MXN",
        heading="Mexican Peso",
        notes="Mexico",
    ),
    "MYR": CodeListEntry(
        list_number=96,
        code="MYR",
        heading="Malaysian Ringgit",
        notes="Malaysia",
    ),
    "MZN": CodeListEntry(
        list_number=96,
        code="MZN",
        heading="Mozambique Metical",
        notes="Mozambique",
        added_version=7,
    ),
    "NAD": CodeListEntry(
        list_number=96,
        code="NAD",
        heading="Namibia Dollar",
        notes="Namibia",
    ),
    "NGN": CodeListEntry(
        list_number=96,
        code="NGN",
        heading="Naira",
        notes="Nigeria",
    ),
    "NIO": CodeListEntry(
        list_number=96,
        code="NIO",
        heading="Cordoba Oro",
        notes="Nicaragua",
    ),
    "NLG": CodeListEntry(
        list_number=96,
        code="NLG",
        heading="Guilder",
        notes="Netherlands. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "NOK": CodeListEntry(
        list_number=96,
        code="NOK",
        heading="Norwegian Krone",
        notes="Norway, Bouvet Island, Svalbard and Jan Mayen",
    ),
    "NPR": CodeListEntry(
        list_number=96,
        code="NPR",
        heading="Nepalese Rupee",
        notes="Nepal",
    ),
    "NZD": CodeListEntry(
        list_number=96,
        code="NZD",
        heading="New Zealand Dollar",
        notes="New Zealand, Cook Islands, Niue, Pitcairn, Tokelau",
    ),
    "OMR": CodeListEntry(
        list_number=96,
        code="OMR",
        heading="Rial Omani",
        notes="Oman (prices normally quoted with 3 decimal places)",
    ),
    "PAB": CodeListEntry(
        list_number=96,
        code="PAB",
        heading="Balboa",
        notes="Panama",
    ),
    "PEN": CodeListEntry(
        list_number=96,
        code="PEN",
        heading="Sol",
        notes="Peru (formerly Nuevo Sol)",
    ),
    "PGK": CodeListEntry(
        list_number=96,
        code="PGK",
        heading="Kina",
        notes="Papua New Guinea",
    ),
    "PHP": CodeListEntry(
        list_number=96,
        code="PHP",
        heading="Philippine Peso",
        notes="Philippines",
    ),
    "PKR": CodeListEntry(
        list_number=96,
        code="PKR",
        heading="Pakistan Rupee",
        notes="Pakistan (prices normally quoted as integers)",
    ),
    "PLN": CodeListEntry(
        list_number=96,
        code="PLN",
        heading="Złoty",
        notes="Poland",
    ),
    "PTE": CodeListEntry(
        list_number=96,
        code="PTE",
        heading="Escudo",
        notes="Portugal. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "PYG": CodeListEntry(
        list_number=96,
        code="PYG",
        heading="Guarani",
        notes="Paraguay (prices normally quoted as integers)",
    ),
    "QAR": CodeListEntry(
        list_number=96,
        code="QAR",
        heading="Qatari Rial",
        notes="Qatar",
    ),
    "ROL": CodeListEntry(
        list_number=96,
        code="ROL",
        heading="Romanian Old Leu",
        notes="Deprecated, replaced by RON",
        deprecated_version=17,
    ),
    "RON": CodeListEntry(
        list_number=96,
        code="RON",
        heading="Romanian Leu",
        notes="Romania",
        added_version=7,
    ),
    "RSD": CodeListEntry(
        list_number=96,
        code="RSD",
        heading="Serbian Dinar",
        notes="Serbia (prices normally quoted as integers)",
        added_version=17,
    ),
    "RUB": CodeListEntry(
        list_number=96,
        code="RUB",
        heading="Russian Ruble",
        notes="Russian Federation",
        added_version=4,
    ),
    "RUR": CodeListEntry(
        list_number=96,
        code="RUR",
        heading="Russian Ruble",
        notes="Deprecated, replaced by RUB",
        deprecated_version=4,
    ),
    "RWF": CodeListEntry(
        list_number=96,
        code="RWF",
        heading="Rwanda Franc",
        notes="Rwanda (prices normally quoted as integers)",
    ),
    "SAR": CodeListEntry(
        list_number=96,
        code="SAR",
        heading="Saudi Riyal",
        notes="Saudi Arabia",
    ),
    "SBD": CodeListEntry(
        list_number=96,
        code="SBD",
        heading="Solomon Islands Dollar",
        notes="Solomon Islands",
    ),
    "SCR": CodeListEntry(
        list_number=96,
        code="SCR",
        heading="Seychelles Rupee",
        notes="Seychelles",
    ),
    "SDD": CodeListEntry(
        list_number=96,
        code="SDD",
        heading="Sudanese Dinar",
        notes="Now replaced by the Sudanese Pound (SDG)",
    ),
    "SDG": CodeListEntry(
        list_number=96,
        code="SDG",
        heading="Sudanese Pound",
        notes="Sudan",
        added_version=17,
    ),
    "SEK": CodeListEntry(
        list_number=96,
        code="SEK",
        heading="Swedish Krona",
        notes="Sweden",
    ),
    "SGD": CodeListEntry(
        list_number=96,
        code="SGD",
        heading="Singapore Dollar",
        notes="Singapore",
    ),
    "SHP": CodeListEntry(
        list_number=96,
        code="SHP",
        heading="Saint Helena Pound",
        notes="Saint Helena",
    ),
    "SIT": CodeListEntry(
        list_number=96,
        code="SIT",
        heading="Tolar",
        notes="Slovenia. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "SKK": CodeListEntry(
        list_number=96,
        code="SKK",
        heading="Slovak Koruna",
        notes="Slovakia. Now replaced by the Euro (EUR). Deprecated - use only for historical prices that pre-date the introduction of the Euro",
        deprecated_version=42,
    ),
    "SLE": CodeListEntry(
        list_number=96,
        code="SLE",
        heading="Leone",
        notes="Sierra Leone (from April 2022). Only for use in ONIX 3.0 or later",
        added_version=57,
    ),
    "SLL": CodeListEntry(
        list_number=96,
        code="SLL",
        heading="Leone",
        notes="Sierra Leone (prices normally quoted as integers). Deprecated - gradually replaced by SLE from April 2022, but SLL Leone still usable until December 2023 (SLE is a redenomination of the Leone by a factor of 1,000)",
        deprecated_version=58,
    ),
    "SOS": CodeListEntry(
        list_number=96,
        code="SOS",
        heading="Somali Shilling",
        notes="Somalia (prices normally quoted as integers)",
    ),
    "SRD": CodeListEntry(
        list_number=96,
        code="SRD",
        heading="Surinam Dollar",
        notes="Suriname",
        added_version=4,
    ),
    "SRG": CodeListEntry(
        list_number=96,
        code="SRG",
        heading="Suriname Guilder",
        notes="DEPRECATED, replaced by SRD",
        deprecated_version=4,
    ),
    "STD": CodeListEntry(
        list_number=96,
        code="STD",
        heading="(Old) Dobra",
        notes="São Tome and Principe (prices normally quoted as integers). Was interchangeable with STN (New) Dobra at rate of 1000:1 until June 2018. Deprecated, use STN instead",
        deprecated_version=42,
    ),
    "STN": CodeListEntry(
        list_number=96,
        code="STN",
        heading="Dobra",
        notes="São Tome and Principe. Replaced STD (old) Dobra at rate of 1000:1 in June 2018. Only for use in ONIX 3.0 or later",
        added_version=39,
    ),
    "SVC": CodeListEntry(
        list_number=96,
        code="SVC",
        heading="El Salvador Colon",
        notes="El Salvador",
    ),
    "SYP": CodeListEntry(
        list_number=96,
        code="SYP",
        heading="Syrian Pound",
        notes="Syrian Arab Republic (prices normally quoted as integers)",
    ),
    "SZL": CodeListEntry(
        list_number=96,
        code="SZL",
        heading="Lilangeni",
        notes="Eswatini (formerly known as Swaziland)",
    ),
    "THB": CodeListEntry(
        list_number=96,
        code="THB",
        heading="Baht",
        notes="Thailand",
    ),
    "TJS": CodeListEntry(
        list_number=96,
        code="TJS",
        heading="Somoni",
        notes="Tajikistan",
    ),
    "TMM": CodeListEntry(
        list_number=96,
        code="TMM",
        heading="Turkmenistan Manat",
        notes="Deprecated, replaced by TMT (prices normally quoted as integers)",
        deprecated_version=17,
    ),
    "TMT": CodeListEntry(
        list_number=96,
        code="TMT",
        heading="Turkmenistan New Manat",
        notes="Turkmenistan",
        added_version=17,
    ),
    "TND": CodeListEntry(
        list_number=96,
        code="TND",
        heading="Tunisian Dinar",
        notes="Tunisia (prices normally quoted with 3 decimal places)",
    ),
    "TOP": CodeListEntry(
        list_number=96,
        code="TOP",
        heading="Pa’anga",
        notes="Tonga",
    ),
    "TPE": CodeListEntry(
        list_number=96,
        code="TPE",
        heading="Timor Escudo",
        notes="Deprecated. Timor-Leste now uses the US Dollar",
        deprecated_version=7,
    ),
    "TRL": CodeListEntry(
        list_number=96,
        code="TRL",
        heading="Turkish Lira (old)",
        notes="Deprecated, replaced by TRY (prices normally quoted as integers)",
        deprecated_version=17,
    ),
    "TRY": CodeListEntry(
        list_number=96,
        code="TRY",
        heading="Turkish Lira",
        notes="Türkiye, from 1 January 2005",
        added_version=4,
    ),
    "TTD": CodeListEntry(
        list_number=96,
        code="TTD",
        heading="Trinidad and Tobago Dollar",
        notes="Trinidad and Tobago",
    ),
    "TWD": CodeListEntry(
        list_number=96,
        code="TWD",
        heading="New Taiwan Dollar",
        notes="Taiwan (Province of China)",
    ),
    "TZS": CodeListEntry(
        list_number=96,
        code="TZS",
        heading="Tanzanian Shilling",
        notes="Tanzania (United Republic of) (prices normally quoted as integers)",
    ),
    "UAH": CodeListEntry(
        list_number=96,
        code="UAH",
        heading="Hryvnia",
        notes="Ukraine",
    ),
    "UGX": CodeListEntry(
        list_number=96,
        code="UGX",
        heading="Uganda Shilling",
        notes="Uganda (prices normally quoted as integers)",
    ),
    "USD": CodeListEntry(
        list_number=96,
        code="USD",
        heading="US Dollar",
        notes="United States, American Samoa, Bonaire, Sint Eustatius and Saba, British Indian Ocean Territory, Ecuador, El Salvador, Guam, Haiti, Marshall Is, Micronesia (Federated States of), Northern Mariana Is, Palau, Panama, Puerto Rico, Timor-Leste, Turks and Caicos Is, US Minor Outlying Is, Virgin Is (British), Virgin Is (US)",
    ),
    "UYU": CodeListEntry(
        list_number=96,
        code="UYU",
        heading="Peso Uruguayo",
        notes="Uruguay",
    ),
    "UZS": CodeListEntry(
        list_number=96,
        code="UZS",
        heading="Uzbekistan Sum",
        notes="Uzbekistan (prices normally quoted as integers)",
    ),
    "VEB": CodeListEntry(
        list_number=96,
        code="VEB",
        heading="Bolívar",
        notes="Deprecated, replaced by VEF",
        deprecated_version=17,
    ),
    "VEF": CodeListEntry(
        list_number=96,
        code="VEF",
        heading="Bolívar",
        notes="Venezuela (formerly Bolívar fuerte). Deprecated, replaced by VES",
        added_version=17,
        deprecated_version=43,
    ),
    "VES": CodeListEntry(
        list_number=96,
        code="VES",
        heading="Bolívar Soberano",
        notes="Venezuela (replaced VEF from August 2018 at rate of 100,000:1, and was redenominated by a further factor of 1,000,000:1 in late 2021). Only for use in ONIX 3.0 or later",
        added_version=42,
    ),
    "VND": CodeListEntry(
        list_number=96,
        code="VND",
        heading="Dong",
        notes="Viet Nam (prices normally quoted as integers)",
    ),
    "VUV": CodeListEntry(
        list_number=96,
        code="VUV",
        heading="Vatu",
        notes="Vanuatu (prices normally quoted as integers)",
    ),
    "WST": CodeListEntry(
        list_number=96,
        code="WST",
        heading="Tala",
        notes="Samoa",
    ),
    "XAF": CodeListEntry(
        list_number=96,
        code="XAF",
        heading="CFA Franc BEAC",
        notes="Cameroon, Central African Republic, Chad, Congo, Equatorial Guinea, Gabon (prices normally quoted as integers)",
    ),
    "XCD": CodeListEntry(
        list_number=96,
        code="XCD",
        heading="East Caribbean Dollar",
        notes="Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines",
    ),
    "XCG": CodeListEntry(
        list_number=96,
        code="XCG",
        heading="Caribbean Guilder",
        notes="Curaçao, Sint Maarten. Only for use in ONIX 3.0",
        added_version=69,
    ),
    "XOF": CodeListEntry(
        list_number=96,
        code="XOF",
        heading="CFA Franc BCEAO",
        notes="Benin, Burkina Faso, Côte D’Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo (prices normally quoted as integers)",
    ),
    "XPF": CodeListEntry(
        list_number=96,
        code="XPF",
        heading="CFP Franc",
        notes="French Polynesia, New Caledonia, Wallis and Futuna (prices normally quoted as integers)",
    ),
    "YER": CodeListEntry(
        list_number=96,
        code="YER",
        heading="Yemeni Rial",
        notes="Yemen (prices normally quoted as integers)",
    ),
    "YUM": CodeListEntry(
        list_number=96,
        code="YUM",
        heading="Yugoslavian Dinar",
        notes="Deprecated, replaced by CSD",
        deprecated_version=4,
    ),
    "ZAR": CodeListEntry(
        list_number=96,
        code="ZAR",
        heading="Rand",
        notes="South Africa, Namibia, Lesotho",
    ),
    "ZMK": CodeListEntry(
        list_number=96,
        code="ZMK",
        heading="Kwacha",
        notes="Zambia. Deprecated, replaced with ZMW (prices normally quoted as integers)",
        deprecated_version=27,
    ),
    "ZMW": CodeListEntry(
        list_number=96,
        code="ZMW",
        heading="Zambian Kwacha",
        notes="Zambia",
        added_version=23,
    ),
    "ZWD": CodeListEntry(
        list_number=96,
        code="ZWD",
        heading="Zimbabwe Dollar",
        notes="Deprecated, replaced with ZWL (prices normally quoted as integers)",
        deprecated_version=17,
    ),
    "ZWG": CodeListEntry(
        list_number=96,
        code="ZWG",
        heading="Zimbabwe Gold",
        notes="Zimbabwe. Also known as ZiG. Only for use in ONIX 3.0 or later",
        added_version=66,
    ),
    "ZWL": CodeListEntry(
        list_number=96,
        code="ZWL",
        heading="Zimbabwe Dollar",
        notes="Deprecated, replaced by ZWG",
        added_version=17,
        deprecated_version=66,
    ),
}

List96 = CodeList(
    number=96,
    heading="Currency code - based on ISO 4217",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
CurrencyCode = List96
