"""ONIX Code List 175: Product form detail."""

from onix.lists.models import CodeList, CodeListEntry

_ENTRIES = {
    "A101": CodeListEntry(
        list_number=175,
        code="A101",
        heading="CD standard audio format",
        notes="CD ‘red book’ format",
        added_version=2,
    ),
    "A102": CodeListEntry(
        list_number=175,
        code="A102",
        heading="SACD super audio format",
        added_version=2,
    ),
    "A103": CodeListEntry(
        list_number=175,
        code="A103",
        heading="MP3 format",
        notes="MPEG-1/2 Audio Layer III file",
        added_version=2,
    ),
    "A104": CodeListEntry(
        list_number=175,
        code="A104",
        heading="WAV format",
        added_version=2,
    ),
    "A105": CodeListEntry(
        list_number=175,
        code="A105",
        heading="Real Audio format",
        added_version=2,
    ),
    "A106": CodeListEntry(
        list_number=175,
        code="A106",
        heading="WMA",
        notes="Windows Media Audio format",
        added_version=9,
    ),
    "A107": CodeListEntry(
        list_number=175,
        code="A107",
        heading="AAC",
        notes="Advanced Audio Coding format",
        added_version=9,
    ),
    "A108": CodeListEntry(
        list_number=175,
        code="A108",
        heading="Ogg/Vorbis",
        notes="Vorbis audio format in the Ogg container",
        added_version=9,
    ),
    "A109": CodeListEntry(
        list_number=175,
        code="A109",
        heading="Audible",
        notes="Audio format proprietary to Audible.com",
        added_version=9,
    ),
    "A110": CodeListEntry(
        list_number=175,
        code="A110",
        heading="FLAC",
        notes="Free lossless audio codec",
        added_version=9,
    ),
    "A111": CodeListEntry(
        list_number=175,
        code="A111",
        heading="AIFF",
        notes="Audio Interchangeable File Format",
        added_version=9,
    ),
    "A112": CodeListEntry(
        list_number=175,
        code="A112",
        heading="ALAC",
        notes="Apple Lossless Audio Codec",
        added_version=9,
    ),
    "A113": CodeListEntry(
        list_number=175,
        code="A113",
        heading="W3C Audiobook format",
        notes="Audiobook package format",
        added_version=51,
    ),
    "A201": CodeListEntry(
        list_number=175,
        code="A201",
        heading="DAISY 2: full audio with title only (no navigation)",
        notes="Deprecated, as does not meet DAISY 2 standard. Use conventional audiobook codes instead",
        added_version=8,
        deprecated_version=13,
    ),
    "A202": CodeListEntry(
        list_number=175,
        code="A202",
        heading="DAISY 2: full audio with navigation (no text)",
        added_version=8,
    ),
    "A203": CodeListEntry(
        list_number=175,
        code="A203",
        heading="DAISY 2: full audio with navigation and partial text",
        added_version=8,
    ),
    "A204": CodeListEntry(
        list_number=175,
        code="A204",
        heading="DAISY 2: full audio with navigation and full text",
        added_version=8,
    ),
    "A205": CodeListEntry(
        list_number=175,
        code="A205",
        heading="DAISY 2: full text with navigation and partial audio",
        notes="Reading systems may provide full audio via text-to-speech",
        added_version=8,
    ),
    "A206": CodeListEntry(
        list_number=175,
        code="A206",
        heading="DAISY 2: full text with navigation and no audio",
        notes="Reading systems may provide full audio via text-to-speech",
        added_version=8,
    ),
    "A207": CodeListEntry(
        list_number=175,
        code="A207",
        heading="DAISY 3: full audio with title only (no navigation)",
        notes="Deprecated, as does not meet DAISY 3 standard. Use conventional audiobook codes instead",
        added_version=8,
        deprecated_version=13,
    ),
    "A208": CodeListEntry(
        list_number=175,
        code="A208",
        heading="DAISY 3: full audio with navigation (no text)",
        added_version=8,
    ),
    "A209": CodeListEntry(
        list_number=175,
        code="A209",
        heading="DAISY 3: full audio with navigation and partial text",
        added_version=8,
    ),
    "A210": CodeListEntry(
        list_number=175,
        code="A210",
        heading="DAISY 3: full audio with navigation and full text",
        added_version=8,
    ),
    "A211": CodeListEntry(
        list_number=175,
        code="A211",
        heading="DAISY 3: full text with navigation and partial audio",
        notes="Reading systems may provide full audio via text-to-speech",
        added_version=8,
    ),
    "A212": CodeListEntry(
        list_number=175,
        code="A212",
        heading="DAISY 3: full text with navigation and no audio",
        notes="Reading systems may provide full audio via text-to-speech",
        added_version=8,
    ),
    "A301": CodeListEntry(
        list_number=175,
        code="A301",
        heading="Standalone audio",
        added_version=15,
    ),
    "A302": CodeListEntry(
        list_number=175,
        code="A302",
        heading="Readalong audio",
        notes="Audio intended exclusively for use alongside a printed copy of the book. Most often a children’s product. Normally contains instructions such as ‘turn the page now’ and other references to the printed item, and is usually sold packaged together with a printed copy",
        added_version=15,
    ),
    "A303": CodeListEntry(
        list_number=175,
        code="A303",
        heading="Playalong audio",
        notes="Audio intended for musical accompaniment, eg ‘Music minus one’, etc, often used for music learning. Includes singalong backing audio for musical learning or for Karaoke-style entertainment",
        added_version=15,
    ),
    "A304": CodeListEntry(
        list_number=175,
        code="A304",
        heading="Speakalong audio",
        notes="Audio intended for language learning, which includes speech plus gaps intended to be filled by the listener",
        added_version=15,
    ),
    "A305": CodeListEntry(
        list_number=175,
        code="A305",
        heading="Synchronized audio",
        notes="Audio synchronized to text within an e-publication, for example an EPUB3 with audio overlay. Synchronization at least at paragraph level, and covering the full content",
        added_version=26,
    ),
    "A310": CodeListEntry(
        list_number=175,
        code="A310",
        heading="Sound effects",
        notes="Incidental sounds added to the audiobook narration (eg background environmental sounds)",
        added_version=47,
    ),
    "A311": CodeListEntry(
        list_number=175,
        code="A311",
        heading="Background music",
        notes="Incidental music added to the audiobook narration (eg to heighten atmosphere). Do not use where the music is a primary part of the audio",
        added_version=47,
    ),
    "A312": CodeListEntry(
        list_number=175,
        code="A312",
        heading="Without background sounds",
        notes="Pre-recorded audiobook narration does not contain any background sounds, including music, sound effects, etc, though music and effects may be present if isolated from the speech (ie the sounds do not overlap)",
        added_version=62,
    ),
    "A400": CodeListEntry(
        list_number=175,
        code="A400",
        heading="64kbits/s",
        notes="Constant or average bit rate (eg of an mp3 or AAC audio file) 64kbits/second or more. Note the bit rate is the total across all channels, not a per channel rate",
        added_version=54,
    ),
    "A401": CodeListEntry(
        list_number=175,
        code="A401",
        heading="128kbits/s",
        notes="Constant or average bit rate 128bbits/second or more",
        added_version=54,
    ),
    "A402": CodeListEntry(
        list_number=175,
        code="A402",
        heading="192kbits/s",
        added_version=54,
    ),
    "A403": CodeListEntry(
        list_number=175,
        code="A403",
        heading="256kbits/s",
        added_version=54,
    ),
    "A404": CodeListEntry(
        list_number=175,
        code="A404",
        heading="320kbits/s",
        added_version=54,
    ),
    "A410": CodeListEntry(
        list_number=175,
        code="A410",
        heading="Mono",
        notes="Includes ‘stereo’ where channels are identical",
        added_version=29,
    ),
    "A420": CodeListEntry(
        list_number=175,
        code="A420",
        heading="Stereo",
        notes="Includes ‘joint stereo’",
        added_version=29,
    ),
    "A421": CodeListEntry(
        list_number=175,
        code="A421",
        heading="Stereo 2.1",
        notes="Stereo plus low-frequency channel",
        added_version=29,
    ),
    "A441": CodeListEntry(
        list_number=175,
        code="A441",
        heading="Surround 4.1",
        notes="Five-channel audio (including low-frequency channel)",
        added_version=29,
    ),
    "A451": CodeListEntry(
        list_number=175,
        code="A451",
        heading="Surround 5.1",
        notes="Six-channel audio (including low-frequency channel)",
        added_version=29,
    ),
    "A471": CodeListEntry(
        list_number=175,
        code="A471",
        heading="Dolby Atmos",
        notes="Multi-channel ‘spatial’ audio (eg for 7.1.4 speaker arrangements or processed for headphone delivery)",
        added_version=62,
    ),
    "B101": CodeListEntry(
        list_number=175,
        code="B101",
        heading="Mass market (rack) paperback",
        notes="In North America, a category of paperback characterized partly by page size (typically from 6¾ up to 7⅛ x 4¼ inches) and partly by target market and terms of trade. Use with Product Form code BC",
        added_version=2,
    ),
    "B102": CodeListEntry(
        list_number=175,
        code="B102",
        heading="Trade paperback (US)",
        notes="In North America, a category of paperback characterized partly by page size (larger than rack-sized) and partly by target market and terms of trade. AKA ‘quality paperback’, and including textbooks. Most paperback books sold in North America except ‘mass-market’ (B101) and ‘tall rack’ (B107) are correctly described with this code. Use with Product Form code BC",
        added_version=2,
    ),
    "B103": CodeListEntry(
        list_number=175,
        code="B103",
        heading="Digest format paperback",
        notes="In North America, a category of paperback characterized by page size (typically 7 x 5 inches) and generally used for children’s books; use with Product Form code BC. Note: was wrongly shown as B102 (duplicate entry) in Issue 3",
        added_version=4,
    ),
    "B104": CodeListEntry(
        list_number=175,
        code="B104",
        heading="A-format paperback",
        notes="In UK and IE, a category of paperback characterized by page size (normally 178 x 111 mm approx); use with Product Form code BC",
        added_version=2,
    ),
    "B105": CodeListEntry(
        list_number=175,
        code="B105",
        heading="B-format paperback",
        notes="In UK and IE, a category of paperback characterized by page size (normally 198 x 129 mm approx); use with Product Form code BC",
        added_version=2,
    ),
    "B106": CodeListEntry(
        list_number=175,
        code="B106",
        heading="Trade paperback (UK)",
        notes="In UK and IE, a category of paperback characterized largely by size (usually in traditional hardback dimensions), and often used for paperback originals or retailer/travel/export-exclusives; use with Product Form code BC",
        added_version=2,
    ),
    "B107": CodeListEntry(
        list_number=175,
        code="B107",
        heading="Tall rack paperback (US)",
        notes="In North America, a category of paperback characterized partly by page size (typically 7½ x 4¼ inches) and partly by target market and terms of trade; use with Product Form code BC",
        added_version=4,
    ),
    "B108": CodeListEntry(
        list_number=175,
        code="B108",
        heading="A5 size Tankobon",
        notes="Japanese A-series size, 210 x 148mm. A tankobon is a complete collected story originally published in serialized form (eg in a magazine)",
        added_version=5,
    ),
    "B109": CodeListEntry(
        list_number=175,
        code="B109",
        heading="JIS B5 size Tankobon",
        notes="Japanese B-series size, 257 x 182mm",
        added_version=5,
    ),
    "B110": CodeListEntry(
        list_number=175,
        code="B110",
        heading="JIS B6 size Tankobon",
        notes="Japanese B-series size, 182 x 128mm",
        added_version=5,
    ),
    "B111": CodeListEntry(
        list_number=175,
        code="B111",
        heading="A6 size Bunko",
        notes="Japanese A-series size, 148 x 105mm",
        added_version=5,
    ),
    "B112": CodeListEntry(
        list_number=175,
        code="B112",
        heading="B40-dori Shinsho",
        notes="Japanese format, 182x103mm or 173x105mm",
        added_version=5,
    ),
    "B113": CodeListEntry(
        list_number=175,
        code="B113",
        heading="Pocket (Sweden, Norway, France)",
        notes="A Swedish, Norwegian, French paperback format, of no particular fixed size. Use with Product Form Code BC",
        added_version=7,
    ),
    "B114": CodeListEntry(
        list_number=175,
        code="B114",
        heading="Storpocket (Sweden)",
        notes="A Swedish paperback format, use with Product Form Code BC. In Finnish, Jättipokkari",
        added_version=7,
    ),
    "B115": CodeListEntry(
        list_number=175,
        code="B115",
        heading="Kartonnage (Sweden)",
        notes="A Swedish hardback format, use with Product Form Code BB",
        added_version=7,
    ),
    "B116": CodeListEntry(
        list_number=175,
        code="B116",
        heading="Flexband (Sweden)",
        notes="A Swedish softback format, use with Product Form Code BC",
        added_version=7,
    ),
    "B117": CodeListEntry(
        list_number=175,
        code="B117",
        heading="Mook / Bookazine",
        notes="A softback book in the format of a magazine, usually sold like a book. Use with Product Form code BC",
        added_version=11,
    ),
    "B118": CodeListEntry(
        list_number=175,
        code="B118",
        heading="Dwarsligger",
        notes="Also called ‘Flipback’. A softback book in a specially compact proprietary format with pages printed in landscape on very thin paper and bound along the long (top) edge (ie parallel with the lines of text). Use with Product Form code BC - see www.dwarsligger.com",
        added_version=11,
    ),
    "B119": CodeListEntry(
        list_number=175,
        code="B119",
        heading="46 size",
        notes="Japanese format, 188 x 127mm",
        added_version=12,
    ),
    "B120": CodeListEntry(
        list_number=175,
        code="B120",
        heading="46-Henkei size",
        notes="Japanese format, approximately 188 x 127mm",
        added_version=12,
    ),
    "B121": CodeListEntry(
        list_number=175,
        code="B121",
        heading="A4",
        notes="297 x 210mm",
        added_version=12,
    ),
    "B122": CodeListEntry(
        list_number=175,
        code="B122",
        heading="A4-Henkei size",
        notes="Japanese format, approximately 297 x 210mm",
        added_version=12,
    ),
    "B123": CodeListEntry(
        list_number=175,
        code="B123",
        heading="A5-Henkei size",
        notes="Japanese format, approximately 210 x 146mm",
        added_version=12,
    ),
    "B124": CodeListEntry(
        list_number=175,
        code="B124",
        heading="B5-Henkei size",
        notes="Japanese format, approximately 257 x 182mm",
        added_version=12,
    ),
    "B125": CodeListEntry(
        list_number=175,
        code="B125",
        heading="B6-Henkei size",
        notes="Japanese format, approximately 182 x 128mm",
        added_version=12,
    ),
    "B126": CodeListEntry(
        list_number=175,
        code="B126",
        heading="AB size",
        notes="257 x 210mm",
        added_version=12,
    ),
    "B127": CodeListEntry(
        list_number=175,
        code="B127",
        heading="JIS B7 size",
        notes="Japanese B-series size, 128 x 91mm",
        added_version=12,
    ),
    "B128": CodeListEntry(
        list_number=175,
        code="B128",
        heading="Kiku size",
        notes="Japanese format, 218 x 152mm or 227 x 152mm",
        added_version=12,
    ),
    "B129": CodeListEntry(
        list_number=175,
        code="B129",
        heading="Kiku-Henkei size",
        notes="Japanese format",
        added_version=12,
    ),
    "B130": CodeListEntry(
        list_number=175,
        code="B130",
        heading="JIS B4 size",
        notes="Japanese B-series size, 364 x 257 mm",
        added_version=17,
    ),
    "B131": CodeListEntry(
        list_number=175,
        code="B131",
        heading="Paperback (DE)",
        notes="German large paperback format, greater than about 205mm high, with flaps. Use with Product form code BC",
        added_version=24,
    ),
    "B132": CodeListEntry(
        list_number=175,
        code="B132",
        heading="Libro de bolsillo",
        notes="Spanish pocket paperback. Use with Product form code BC",
        added_version=36,
    ),
    "B133": CodeListEntry(
        list_number=175,
        code="B133",
        heading="Pocket-sized",
        notes="Pocket-sized format, usually less than about 205mm high, without necessarily implying a particular trade category (de: ,Taschenbuch‘; it: «Tascabile / Supertascabile»; es: «libro de bolsillo»; fr: « livre de poche » etc). Use with Product form code BB or BC. See also List 12 code 04",
        added_version=38,
    ),
    "B134": CodeListEntry(
        list_number=175,
        code="B134",
        heading="A5",
        notes="210 x 148mm",
        added_version=39,
    ),
    "B135": CodeListEntry(
        list_number=175,
        code="B135",
        heading="Mass market max paperback",
        notes="In North America, a category of paperback characterized partly by page size (typically 7⅛ x 4¾ inches) and partly by target market and terms of trade. Use with Product Form code BC",
        added_version=50,
    ),
    "B139": CodeListEntry(
        list_number=175,
        code="B139",
        heading="Comic book size (US)",
        notes="Standard 10.25 x 6.625in size approx (260 x 170mm)",
        added_version=63,
    ),
    "B140": CodeListEntry(
        list_number=175,
        code="B140",
        heading="Comic album size (Euro)",
        notes="Standard 240 x 320mm size approx",
        added_version=63,
    ),
    "B141": CodeListEntry(
        list_number=175,
        code="B141",
        heading="B4-Henkei size",
        notes="Japanese format, approximately 364 x 257 mm",
        added_version=64,
    ),
    "B201": CodeListEntry(
        list_number=175,
        code="B201",
        heading="Coloring / join-the-dot book",
        added_version=2,
    ),
    "B202": CodeListEntry(
        list_number=175,
        code="B202",
        heading="Lift-the-flap book",
        added_version=2,
    ),
    "B204": CodeListEntry(
        list_number=175,
        code="B204",
        heading="Miniature book",
        added_version=4,
    ),
    "B205": CodeListEntry(
        list_number=175,
        code="B205",
        heading="Moving picture / flicker book",
        added_version=2,
    ),
    "B206": CodeListEntry(
        list_number=175,
        code="B206",
        heading="Pop-up book",
        added_version=2,
    ),
    "B207": CodeListEntry(
        list_number=175,
        code="B207",
        heading="Scented / ‘smelly’ book",
        added_version=2,
    ),
    "B208": CodeListEntry(
        list_number=175,
        code="B208",
        heading="Sound story / ‘noisy’ book",
        added_version=2,
    ),
    "B209": CodeListEntry(
        list_number=175,
        code="B209",
        heading="Sticker book",
        added_version=2,
    ),
    "B210": CodeListEntry(
        list_number=175,
        code="B210",
        heading="Touch-and-feel book",
        notes="Sensory book. A book whose pages have a variety of textured inserts designed to stimulate tactile exploration: see also B214 and B215",
        added_version=10,
    ),
    "B212": CodeListEntry(
        list_number=175,
        code="B212",
        heading="Die-cut book",
        notes="A book which is cut into a distinctive non-rectilinear shape and/or in which holes or shapes have been cut internally. (‘Die-cut’ is used here as a convenient shorthand, and does not imply strict limitation to a particular production process)",
        added_version=10,
    ),
    "B213": CodeListEntry(
        list_number=175,
        code="B213",
        heading="Book-as-toy",
        notes="A book which is also a toy, or which incorporates a toy as an integral part. (Do not, however, use B213 for a multiple-item product which includes a book and a toy as separate items)",
        added_version=10,
    ),
    "B214": CodeListEntry(
        list_number=175,
        code="B214",
        heading="Soft-to-touch book",
        notes="A book whose cover has a soft textured finish, typically over board",
        added_version=10,
    ),
    "B215": CodeListEntry(
        list_number=175,
        code="B215",
        heading="Fuzzy-felt book",
        notes="A book with detachable felt pieces and textured pages on which they can be arranged",
        added_version=10,
    ),
    "B216": CodeListEntry(
        list_number=175,
        code="B216",
        heading="Press-out pieces",
        notes="A book containing pages with die-cut or press-out pieces that can be used as a jigsaw, as puzzle or game pieces, play pieces (eg paper dolls) etc",
        added_version=38,
    ),
    "B221": CodeListEntry(
        list_number=175,
        code="B221",
        heading="Picture book",
        notes="Picture book, generally for children though also occasionally for teens or adults, with few words per illustration: use with applicable Product form code",
        added_version=2,
    ),
    "B222": CodeListEntry(
        list_number=175,
        code="B222",
        heading="‘Carousel’ book",
        notes="(aka ‘Star’ book). Tax treatment of products may differ from that of products with similar codes such as Book as toy or Pop-up book)",
        added_version=12,
    ),
    "B223": CodeListEntry(
        list_number=175,
        code="B223",
        heading="Pull-the-tab book",
        notes="A book with movable card ‘tabs’ within the pages. Pull a tab to reveal or animate part of a picture (distinct from a ‘lift-the-flap’ book, where flaps simply reveal hidden pictures, and not specifically a ‘pop-up’ book with 3D paper engineering - though when combined with code B206 indicates a pop-up book with tabs for moveable parts of 3D ‘scenes’)",
        added_version=35,
    ),
    "B224": CodeListEntry(
        list_number=175,
        code="B224",
        heading="‘Wordless’ book",
        notes="Picture book, generally for children though also used in augmentative and alternative education, or for teens and adults, without text in the body of the book. Also ‘silent books’, wordless graphic novels and comic books: use with applicable Product Form code",
        added_version=62,
    ),
    "B225": CodeListEntry(
        list_number=175,
        code="B225",
        heading="Cut-out pieces",
        notes="A book containing pages with pieces intended to be cut out (not pre-cut or press-out - see B216) that can be used as puzzle or game pieces, play pieces etc, but which may not be suitable for young children",
        added_version=67,
    ),
    "B301": CodeListEntry(
        list_number=175,
        code="B301",
        heading="Loose leaf or partwork - sheets / parts and binder / wallet",
        notes="Use with Product Form code BD, BN or PM",
        added_version=2,
    ),
    "B302": CodeListEntry(
        list_number=175,
        code="B302",
        heading="Loose leaf or partwork - binder / wallet only",
        notes="Use with Product Form code BD, BN or PM",
        added_version=2,
    ),
    "B303": CodeListEntry(
        list_number=175,
        code="B303",
        heading="Loose leaf or partwork - sheets / parts only",
        notes="Use with Product Form code BD, BN or PM",
        added_version=2,
    ),
    "B304": CodeListEntry(
        list_number=175,
        code="B304",
        heading="Sewn",
        notes="AKA stitched; for ‘saddle-sewn’, prefer code B310",
        added_version=2,
    ),
    "B305": CodeListEntry(
        list_number=175,
        code="B305",
        heading="Unsewn / adhesive bound",
        notes="Including ‘perfect bound’, ‘glued’",
        added_version=3,
    ),
    "B306": CodeListEntry(
        list_number=175,
        code="B306",
        heading="Library binding",
        notes="Strengthened cloth-over-boards binding intended for libraries: use with Product form code BB",
        added_version=2,
    ),
    "B307": CodeListEntry(
        list_number=175,
        code="B307",
        heading="Reinforced binding",
        notes="Strengthened binding, not specifically intended for libraries: use with Product form code BB or BC",
        added_version=2,
    ),
    "B308": CodeListEntry(
        list_number=175,
        code="B308",
        heading="Half bound",
        notes="Highest quality material used on spine and corners only. Must be accompanied by a code specifying a material, eg ‘half-bound real leather’",
        added_version=2,
    ),
    "B309": CodeListEntry(
        list_number=175,
        code="B309",
        heading="Quarter bound",
        notes="Highest quality material used on spine only. Must be accompanied by a code specifying a material, eg ‘quarter bound real leather’",
        added_version=2,
    ),
    "B310": CodeListEntry(
        list_number=175,
        code="B310",
        heading="Saddle-sewn",
        notes="AKA ‘saddle-stitched’ or ‘wire-stitched’",
        added_version=3,
    ),
    "B311": CodeListEntry(
        list_number=175,
        code="B311",
        heading="Comb bound",
        notes="Round or oval plastic forms in a clamp-like configuration: use with Product Form code BE",
        added_version=6,
    ),
    "B312": CodeListEntry(
        list_number=175,
        code="B312",
        heading="Wire-O",
        notes="Twin loop metal wire spine: use with Product Form code BE",
        added_version=6,
    ),
    "B313": CodeListEntry(
        list_number=175,
        code="B313",
        heading="Concealed wire",
        notes="Cased over Coiled or Wire-O binding: use with Product Form code BE and Product Form Detail code B312 or B314",
        added_version=6,
    ),
    "B314": CodeListEntry(
        list_number=175,
        code="B314",
        heading="Coiled wire bound",
        notes="Spiral wire bound. Use with product form code BE. The default if a spiral binding type is not stated. Cf. Comb and Wire-O binding",
        added_version=28,
    ),
    "B315": CodeListEntry(
        list_number=175,
        code="B315",
        heading="Trade binding",
        notes="Hardcover binding intended for general consumers rather than libraries, use with Product form code BB. The default if a hardcover binding detail is not stated. cf. Library binding",
        added_version=28,
    ),
    "B316": CodeListEntry(
        list_number=175,
        code="B316",
        heading="Swiss binding",
        notes="Cover is attached to the book block along only one edge of the spine, allowing the cover to lay flat",
        added_version=34,
    ),
    "B317": CodeListEntry(
        list_number=175,
        code="B317",
        heading="Notched binding",
        notes="Refinement of perfect binding, with notches cut in the spine of the book block prior to glueing, to improve adhesion and durability",
        added_version=34,
    ),
    "B318": CodeListEntry(
        list_number=175,
        code="B318",
        heading="Lay-flat binding",
        notes="Hardcover or softcover where interior spreads lay flat across the spine",
        added_version=57,
    ),
    "B319": CodeListEntry(
        list_number=175,
        code="B319",
        heading="Flush cut binding",
        notes="Hardcover where the cover boards are trimmed flush with the trimmed book block",
        added_version=68,
    ),
    "B320": CodeListEntry(
        list_number=175,
        code="B320",
        heading="Rounded spine",
        notes="Hardcover where the spine is rounded during binding",
        added_version=69,
    ),
    "B321": CodeListEntry(
        list_number=175,
        code="B321",
        heading="Square spine",
        notes="Hardcover where the spine is straight",
        added_version=69,
    ),
    "B400": CodeListEntry(
        list_number=175,
        code="B400",
        heading="Self-covered",
        notes="Covers do not use a distinctive stock, but are the same as the body pages. Use for example with Product form BF, to indicate a pamphlet does not use a card or distinct paper cover. See also B416 (for card covers) and B418 (for distinct paper covers)",
        added_version=29,
    ),
    "B401": CodeListEntry(
        list_number=175,
        code="B401",
        heading="Cloth over boards",
        notes="Cotton, linen or other woven fabric over boards. Use with <ProductForm> BB",
        added_version=2,
    ),
    "B402": CodeListEntry(
        list_number=175,
        code="B402",
        heading="Paper over boards",
        notes="Cellulose-based or similar non-woven material, which may be printed and may be embossed with an artificial cloth or leather-like texture, over boards. Use with <ProductForm> BB",
        added_version=2,
    ),
    "B403": CodeListEntry(
        list_number=175,
        code="B403",
        heading="Leather, real",
        notes="Covered with leather created by tanning animal hide. May be ‘full-grain’ using the entire thickness of the hide, ‘top grain’ using the outer layer of the hide, or ‘split’ using the inner layers of the hide. Split leather may be embossed with an artificial grain or texture. Use with <ProductForm> BG, and if appropriate with codes B308 or B309 (otherwise ‘full-bound’ is implied)",
        added_version=2,
    ),
    "B404": CodeListEntry(
        list_number=175,
        code="B404",
        heading="Leather, imitation",
        notes="Covered with synthetic leather-like material - polymer or non-animal fibre over a textile backing, usually coated and embossed with an artificial grain or texture. Leatherette, pleather etc. Use with <ProductForm> BB (or BG if particularly high-quality), and if appropriate with codes B308 or B309 (otherwise ‘full-bound’ is implied)",
        added_version=2,
    ),
    "B405": CodeListEntry(
        list_number=175,
        code="B405",
        heading="Leather, bonded",
        notes="Covered with leather reconstituted from a pulp made from shredded animal hide, layered on a fibre or textile backing, coated and usually embossed with an artificial grain or texture. Use with <ProductForm> BG, and if appropriate with codes B308 or B309 (otherwise ‘full-bound’ is implied)",
        added_version=2,
    ),
    "B406": CodeListEntry(
        list_number=175,
        code="B406",
        heading="Vellum",
        notes="Pages made with prepared but untanned animal skin (usually calf, occasionally goat or sheep). Includes parchment, a thicker and less refined form of animal skin, but not ‘paper vellum’ or vegetable parchment made from synthetic or plant fibres",
        added_version=2,
    ),
    "B407": CodeListEntry(
        list_number=175,
        code="B407",
        heading="Head and tail bands",
        notes="Capital bands, either decorative or functional. Use <ProductFormFeature> to specify the color",
        added_version=63,
    ),
    "B419": CodeListEntry(
        list_number=175,
        code="B419",
        heading="Decorated page edges",
        notes="Colored, stained, gilded, patterned, abstract or illustrated sprayed edges. Use <ProductFormFeature> to specify the color, and optionally, use <SupportingResource> to provide an image of the decoration",
        added_version=69,
    ),
    "B408": CodeListEntry(
        list_number=175,
        code="B408",
        heading="Decorated endpapers",
        notes="Colored, patterned, printed, abstract or illustrated endpapers or of inside front and back covers. Use <ProductFormFeature> to specify the color, and optionally, use <SupportingResource> to provide an image of the decoration",
        added_version=63,
    ),
    "B409": CodeListEntry(
        list_number=175,
        code="B409",
        heading="Cloth",
        notes="Cloth, not necessarily over boards - cf B401",
        added_version=6,
    ),
    "B410": CodeListEntry(
        list_number=175,
        code="B410",
        heading="Imitation cloth",
        notes="Spanish ‘simil-tela’",
        added_version=6,
    ),
    "B411": CodeListEntry(
        list_number=175,
        code="B411",
        heading="Velvet",
        added_version=8,
    ),
    "B412": CodeListEntry(
        list_number=175,
        code="B412",
        heading="Flexible plastic / vinyl cover",
        notes="AKA ‘flexibound’: use with Product Form code BC",
        added_version=8,
    ),
    "B413": CodeListEntry(
        list_number=175,
        code="B413",
        heading="Plastic-covered",
        notes="Separate outer plastic cover, often transparent and allowing the cover to show through. Typically has pockets into which the cover tucks. See also B412, where the cover itself is plastic or vinyl",
        added_version=8,
    ),
    "B414": CodeListEntry(
        list_number=175,
        code="B414",
        heading="Vinyl-covered",
        notes="Separate outer vinyl cover. See also B412, where the cover itself is plastic or vinyl",
        added_version=8,
    ),
    "B415": CodeListEntry(
        list_number=175,
        code="B415",
        heading="Laminated cover",
        notes="Book, laminating material unspecified, often termed PLC or PPC (printed laminated case, printed paper case) when used with Product form BB. Use L101 for ‘whole product laminated’, eg a laminated sheet map or wallchart",
        added_version=8,
    ),
    "B416": CodeListEntry(
        list_number=175,
        code="B416",
        heading="Card cover",
        notes="With card cover (like a typical paperback). As distinct from a self-cover or more elaborate binding. Use for example with Product form BF, to indicate a pamphlet is bound within a card cover. See also B400 (for self-covers) and B418 (for distinct paper covers)",
        added_version=29,
    ),
    "B417": CodeListEntry(
        list_number=175,
        code="B417",
        heading="Duplex-printed cover",
        notes="Printed both inside and outside the front and/or back cover",
        added_version=39,
    ),
    "B418": CodeListEntry(
        list_number=175,
        code="B418",
        heading="Paper cover",
        notes="Cover uses a distinct, usually heavier (thicker) paper than the interior pages. Use for example with Product form BF, to indicate a pamphlet is bound within a paper cover. See also B400 (for self-covers) and B416 (for card covers)",
        added_version=66,
    ),
    "B420": CodeListEntry(
        list_number=175,
        code="B420",
        heading="Delicate cover / jacket finish",
        notes="Cover or jacket finish may merit special handling or packaging during distribution and fulfilment, for example because of gloss varnish which may hold fingerprints or matt laminate liable to scuffing",
        added_version=55,
    ),
    "B421": CodeListEntry(
        list_number=175,
        code="B421",
        heading="Embossed cover",
        notes="Embossing (or debossing) used on cover or jacket",
        added_version=69,
    ),
    "B422": CodeListEntry(
        list_number=175,
        code="B422",
        heading="Foil (on cover)",
        added_version=71,
    ),
    "B423": CodeListEntry(
        list_number=175,
        code="B423",
        heading="Foil (on jacket)",
        added_version=71,
    ),
    "B424": CodeListEntry(
        list_number=175,
        code="B424",
        heading="Temporary stickers on cover or jacket",
        notes="All types of promotional stickers, applied on behalf of the publisher, but easily removable by the reader without damage to the cover or jacket",
        added_version=71,
    ),
    "B425": CodeListEntry(
        list_number=175,
        code="B425",
        heading="Permanent stickers on cover or jacket",
        notes="All types of promotional stickers, applied on behalf of the publisher, but not capable of being removed easily without damage to the cover or jacket",
        added_version=71,
    ),
    "B426": CodeListEntry(
        list_number=175,
        code="B426",
        heading="Spine panorama",
        notes="Spine illustration combines with spines of other products in a collection to form a panoramic image. Sometimes termed a ‘spinescape’",
        added_version=71,
    ),
    "B501": CodeListEntry(
        list_number=175,
        code="B501",
        heading="With dust jacket",
        notes="Type unspecified",
        added_version=2,
    ),
    "B502": CodeListEntry(
        list_number=175,
        code="B502",
        heading="With printed dust jacket",
        notes="Used to distinguish from B503",
        added_version=2,
    ),
    "B503": CodeListEntry(
        list_number=175,
        code="B503",
        heading="With translucent dust cover",
        notes="With translucent paper or plastic protective cover",
        added_version=2,
    ),
    "B504": CodeListEntry(
        list_number=175,
        code="B504",
        heading="With flaps",
        notes="For paperback with flaps - sometimes known as gatefolds or French flaps (extensions of the cover that fold inside the front and back cover)",
        added_version=2,
    ),
    "B505": CodeListEntry(
        list_number=175,
        code="B505",
        heading="With thumb index",
        added_version=2,
    ),
    "B506": CodeListEntry(
        list_number=175,
        code="B506",
        heading="With ribbon marker(s)",
        notes="If the number of markers is significant, it can be stated as free text in <ProductFormDescription>. Use <ProductFormFeature> to specify the color",
        added_version=2,
    ),
    "B507": CodeListEntry(
        list_number=175,
        code="B507",
        heading="With zip fastener",
        added_version=2,
    ),
    "B508": CodeListEntry(
        list_number=175,
        code="B508",
        heading="With button snap fastener",
        added_version=2,
    ),
    "B509": CodeListEntry(
        list_number=175,
        code="B509",
        heading="With leather edge lining",
        notes="AKA yapp edge?",
        added_version=2,
    ),
    "B510": CodeListEntry(
        list_number=175,
        code="B510",
        heading="Rough front",
        notes="With edge trimming such that the front edge is ragged, not neatly and squarely trimmed: AKA deckle edge, feather edge, uncut edge, rough cut",
        added_version=11,
    ),
    "B511": CodeListEntry(
        list_number=175,
        code="B511",
        heading="Foldout",
        notes="With one or more gatefold or foldout sections bound into the book block",
        added_version=24,
    ),
    "B512": CodeListEntry(
        list_number=175,
        code="B512",
        heading="Wide margin",
        notes="Pages include extra-wide margin specifically intended for hand-written annotations",
        added_version=27,
    ),
    "B513": CodeListEntry(
        list_number=175,
        code="B513",
        heading="With fastening strap",
        notes="Book with attached loop for fixing to baby stroller, cot, chair etc",
        added_version=28,
    ),
    "B514": CodeListEntry(
        list_number=175,
        code="B514",
        heading="With perforated pages",
        notes="With one or more pages perforated and intended to be torn out for use",
        added_version=29,
    ),
    "B515": CodeListEntry(
        list_number=175,
        code="B515",
        heading="Acid-free paper",
        notes="Printed on acid-free or alkaline buffered paper conforming with ISO 9706",
        added_version=35,
    ),
    "B516": CodeListEntry(
        list_number=175,
        code="B516",
        heading="Archival paper",
        notes="Printed on acid-free or alkaline buffered paper with a high cotton content, conforming with ISO 11108",
        added_version=35,
    ),
    "B517": CodeListEntry(
        list_number=175,
        code="B517",
        heading="With elasticated strap",
        notes="Strap acts as closure or as page marker",
        added_version=38,
    ),
    "B518": CodeListEntry(
        list_number=175,
        code="B518",
        heading="With serialized authenticity token",
        notes="For example, holographic sticker such as the banderol used in the Turkish book trade",
        added_version=43,
    ),
    "B519": CodeListEntry(
        list_number=175,
        code="B519",
        heading="With dust jacket poster",
        notes="Jacket in the form of a pamphlet or poster, specifically intended to be removed and read or used separately from the book",
        added_version=45,
    ),
    "B520": CodeListEntry(
        list_number=175,
        code="B520",
        heading="Rounded corners",
        notes="Usually die-cut rounding to foredge corners of cover (and/or to foredge page corners). See B212 for elaborate die-cutting",
        added_version=54,
    ),
    "B521": CodeListEntry(
        list_number=175,
        code="B521",
        heading="Splashproof",
        notes="Water-resistant or ‘waterproof’ cover and pages",
        added_version=59,
    ),
    "B522": CodeListEntry(
        list_number=175,
        code="B522",
        heading="Mineral paper",
        notes="Pages composed of ‘mineral paper’ comprised of HDPE plastic and ground calcium carbonate, eg Stonepaper",
        added_version=64,
    ),
    "B523": CodeListEntry(
        list_number=175,
        code="B523",
        heading="With accessibility claim ticket",
        notes="For example, cut-out claim form such as the ‘text data request ticket’ used in the Japanese book trade",
        added_version=66,
    ),
    "B524": CodeListEntry(
        list_number=175,
        code="B524",
        heading="Plastic paper",
        notes="Pages composed of microporous sheets comprised of non-woven HDPE or HDPP fibers, or of non-porous HDPP film, eg Tyvek or Yupo",
        added_version=70,
    ),
    "B525": CodeListEntry(
        list_number=175,
        code="B525",
        heading="With wraparound foredge flap",
        notes="For paperback with flaps (an extension of the cover that folds outside the front or back cover, covering the foredge). The other flap may be absent, conventional or may also wrap around the foredge",
        added_version=71,
    ),
    "B601": CodeListEntry(
        list_number=175,
        code="B601",
        heading="Turn-around book",
        notes="A book in which half the content is printed upside-down, to be read the other way round. Also known as a ‘flip-book’ or ‘tête-bêche’ (Fr) binding, it has two front covers and a single spine. Usually an omnibus of two works",
        added_version=7,
    ),
    "B602": CodeListEntry(
        list_number=175,
        code="B602",
        heading="Unflipped manga format",
        notes="Manga with pages and panels in the sequence of (right-to-left flowing) Japanese-style design",
        added_version=8,
    ),
    "B603": CodeListEntry(
        list_number=175,
        code="B603",
        heading="Back-to-back book",
        notes="A book in which half the content is printed so as to be read from the other cover. All content is printed the same way up. Also known as ‘dos-à-dos’ (Fr) binding, it has two front covers and two spines. Usually an omnibus of two works",
        added_version=42,
    ),
    "B604": CodeListEntry(
        list_number=175,
        code="B604",
        heading="Flipped manga format",
        notes="Manga with pages and panels in the sequence mirrored from Japanese-style design (thus flowing left-to-right)",
        added_version=60,
    ),
    "B605": CodeListEntry(
        list_number=175,
        code="B605",
        heading="Variant turn-around book",
        notes="A book in which half the content is read the other way round from ‘back’ to ‘front’. A variant on ‘flip-book’ or ‘tête-bêche’ (fr) binding where the text is in two languages with different page progression (eg English and Arabic) and neither needs to be upside down, it has two front covers and a single spine. Usually an omnibus of a work and a derived translated work",
        added_version=62,
    ),
    "B606": CodeListEntry(
        list_number=175,
        code="B606",
        heading="Page progression LTR",
        notes="Pages are ordered left to right (the left page in a spread is read before the right). Note this does not specifically mean text on the page is also read left to right",
        added_version=62,
    ),
    "B607": CodeListEntry(
        list_number=175,
        code="B607",
        heading="Page progression RTL",
        notes="Pages are ordered right to left",
        added_version=62,
    ),
    "B608": CodeListEntry(
        list_number=175,
        code="B608",
        heading="Page progression TTB",
        notes="Pages are ordered top to bottom, with the spine oriented horizontally. See also Dwarsligger (code B118), a proprietary variation of this format",
        added_version=62,
    ),
    "B609": CodeListEntry(
        list_number=175,
        code="B609",
        heading="Page progression other",
        notes="Pages are ordered bottom to top, with the spine oriented horizontally, or in a way for which there is no other code",
        added_version=62,
    ),
    "B610": CodeListEntry(
        list_number=175,
        code="B610",
        heading="Syllabification",
        notes="Text shows syllable breaks",
        added_version=25,
    ),
    "B611": CodeListEntry(
        list_number=175,
        code="B611",
        heading="Upper case only",
        notes="For bicameral scripts, body text is upper case only",
        added_version=62,
    ),
    "B701": CodeListEntry(
        list_number=175,
        code="B701",
        heading="UK Uncontracted Braille",
        notes="Single letters only. Was formerly identified as UK Braille Grade 1",
        added_version=8,
    ),
    "B702": CodeListEntry(
        list_number=175,
        code="B702",
        heading="UK Contracted Braille",
        notes="With some letter combinations. Was formerly identified as UK Braille Grade 2",
        added_version=8,
    ),
    "B703": CodeListEntry(
        list_number=175,
        code="B703",
        heading="US Braille",
        notes="For US Braille, prefer codes B704 and B705 as appropriate",
        added_version=8,
    ),
    "B704": CodeListEntry(
        list_number=175,
        code="B704",
        heading="US Uncontracted Braille",
        added_version=12,
    ),
    "B705": CodeListEntry(
        list_number=175,
        code="B705",
        heading="US Contracted Braille",
        added_version=12,
    ),
    "B706": CodeListEntry(
        list_number=175,
        code="B706",
        heading="Unified English Braille",
        notes="For UEB, prefer codes B708 and B709 as appropriate",
        added_version=12,
    ),
    "B707": CodeListEntry(
        list_number=175,
        code="B707",
        heading="Moon",
        notes="Moon embossed alphabet, used by some print-impaired readers who have difficulties with Braille",
        added_version=13,
    ),
    "B708": CodeListEntry(
        list_number=175,
        code="B708",
        heading="Unified English Uncontracted Braille",
        added_version=36,
    ),
    "B709": CodeListEntry(
        list_number=175,
        code="B709",
        heading="Unified English Contracted Braille",
        added_version=36,
    ),
    "B750": CodeListEntry(
        list_number=175,
        code="B750",
        heading="Tactile images",
        notes="Eg charts, diagrams, maps, or other tactile graphics or illustrations that are embossed or textured for accessibility purposes",
        added_version=59,
    ),
    "B751": CodeListEntry(
        list_number=175,
        code="B751",
        heading="Lenticular images",
        notes="Image-changing effect, ‘3D’ images, ‘tilt cards’, printed with tiny lenses",
        added_version=59,
    ),
    "B752": CodeListEntry(
        list_number=175,
        code="B752",
        heading="Anaglyph images",
        notes="Stereoscopic 3D effect (eg of images) as viewed through red/green filters",
        added_version=59,
    ),
    "C750": CodeListEntry(
        list_number=175,
        code="C750",
        heading="Raised 3D relief",
        notes="Physical 3D relief (eg of a map, globe) reflects height of terrain etc",
        added_version=59,
    ),
    "D101": CodeListEntry(
        list_number=175,
        code="D101",
        heading="Real Video format",
        notes="Proprietary RealNetworks format. Includes Real Video packaged within a .rm RealMedia container",
        added_version=2,
    ),
    "D102": CodeListEntry(
        list_number=175,
        code="D102",
        heading="Quicktime format",
        added_version=2,
    ),
    "D103": CodeListEntry(
        list_number=175,
        code="D103",
        heading="AVI format",
        added_version=2,
    ),
    "D104": CodeListEntry(
        list_number=175,
        code="D104",
        heading="Windows Media Video format",
        added_version=2,
    ),
    "D105": CodeListEntry(
        list_number=175,
        code="D105",
        heading="MPEG-4",
        added_version=5,
    ),
    "D201": CodeListEntry(
        list_number=175,
        code="D201",
        heading="MS-DOS",
        notes="Use with an applicable Product Form code D*; note that more detail of operating system requirements can be given in a Product Form Feature composite",
        added_version=2,
    ),
    "D202": CodeListEntry(
        list_number=175,
        code="D202",
        heading="Windows",
        notes="Use with an applicable Product Form code D*; see note on D201",
        added_version=2,
    ),
    "D203": CodeListEntry(
        list_number=175,
        code="D203",
        heading="Macintosh",
        notes="Use with an applicable Product Form code D*; see note on D201",
        added_version=2,
    ),
    "D204": CodeListEntry(
        list_number=175,
        code="D204",
        heading="UNIX / LINUX",
        notes="Use with an applicable Product Form code D*; see note on D201",
        added_version=2,
    ),
    "D205": CodeListEntry(
        list_number=175,
        code="D205",
        heading="Other operating system(s)",
        notes="Use with an applicable Product Form code D*; see note on D201",
        added_version=2,
    ),
    "D206": CodeListEntry(
        list_number=175,
        code="D206",
        heading="Palm OS",
        notes="Use with an applicable Product Form code D*; see note on D201",
        added_version=6,
    ),
    "D207": CodeListEntry(
        list_number=175,
        code="D207",
        heading="Windows Mobile",
        notes="Use with an applicable Product Form code D*; see note on D201",
        added_version=6,
    ),
    "D301": CodeListEntry(
        list_number=175,
        code="D301",
        heading="Microsoft XBox",
        notes="Use with Product Form code DB or DI as applicable",
        added_version=2,
    ),
    "D302": CodeListEntry(
        list_number=175,
        code="D302",
        heading="Nintendo Gameboy Color",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D303": CodeListEntry(
        list_number=175,
        code="D303",
        heading="Nintendo Gameboy Advanced",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D304": CodeListEntry(
        list_number=175,
        code="D304",
        heading="Nintendo Gameboy",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D305": CodeListEntry(
        list_number=175,
        code="D305",
        heading="Nintendo Gamecube",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D306": CodeListEntry(
        list_number=175,
        code="D306",
        heading="Nintendo 64",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D307": CodeListEntry(
        list_number=175,
        code="D307",
        heading="Sega Dreamcast",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D308": CodeListEntry(
        list_number=175,
        code="D308",
        heading="Sega Genesis/Megadrive",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D309": CodeListEntry(
        list_number=175,
        code="D309",
        heading="Sega Saturn",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=2,
    ),
    "D310": CodeListEntry(
        list_number=175,
        code="D310",
        heading="Sony PlayStation 1",
        notes="Use with Product Form code DB as applicable",
        added_version=2,
    ),
    "D311": CodeListEntry(
        list_number=175,
        code="D311",
        heading="Sony PlayStation 2",
        notes="Use with Product Form code DB or DI as applicable",
        added_version=2,
    ),
    "D312": CodeListEntry(
        list_number=175,
        code="D312",
        heading="Nintendo Dual Screen",
        notes="Use with Product Form code DE as applicable",
        added_version=6,
    ),
    "D313": CodeListEntry(
        list_number=175,
        code="D313",
        heading="Sony PlayStation 3",
        notes="Use with Product Form code DB, DI, DO or E* as applicable",
        added_version=7,
    ),
    "D314": CodeListEntry(
        list_number=175,
        code="D314",
        heading="Microsoft Xbox 360",
        notes="Use with Product Form code DB, DI or VN as applicable",
        added_version=7,
    ),
    "D315": CodeListEntry(
        list_number=175,
        code="D315",
        heading="Nintendo Wii",
        notes="Use with Product Form code DA or E* as applicable",
        added_version=7,
    ),
    "D316": CodeListEntry(
        list_number=175,
        code="D316",
        heading="Sony PlayStation Portable (PSP)",
        notes="Use with Product Form code DL or VL as applicable",
        added_version=7,
    ),
    "D317": CodeListEntry(
        list_number=175,
        code="D317",
        heading="Sony PlayStation 3",
        notes="Use with Product Form code DB, DI, DO or E* as applicable. Deprecated - use D313",
        added_version=47,
        deprecated_version=51,
    ),
    "D318": CodeListEntry(
        list_number=175,
        code="D318",
        heading="Sony PlayStation 4",
        notes="Use with Product Form code DB, DI, DO or E* as applicable",
        added_version=47,
    ),
    "D319": CodeListEntry(
        list_number=175,
        code="D319",
        heading="Sony PlayStation Vita",
        notes="Use with Product Form code DA or E* as applicable",
        added_version=47,
    ),
    "D320": CodeListEntry(
        list_number=175,
        code="D320",
        heading="Microsoft Xbox One",
        notes="Use with Product Form code DB, DI, DO or E* as applicable",
        added_version=47,
    ),
    "D321": CodeListEntry(
        list_number=175,
        code="D321",
        heading="Nintendo Switch",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=47,
    ),
    "D322": CodeListEntry(
        list_number=175,
        code="D322",
        heading="Nintendo Wii U",
        notes="Use with Product Form code DE or DB as applicable",
        added_version=47,
    ),
    "D323": CodeListEntry(
        list_number=175,
        code="D323",
        heading="Sony PlayStation 5",
        notes="Use with Product Form code DB, DI, DO or E* as applicable",
        added_version=51,
    ),
    "D324": CodeListEntry(
        list_number=175,
        code="D324",
        heading="Microsoft Xbox Series X / S",
        notes="Use with Product Form code DB, DI, DO or E* as applicable",
        added_version=51,
    ),
    "E100": CodeListEntry(
        list_number=175,
        code="E100",
        heading="Other",
        notes="No code allocated for this e-publication format yet",
        added_version=13,
    ),
    "E101": CodeListEntry(
        list_number=175,
        code="E101",
        heading="EPUB",
        notes="The Open Publication Structure / OPS Container Format standard of the International Digital Publishing Forum (IDPF) [File extension .epub]",
        added_version=10,
    ),
    "E102": CodeListEntry(
        list_number=175,
        code="E102",
        heading="OEB",
        notes="The Open EBook format of the IDPF, a predecessor of the full EPUB format, still (2008) supported as part of the latter [File extension .opf]. Includes EPUB format up to and including version 2 - but prefer code E101 for EPUB 2, and always use code E101 for EPUB 3",
        added_version=10,
    ),
    "E103": CodeListEntry(
        list_number=175,
        code="E103",
        heading="DOC",
        notes="Microsoft Word binary document format [File extension .doc]",
        added_version=10,
    ),
    "E104": CodeListEntry(
        list_number=175,
        code="E104",
        heading="DOCX",
        notes="Office Open XML / Microsoft Word XML document format (ISO/IEC 29500:2008) [File extension .docx]",
        added_version=10,
    ),
    "E105": CodeListEntry(
        list_number=175,
        code="E105",
        heading="HTML",
        notes="HyperText Mark-up Language [File extension .html, .htm]",
        added_version=10,
    ),
    "E106": CodeListEntry(
        list_number=175,
        code="E106",
        heading="ODF",
        notes="Open Document Format [File extension .odt]",
        added_version=10,
    ),
    "E107": CodeListEntry(
        list_number=175,
        code="E107",
        heading="PDF",
        notes="Portable Document Format (ISO 32000-1:2008) [File extension .pdf]",
        added_version=10,
    ),
    "E108": CodeListEntry(
        list_number=175,
        code="E108",
        heading="PDF/A",
        notes="PDF archiving format defined by ISO 19005-1:2005 [File extension .pdf]",
        added_version=10,
    ),
    "E109": CodeListEntry(
        list_number=175,
        code="E109",
        heading="RTF",
        notes="Rich Text Format [File extension .rtf]",
        added_version=10,
    ),
    "E110": CodeListEntry(
        list_number=175,
        code="E110",
        heading="SGML",
        notes="Standard Generalized Mark-up Language",
        added_version=10,
    ),
    "E111": CodeListEntry(
        list_number=175,
        code="E111",
        heading="TCR",
        notes="A compressed text format mainly used on Psion handheld devices [File extension .tcr]",
        added_version=10,
    ),
    "E112": CodeListEntry(
        list_number=175,
        code="E112",
        heading="TXT",
        notes="Text file format [File extension .txt]. Typically ASCII or Unicode UTF-8/16",
        added_version=10,
    ),
    "E113": CodeListEntry(
        list_number=175,
        code="E113",
        heading="XHTML",
        notes="Extensible Hypertext Markup Language [File extension .xhtml, .xht, .xml, .html, .htm]",
        added_version=10,
    ),
    "E114": CodeListEntry(
        list_number=175,
        code="E114",
        heading="zTXT",
        notes="A compressed text format mainly used on Palm handheld devices [File extension .pdb - see also E121, E125, E130]",
        added_version=10,
    ),
    "E115": CodeListEntry(
        list_number=175,
        code="E115",
        heading="XPS",
        notes="XML Paper Specification format [File extension .xps]",
        added_version=10,
    ),
    "E116": CodeListEntry(
        list_number=175,
        code="E116",
        heading="Amazon Kindle",
        notes="A format proprietary to Amazon for use with its Kindle reading devices or software readers [File extensions .azw, .mobi, .prc etc]. Prefer code E148 for Print Replica files",
        added_version=10,
    ),
    "E117": CodeListEntry(
        list_number=175,
        code="E117",
        heading="BBeB",
        notes="A Sony proprietary format for use with the Sony Reader and LIBRIé reading devices [File extension .lrf]",
        added_version=10,
    ),
    "E118": CodeListEntry(
        list_number=175,
        code="E118",
        heading="DXReader",
        notes="A proprietary format for use with DXReader software",
        added_version=10,
    ),
    "E119": CodeListEntry(
        list_number=175,
        code="E119",
        heading="EBL",
        notes="A format proprietary to the Ebook Library service",
        added_version=10,
    ),
    "E120": CodeListEntry(
        list_number=175,
        code="E120",
        heading="Ebrary",
        notes="A format proprietary to the Ebrary service",
        added_version=10,
    ),
    "E121": CodeListEntry(
        list_number=175,
        code="E121",
        heading="eReader",
        notes="A proprietary format for use with eReader (AKA ‘Palm Reader’) software on various hardware platforms [File extension .pdb - see also E114, E125, E130]",
        added_version=10,
    ),
    "E122": CodeListEntry(
        list_number=175,
        code="E122",
        heading="Exebook",
        notes="A proprietary format with its own reading system for Windows platforms [File extension .exe]",
        added_version=10,
    ),
    "E123": CodeListEntry(
        list_number=175,
        code="E123",
        heading="Franklin eBookman",
        notes="A proprietary format for use with the Franklin eBookman reader",
        added_version=10,
    ),
    "E124": CodeListEntry(
        list_number=175,
        code="E124",
        heading="Gemstar Rocketbook",
        notes="A proprietary format for use with the Gemstar Rocketbook reader [File extension .rb]",
        added_version=10,
    ),
    "E125": CodeListEntry(
        list_number=175,
        code="E125",
        heading="iSilo",
        notes="A proprietary format for use with iSilo software on various hardware platforms [File extension .pdb - see also E114, E121, E130]",
        added_version=10,
    ),
    "E126": CodeListEntry(
        list_number=175,
        code="E126",
        heading="Microsoft Reader",
        notes="A proprietary format for use with Microsoft Reader software on Windows and Pocket PC platforms [File extension .lit]",
        added_version=10,
    ),
    "E127": CodeListEntry(
        list_number=175,
        code="E127",
        heading="Mobipocket",
        notes="A proprietary format for use with Mobipocket software on various hardware platforms [File extensions .mobi, .prc]. Includes Amazon Kindle formats up to and including version 7 - but prefer code E116 for version 7, and always use E116 for KF8",
        added_version=10,
    ),
    "E128": CodeListEntry(
        list_number=175,
        code="E128",
        heading="MyiLibrary",
        notes="A format proprietary to the MyiLibrary service",
        added_version=10,
    ),
    "E129": CodeListEntry(
        list_number=175,
        code="E129",
        heading="NetLibrary",
        notes="A format proprietary to the NetLibrary service",
        added_version=10,
    ),
    "E130": CodeListEntry(
        list_number=175,
        code="E130",
        heading="Plucker",
        notes="A proprietary format for use with Plucker reader software on Palm and other handheld devices [File extension .pdb - see also E114, E121, E125]",
        added_version=10,
    ),
    "E131": CodeListEntry(
        list_number=175,
        code="E131",
        heading="VitalBook",
        notes="A format proprietary to the VitalSource service",
        added_version=10,
    ),
    "E132": CodeListEntry(
        list_number=175,
        code="E132",
        heading="Vook",
        notes="A proprietary digital product combining text and video content and available to be used online or as a downloadable application for a mobile device - see www.vook.com",
        added_version=11,
    ),
    "E133": CodeListEntry(
        list_number=175,
        code="E133",
        heading="Google Edition",
        notes="An epublication made available by Google in association with a publisher; readable online on a browser-enabled device and offline on designated ebook readers",
        added_version=11,
    ),
    "E134": CodeListEntry(
        list_number=175,
        code="E134",
        heading="Book ‘app’ for iOS",
        notes="Epublication packaged as application for iOS (eg Apple iPhone, iPad etc), containing both executable code and content. Use <ProductContentType> to describe content, and <ProductFormFeatureType> to list detailed technical requirements",
        added_version=12,
    ),
    "E135": CodeListEntry(
        list_number=175,
        code="E135",
        heading="Book ‘app’ for Android",
        notes="Epublication packaged as application for Android (eg Android phone or tablet), containing both executable code and content. Use <ProductContentType> to describe content, and <ProductFormFeatureType> to list detailed technical requirements",
        added_version=12,
    ),
    "E136": CodeListEntry(
        list_number=175,
        code="E136",
        heading="Book ‘app’ for other operating system",
        notes="Epublication packaged as application, containing both executable code and content. Use where other ‘app’ codes are not applicable. Technical requirements such as target operating system and/or device should be provided eg in <ProductFormFeatureType>. Content type (text or text plus various ‘enhancements’) may be described with <ProductContentType>",
        added_version=12,
    ),
    "E139": CodeListEntry(
        list_number=175,
        code="E139",
        heading="CEB",
        notes="Founder Apabi’s proprietary basic e-book format",
        added_version=15,
    ),
    "E140": CodeListEntry(
        list_number=175,
        code="E140",
        heading="CEBX",
        notes="Founder Apabi’s proprietary XML e-book format",
        added_version=15,
    ),
    "E141": CodeListEntry(
        list_number=175,
        code="E141",
        heading="iBook",
        notes="Apple’s iBook format (a proprietary extension of EPUB), can only be read on Apple iOS devices",
        added_version=17,
    ),
    "E142": CodeListEntry(
        list_number=175,
        code="E142",
        heading="ePIB",
        notes="Proprietary format based on EPUB used by Barnes and Noble for fixed-format e-books, readable on NOOK devices and Nook reader software",
        added_version=17,
    ),
    "E143": CodeListEntry(
        list_number=175,
        code="E143",
        heading="SCORM",
        notes="Sharable Content Object Reference Model, standard content and packaging format for e-learning objects",
        added_version=20,
    ),
    "E144": CodeListEntry(
        list_number=175,
        code="E144",
        heading="EBP",
        notes="E-book Plus (proprietary Norwegian e-book format)",
        added_version=24,
    ),
    "E145": CodeListEntry(
        list_number=175,
        code="E145",
        heading="Page Perfect",
        notes="Proprietary format based on PDF used by Barnes and Noble for fixed-format e-books, readable on some NOOK devices and Nook reader software",
        added_version=28,
    ),
    "E146": CodeListEntry(
        list_number=175,
        code="E146",
        heading="BRF",
        notes="(Braille-ready file) Electronic Braille file",
        added_version=37,
    ),
    "E147": CodeListEntry(
        list_number=175,
        code="E147",
        heading="Erudit",
        notes="Proprietary XML format for articles, see for example https://www.cairn.info/services-aux-editeurs.php",
        added_version=41,
    ),
    "E148": CodeListEntry(
        list_number=175,
        code="E148",
        heading="Amazon Kindle Print Replica",
        notes="A format proprietary to Amazon for use with its Kindle reading devices or software readers. Essentially a PDF embedded within a KF8 format file",
        added_version=47,
    ),
    "E149": CodeListEntry(
        list_number=175,
        code="E149",
        heading="Comic Book Archive",
        notes="Format for comic books, consisting primarily of sequentially-named PNG or JPEG images in a zip container",
        added_version=50,
    ),
    "E150": CodeListEntry(
        list_number=175,
        code="E150",
        heading="EPUB/A",
        added_version=66,
    ),
    "E151": CodeListEntry(
        list_number=175,
        code="E151",
        heading="eBraille",
        notes="DAISY/APH Braille file standard based on ePUB (formerly known as eBRF)",
        added_version=71,
    ),
    "E200": CodeListEntry(
        list_number=175,
        code="E200",
        heading="Reflowable",
        notes="Use this and/or code E201 when a particular e-publication type (specified using codes E100 and upwards) is reflowable or has both fixed layout and reflowable sections or variants, to indicate which option is included in this product",
        added_version=15,
    ),
    "E201": CodeListEntry(
        list_number=175,
        code="E201",
        heading="Fixed format",
        notes="Use this and possibly code E200 when a particular e-publication type (specified using codes E100 and upwards) is fixed layout or has both fixed layout and reflowable sections or variants, to indicate which option is included in this product",
        added_version=15,
    ),
    "E202": CodeListEntry(
        list_number=175,
        code="E202",
        heading="Readable offline",
        notes="All e-publication resources are included within the e-publication package",
        added_version=15,
    ),
    "E203": CodeListEntry(
        list_number=175,
        code="E203",
        heading="Requires network connection",
        notes="E-publication requires a network connection to access some resources (eg an enhanced e-book where video clips are not stored within the e-publication package itself, but are delivered via an internet connection)",
        added_version=15,
    ),
    "E204": CodeListEntry(
        list_number=175,
        code="E204",
        heading="Content removed",
        notes="Resources (eg images) present in other editions have been removed from this product, eg due to rights issues",
        added_version=19,
    ),
    "E205": CodeListEntry(
        list_number=175,
        code="E205",
        heading="Visible page numbering",
        notes="(Mostly fixed-format) e-publication contains visible page numbers. Use with List 196 code 19 if numbering has a print-equivalent",
        added_version=62,
    ),
    "E206": CodeListEntry(
        list_number=175,
        code="E206",
        heading="No preferred page progression",
        notes="For e-publications only, pages may be rendered LTR or RTL (see B606 to B609)",
        added_version=62,
    ),
    "E210": CodeListEntry(
        list_number=175,
        code="E210",
        heading="Landscape",
        notes="Use for fixed-format e-books optimized for landscape display. Also include an indication of the optimal screen aspect ratio",
        added_version=23,
    ),
    "E211": CodeListEntry(
        list_number=175,
        code="E211",
        heading="Portrait",
        notes="Use for fixed-format e-books optimized for portrait display. Also include an indication of the optimal screen aspect ratio",
        added_version=23,
    ),
    "E212": CodeListEntry(
        list_number=175,
        code="E212",
        heading="Square",
        notes="Use for fixed-format e-books optimized for a square display",
        added_version=54,
    ),
    "E213": CodeListEntry(
        list_number=175,
        code="E213",
        heading="Vertical scrolling",
        notes="Use for fixed-format e-publications optimized for vertical scrolling display (‘webtoon format’)",
        added_version=62,
    ),
    "E221": CodeListEntry(
        list_number=175,
        code="E221",
        heading="5:4",
        notes="(1.25:1) Use for fixed-format e-books optimized for displays with a 5:4 aspect ratio (eg 1280x1024 pixels etc, assuming square pixels). Note that aspect ratio codes are NOT specific to actual screen dimensions or pixel counts, but to the ratios between two dimensions or two pixel counts",
        added_version=23,
    ),
    "E222": CodeListEntry(
        list_number=175,
        code="E222",
        heading="4:3",
        notes="(1.33:1) Use for fixed-format e-books optimized for displays with a 4:3 aspect ratio (eg 800x600, 1024x768, 2048x1536 pixels etc)",
        added_version=23,
    ),
    "E223": CodeListEntry(
        list_number=175,
        code="E223",
        heading="3:2",
        notes="(1.5:1) Use for fixed-format e-books optimized for displays with a 3:2 aspect ratio (eg 960x640, 3072x2048 pixels etc)",
        added_version=23,
    ),
    "E224": CodeListEntry(
        list_number=175,
        code="E224",
        heading="16:10",
        notes="(1.6:1) Use for fixed-format e-books optimized for displays with a 16:10 aspect ratio (eg 1440x900, 2560x1600 pixels etc)",
        added_version=23,
    ),
    "E225": CodeListEntry(
        list_number=175,
        code="E225",
        heading="16:9",
        notes="(1.77:1) Use for fixed-format e-books optimized for displays with a 16:9 aspect ratio (eg 1024x576, 1920x1080, 2048x1152 pixels etc)",
        added_version=23,
    ),
    "E226": CodeListEntry(
        list_number=175,
        code="E226",
        heading="18:9",
        notes="(2:1) Use for fixed-format e-books optimized for displays with an 18:9 aspect ratio (eg 2160x1080, 2880x1440 pixels etc)",
        added_version=54,
    ),
    "E227": CodeListEntry(
        list_number=175,
        code="E227",
        heading="21:9",
        notes="(2.37:1) Use for fixed-format e-books optimized for displays with an 21:9 (or 64:27) aspect ratio (eg 3840x1644 pixels etc)",
        added_version=54,
    ),
    "L101": CodeListEntry(
        list_number=175,
        code="L101",
        heading="Laminated",
        notes="Whole product laminated (eg laminated map, fold-out chart, wallchart, etc): use B415 for book with laminated cover",
        added_version=8,
    ),
    "P091": CodeListEntry(
        list_number=175,
        code="P091",
        heading="Calendar with write-in space",
        notes="(de: Nutzkalendarium) Calendar or diary has spaces intended for entering birthdays, appointments, notes etc. Use with other calendar / diary type codes",
        added_version=62,
    ),
    "P092": CodeListEntry(
        list_number=175,
        code="P092",
        heading="Calendar without write-in space",
        notes="(de: Schmuckkalendarium) Calendar or diary has no spaces intended for entering birthdays, appointments, notes etc. Use with other calendar / diary type codes",
        added_version=62,
    ),
    "P096": CodeListEntry(
        list_number=175,
        code="P096",
        heading="Multiple months per page",
        notes="(de: Mehrmonatskalender) Calendar has multiple months (but not whole year) per page or view. Use with other calendar / diary type codes when the time period per sheet, page or view is not the expected arrangement",
        added_version=62,
    ),
    "P097": CodeListEntry(
        list_number=175,
        code="P097",
        heading="One month per page",
        notes="(de: Monatskalender) Calendar has one month per page or view",
        added_version=62,
    ),
    "P098": CodeListEntry(
        list_number=175,
        code="P098",
        heading="One week per page",
        notes="(de: Wochenkalender) Calendar has one week per page or view",
        added_version=62,
    ),
    "P099": CodeListEntry(
        list_number=175,
        code="P099",
        heading="One day per page",
        notes="(de: Tageskalender) Calendar has one day per page or view",
        added_version=62,
    ),
    "P101": CodeListEntry(
        list_number=175,
        code="P101",
        heading="Desk calendar or diary",
        notes="Large format, usually one week per page or view. Use with Product Form code PC or PF",
        added_version=2,
    ),
    "P102": CodeListEntry(
        list_number=175,
        code="P102",
        heading="Mini calendar or pocket diary",
        notes="Small format, usually one week per page or view. Use with Product Form code PC or PF",
        added_version=2,
    ),
    "P103": CodeListEntry(
        list_number=175,
        code="P103",
        heading="Engagement calendar or Appointment diary",
        notes="Day planner. Usually one day per page or view, with time-of-day subdivisions (rather than just days) or adequate space to add them. Use with Product Form code PC or PF",
        added_version=2,
    ),
    "P104": CodeListEntry(
        list_number=175,
        code="P104",
        heading="Day by day calendar",
        notes="Eg tear-off calendars (one day per sheet). Use with Product Form code PC",
        added_version=2,
    ),
    "P105": CodeListEntry(
        list_number=175,
        code="P105",
        heading="Poster calendar",
        notes="Large single-sheet calendar intended for hanging. Use with Product Form code PC or PK",
        added_version=2,
    ),
    "P106": CodeListEntry(
        list_number=175,
        code="P106",
        heading="Wall calendar",
        notes="Large calendar usually intended for hanging from the spine, typically one page per view and one month per view, with illustrations. See also P134. Use with Product Form code PC",
        added_version=2,
    ),
    "P107": CodeListEntry(
        list_number=175,
        code="P107",
        heading="Perpetual calendar or diary",
        notes="Usually undated. Use with Product Form code PC or PF, and can be combined with other calendar/diary type codes",
        added_version=6,
    ),
    "P108": CodeListEntry(
        list_number=175,
        code="P108",
        heading="Advent calendar",
        notes="Use with Product Form code PC, and can be combined with other calendar/diary type codes",
        added_version=6,
    ),
    "P109": CodeListEntry(
        list_number=175,
        code="P109",
        heading="Bookmark calendar",
        notes="Use with Product Form code PC or PT",
        added_version=8,
    ),
    "P110": CodeListEntry(
        list_number=175,
        code="P110",
        heading="Student or Academic calendar or diary",
        notes="Mid-year diary, start and end aligned with the academic year. Use with Product Form code PC or PF, and can be combined with other calendar/diary type codes",
        added_version=8,
    ),
    "P111": CodeListEntry(
        list_number=175,
        code="P111",
        heading="Project calendar",
        notes="Use with Product Form code PC",
        added_version=8,
    ),
    "P112": CodeListEntry(
        list_number=175,
        code="P112",
        heading="Almanac calendar",
        notes="Use with Product Form code PC",
        added_version=8,
    ),
    "P113": CodeListEntry(
        list_number=175,
        code="P113",
        heading="Other calendar, diary or organiser",
        notes="A calendar, diary or organiser that is not one of the types specified elsewhere: use with Product Form code PC, PF or PS",
        added_version=8,
    ),
    "P114": CodeListEntry(
        list_number=175,
        code="P114",
        heading="Other calendar or organiser product",
        notes="A product that is associated with or ancillary to a calendar or organiser, eg a deskstand for a calendar, or an insert for an organiser: use with Product Form code PC or PS",
        added_version=8,
    ),
    "P115": CodeListEntry(
        list_number=175,
        code="P115",
        heading="Family planner",
        notes="Wall or poster calendar with entries for each family member. Use with Product Form code PC or PK",
        added_version=49,
    ),
    "P116": CodeListEntry(
        list_number=175,
        code="P116",
        heading="Postcard calendar",
        notes="Calendar sheets detachable (usually perforated) and intended for mailing as postcards. Use with Product Form code PC",
        added_version=51,
    ),
    "P131": CodeListEntry(
        list_number=175,
        code="P131",
        heading="Blank calendar",
        notes="Wall calendar without illustrations, usually one page per month, intended to be used by adding your own images (de: Bastelkalender). Use with Product Form code PC",
        added_version=62,
    ),
    "P132": CodeListEntry(
        list_number=175,
        code="P132",
        heading="Panoramic calendar",
        notes="Very large wall calendar intended for hanging, usually one page per month, wide landscape orientation, with illustrations. Use with Product Form code PC",
        added_version=62,
    ),
    "P133": CodeListEntry(
        list_number=175,
        code="P133",
        heading="Columnar calendar",
        notes="Very large wall calendar intended for hanging, usually one page per month, narrow portrait orientation, with illustrations. Use with Product Form code PC",
        added_version=62,
    ),
    "P134": CodeListEntry(
        list_number=175,
        code="P134",
        heading="Square calendar",
        notes="(de: Broschurkalender) Wall calendar, usually intended for hanging from a page edge, typically two pages per view and one month per view, with illustrations. See also P106. Use with Product Form code PC",
        added_version=63,
    ),
    "P120": CodeListEntry(
        list_number=175,
        code="P120",
        heading="Picture story cards",
        notes="Kamishibai / Cantastoria cards",
        added_version=30,
    ),
    "P121": CodeListEntry(
        list_number=175,
        code="P121",
        heading="Flash cards",
        notes="For use to specify letter, word, image (etc) recognition cards for teaching reading or other classroom use. Use with Product form code PD",
        added_version=51,
    ),
    "P122": CodeListEntry(
        list_number=175,
        code="P122",
        heading="Reference cards",
        notes="Quick reference cards, revision cards, recipe cards etc. Use with Product form code PD",
        added_version=51,
    ),
    "P123": CodeListEntry(
        list_number=175,
        code="P123",
        heading="Recreation cards",
        notes="For use to specify cards and card decks for gaming, collecting and trading etc. Use also for divination cards. Use with Product form codes PD",
        added_version=51,
    ),
    "P124": CodeListEntry(
        list_number=175,
        code="P124",
        heading="Postcards",
        notes="And postcard packs / books. Use with Product form code PJ",
        added_version=51,
    ),
    "P125": CodeListEntry(
        list_number=175,
        code="P125",
        heading="Greeting cards",
        notes="And greeting card packs. Use with Product form code PJ",
        added_version=51,
    ),
    "P126": CodeListEntry(
        list_number=175,
        code="P126",
        heading="Gift cards",
        notes="Physical cards which carry an intrinsic value, or which are intended to have value added to them, that may be redeemed later. For example book token cards, gift cards. Note value additions and redemption may be in a physical store or online",
        added_version=53,
    ),
    "P127": CodeListEntry(
        list_number=175,
        code="P127",
        heading="Certificate cards",
        notes="Blank certificate, award or achievement cards, Use with Product form code PD",
        added_version=58,
    ),
    "P201": CodeListEntry(
        list_number=175,
        code="P201",
        heading="Hardback (stationery)",
        notes="Stationery item in hardback book format",
        added_version=10,
    ),
    "P202": CodeListEntry(
        list_number=175,
        code="P202",
        heading="Paperback / softback (stationery)",
        notes="Stationery item in paperback/softback book format",
        added_version=10,
    ),
    "P203": CodeListEntry(
        list_number=175,
        code="P203",
        heading="Spiral bound (stationery)",
        notes="Stationery item in spiral-bound book format",
        added_version=10,
    ),
    "P204": CodeListEntry(
        list_number=175,
        code="P204",
        heading="Leather / fine binding (stationery)",
        notes="Stationery item in leather-bound book format, or other fine binding",
        added_version=10,
    ),
    "P301": CodeListEntry(
        list_number=175,
        code="P301",
        heading="With hanging strips",
        notes="For wall map, poster, wallchart etc",
        added_version=32,
    ),
    "P305": CodeListEntry(
        list_number=175,
        code="P305",
        heading="Single-sided",
        notes="Content is printed single-sided (for wallcharts and hanging maps, calendars, etc)",
        added_version=57,
    ),
    "P306": CodeListEntry(
        list_number=175,
        code="P306",
        heading="Double-sided",
        notes="Content is printed double-sided (for wallcharts and hanging maps, calendars, etc, where double-sided may not always be expected)",
        added_version=57,
    ),
    "V201": CodeListEntry(
        list_number=175,
        code="V201",
        heading="PAL",
        notes="SD TV standard for video or DVD",
        added_version=2,
    ),
    "V202": CodeListEntry(
        list_number=175,
        code="V202",
        heading="NTSC",
        notes="SD TV standard for video or DVD",
        added_version=2,
    ),
    "V203": CodeListEntry(
        list_number=175,
        code="V203",
        heading="SECAM",
        notes="SD TV standard for video or DVD",
        added_version=2,
    ),
    "V205": CodeListEntry(
        list_number=175,
        code="V205",
        heading="HD",
        notes="Up to 2K resolution (1920 or 2048 pixels wide) eg for Blu-Ray",
        added_version=40,
    ),
    "V206": CodeListEntry(
        list_number=175,
        code="V206",
        heading="UHD",
        notes="Up to 4K resolution (3840 or 4096 pixels wide) eg for Ultra HD Blu-Ray",
        added_version=40,
    ),
    "V207": CodeListEntry(
        list_number=175,
        code="V207",
        heading="3D video",
        notes="Eg for Blu-ray 3D",
        added_version=40,
    ),
    "V210": CodeListEntry(
        list_number=175,
        code="V210",
        heading="Closed captions",
        notes="Or subtitles, where visibility may be controlled by the viewer. Use <Language> for the language of the captions/subtitles",
        added_version=64,
    ),
    "V211": CodeListEntry(
        list_number=175,
        code="V211",
        heading="Open captions",
        notes="‘Burnt-in’ or hard captions or subtitles. Use <Language> for the language of the captions/subtitles",
        added_version=64,
    ),
    "V212": CodeListEntry(
        list_number=175,
        code="V212",
        heading="Transcript",
        notes="Full transcript of audio and audiovisual content, supplied as a separate file (not as captions or subtitles) and included within the product. See also List 158, where a transcript is a separate resource",
        added_version=66,
    ),
    "V213": CodeListEntry(
        list_number=175,
        code="V213",
        heading="Sign language interpretation",
        notes="Full signing of audio and audiovisual content included within the product",
        added_version=66,
    ),
    "V214": CodeListEntry(
        list_number=175,
        code="V214",
        heading="Textual description of audio",
        notes="Closed or open captions/subtitles include descriptions of non-dialogue audio (eg background sounds, music, speaker identification) in addition to dialogue. Use in combination with V210 or V211. Use V210, V211 alone for captions/subtitles that include only dialogue. In some markets, textual description of audio is termed ‘subtitles for the deaf and hard of hearing’ (SDH)",
        added_version=69,
    ),
    "V215": CodeListEntry(
        list_number=175,
        code="V215",
        heading="Audio description of video",
        notes="Also termed ‘described video’ - audio track describes the video content",
        added_version=69,
    ),
    "V220": CodeListEntry(
        list_number=175,
        code="V220",
        heading="Home use",
        notes="Licensed for use in domestic contexts only",
        added_version=28,
    ),
    "V221": CodeListEntry(
        list_number=175,
        code="V221",
        heading="Classroom use",
        notes="Licensed for use in education",
        added_version=28,
    ),
    "Z101": CodeListEntry(
        list_number=175,
        code="Z101",
        heading="Wooden",
        notes="Primary material composition (eg of kit or puzzle pieces, of gameplay tokens or tiles) is wood or has wooden pieces/parts",
        added_version=50,
    ),
    "Z102": CodeListEntry(
        list_number=175,
        code="Z102",
        heading="Plastic",
        notes="Plastic or plastic pieces/parts",
        added_version=50,
    ),
    "Z103": CodeListEntry(
        list_number=175,
        code="Z103",
        heading="Board",
        notes="Card or board pieces/parts",
        added_version=50,
    ),
    "Z111": CodeListEntry(
        list_number=175,
        code="Z111",
        heading="3D puzzle",
        notes="Puzzle assembles into a 3D object",
        added_version=51,
    ),
    "Z112": CodeListEntry(
        list_number=175,
        code="Z112",
        heading="Noisy kit / puzzle / toy",
        notes="Toy makes a noise. See B208 for noisy books",
        added_version=51,
    ),
    "Z113": CodeListEntry(
        list_number=175,
        code="Z113",
        heading="Puppet",
        notes="Including finger / hand puppets, marionettes",
        added_version=51,
    ),
    "Z121": CodeListEntry(
        list_number=175,
        code="Z121",
        heading="Extra large pieces",
        notes="Designed and sized for the very young, or those with visual impairments, limited motor skills, dementia etc",
        added_version=50,
    ),
}

List175 = CodeList(
    number=175,
    heading="Product form detail",
    scope_note="",
    entries=_ENTRIES,
)

# Alias by name
ProductFormDetail = List175
