import amsdal_glue as glue
from amsdal_data.connections.historical.data_query_transform import META_CLASS_NAME as META_CLASS_NAME

def get_table_version(table: glue.SchemaReference | glue.SubQueryStatement) -> str | glue.Version: ...
def get_class_name(table: glue.SchemaReference | glue.SubQueryStatement) -> str: ...
