from invenio_db import db as db
from invenio_records_resources.records.systemfields.pid import PIDFieldContext
from invenio_vocabularies.records.api import Vocabulary as Vocabulary
from invenio_vocabularies.records.models import VocabularyType as VocabularyType

class BaseVocabularyPIDFieldContext(PIDFieldContext[Vocabulary]):
    def create(self, record: Vocabulary): ...
    def delete(self, record: Vocabulary): ...

class VocabularyPIDFieldContext(BaseVocabularyPIDFieldContext):
    def get_pid_type(self, type_id: str) -> str: ...
    @property
    def pid_type(self) -> str: ...
    def with_type_ctx(self, type_id: str) -> VocabularyPIDFieldContext: ...
