# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/kodypay/grpc/errors/error.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'com/kodypay/grpc/errors/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#com/kodypay/grpc/errors/error.proto\x12\x17\x63om.kodypay.grpc.errors*\x97\x08\n\x07KpError\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x1d\n\x18INVALID_ARGUMENT_GENERIC\x10\xb8\x17\x12\x1e\n\x19INVALID_ARGUMENT_STORE_ID\x10\xb9\x17\x12\x1c\n\x17INVALID_ARGUMENT_AMOUNT\x10\xba\x17\x12#\n\x1eINVALID_ARGUMENT_CURRENCY_CODE\x10\xbb\x17\x12\"\n\x1dINVALID_ARGUMENT_PAYMENT_MODE\x10\xbc\x17\x12!\n\x1cINVALID_ARGUMENT_DESCRIPTION\x10\xbd\x17\x12$\n\x1fINVALID_ARGUMENT_INTERNAL_NOTES\x10\xbe\x17\x12\x1e\n\x19\x44\x45\x41\x44LINE_EXCEEDED_GENERIC\x10\xa0\x1f\x12\x16\n\x11NOT_FOUND_GENERIC\x10\x88\'\x12\x1c\n\x17NOT_FOUND_STORE_DETAILS\x10\x89\'\x12\x16\n\x11NOT_FOUND_PAYMENT\x10\x8a\'\x12\x1b\n\x16\x41LREADY_EXISTS_GENERIC\x10\xf0.\x12\x1b\n\x16\x41LREADY_EXISTS_PAYMENT\x10\xf1.\x12\x1e\n\x19PERMISSION_DENIED_GENERIC\x10\xd8\x36\x12*\n%PERMISSION_DENIED_UNAUTHORIZED_ACCESS\x10\xd9\x36\x12\x1f\n\x1aRESOURCE_EXHAUSTED_GENERIC\x10\xc0>\x12\"\n\x1dRESOURCE_EXHAUSTED_RATE_LIMIT\x10\xc1>\x12 \n\x1b\x46\x41ILED_PRECONDITION_GENERIC\x10\xa8\x46\x12\'\n\"FAILED_PRECONDITION_PAYMENT_LOCKED\x10\xa9\x46\x12\x14\n\x0f\x41\x42ORTED_GENERIC\x10\x90N\x12\x19\n\x14OUT_OF_RANGE_GENERIC\x10\xf8U\x12\x1a\n\x15UNIMPLEMENTED_GENERIC\x10\xe0]\x12\x15\n\x10INTERNAL_GENERIC\x10\xc8\x65\x12\x1d\n\x18INTERNAL_SERVICE_TIMEOUT\x10\xc9\x65\x12-\n(INTERNAL_PENDING_PAYMENT_CREATION_FAILED\x10\xca\x65\x12\x1c\n\x17INTERNAL_PAYMENT_FAILED\x10\xcb\x65\x12*\n%INTERNAL_PAYMENT_STATUS_UPDATE_FAILED\x10\xcc\x65\x12\x16\n\x11INTERNAL_DATABASE\x10\xcd\x65\x12\x18\n\x13UNAVAILABLE_GENERIC\x10\xb0m\x12\x16\n\x11\x44\x41TA_LOSS_GENERIC\x10\x98u\x12\x1c\n\x17UNAUTHENTICATED_GENERIC\x10\x80}\x12$\n\x1fUNAUTHENTICATED_SESSION_EXPIRED\x10\x81}b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.kodypay.grpc.errors.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KPERROR']._serialized_start=65
  _globals['_KPERROR']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
