# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.models.dogma_dynamic_items_type_id_item_id_get import DogmaDynamicItemsTypeIdItemIdGet

class TestDogmaDynamicItemsTypeIdItemIdGet(unittest.TestCase):
    """DogmaDynamicItemsTypeIdItemIdGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DogmaDynamicItemsTypeIdItemIdGet:
        """Test DogmaDynamicItemsTypeIdItemIdGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DogmaDynamicItemsTypeIdItemIdGet`
        """
        model = DogmaDynamicItemsTypeIdItemIdGet()
        if include_optional:
            return DogmaDynamicItemsTypeIdItemIdGet(
                created_by = 56,
                dogma_attributes = [
                    esi_genoa_client.models.dogma_dynamic_items_type_id_item_id_get_dogma_attributes_inner.DogmaDynamicItemsTypeIdItemIdGet_dogma_attributes_inner(
                        attribute_id = 56, 
                        value = 1.337, )
                    ],
                dogma_effects = [
                    esi_genoa_client.models.dogma_dynamic_items_type_id_item_id_get_dogma_effects_inner.DogmaDynamicItemsTypeIdItemIdGet_dogma_effects_inner(
                        effect_id = 56, 
                        is_default = True, )
                    ],
                mutator_type_id = 56,
                source_type_id = 56
            )
        else:
            return DogmaDynamicItemsTypeIdItemIdGet(
                created_by = 56,
                dogma_attributes = [
                    esi_genoa_client.models.dogma_dynamic_items_type_id_item_id_get_dogma_attributes_inner.DogmaDynamicItemsTypeIdItemIdGet_dogma_attributes_inner(
                        attribute_id = 56, 
                        value = 1.337, )
                    ],
                dogma_effects = [
                    esi_genoa_client.models.dogma_dynamic_items_type_id_item_id_get_dogma_effects_inner.DogmaDynamicItemsTypeIdItemIdGet_dogma_effects_inner(
                        effect_id = 56, 
                        is_default = True, )
                    ],
                mutator_type_id = 56,
                source_type_id = 56,
        )
        """

    def testDogmaDynamicItemsTypeIdItemIdGet(self):
        """Test DogmaDynamicItemsTypeIdItemIdGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
