# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.models.corporations_corporation_id_titles_get_inner import CorporationsCorporationIdTitlesGetInner

class TestCorporationsCorporationIdTitlesGetInner(unittest.TestCase):
    """CorporationsCorporationIdTitlesGetInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorporationsCorporationIdTitlesGetInner:
        """Test CorporationsCorporationIdTitlesGetInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorporationsCorporationIdTitlesGetInner`
        """
        model = CorporationsCorporationIdTitlesGetInner()
        if include_optional:
            return CorporationsCorporationIdTitlesGetInner(
                grantable_roles = [
                    'Account_Take_1'
                    ],
                grantable_roles_at_base = [
                    'Account_Take_1'
                    ],
                grantable_roles_at_hq = [
                    'Account_Take_1'
                    ],
                grantable_roles_at_other = [
                    'Account_Take_1'
                    ],
                name = '',
                roles = [
                    'Account_Take_1'
                    ],
                roles_at_base = [
                    'Account_Take_1'
                    ],
                roles_at_hq = [
                    'Account_Take_1'
                    ],
                roles_at_other = [
                    'Account_Take_1'
                    ],
                title_id = 56
            )
        else:
            return CorporationsCorporationIdTitlesGetInner(
        )
        """

    def testCorporationsCorporationIdTitlesGetInner(self):
        """Test CorporationsCorporationIdTitlesGetInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
