# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.api.routes_api import RoutesApi


class TestRoutesApi(unittest.TestCase):
    """RoutesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutesApi()

    def tearDown(self) -> None:
        pass

    def test_get_route_origin_destination(self) -> None:
        """Test case for get_route_origin_destination

        Get route
        """
        pass


if __name__ == '__main__':
    unittest.main()
