# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.models.characters_character_id_planets_planet_id_get_links_inner import CharactersCharacterIdPlanetsPlanetIdGetLinksInner

class TestCharactersCharacterIdPlanetsPlanetIdGetLinksInner(unittest.TestCase):
    """CharactersCharacterIdPlanetsPlanetIdGetLinksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CharactersCharacterIdPlanetsPlanetIdGetLinksInner:
        """Test CharactersCharacterIdPlanetsPlanetIdGetLinksInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CharactersCharacterIdPlanetsPlanetIdGetLinksInner`
        """
        model = CharactersCharacterIdPlanetsPlanetIdGetLinksInner()
        if include_optional:
            return CharactersCharacterIdPlanetsPlanetIdGetLinksInner(
                destination_pin_id = 56,
                link_level = 56,
                source_pin_id = 56
            )
        else:
            return CharactersCharacterIdPlanetsPlanetIdGetLinksInner(
                destination_pin_id = 56,
                link_level = 56,
                source_pin_id = 56,
        )
        """

    def testCharactersCharacterIdPlanetsPlanetIdGetLinksInner(self):
        """Test CharactersCharacterIdPlanetsPlanetIdGetLinksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
