# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.models.post_characters_character_id_mail_request import PostCharactersCharacterIdMailRequest

class TestPostCharactersCharacterIdMailRequest(unittest.TestCase):
    """PostCharactersCharacterIdMailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostCharactersCharacterIdMailRequest:
        """Test PostCharactersCharacterIdMailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostCharactersCharacterIdMailRequest`
        """
        model = PostCharactersCharacterIdMailRequest()
        if include_optional:
            return PostCharactersCharacterIdMailRequest(
                approved_cost = 56,
                body = '',
                recipients = [
                    esi_genoa_client.models.post_characters_character_id_mail_request_recipients_inner.PostCharactersCharacterIdMail_request_recipients_inner(
                        recipient_id = 56, 
                        recipient_type = 'alliance', )
                    ],
                subject = ''
            )
        else:
            return PostCharactersCharacterIdMailRequest(
                body = '',
                recipients = [
                    esi_genoa_client.models.post_characters_character_id_mail_request_recipients_inner.PostCharactersCharacterIdMail_request_recipients_inner(
                        recipient_id = 56, 
                        recipient_type = 'alliance', )
                    ],
                subject = '',
        )
        """

    def testPostCharactersCharacterIdMailRequest(self):
        """Test PostCharactersCharacterIdMailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
