from invenio_records_resources.services.records.components import MetadataComponent

class DraftMetadataComponent(MetadataComponent):
    def update_draft(self, identity, data=None, record=None, **kwargs) -> None: ...
    def publish(self, identity, draft=None, record=None, **kwargs) -> None: ...
    def edit(self, identity, draft=None, record=None, **kwargs) -> None: ...
    def new_version(self, identity, draft=None, record=None, **kwargs) -> None: ...
