from invenio_records_resources.services.records.components import ServiceComponent

class PIDComponent(ServiceComponent):
    def publish(self, identity, draft=None, record=None) -> None: ...
    def delete_draft(self, identity, draft=None, record=None, force: bool = False) -> None: ...
