from .compendium import Compendium as Compendium, slugify as slugify
from .create_llm_clients import MissingAPIKeyError as MissingAPIKeyError, create_openai_client as create_openai_client
from .research import CancellationContext as CancellationContext, DeepResearchError as DeepResearchError, MissingConfigurationError as MissingConfigurationError, ResearchCancelledError as ResearchCancelledError, ResearchConfig as ResearchConfig, ResearchProgress as ResearchProgress, ResearchTimeoutError as ResearchTimeoutError, build_compendium as build_compendium, recover_compendium as recover_compendium
from pathlib import Path

def cli() -> None: ...
def create(topic: str, output_path: Path | None, no_background: bool, formats: tuple[str, ...], max_tool_calls: int | None): ...
def render(input_file: Path, formats: tuple[str, ...], output_path: Path | None): ...
def recover(input_file: Path): ...
