from __future__ import annotations

from click.core import Context

COMMUNITY_OWNER_EMAIL: str
USER_EMAIL: str
HELP_MSG_USER: str
ADMIN_EMAIL: str

def rdm_records() -> None: ...
def demo(ctx: Context) -> None: ...
def records(user_email: str, n_records: int) -> None: ...
def oai_sets(user_email: str, n_records: int) -> None: ...
def drafts(user_email: str, n_drafts: int) -> None: ...
def communities(user_email: str, n_communities: int) -> None: ...
def inclusion_requests(user_email: str, n_requests: int) -> None: ...
def invitation_requests(user_email: str, n_requests: int) -> None: ...
def create_fixtures() -> None: ...
def add_to_fixture(fixture: str) -> None: ...
def rebuild_index() -> None: ...
def custom_fields() -> None: ...
def create_records_custom_field(field_name: tuple[str, ...] | None) -> None: ...
def custom_field_exists_in_records(field_name: str) -> None: ...
