from __future__ import annotations

from collections.abc import Callable, Mapping
from datetime import timedelta
from typing import Any

from invenio_rdm_records.services.permissions import RDMRecordPermissionPolicy
from invenio_rdm_records.services.pids.providers.base import PIDProvider

Validator = Callable[[str], bool]

RDM_RECORDS_USER_FIXTURE_PASSWORDS: dict[str, str | None]
RDM_RECORDS_UI_EDIT_URL: str
RDM_ARCHIVE_DOWNLOAD_ENABLED: bool
THEME_SITEURL: str

def always_valid(identifier: str) -> bool: ...

RDM_RECORDS_PERSONORG_SCHEMES: dict[str, Mapping[str, str | Validator]]
RDM_RECORDS_IDENTIFIERS_SCHEMES: dict[str, Mapping[str, str | Validator]]
RDM_RECORDS_LOCATION_SCHEMES: dict[str, Mapping[str, str | Validator]]

RDM_PERMISSION_POLICY: type[RDMRecordPermissionPolicy]

RDM_RECORDS_REVIEWS: list[str]
RDM_COMMUNITY_SUBMISSION_REQUEST_CLS: type

RDM_ALLOW_METADATA_ONLY_RECORDS: bool
RDM_DEFAULT_FILES_ENABLED: bool
RDM_ALLOW_RESTRICTED_RECORDS: bool

RDM_COMMUNITY_REQUIRED_TO_PUBLISH: bool
RDM_COMMUNITY_INCLUSION_REQUEST_CLS: type

RDM_FACETS: dict[str, dict[str, Any]]
RDM_SEARCH_SORT_BY_VERIFIED: bool
RDM_SORT_OPTIONS: dict[str, dict[str, Any]]
RDM_SEARCH: dict[str, Any]
RDM_SEARCH_DRAFTS: dict[str, Any]
RDM_SEARCH_VERSIONING: dict[str, Any]

RDM_OAI_PMH_FACETS: dict[str, Any]
RDM_OAI_PMH_SORT_OPTIONS: dict[str, dict[str, Any]]
RDM_OAI_PMH_SEARCH: dict[str, Any]

RDM_PERSISTENT_IDENTIFIER_PROVIDERS: list[PIDProvider]
RDM_PERSISTENT_IDENTIFIERS: dict[str, dict[str, Any]]
RDM_PARENT_PERSISTENT_IDENTIFIER_PROVIDERS: list[PIDProvider]
RDM_PARENT_PERSISTENT_IDENTIFIERS: dict[str, dict[str, Any]]
RDM_ALLOW_EXTERNAL_DOI_VERSIONING: bool

RDM_OPTIONAL_DOI_VALIDATOR: Callable[..., None]

DATACITE_ENABLED: bool
DATACITE_USERNAME: str
DATACITE_PASSWORD: str
DATACITE_PREFIX: str
DATACITE_TEST_MODE: bool
DATACITE_FORMAT: str | Callable[..., str]
DATACITE_DATACENTER_SYMBOL: str

RDM_NAMESPACES: dict[str, str]
RDM_CUSTOM_FIELDS: list[Any]
RDM_CUSTOM_FIELDS_UI: list[Any]

RDM_RESOURCE_ACCESS_TOKENS_ENABLED: bool
RDM_RESOURCE_ACCESS_TOKENS_JWT_LIFETIME: timedelta
RDM_RESOURCE_ACCESS_TOKENS_WHITELISTED_JWT_ALGORITHMS: list[str]
RDM_RESOURCE_ACCESS_TOKEN_REQUEST_ARG: str
RDM_RESOURCE_ACCESS_TOKENS_SUBJECT_SCHEMA: type

RDM_LOCK_EDIT_PUBLISHED_FILES: Callable[..., None]

RDM_CONTENT_MODERATION_HANDLERS: list[Any]
RDM_COMMUNITY_CONTENT_MODERATION_HANDLERS: list[Any]
RDM_USER_MODERATION_ENABLED: bool

RDM_RECORDS_MAX_FILES_COUNT: int
RDM_RECORDS_MAX_MEDIA_FILES_COUNT: int
RDM_MEDIA_FILES_DEFAULT_QUOTA_SIZE: int
RDM_MEDIA_FILES_DEFAULT_MAX_FILE_SIZE: int

RDM_FILES_DEFAULT_QUOTA_SIZE: int | None
RDM_FILES_DEFAULT_MAX_FILE_SIZE: int | None

RDM_DATACITE_FUNDER_IDENTIFIERS_PRIORITY: tuple[str, ...]
RDM_DATACITE_DUMP_OPENAIRE_ACCESS_RIGHTS: bool

RDM_IIIF_MANIFEST_FORMATS: list[str]

IIIF_TILES_GENERATION_ENABLED: bool
IIIF_TILES_VALID_EXTENSIONS: list[str]
IIIF_TILES_STORAGE_BASE_PATH: str
IIIF_TILES_CONVERTER_PARAMS: dict[str, int | str]

RDM_RECORDS_RESTRICTION_GRACE_PERIOD: timedelta
RDM_RECORDS_ALLOW_RESTRICTION_AFTER_GRACE_PERIOD: bool
