from __future__ import annotations

from typing import Any

from flask_principal import Identity

def get_or_create_user(email: str) -> Any: ...

class ChainObject:
    def __init__(self, *objs: Any, aliases: dict[str, Any] | None = ...) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default: Any | None = ...) -> Any | None: ...

def verify_token(identity: Identity) -> None: ...
