from typing import Dict

from invenio_records_resources.services.custom_fields.base import BaseListCF

class DoubleCF(BaseListCF):
    def __init__(self, name: str, **kwargs): ...
    @property
    def mapping(self) -> Dict[str, str]: ...

class IntegerCF(BaseListCF):
    def __init__(self, name: str, **kwargs): ...
    @property
    def mapping(self) -> Dict[str, str]: ...
