
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-12-31T11:29:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2de84243ae4d1f2d958921ef1f1ec598279b926f",
 "version": "0.0.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
