from typing import Any

__all__ = ['CancellationContext']

class CancellationContext:
    def __init__(self, client: Any, config: Any = None) -> None: ...
    @property
    def is_cancel_requested(self) -> bool: ...
    @property
    def response_id(self) -> str | None: ...
    def register_response(self, response_id: str) -> None: ...
    def request_cancel(self) -> None: ...
    def install_signal_handler(self) -> None: ...
    def restore_signal_handler(self) -> None: ...
