from typing import Any, Dict, Optional

from flask.app import Flask

class _RecordsState:
    def __init__(self, app: Flask, entry_point_group: Optional[str] = ...) -> None: ...
    def validate(self, data: Dict[str, Any], schema: Any, **kwargs: Any) -> None: ...
    def replace_refs(self, data: Any) -> Any: ...

class InvenioRecords:
    def __init__(self, app: Optional[Flask] = ..., **kwargs: Any) -> None: ...
    def init_app(
        self, app: Flask, entry_point_group: str = ..., **kwargs: Any
    ) -> _RecordsState: ...
    def init_config(self, app: Flask) -> None: ...
