from typing import Tuple

from invenio_records_resources.records.api import FileRecord
from invenio_records_resources.services.files.processors.base import FileProcessor

class ImageMetadataExtractor(FileProcessor):
    def can_process(self, file_record: FileRecord) -> bool: ...
    def _process_wand(self, file_record: FileRecord) -> Tuple[int, int]: ...
    def _process_vips(self, file_record: FileRecord) -> Tuple[int, int]: ...
    def process(self, file_record: FileRecord) -> None: ...
