from .progress import ResearchProgress
from _typeshed import Incomplete
from dataclasses import dataclass, field
from typing import Callable

__all__ = ['ResearchConfig', '_default_deep_research_model']

@dataclass
class ResearchConfig:
    deep_research_model: str = field(default_factory=Incomplete)
    prompt_refiner_model: str = field(default_factory=Incomplete)
    use_prompt_refinement: bool = ...
    background: bool = ...
    polling_interval_seconds: float = field(default_factory=Incomplete)
    max_poll_time_minutes: float = field(default_factory=Incomplete)
    enable_code_interpreter: bool = ...
    use_web_search: bool = ...
    max_tool_calls: int | None = ...
    request_timeout_seconds: int = ...
    progress_callback: Callable[[ResearchProgress], None] | None = ...

def _default_deep_research_model() -> str: ...
