from .config import ResearchConfig
from promptdown import StructuredPrompt
from typing import Any

__all__ = ['compose_deep_research_prompt', 'default_research_plan', 'generate_research_plan', 'load_prompt_template']

def generate_research_plan(client: Any, topic: str, config: ResearchConfig) -> dict[str, Any] | None: ...
def default_research_plan(topic: str) -> dict[str, Any]: ...
def compose_deep_research_prompt(topic: str, plan: dict[str, Any]) -> Any: ...
def load_prompt_template(filename: str) -> StructuredPrompt: ...
