# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: domains/envelope/v1.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'domains/envelope/v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from materi_proto.shared import v1_pb2 as shared_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64omains/envelope/v1.proto\x12\x12materi.v1.envelope\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0fshared/v1.proto\"\xd2\x03\n\x0b\x44omainEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x14\n\x0c\x61ggregate_id\x18\x03 \x01(\t\x12\x16\n\x0e\x61ggregate_type\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\x03\x12(\n\x07payload\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12)\n\x08metadata\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12/\n\x0boccurred_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0cpublished_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0esource_service\x18\n \x01(\t\x12\x0f\n\x07user_id\x18\x0b \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x0c \x01(\t\x12\x10\n\x08trace_id\x18\r \x01(\t\x12\x0f\n\x07span_id\x18\x0e \x01(\t\x12\x16\n\x0eparent_span_id\x18\x0f \x01(\t\x12\x15\n\rhlc_timestamp\x18\x10 \x01(\x03\x12\x13\n\x0bhlc_counter\x18\x11 \x01(\x05\"\x9b\x01\n\x13\x45ventAcknowledgment\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x18\n\x10\x63onsumer_service\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x30\n\x0cprocessed_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB3Z1github.com/materi/domain/proto/materi/v1/envelopeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'domains.envelope.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/materi/domain/proto/materi/v1/envelope'
  _globals['_DOMAINEVENT']._serialized_start=130
  _globals['_DOMAINEVENT']._serialized_end=596
  _globals['_EVENTACKNOWLEDGMENT']._serialized_start=599
  _globals['_EVENTACKNOWLEDGMENT']._serialized_end=754
# @@protoc_insertion_point(module_scope)
