# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class TmuxClientInternalTypesPlanStatus(str, Enum):
    """
    TmuxClientInternalTypesPlanStatus
    """

    """
    allowed enum values
    """
    PlanStatusPending = "pending"
    PlanStatusInProgress = "in_progress"
    PlanStatusCompleted = "completed"
    PlanStatusFailed = "failed"
    PlanStatusAborted = "aborted"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TmuxClientInternalTypesPlanStatus from a JSON string"""
        return cls(json.loads(json_str))
