<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="3.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:jp="http://www.jpo.go.jp">

    <!-- this xslt was created with reference to pat_common.xsl
         of Internet Application Software version i5.30 provided by JPO -->

    <!-- ====================================================================
         original: 国名県名変換
            INPUT: country-code (value-of jp:country) e.g. "01", "JP", "US"
            OUTPUT: e.g. "北海道", "日本", "アメリカ合衆国"
         ====================================================================-->
    <xsl:template name="convert-country">
        <xsl:param name="country-code" as="xs:string" />
        <xsl:value-of select="key('countries-table-key', $country-code, $countries-table)/@value" />
    </xsl:template>

    <xsl:key name="countries-table-key" match="item" use="@key" />
    <xsl:variable name="countries-table">
        <item key="00" value="住所無し" />
        <item key="01" value="北海道" />
        <item key="02" value="青森県" />
        <item key="03" value="岩手県" />
        <item key="04" value="宮城県" />
        <item key="05" value="秋田県" />
        <item key="06" value="山形県" />
        <item key="07" value="福島県" />
        <item key="08" value="茨城県" />
        <item key="09" value="栃木県" />
        <item key="10" value="群馬県" />
        <item key="11" value="埼玉県" />
        <item key="12" value="千葉県" />
        <item key="13" value="東京都" />
        <item key="14" value="神奈川県" />
        <item key="15" value="新潟県" />
        <item key="16" value="富山県" />
        <item key="17" value="石川県" />
        <item key="18" value="福井県" />
        <item key="19" value="山梨県" />
        <item key="20" value="長野県" />
        <item key="21" value="岐阜県" />
        <item key="22" value="静岡県" />
        <item key="23" value="愛知県" />
        <item key="24" value="三重県" />
        <item key="25" value="滋賀県" />
        <item key="26" value="京都府" />
        <item key="27" value="大阪府" />
        <item key="28" value="兵庫県" />
        <item key="29" value="奈良県" />
        <item key="30" value="和歌山県" />
        <item key="31" value="鳥取県" />
        <item key="32" value="島根県" />
        <item key="33" value="岡山県" />
        <item key="34" value="広島県" />
        <item key="35" value="山口県" />
        <item key="36" value="徳島県" />
        <item key="37" value="香川県" />
        <item key="38" value="愛媛県" />
        <item key="39" value="高知県" />
        <item key="40" value="福岡県" />
        <item key="41" value="佐賀県" />
        <item key="42" value="長崎県" />
        <item key="43" value="熊本県" />
        <item key="44" value="大分県" />
        <item key="45" value="宮崎県" />
        <item key="46" value="鹿児島県" />
        <item key="47" value="沖縄県" />
        <item key="JP" value="日本" />
        <item key="AD" value="アンドラ" />
        <item key="AE" value="アラブ首長国連邦" />
        <item key="AF" value="アフガニスタン" />
        <item key="AG" value="アンティグア・バーブーダ" />
        <item key="AI" value="アンギラ" />
        <item key="AL" value="アルバニア" />
        <item key="AM" value="アルメニア" />
        <item key="AO" value="アンゴラ" />
        <item key="AP" value="アフリカ地域工業所有権機関" />
        <item key="AR" value="アルゼンチン" />
        <item key="AT" value="オーストリア" />
        <item key="AU" value="オーストラリア" />
        <item key="AW" value="アルバ島" />
        <item key="AZ" value="アゼルバイジャン" />
        <item key="BA" value="ボスニア・ヘルツェゴビナ" />
        <item key="BB" value="バルバドス" />
        <item key="BD" value="バングラデシュ" />
        <item key="BE" value="ベルギー" />
        <item key="BF" value="ブルキナファソ" />
        <item key="BG" value="ブルガリア" />
        <item key="BH" value="バーレーン" />
        <item key="BI" value="ブルンジ" />
        <item key="BJ" value="ベナン" />
        <item key="BM" value="バーミューダ" />
        <item key="BN" value="ブルネイ" />
        <item key="BO" value="ボリビア" />
        <item key="BQ" value="ボネール島、シント・ユースタティウス島、サバ島" />
        <item key="BR" value="ブラジル" />
        <item key="BS" value="バハマ" />
        <item key="BT" value="ブータン" />
        <item key="BU" value="ビルマ" />
        <item key="BW" value="ボツワナ" />
        <item key="BX" value="ベネルクス商標庁及びベネルクス意匠庁" />
        <item key="BY" value="ベラルーシ" />
        <item key="BZ" value="ベリーズ" />
        <item key="CA" value="カナダ" />
        <item key="CD" value="コンゴ民主共和国" />
        <item key="CF" value="中央アフリカ" />
        <item key="CG" value="コンゴ共和国" />
        <item key="CH" value="スイス" />
        <item key="CI" value="コートジボワール" />
        <item key="CK" value="クック諸島" />
        <item key="CL" value="チリ" />
        <item key="CM" value="カメルーン" />
        <item key="CN" value="中華人民共和国" />
        <item key="CO" value="コロンビア" />
        <item key="CR" value="コスタリカ" />
        <item key="CS" value="チェッコ・スロヴァキア" />
        <item key="CU" value="キューバ" />
        <item key="CV" value="カーボヴェルデ" />
        <item key="CW" value="キュラソー島" />
        <item key="CY" value="キプロス" />
        <item key="CZ" value="チェコ" />
        <item key="DD" value="ドイツ民主共和国" />
        <item key="DE" value="ドイツ" />
        <item key="DJ" value="ジブチ" />
        <item key="DK" value="デンマーク" />
        <item key="DM" value="ドミニカ" />
        <item key="DO" value="ドミニカ共和国" />
        <item key="DZ" value="アルジェリア" />
        <item key="EA" value="ユーラシア特許庁" />
        <item key="EC" value="エクアドル" />
        <item key="EE" value="エストニア" />
        <item key="EG" value="エジプト" />
        <item key="EM" value="欧州連合知的財産庁" />
        <item key="EP" value="欧州特許庁" />
        <item key="ER" value="エリトリア" />
        <item key="ES" value="スペイン" />
        <item key="ET" value="エチオピア" />
        <item key="FI" value="フィンランド" />
        <item key="FJ" value="フィジー" />
        <item key="FK" value="フォークランド諸島" />
        <item key="FO" value="フェロー諸島" />
        <item key="FR" value="フランス" />
        <item key="GA" value="ガボン" />
        <item key="GB" value="英国" />
        <item key="GC" value="湾岸協力理事会特許庁" />
        <item key="GD" value="グレナダ" />
        <item key="GE" value="ジョージア" />
        <item key="GG" value="ガーンジー島" />
        <item key="GH" value="ガーナ" />
        <item key="GI" value="ジブラルタル" />
        <item key="GM" value="ガンビア" />
        <item key="GN" value="ギニア" />
        <item key="GQ" value="赤道ギニア" />
        <item key="GR" value="ギリシャ" />
        <item key="GT" value="グアテマラ" />
        <item key="GW" value="ギニアビサウ" />
        <item key="GY" value="ガイアナ" />
        <item key="HK" value="香港" />
        <item key="HN" value="ホンジュラス" />
        <item key="HR" value="クロアチア" />
        <item key="HT" value="ハイチ" />
        <item key="HU" value="ハンガリー" />
        <item key="HV" value="上ヴォルタ共和国" />
        <item key="IB" value="国際事務局" />
        <item key="ID" value="インドネシア" />
        <item key="IE" value="アイルランド" />
        <item key="IL" value="イスラエル" />
        <item key="IM" value="マン島" />
        <item key="IN" value="インド" />
        <item key="IQ" value="イラク" />
        <item key="IR" value="イラン" />
        <item key="IS" value="アイスランド" />
        <item key="IT" value="イタリア" />
        <item key="JE" value="ジャージー島" />
        <item key="JM" value="ジャマイカ" />
        <item key="JO" value="ヨルダン" />
        <item key="KE" value="ケニア" />
        <item key="KG" value="キルギス" />
        <item key="KH" value="カンボジア" />
        <item key="KI" value="キリバス" />
        <item key="KM" value="コモロ" />
        <item key="KN" value="セントクリストファー・ネーヴィス" />
        <item key="KP" value="北朝鮮" />
        <item key="KR" value="大韓民国" />
        <item key="KW" value="クウェート" />
        <item key="KY" value="ケイマン諸島" />
        <item key="KZ" value="カザフスタン" />
        <item key="LA" value="ラオス" />
        <item key="LB" value="レバノン" />
        <item key="LC" value="セントルシア" />
        <item key="LI" value="リヒテンシュタイン" />
        <item key="LK" value="スリランカ" />
        <item key="LR" value="リベリア" />
        <item key="LS" value="レソト" />
        <item key="LT" value="リトアニア" />
        <item key="LU" value="ルクセンブルク" />
        <item key="LV" value="ラトビア" />
        <item key="LY" value="リビア" />
        <item key="MA" value="モロッコ" />
        <item key="MC" value="モナコ" />
        <item key="MD" value="モルドバ" />
        <item key="MG" value="マダガスカル" />
        <item key="MK" value="北マケドニア共和国" />
        <item key="ML" value="マリ" />
        <item key="MM" value="ミャンマー" />
        <item key="MN" value="モンゴル" />
        <item key="MO" value="マカオ" />
        <item key="MR" value="モーリタニア" />
        <item key="MS" value="モンセラット" />
        <item key="MT" value="マルタ" />
        <item key="MU" value="モーリシャス" />
        <item key="MV" value="モルディブ" />
        <item key="MW" value="マラウイ" />
        <item key="MX" value="メキシコ" />
        <item key="MY" value="マレーシア" />
        <item key="MZ" value="モザンビーク" />
        <item key="ME" value="モンテネグロ" />
        <item key="NA" value="ナミビア" />
        <item key="NE" value="ニジェール" />
        <item key="NG" value="ナイジェリア" />
        <item key="NI" value="ニカラグア" />
        <item key="NL" value="オランダ" />
        <item key="NO" value="ノルウェー" />
        <item key="NP" value="ネパール" />
        <item key="NR" value="ナウル" />
        <item key="NU" value="ニウエ" />
        <item key="NZ" value="ニュージーランド" />
        <item key="OA" value="アフリカ知的所有権機関" />
        <item key="OM" value="オマーン" />
        <item key="PA" value="パナマ" />
        <item key="PE" value="ペルー" />
        <item key="PG" value="パプアニューギニア" />
        <item key="PH" value="フィリピン" />
        <item key="PK" value="パキスタン" />
        <item key="PL" value="ポーランド" />
        <item key="PR" value="プエルトリコ" />
        <item key="PT" value="ポルトガル" />
        <item key="PW" value="パラオ" />
        <item key="PY" value="パラグアイ" />
        <item key="QA" value="カタール" />
        <item key="RH" value="南ローデシア" />
        <item key="RO" value="ルーマニア" />
        <item key="RU" value="ロシア" />
        <item key="RW" value="ルワンダ" />
        <item key="RS" value="セルビア" />
        <item key="SA" value="サウジアラビア" />
        <item key="SB" value="ソロモン" />
        <item key="SC" value="セーシェル" />
        <item key="SD" value="スーダン" />
        <item key="SE" value="スウェーデン" />
        <item key="SG" value="シンガポール" />
        <item key="SH" value="セントヘレナ島" />
        <item key="SI" value="スロベニア" />
        <item key="SK" value="スロバキア" />
        <item key="SL" value="シエラレオネ" />
        <item key="SM" value="サンマリノ" />
        <item key="SN" value="セネガル" />
        <item key="SO" value="ソマリア" />
        <item key="SR" value="スリナム" />
        <item key="ST" value="サントメ・プリンシペ" />
        <item key="SU" value="ソヴィエト連邦" />
        <item key="SV" value="エルサルバドル" />
        <item key="SX" value="シント・マールテン島" />
        <item key="SY" value="シリア" />
        <item key="SZ" value="エスワティニ" />
        <item key="TD" value="チャド" />
        <item key="TG" value="トーゴ" />
        <item key="TH" value="タイ" />
        <item key="TJ" value="タジキスタン" />
        <item key="TK" value="トケラウ諸島" />
        <item key="TL" value="東ティモール" />
        <item key="TM" value="トルクメニスタン" />
        <item key="TN" value="チュニジア" />
        <item key="TO" value="トンガ" />
        <item key="TR" value="トルコ" />
        <item key="TT" value="トリニダード・トバゴ" />
        <item key="TV" value="ツバル" />
        <item key="TW" value="台湾" />
        <item key="TZ" value="タンザニア" />
        <item key="UA" value="ウクライナ" />
        <item key="UG" value="ウガンダ" />
        <item key="US" value="アメリカ合衆国" />
        <item key="UY" value="ウルグアイ" />
        <item key="UZ" value="ウズベキスタン" />
        <item key="VA" value="バチカン" />
        <item key="VC" value="セントビンセント" />
        <item key="VE" value="ベネズエラ" />
        <item key="VG" value="ヴァージン諸島" />
        <item key="VN" value="ベトナム" />
        <item key="VU" value="バヌアツ" />
        <item key="WO" value="世界知的所有権機関" />
        <item key="WS" value="サモア" />
        <item key="XX" value="無国籍、その他の国名及び地域名" />
        <item key="YD" value="南イエメン" />
        <item key="YE" value="イエメン" />
        <item key="YU" value="セルビア・モンテネグロ" />
        <item key="ZA" value="南アフリカ" />
        <item key="ZM" value="ザンビア" />
        <item key="ZR" value="ザイール" />
        <item key="ZW" value="ジンバブエ" />
        <item key="99" value="９９" />
    </xsl:variable>

</xsl:stylesheet>