from typing import Any

from invenio_records_permissions.generators import Generator
from invenio_records_permissions.policies.records import RecordPermissionPolicy
from invenio_requests.services.permissions import (
    PermissionPolicy as RequestPermissionPolicy,
)

class RDMRecordPermissionPolicy(RecordPermissionPolicy):
    NEED_LABEL_TO_ACTION: dict[str, str]
    # NOTE: tuples keep the base defaults immutable while subclasses may
    # override them with their own generator tuples.
    can_manage_internal: tuple[Generator, ...]
    can_manage: tuple[Generator, ...]
    can_curate: tuple[Generator, ...]
    can_review: tuple[Generator, ...]
    can_preview: tuple[Generator, ...]
    can_view: tuple[Generator, ...]
    can_authenticated: tuple[Generator, ...]
    can_all: tuple[Generator, ...]
    can_query_stats: tuple[Generator, ...]
    can_search: tuple[Generator, ...]
    can_read: tuple[Generator, ...]
    can_read_deleted: tuple[Generator, ...]
    can_read_deleted_files: tuple[Generator, ...]
    can_media_read_deleted_files: tuple[Generator, ...]
    can_read_files: tuple[Generator, ...]
    can_get_content_files: tuple[Generator, ...]
    can_create: tuple[Generator, ...]
    can_search_revisions: tuple[Generator, ...]
    can_search_drafts: tuple[Generator, ...]
    can_read_draft: tuple[Generator, ...]
    can_draft_read_files: tuple[Generator, ...]
    can_update_draft: tuple[Generator, ...]
    can_draft_create_files: tuple[Generator, ...]
    can_draft_set_content_files: tuple[Generator, ...]
    can_draft_get_content_files: tuple[Generator, ...]
    can_draft_commit_files: tuple[Generator, ...]
    can_draft_update_files: tuple[Generator, ...]
    can_draft_delete_files: tuple[Generator, ...]
    can_draft_get_file_transfer_metadata: tuple[Generator, ...]
    can_draft_update_file_transfer_metadata: tuple[Generator, ...]
    can_manage_files: tuple[Generator, ...]
    can_manage_record_access: tuple[Generator, ...]
    can_pid_create: tuple[Generator, ...]
    can_pid_register: tuple[Generator, ...]
    can_pid_update: tuple[Generator, ...]
    can_pid_discard: tuple[Generator, ...]
    can_pid_delete: tuple[Generator, ...]
    can_pid_manage: tuple[Generator, ...]
    can_edit: tuple[Generator, ...]
    can_delete_draft: tuple[Generator, ...]
    can_new_version: tuple[Generator, ...]
    can_publish: tuple[Generator, ...]
    can_lift_embargo: tuple[Generator, ...]
    can_add_community: tuple[Generator, ...]
    can_remove_community_: tuple[Generator, ...]
    can_remove_community: tuple[Generator, ...]
    can_remove_record: tuple[Generator, ...]
    can_bulk_add: tuple[Generator, ...]
    can_draft_media_create_files: tuple[Generator, ...]
    can_draft_media_read_files: tuple[Generator, ...]
    can_draft_media_set_content_files: tuple[Generator, ...]
    can_draft_media_get_content_files: tuple[Generator, ...]
    can_draft_media_commit_files: tuple[Generator, ...]
    can_draft_media_update_files: tuple[Generator, ...]
    can_draft_media_delete_files: tuple[Generator, ...]
    can_media_read_files: tuple[Generator, ...]
    can_media_get_content_files: tuple[Generator, ...]
    can_media_create_files: tuple[Generator, ...]
    can_media_set_content_files: tuple[Generator, ...]
    can_media_commit_files: tuple[Generator, ...]
    can_media_update_files: tuple[Generator, ...]
    can_media_delete_files: tuple[Generator, ...]
    can_delete: tuple[Generator, ...]
    can_delete_files: tuple[Generator, ...]
    can_purge: tuple[Generator, ...]
    can_manage_quota: tuple[Generator, ...]
    can_update: tuple[Generator, ...]
    can_create_files: tuple[Generator, ...]
    can_set_content_files: tuple[Generator, ...]
    can_commit_files: tuple[Generator, ...]
    can_update_files: tuple[Generator, ...]
    can_get_file_transfer_metadata: tuple[Generator, ...]
    can_update_file_transfer_metadata: tuple[Generator, ...]
    can_moderate: tuple[Generator, ...]

guest_token: Any

class RDMRequestsPermissionPolicy(RequestPermissionPolicy):
    # NOTE: tuples make the defaults immutable while supporting subclass
    # overrides with custom generator tuples.
    can_read: tuple[Generator, ...]
    can_update: tuple[Generator, ...]
    can_action_submit: tuple[Generator, ...]
    can_action_cancel: tuple[Generator, ...]
    can_create_comment: tuple[Generator, ...]
    can_update_comment: tuple[Generator, ...]
    can_delete_comment: tuple[Generator, ...]
    can_manage_access_options: tuple[Generator, ...]
