# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from openapi_client.models.bank_dtls import BankDtls
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ClientDetailsData(BaseModel):
    """
    ClientDetailsData
    """ # noqa: E501
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    user_name: Optional[StrictStr] = Field(default=None, alias="userName")
    mobile: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    pan: Optional[StrictStr] = None
    dp_id: Optional[StrictStr] = Field(default=None, alias="dpId")
    bank_details: Optional[List[BankDtls]] = Field(default=None, alias="bankDetails")
    dp_ids: Optional[List[StrictStr]] = Field(default=None, alias="dpIds")
    products: Optional[List[StrictStr]] = None
    segments: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["userId", "userName", "mobile", "email", "pan", "dpId", "bankDetails", "dpIds", "products", "segments"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ClientDetailsData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bank_details (list)
        _items = []
        if self.bank_details:
            for _item in self.bank_details:
                if _item:
                    _items.append(_item.to_dict())
            _dict['bankDetails'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ClientDetailsData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "userId": obj.get("userId"),
            "userName": obj.get("userName"),
            "mobile": obj.get("mobile"),
            "email": obj.get("email"),
            "pan": obj.get("pan"),
            "dpId": obj.get("dpId"),
            "bankDetails": [BankDtls.from_dict(_item) for _item in obj.get("bankDetails")] if obj.get("bankDetails") is not None else None,
            "dpIds": obj.get("dpIds"),
            "products": obj.get("products"),
            "segments": obj.get("segments")
        })
        return _obj


