GITHUB_API_BASE_URL = "https://api.github.com"
GITHUB_API_VERSION = "2022-11-28"

GITHUB_RATE_LIMIT = 5000
GITHUB_RATE_LIMIT_UNAUTHENTICATED = 60
DEFAULT_TIMEOUT = 30.0
MAX_RETRIES = 3

DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
