from invenio_records_resources.services.records.components import ServiceComponent
from invenio_vocabularies.records.models import VocabularyType as VocabularyType

class VocabularyTypeComponent(ServiceComponent): ...
class PIDComponent(ServiceComponent): ...
class ModelPIDComponent(PIDComponent): ...
