class Pagination:
    size: int
    page: int
    max_results: int

    def __init__(self, size: int, page: int, max_results: int) -> None: ...
    @property
    def from_idx(self) -> int: ...
    @property
    def has_next(self) -> bool: ...
    @property
    def has_prev(self) -> bool: ...
    @property
    def next_page(self) -> Pagination | None: ...
    @property
    def prev_page(self) -> Pagination | None: ...
    @property
    def to_idx(self) -> int: ...
    def valid(self) -> bool: ...
