from typing import Any

class OAIPMHError(Exception):
    description: str
    def __init__(self, description: str, *args: Any) -> None: ...

class OAIPMHSetDoesNotExistError(OAIPMHError): ...
class OAIPMHSetIDDoesNotExistError(OAIPMHError): ...
class OAIPMHSetSpecAlreadyExistsError(OAIPMHError): ...
class OAIPMHSetNotEditable(OAIPMHError): ...
