from __future__ import annotations

from typing import Any

from flask import Blueprint, Flask

blueprint: Blueprint

def create_records_bp(app: Flask) -> Any: ...
def create_record_files_bp(app: Flask) -> Any: ...
def create_draft_files_bp(app: Flask) -> Any: ...
def create_record_media_files_bp(app: Flask) -> Any: ...
def create_draft_media_files_bp(app: Flask) -> Any: ...
def create_parent_record_links_bp(app: Flask) -> Any: ...
def create_parent_grants_bp(app: Flask) -> Any: ...
def create_grant_user_access_bp(app: Flask) -> Any: ...
def create_grant_group_access_bp(app: Flask) -> Any: ...
def create_pid_resolver_resource_bp(app: Flask) -> Any: ...
def create_community_records_bp(app: Flask) -> Any: ...
def create_record_communities_bp(app: Flask) -> Any: ...
def create_record_requests_bp(app: Flask) -> Any: ...
def create_oaipmh_server_blueprint_from_app(app: Flask) -> Any: ...
def create_iiif_bp(app: Flask) -> Any: ...
def file_transfer_type() -> dict[str, Any]: ...
