class IncorrectApiUsageError(Exception): ...
class UrlError(Exception): ...
class PostgresError(Exception): ...
class ConnectionClosedError(Exception): ...
class TransactionClosedError(Exception): ...
class DecodeError(Exception): ...
class PoisonError(Exception): ...
class PythonObjectCreationError(Exception): ...
