import cr_mech_coli as crm
from pathlib import Path

class MultilayerConfig:
    agent_settings: crm.AgentSettings
    config: crm.Configuration
    rng_seed: int
    dx: tuple[float, float]
    randomize_positions: float
    n_vertices: int

    def clone_with_args(self, **kwargs) -> MultilayerConfig: ...
    @staticmethod
    def __new__(cls, **kwargs) -> MultilayerConfig: ...
    @staticmethod
    def load_from_toml_file(path: Path) -> MultilayerConfig: ...
    @staticmethod
    def load_from_toml_str(input: str) -> MultilayerConfig: ...
    def to_toml_file(self, filepath: Path): ...
    def to_toml_string(self) -> str: ...
    def approx_eq(self, other) -> bool: ...
