from ._sdl.sdlmixer import Mix_Music, Mix_Chunk

__all__ = ["Sound", "Music"]

class Sound:
    _path: str
    sound:Mix_Chunk|None
    _channel: int
    _volume: int
    _load_type: int

    def __init__(self, path: str, preload: bool = True): ...

    def _threading_load(self, path: str | None): ...

    def _load(self, path: str | None): ...

    def load(self, path: str | None = None): ...

    def play(self, loops: int = -1): ...

    def pause(self): ...

    def resume(self): ...

    @property
    def volume(self) -> int: ...

    @volume.setter
    def volume(self, volume: int): ...

class Music:
    music: Mix_Music
    _volume: int

    def __init__(self, path: str): ...

    def play(self, loops: int = -1): ...

    def pause(self): ...

    def resume(self): ...

    @property
    def position(self) -> int: ...

    @position.setter
    def position(self, position: int): ...

    @property
    def volume(self) -> int: ...

    @volume.setter
    def volume(self, volume: int): ...
