from typing import Any

__all__ = ["Time", "fps_to_time", "get_fps_from_time"]

class Time:
    def __init__(self, delta_time: float) -> None: ...
    @property
    def delta_time(self) -> float: ...
    @delta_time.setter
    def delta_time(self, delta_time: float) -> None: ...
    @property
    def flipflop(self) -> bool: ...
    @flipflop.setter
    def flipflop(self, b: bool) -> None: ...
    def restart(self) -> None: ...
    def tick(self, restart: bool = False) -> bool: ...
    def tickSleep(self) -> None: ...
    def tickMotion(self) -> float: ...
    def tickFlipFlop(self) -> bool: ...
    def last_elapsed(self) -> float: ...

def fps_to_time(target_fps: float) -> float: ...
def get_fps_from_time(object_time: Time) -> int: ...
