# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kody_clientsdk_python.ordering.v1 import inventory_pb2 as com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in com/kodypay/grpc/ordering/v1/inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInventory = channel.unary_unary(
                '/com.kodypay.grpc.ordering.v1.InventoryService/GetInventory',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetInventoryRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetInventoryResponse.FromString,
                _registered_method=True)
        self.GetCategories = channel.unary_unary(
                '/com.kodypay.grpc.ordering.v1.InventoryService/GetCategories',
                request_serializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetCategoriesRequest.SerializeToString,
                response_deserializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetCategoriesResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInventory(self, request, context):
        """Retrieve full inventory or items filtered by category
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategories(self, request, context):
        """Retrieve all categories for a store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventory,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetInventoryRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetInventoryResponse.SerializeToString,
            ),
            'GetCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategories,
                    request_deserializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetCategoriesRequest.FromString,
                    response_serializer=com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetCategoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.kodypay.grpc.ordering.v1.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.kodypay.grpc.ordering.v1.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.kodypay.grpc.ordering.v1.InventoryService/GetInventory',
            com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetInventoryRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetInventoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.kodypay.grpc.ordering.v1.InventoryService/GetCategories',
            com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetCategoriesRequest.SerializeToString,
            com_dot_kodypay_dot_grpc_dot_ordering_dot_v1_dot_inventory__pb2.GetCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
