# coding: utf-8

"""
    Chromia Console REST API

    Chromia Console API with Swagger UI

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from de_console_client.models.entity_list_response import EntityListResponse

class TestEntityListResponse(unittest.TestCase):
    """EntityListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityListResponse:
        """Test EntityListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityListResponse`
        """
        model = EntityListResponse()
        if include_optional:
            return EntityListResponse(
                entities = [{"name":"users","fields":[{"name":"name","type":"text","isMutable":true},{"name":"email","type":"text","isMutable":false},{"name":"age","type":"integer","isMutable":false}]},{"name":"products","fields":[{"name":"title","type":"text","isMutable":true},{"name":"price","type":"decimal","isMutable":false},{"name":"stock","type":"integer","isMutable":false}]}]
            )
        else:
            return EntityListResponse(
                entities = [{"name":"users","fields":[{"name":"name","type":"text","isMutable":true},{"name":"email","type":"text","isMutable":false},{"name":"age","type":"integer","isMutable":false}]},{"name":"products","fields":[{"name":"title","type":"text","isMutable":true},{"name":"price","type":"decimal","isMutable":false},{"name":"stock","type":"integer","isMutable":false}]}],
        )
        """

    def testEntityListResponse(self):
        """Test EntityListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
