# coding: utf-8

"""
    Chromia Console REST API

    Chromia Console API with Swagger UI

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from de_console_client.models.error_response import ErrorResponse

class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponse:
        """Test ErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponse`
        """
        model = ErrorResponse()
        if include_optional:
            return ErrorResponse(
                error = {"code":"INTERNAL_ERROR","message":"Internal server error","details":{}},
                timestamp = '2025-12-30T13:08:42.564007Z'
            )
        else:
            return ErrorResponse(
                error = {"code":"INTERNAL_ERROR","message":"Internal server error","details":{}},
                timestamp = '2025-12-30T13:08:42.564007Z',
        )
        """

    def testErrorResponse(self):
        """Test ErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
