# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-12-16
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.models.freelance_jobs_detail import FreelanceJobsDetail

class TestFreelanceJobsDetail(unittest.TestCase):
    """FreelanceJobsDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FreelanceJobsDetail:
        """Test FreelanceJobsDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FreelanceJobsDetail`
        """
        model = FreelanceJobsDetail()
        if include_optional:
            return FreelanceJobsDetail(
                access_and_visibility = esi_genoa_client.models.freelance_jobs_detail_accessandvisibility.FreelanceJobsDetailAccessandvisibility(
                    acl_protected = True, 
                    broadcast_locations = [
                        esi_genoa_client.models.freelance_jobs_detail_broadcastlocations.FreelanceJobsDetailBroadcastlocations(
                            id = 56, 
                            name = '', )
                        ], 
                    restrictions = esi_genoa_client.models.freelance_jobs_detail_restrictions.FreelanceJobsDetailRestrictions(
                        maximum_age = 56, 
                        minimum_age = 56, ), ),
                configuration = esi_genoa_client.models.freelance_jobs_detail_configuration.FreelanceJobsDetailConfiguration(
                    method = '', 
                    parameters = {
                        'key' : null
                        }, 
                    version = 56, ),
                contribution = esi_genoa_client.models.freelance_jobs_detail_contribution.FreelanceJobsDetailContribution(
                    contribution_per_participant_limit = 56, 
                    max_committed_participants = 56, 
                    reward_per_contribution = 1.337, 
                    submission_limit = 56, 
                    submission_multiplier = 1.337, ),
                details = esi_genoa_client.models.freelance_jobs_detail_details.FreelanceJobsDetailDetails(
                    career = 'Unspecified', 
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    creator = esi_genoa_client.models.freelance_jobs_detail_creator.FreelanceJobsDetailCreator(
                        character = esi_genoa_client.models.freelance_jobs_detail_creatorcharacter.FreelanceJobsDetailCreatorcharacter(
                            id = 56, 
                            name = '', ), 
                        corporation = esi_genoa_client.models.freelance_jobs_detail_creatorcorporation.FreelanceJobsDetailCreatorcorporation(
                            id = 56, 
                            name = '', ), ), 
                    description = '', 
                    expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finished = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                id = '',
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                progress = esi_genoa_client.models.freelance_jobs_detail_progress.FreelanceJobsDetailProgress(
                    current = 56, 
                    desired = 56, ),
                reward = esi_genoa_client.models.freelance_jobs_detail_reward.FreelanceJobsDetailReward(
                    initial = 1.337, 
                    remaining = 1.337, ),
                state = 'Unspecified'
            )
        else:
            return FreelanceJobsDetail(
                access_and_visibility = esi_genoa_client.models.freelance_jobs_detail_accessandvisibility.FreelanceJobsDetailAccessandvisibility(
                    acl_protected = True, 
                    broadcast_locations = [
                        esi_genoa_client.models.freelance_jobs_detail_broadcastlocations.FreelanceJobsDetailBroadcastlocations(
                            id = 56, 
                            name = '', )
                        ], 
                    restrictions = esi_genoa_client.models.freelance_jobs_detail_restrictions.FreelanceJobsDetailRestrictions(
                        maximum_age = 56, 
                        minimum_age = 56, ), ),
                configuration = esi_genoa_client.models.freelance_jobs_detail_configuration.FreelanceJobsDetailConfiguration(
                    method = '', 
                    parameters = {
                        'key' : null
                        }, 
                    version = 56, ),
                details = esi_genoa_client.models.freelance_jobs_detail_details.FreelanceJobsDetailDetails(
                    career = 'Unspecified', 
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    creator = esi_genoa_client.models.freelance_jobs_detail_creator.FreelanceJobsDetailCreator(
                        character = esi_genoa_client.models.freelance_jobs_detail_creatorcharacter.FreelanceJobsDetailCreatorcharacter(
                            id = 56, 
                            name = '', ), 
                        corporation = esi_genoa_client.models.freelance_jobs_detail_creatorcorporation.FreelanceJobsDetailCreatorcorporation(
                            id = 56, 
                            name = '', ), ), 
                    description = '', 
                    expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finished = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                id = '',
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                progress = esi_genoa_client.models.freelance_jobs_detail_progress.FreelanceJobsDetailProgress(
                    current = 56, 
                    desired = 56, ),
                state = 'Unspecified',
        )
        """

    def testFreelanceJobsDetail(self):
        """Test FreelanceJobsDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
