# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-12-16
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.api.corporation_projects_api import CorporationProjectsApi


class TestCorporationProjectsApi(unittest.TestCase):
    """CorporationProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorporationProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_get_corporations_projects_contribution(self) -> None:
        """Test case for get_corporations_projects_contribution

        Get your project contribution
        """
        pass

    def test_get_corporations_projects_contributors(self) -> None:
        """Test case for get_corporations_projects_contributors

        List project contributors
        """
        pass

    def test_get_corporations_projects_detail(self) -> None:
        """Test case for get_corporations_projects_detail

        Get project details
        """
        pass

    def test_get_corporations_projects_listing(self) -> None:
        """Test case for get_corporations_projects_listing

        List corporation projects
        """
        pass


if __name__ == '__main__':
    unittest.main()
