from _hashlib import HASH
from typing import BinaryIO

def compute_checksum(
    file_stream: BinaryIO, object_checksum: HASH, part_size: int
) -> bytes | None: ...
def fetch_file(service_id: str, record_id: str, file_key: str) -> None: ...
def recompute_multipart_checksum_task(file_instance_id: str) -> None: ...
