from typing import Any

__all__ = ['collect_response_text', 'decode_json_payload', 'parse_deep_research_response']

def parse_deep_research_response(response: Any) -> dict[str, Any]: ...
def collect_response_text(response: Any) -> str: ...
def decode_json_payload(text: str) -> dict[str, Any]: ...
