# interfaces/env_handler_interface.py
from typing import Protocol, Callable, Optional, Union
from flask import Response

ItemId   = Optional[str]
ItemIdGetter = Optional[Callable[[dict], ItemId]]

class IHttpResponseHandler(Protocol):
    def http_response(self, method, response) -> Response: ...
    def http_handler(self, request, endpoint: str, fn: Callable[[object, str], dict])  -> Response: ...
    def get_http_request(self, request, query_list, url_key, endpoint, item_id: ItemId = Response) -> Response: ...    
    def post_http_request(self, request, body, query_list, url_key, endpoint, item_id: ItemId = None, item_id_getter: ItemIdGetter = None,) -> Response: ...
    def client_get_http_request(self, request, query_list, url_key, endpoint, item_id: ItemId = None) -> dict: ...
    def client_get_amqp_request(self, body, message, query_list, url_key, endpoint, item_id: ItemId = None) -> dict: ...
    def client_post_http_request(self, request, body: Optional[Union[dict, bytes]], query_list, url_key, endpoint, item_id: ItemId = None, item_id_getter: ItemIdGetter = None,) -> dict: ...
    def client_post_amqp_request(self, body, message, query_list, url_key, endpoint, item_id: ItemId = None, item_id_getter: ItemIdGetter = None, content_type: Optional[str] = None,) -> dict: ...
