# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.bridging_fee import BridgingFee
from cobo_waas2.models.commission_fee import CommissionFee
from cobo_waas2.models.payment_payout_item_status import PaymentPayoutItemStatus
from cobo_waas2.models.payment_transaction import PaymentTransaction
from typing import Optional, Set
from typing_extensions import Self


class PaymentPayoutItem(BaseModel):
    """
    PaymentPayoutItem
    """  # noqa: E501
    payout_item_id: StrictStr = Field(description="The payout item ID generated by Cobo.")
    payout_id: StrictStr = Field(description="The payout ID generated by Cobo.")
    token_id: Optional[StrictStr] = Field(default=None, description="The ID of the cryptocurrency paid out.")
    chain_id: Optional[StrictStr] = Field(default=None, description="The ID of the blockchain network on which the payout occurred.")
    amount: StrictStr = Field(description="The amount of the cryptocurrency to pay out. ")
    status: PaymentPayoutItemStatus
    source_account: StrictStr = Field(description="The source account from which the payout was made. - If the source account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the source account is the developer account, use the string `\"developer\"`. ")
    transactions: Optional[List[PaymentTransaction]] = Field(default=None, description="An array of transactions associated with this payout item. Each transaction represents a separate blockchain operation related to the payout item process.")
    created_timestamp: Optional[StrictInt] = Field(default=None, description="The created time of the payout item, represented as a UNIX timestamp in seconds.")
    updated_timestamp: Optional[StrictInt] = Field(default=None, description="The updated time of the payout item, represented as a UNIX timestamp in seconds.")
    crypto_address_id: Optional[StrictStr] = Field(default=None, description="The ID of the crypto address used for crypto payouts.")
    crypto_address: Optional[StrictStr] = Field(default=None, description="The actual blockchain address to which funds were transferred.")
    commission_fee: Optional[CommissionFee] = None
    bridging_fee: Optional[BridgingFee] = None
    __properties: ClassVar[List[str]] = ["payout_item_id", "payout_id", "token_id", "chain_id", "amount", "status", "source_account", "transactions", "created_timestamp", "updated_timestamp", "crypto_address_id", "crypto_address", "commission_fee", "bridging_fee"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentPayoutItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item in self.transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['transactions'] = _items
        # override the default output from pydantic by calling `to_dict()` of commission_fee
        if self.commission_fee:
            _dict['commission_fee'] = self.commission_fee.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bridging_fee
        if self.bridging_fee:
            _dict['bridging_fee'] = self.bridging_fee.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentPayoutItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payout_item_id": obj.get("payout_item_id"),
            "payout_id": obj.get("payout_id"),
            "token_id": obj.get("token_id"),
            "chain_id": obj.get("chain_id"),
            "amount": obj.get("amount"),
            "status": obj.get("status"),
            "source_account": obj.get("source_account"),
            "transactions": [PaymentTransaction.from_dict(_item) for _item in obj["transactions"]] if obj.get("transactions") is not None else None,
            "created_timestamp": obj.get("created_timestamp"),
            "updated_timestamp": obj.get("updated_timestamp"),
            "crypto_address_id": obj.get("crypto_address_id"),
            "crypto_address": obj.get("crypto_address"),
            "commission_fee": CommissionFee.from_dict(obj["commission_fee"]) if obj.get("commission_fee") is not None else None,
            "bridging_fee": BridgingFee.from_dict(obj["bridging_fee"]) if obj.get("bridging_fee") is not None else None
        })
        return _obj


