from __future__ import annotations

from typing import Any

from flask_resources.serializers import BaseSerializerSchema
from invenio_rdm_records.resources.serializers.schemas import CommonFieldsMixin
from marshmallow import Schema

class CSLCreatorSchema(Schema):
    def update_names(self, data: dict[str, Any], **kwargs: Any) -> dict[str, Any]: ...

def add_if_not_none(
    year: int | None, month: int | None, day: int | None
) -> list[int]: ...

class CSLJSONSchema(BaseSerializerSchema, CommonFieldsMixin):
    def get_type(self, obj: dict[str, Any]) -> Any: ...
    def get_issued(self, obj: dict[str, Any]) -> dict[str, Any] | Any: ...
    def get_language(self, obj: dict[str, Any]) -> Any: ...
    def get_isbn(self, obj: dict[str, Any]) -> Any: ...
    def get_issn(self, obj: dict[str, Any]) -> Any: ...
