from flask import Blueprint, Flask

blueprint: Blueprint

def create_blueprint_from_app(app: Flask) -> Blueprint: ...
def create_affiliations_blueprint_from_app(app: Flask) -> Blueprint: ...
def create_awards_blueprint_from_app(app: Flask) -> Blueprint: ...
def create_funders_blueprint_from_app(app: Flask) -> Blueprint: ...
def create_names_blueprint_from_app(app: Flask) -> Blueprint: ...
def create_subjects_blueprint_from_app(app: Flask) -> Blueprint: ...
def create_list_blueprint_from_app(app: Flask) -> Blueprint: ...
