from typing import Optional

class ActionError(Exception):
    def __init__(self, action: str, reason: str) -> None: ...
    def __str__(self) -> str: ...

class CannotExecuteActionError(ActionError):
    def __init__(self, action: str, reason: Optional[str] = ...) -> None: ...

class NoSuchActionError(ActionError):
    def __init__(self, action: str, reason: Optional[str] = ...) -> None: ...
