from __future__ import annotations

from typing import Any, Callable

JSONSCHEMAS_HOST: str
JSONSCHEMAS_ENDPOINT: str
JSONSCHEMAS_URL_SCHEME: str
JSONSCHEMAS_REPLACE_REFS: bool
JSONSCHEMAS_RESOLVE_SCHEMA: bool
JSONSCHEMAS_LOADER_CLS: Callable[[], Any] | type[Any] | str | None
JSONSCHEMAS_RESOLVER_CLS: str
JSONSCHEMAS_REGISTER_ENDPOINTS_API: bool
JSONSCHEMAS_REGISTER_ENDPOINTS_UI: bool
JSONSCHEMAS_SCHEMAS: list[str] | None
JSONSCHEMAS_LOCAL_REFRESOLVER_URI_SCHEME: str
