class EntityGrant:
    _prefix: str
    _need: tuple[str | int | None, ...]

    def __init__(self, prefix: str, need: tuple[str | int | None, ...]) -> None: ...
    @property
    def token(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
