# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.tmux_client_internal_types_window_info import \
    TmuxClientInternalTypesWindowInfo


class TestTmuxClientInternalTypesWindowInfo(unittest.TestCase):
    """TmuxClientInternalTypesWindowInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TmuxClientInternalTypesWindowInfo:
        """Test TmuxClientInternalTypesWindowInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TmuxClientInternalTypesWindowInfo`
        """
        model = TmuxClientInternalTypesWindowInfo()
        if include_optional:
            return TmuxClientInternalTypesWindowInfo(
                active = True,
                height = 56,
                index = 56,
                name = '',
                panes = 56,
                session_name = '',
                width = 56
            )
        else:
            return TmuxClientInternalTypesWindowInfo(
        )
        """

    def testTmuxClientInternalTypesWindowInfo(self):
        """Test TmuxClientInternalTypesWindowInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
