"""
DataCenter Client 类型存根文件
为IDE提供类型提示和代码补全支持
"""
from typing import Any, Dict, Optional, Union
import pandas as pd

class PageDataFrame(pd.DataFrame):
    """带分页信息的DataFrame"""
    _pagination: Dict[str, Any]

    @property
    def pagination(self) -> Dict[str, Any]: ...
    @property
    def has_pagination(self) -> bool: ...
    @property
    def current_page(self) -> int: ...
    @property
    def page_size(self) -> int: ...
    @property
    def total_count(self) -> int: ...
    @property
    def total_pages(self) -> int: ...

class DatacenterAPIError(Exception):
    """数据中心API异常类"""
    code: int
    message: str

class DataApi:
    """通用数据API客户端"""
    __token: str
    __base_url: str
    __timeout: int
    __dataapi_url: str

    def __init__(self, token: str, base_url: str = '', local: bool = False, timeout: int = 30) -> None: ...

    def query(self, api_name: str, fields: str = '', **kwargs) -> Union[pd.DataFrame, PageDataFrame]: ...

    # HSGT 相关接口
    def hsgt_fund_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def hsgt_north_fundxx(self, **kwargs) -> pd.DataFrame: ...
    def hsgt_south_fundxx(self, **kwargs) -> pd.DataFrame: ...

    # A股相关接口
    def a_stock_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def a_stock_list(self, limit: int = 50, **kwargs) -> pd.DataFrame: ...

    # 港股相关接口
    def hk_stock_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def hk_stock_list(self, limit: int = 50, **kwargs) -> pd.DataFrame: ...

    # 行业相关接口
    def hs_industry_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def hs_industry_list(self, limit: int = 50, **kwargs) -> pd.DataFrame: ...
    def hs_industry_company_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def hs_industry_company_list(self, limit: int = 50, **kwargs) -> pd.DataFrame: ...
    def sw_industry_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def sw_industry_list(self, limit: int = 50, **kwargs) -> pd.DataFrame: ...
    def sw_industry_company_page_list(self, page: int = 1, page_size: int = 20, level_type: str = 'level1', **kwargs) -> PageDataFrame: ...
    def sw_industry_company_list(self, limit: int = 50, level_type: str = 'level1', **kwargs) -> pd.DataFrame: ...

    # 融资融券相关接口
    def margin_account_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def margin_account_list(self, limit: int = 50, **kwargs) -> pd.DataFrame: ...
    def margin_analysis_page_list(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def margin_analysis_list(self, limit: int = 50, **kwargs) -> pd.DataFrame: ...
    def margin_detail_page_list_by_date(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def margin_detail_page_list_by_stock(self, page: int = 1, page_size: int = 20, **kwargs) -> PageDataFrame: ...
    def margin_detail_list_by_stock(self, stock_code: str, limit: int = 50, **kwargs) -> pd.DataFrame: ...

def init(token: str = '', base_url: str = '', local: bool = False, timeout: int = 30) -> DataApi: ...

__all__ = ["DataApi", "init", "PageDataFrame", "DatacenterAPIError"]