from invenio_records.systemfields import RelatedModelField

class ParentField(RelatedModelField):
    def __init__(
        self,
        model,
        key=None,
        create: bool = False,
        soft_delete: bool = True,
        hard_delete: bool = True,
    ) -> None: ...
    def create(self, record): ...
    def delete(self, record, force: bool = False) -> None: ...
    def pre_create(self, record) -> None: ...
    def post_delete(self, record, force: bool = False) -> None: ...
    def pre_dump(self, record, data, dumper=None) -> None: ...
    def post_load(self, record, data, loader=None) -> None: ...
    @staticmethod
    def load_parent(field, record): ...
    @staticmethod
    def dump_parent(field, record, parent_record) -> None: ...
