# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 66.91.2-v202512300114-CD
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class MonitoredConditionOutputV1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'last_run_state': 'LastRunStateOutputV1',
        'suppression_end_condition_guid': 'str',
        'suppression_end_time': 'str',
        'suppression_start_time': 'str'
    }

    attribute_map = {
        'id': 'id',
        'last_run_state': 'lastRunState',
        'suppression_end_condition_guid': 'suppressionEndConditionGuid',
        'suppression_end_time': 'suppressionEndTime',
        'suppression_start_time': 'suppressionStartTime'
    }

    def __init__(self, id=None, last_run_state=None, suppression_end_condition_guid=None, suppression_end_time=None, suppression_start_time=None):
        """
        MonitoredConditionOutputV1 - a model defined in Swagger
        """

        self._id = None
        self._last_run_state = None
        self._suppression_end_condition_guid = None
        self._suppression_end_time = None
        self._suppression_start_time = None

        if id is not None:
          self.id = id
        if last_run_state is not None:
          self.last_run_state = last_run_state
        if suppression_end_condition_guid is not None:
          self.suppression_end_condition_guid = suppression_end_condition_guid
        if suppression_end_time is not None:
          self.suppression_end_time = suppression_end_time
        if suppression_start_time is not None:
          self.suppression_start_time = suppression_start_time

    @property
    def id(self):
        """
        Gets the id of this MonitoredConditionOutputV1.
        The ID of the monitored condition

        :return: The id of this MonitoredConditionOutputV1.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this MonitoredConditionOutputV1.
        The ID of the monitored condition

        :param id: The id of this MonitoredConditionOutputV1.
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def last_run_state(self):
        """
        Gets the last_run_state of this MonitoredConditionOutputV1.

        :return: The last_run_state of this MonitoredConditionOutputV1.
        :rtype: LastRunStateOutputV1
        """
        return self._last_run_state

    @last_run_state.setter
    def last_run_state(self, last_run_state):
        """
        Sets the last_run_state of this MonitoredConditionOutputV1.

        :param last_run_state: The last_run_state of this MonitoredConditionOutputV1.
        :type: LastRunStateOutputV1
        """
        if last_run_state is None:
            raise ValueError("Invalid value for `last_run_state`, must not be `None`")

        self._last_run_state = last_run_state

    @property
    def suppression_end_condition_guid(self):
        """
        Gets the suppression_end_condition_guid of this MonitoredConditionOutputV1.
        Condition ID to end the suppression

        :return: The suppression_end_condition_guid of this MonitoredConditionOutputV1.
        :rtype: str
        """
        return self._suppression_end_condition_guid

    @suppression_end_condition_guid.setter
    def suppression_end_condition_guid(self, suppression_end_condition_guid):
        """
        Sets the suppression_end_condition_guid of this MonitoredConditionOutputV1.
        Condition ID to end the suppression

        :param suppression_end_condition_guid: The suppression_end_condition_guid of this MonitoredConditionOutputV1.
        :type: str
        """

        self._suppression_end_condition_guid = suppression_end_condition_guid

    @property
    def suppression_end_time(self):
        """
        Gets the suppression_end_time of this MonitoredConditionOutputV1.
        End time of the suppression as an ISO-8601 timestamp

        :return: The suppression_end_time of this MonitoredConditionOutputV1.
        :rtype: str
        """
        return self._suppression_end_time

    @suppression_end_time.setter
    def suppression_end_time(self, suppression_end_time):
        """
        Sets the suppression_end_time of this MonitoredConditionOutputV1.
        End time of the suppression as an ISO-8601 timestamp

        :param suppression_end_time: The suppression_end_time of this MonitoredConditionOutputV1.
        :type: str
        """

        self._suppression_end_time = suppression_end_time

    @property
    def suppression_start_time(self):
        """
        Gets the suppression_start_time of this MonitoredConditionOutputV1.
        Start time of the suppression as an ISO-8601 timestamp

        :return: The suppression_start_time of this MonitoredConditionOutputV1.
        :rtype: str
        """
        return self._suppression_start_time

    @suppression_start_time.setter
    def suppression_start_time(self, suppression_start_time):
        """
        Sets the suppression_start_time of this MonitoredConditionOutputV1.
        Start time of the suppression as an ISO-8601 timestamp

        :param suppression_start_time: The suppression_start_time of this MonitoredConditionOutputV1.
        :type: str
        """

        self._suppression_start_time = suppression_start_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MonitoredConditionOutputV1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
