# coding: utf-8

"""
    virsh-sandbox API

    API for managing virtual machine sandboxes using libvirt

    The version of the OpenAPI document: 0.0.1-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virsh_sandbox.models.tmux_client_internal_types_read_pane_response import \
    TmuxClientInternalTypesReadPaneResponse


class TestTmuxClientInternalTypesReadPaneResponse(unittest.TestCase):
    """TmuxClientInternalTypesReadPaneResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TmuxClientInternalTypesReadPaneResponse:
        """Test TmuxClientInternalTypesReadPaneResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TmuxClientInternalTypesReadPaneResponse`
        """
        model = TmuxClientInternalTypesReadPaneResponse()
        if include_optional:
            return TmuxClientInternalTypesReadPaneResponse(
                content = '',
                lines = 56,
                pane_id = ''
            )
        else:
            return TmuxClientInternalTypesReadPaneResponse(
        )
        """

    def testTmuxClientInternalTypesReadPaneResponse(self):
        """Test TmuxClientInternalTypesReadPaneResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
