from unittest.mock import MagicMock

import pytest

from stxsdk import Selection
from stxsdk.storage.user_storage import User


@pytest.fixture
def selection():
    return Selection


@pytest.fixture
def user():
    return User


@pytest.fixture
def client():
    class Client:
        def __init__(self):
            self.transport = MagicMock()
            self.transport.headers = None

    return Client


login_return_fields = {
    "userId": "rID",
    "status": "Int",
    "token": "String",
    "refreshToken": "String",
    "userStatus": "String",
    "userUid": "String",
    "userProfile": {
        "id": "rID!",
        "dateOfBirth": "String",
        "firstName": "String!",
        "lastName": "String!",
        "middleName": "String",
        "preferredName": "String",
        "username": "String!",
        "phoneNumber": "String",
        "countryCode": "String",
        "businessCountryCode": "String",
        "businessPhone": "String",
        "address1": "String",
        "address2": "String",
        "city": "String",
        "state": "String",
        "zipCode": "String",
        "country": "String",
        "citizenshipCountry": "String",
        "ssn": "String",
        "accountId": "rID",
        "employerName": "String",
        "employerAddress": "String",
        "jobTitle": "String",
        "industry": "String",
        "twoFactorAuth": "Boolean",
        "twoFactorAuthPerDevice": "Boolean",
        "optInMarketing": "Boolean",
        "whitelistIpAddresses": "String",
    },
    "lastLoginAt": "String",
    "currentLoginAt": "String",
    "deviceId": "String",
    "ipAddress": "String",
    "limitsNumber": {
        "accountLimits": {
            "accountId": "rID",
            "dailyDeposit": "Int",
            "weeklyDeposit": "Int",
            "monthlyDeposit": "Int",
            "lifetimeDeposit": "Int",
            "orderLiability": "Int",
            "maxOrderLiabilityPerOrder": "Int",
            "lossLimit24Hours": "Int",
            "lossLimitWeekly": "Int",
            "lossLimitMonthly": "Int",
            "coolOffPeriod": "Int",
            "hoursPerDay": "Int",
            "selfExcluded": "Int",
        },
        "adminLimits": {
            "dailyDeposit": "Int",
            "weeklyDeposit": "Int",
            "monthlyDeposit": "Int",
            "lifetimeDeposit": "Int",
            "orderLiability": "Int",
            "maxOrderLiabilityPerOrder": "Int",
            "lossLimit24Hours": "Int",
            "lossLimitWeekly": "Int",
            "lossLimitMonthly": "Int",
            "coolOffPeriod": "Int",
            "hoursPerDay": "Int",
            "selfExcluded": "Int",
        },
    },
    "promptTwoFactorAuth": "Boolean",
    "sessionId": "String",
    "promptTncAcceptance": "Boolean",
    "tncChanged": {
        "terms": "Boolean",
        "privacyPolicy": "Boolean",
        "houseRules": "Boolean",
    },
    "tncId": "String",
    "whitelistIpAddresses": "String",
    "deviceTokens": {
        "deviceId": "String",
        "deviceToken": "String",
        "deviceType": "String",
        "effectiveStartDate": "String",
    },
    "allowMultipleLogins": "Boolean",
    "appSettings": {
        "deviceId": "String",
        "settings": {
            "deviceId": "String",
            "mode": "String",
            "oddsDisplay": "String",
            "enableFaceId": "Boolean",
            "wageringQtyIncrement": "String",
            "closeYourAccount": "Boolean",
            "enable2Fa": "Boolean",
            "deviceType": "String",
            "showTutorialAgain": "Boolean",
        },
    },
    "referralCode": "String",
}

update_profile_return_fields = {"status": "Int!", "userProfile": "UserProfile!"}

cancel_order_return_fields = {"status": "String", "nextGeolocationAt": "String"}

confirm_order_return_fields = {
    "order": {
        "id": "rID",
        "clientOrderId": "String",
        "action": "String",
        "price": "Price",
        "quantity": "Quantity",
        "filled": "Quantity",
        "status": "String",
        "time": "String",
        "insertedAt": "Int",
        "marketId": "rID",
        "filledPercentage": "Int",
        "avgPrice": "Price",
        "totalValue": "Int",
        "orderType": "String",
        "ipAddress": "String",
        "deviceId": "String",
        "oddsType": "OddsType",
        "oddsValue": "String",
        "amount": "Int",
        "filledAmount": "Int",
        "delayedUntil": "Int",
        "placedPreStart": "Boolean",
        "expiration": "OrderExpiration",
        "expirationTime": "NonNegInt",
        "cancellationReason": "String",
        "rejectionReason": "String",
    },
    "nextGeolocationAt": "String",
}

new_token_return_fields = {
    "userId": "rID",
    "status": "Int",
    "token": "String",
    "refreshToken": "String",
    "userStatus": "String",
    "userUid": "String",
    "userProfile": {
        "id": "rID!",
        "dateOfBirth": "String",
        "firstName": "String!",
        "lastName": "String!",
        "middleName": "String",
        "preferredName": "String",
        "username": "String!",
        "phoneNumber": "String",
        "countryCode": "String",
        "businessCountryCode": "String",
        "businessPhone": "String",
        "address1": "String",
        "address2": "String",
        "city": "String",
        "state": "String",
        "zipCode": "String",
        "country": "String",
        "citizenshipCountry": "String",
        "ssn": "String",
        "accountId": "rID",
        "employerName": "String",
        "employerAddress": "String",
        "jobTitle": "String",
        "industry": "String",
        "twoFactorAuth": "Boolean",
        "twoFactorAuthPerDevice": "Boolean",
        "optInMarketing": "Boolean",
        "whitelistIpAddresses": "String",
    },
    "lastLoginAt": "String",
    "currentLoginAt": "String",
    "deviceId": "String",
    "ipAddress": "String",
    "limitsNumber": {
        "accountLimits": {
            "accountId": "rID",
            "dailyDeposit": "Int",
            "weeklyDeposit": "Int",
            "monthlyDeposit": "Int",
            "lifetimeDeposit": "Int",
            "orderLiability": "Int",
            "maxOrderLiabilityPerOrder": "Int",
            "lossLimit24Hours": "Int",
            "lossLimitWeekly": "Int",
            "lossLimitMonthly": "Int",
            "coolOffPeriod": "Int",
            "hoursPerDay": "Int",
            "selfExcluded": "Int",
        },
        "adminLimits": {
            "dailyDeposit": "Int",
            "weeklyDeposit": "Int",
            "monthlyDeposit": "Int",
            "lifetimeDeposit": "Int",
            "orderLiability": "Int",
            "maxOrderLiabilityPerOrder": "Int",
            "lossLimit24Hours": "Int",
            "lossLimitWeekly": "Int",
            "lossLimitMonthly": "Int",
            "coolOffPeriod": "Int",
            "hoursPerDay": "Int",
            "selfExcluded": "Int",
        },
    },
    "promptTwoFactorAuth": "Boolean",
    "sessionId": "String",
    "promptTncAcceptance": "Boolean",
    "tncChanged": {
        "terms": "Boolean",
        "privacyPolicy": "Boolean",
        "houseRules": "Boolean",
    },
    "tncId": "String",
    "whitelistIpAddresses": "String",
    "deviceTokens": {
        "deviceId": "String",
        "deviceToken": "String",
        "deviceType": "String",
        "effectiveStartDate": "String",
    },
    "allowMultipleLogins": "Boolean",
    "appSettings": {
        "deviceId": "String",
        "settings": {
            "deviceId": "String",
            "mode": "String",
            "oddsDisplay": "String",
            "enableFaceId": "Boolean",
            "wageringQtyIncrement": "String",
            "closeYourAccount": "Boolean",
            "enable2Fa": "Boolean",
            "deviceType": "String",
            "showTutorialAgain": "Boolean",
        },
    },
    "referralCode": "String",
}

market_infos_return_fields = {
    "archived": "Boolean",
    "bids": {"price": "Int", "quantity": "Quantity"},
    "settledAt": "String",
    "description": "String",
    "detailedEventBrief": "String",
    "eventBrief": "String",
    "eventId": "rID",
    "eventStart": "String",
    "eventStatus": "String",
    "eventType": "String",
    "filters": {
        "category": "String",
        "subcategory": "String",
        "section": "String",
        "grouping": "String",
        "subgrouping": "String",
        "manual": "Boolean",
    },
    "homeCategory": "String",
    "lastProbabilityAt": "PosInt",
    "manualProbability": "Boolean",
    "lastTradedPrice": "Int",
    "marketId": "rID",
    "maxPrice": "Int",
    "pointsCost": "Int",
    "inPlayDelaySec": "Int",
    "offers": {"price": "Int", "quantity": "Quantity"},
    "orderPriceRules": {"from": "Int", "to": "Int", "inc": "Int"},
    "position": "String",
    "sport": "String",
    "competition": "String",
    "participants": {"abbreviation": "String", "name": "String", "role": "String"},
    "probability": "Float",
    "price": "Float",
    "priceChange24h": "Int",
    "question": "String",
    "recentTrades": {
        "price": "Int",
        "quantity": "Quantity",
        "liquidityTaker": "String",
        "timestamp": "String",
        "timestampInt": "Int",
    },
    "result": "String",
    "status": "String",
    "trading": "Boolean",
    "symbol": "String",
    "shortTitle": "String",
    "groupTitle": "String",
    "title": "String",
    "timestamp": "String",
    "timestampInt": "Int",
    "tradingFilters": {
        "category": "String",
        "subcategory": "String",
        "section": "String",
        "grouping": "String",
        "subgrouping": "String",
        "manual": "Boolean",
    },
    "specifier": "String",
    "rulesSpecifier": "String",
    "rules": "String",
    "volume24h": "Int",
    "totalVolume": "Int",
    "statDetail": {
        "stat": "String",
        "statDisplayName": "String",
        "player": "String",
        "jersey": "String",
        "line": "Float",
    },
    "featured": "Boolean",
}

user_profile_return_fields = {
    "id": "rID!",
    "dateOfBirth": "String",
    "firstName": "String!",
    "lastName": "String!",
    "middleName": "String",
    "preferredName": "String",
    "username": "String!",
    "phoneNumber": "String",
    "countryCode": "String",
    "businessCountryCode": "String",
    "businessPhone": "String",
    "address1": "String",
    "address2": "String",
    "city": "String",
    "state": "String",
    "zipCode": "String",
    "country": "String",
    "citizenshipCountry": "String",
    "ssn": "String",
    "accountId": "rID",
    "employerName": "String",
    "employerAddress": "String",
    "jobTitle": "String",
    "industry": "String",
    "twoFactorAuth": "Boolean",
    "twoFactorAuthPerDevice": "Boolean",
    "optInMarketing": "Boolean",
    "whitelistIpAddresses": "String",
}

geo_fencing_return_fields = {"expiresAt": "String", "license": "String"}
