# Generated by Django 5.2.6 on 2025-12-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0007_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_notice',
            field=models.CharField(blank=True, help_text='Copyright notice to display in the site footer. Content will be HTML-escaped before rendering.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the site, used in site level meta description tags and social media previews.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='preview_image',
            field=models.ForeignKey(blank=True, help_text='Photo to use as the site level social media preview image.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo_objects.photo'),
        ),
    ]
