from typing import List, Optional, Dict, Any, Iterable

class KabodError(Exception): ...
class ConfigError(KabodError): ...
class DatabaseError(KabodError): ...
class SerializationError(KabodError): ...
class ValidationError(KabodError): ...

class Point:
    id: str
    vector: List[float]
    metadata: Optional[Dict[str, Any]]
    
    def __init__(
        self, 
        id: str, 
        vector: List[float], 
        metadata: Optional[Dict[str, Any]] = None
    ) -> None: ...
    def dict(self) -> Dict[str, Any]: ...
    def model_dump(self) -> Dict[str, Any]: ...

class SearchResult:
    id: str
    score: float
    vector: Optional[List[float]]
    metadata: Optional[Dict[str, Any]]
    
    def dict(self) -> Dict[str, Any]: ...
    def model_dump(self) -> Dict[str, Any]: ...

class SearchResponse:
    results: List[SearchResult]
    aggregations: Dict[str, Any]
    
    def dict(self) -> Dict[str, Any]: ...
    def model_dump(self) -> Dict[str, Any]: ...
    def __len__(self) -> int: ...

class Collection:
    async def insert(self, points: List[Point]) -> None: ...
    async def insert_batch(self, points: List[Point], batch_size: Optional[int] = None, parallel: Optional[int] = None) -> None: ...
    async def insert_stream(
        self, 
        points: Iterable[Point], 
        batch_size: int = 1000
    ) -> None: ...
    async def search(
        self, 
        vector: List[float], 
        top_k: int = 10, 
        filter: Optional[Dict[str, Any]] = None,
        include_metadata: bool = True,
        include_vector: bool = False
    ) -> SearchResponse: ...
    async def delete(self, ids: List[str]) -> None: ...
    async def delete_collection(self) -> None: ...
    async def create(
        self, 
        dimension: int, 
        distance: str
    ) -> None: ...

class KabodClient:
    def __init__(
        self, 
        provider: str, 
        url: str, 
        api_key: Optional[str] = None
    ) -> None: ...
    
    def collection(self, name: str) -> Collection: ...
