

class Configurator:

    # Default values
    WAIT_FOR_CONTROL_POLL = 1
    WAIT_FOR_CONTROL_TIMEOUT = 10

    WAIT_FOR_WINDOW_POLL = 1
    WAIT_FOR_WINDOW_TIMEOUT = 10

    WAIT_FOR_WINDOW_ENABLE_POLL = 1
    WAIT_FOR_WINDOW_ENABLE_TIMEOUT = 10

    WAIT_FOR_CONTROL_ACCESSIBLE_POLL = 1
    WAIT_FOR_CONTROL_ACCESSIBLE_TIMEOUT = 10
