# generated by datamodel-codegen:
#   filename:  properties_directory/structural/basis/atomic_constraints_property.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field


class Name(Enum):
    atomic_constraints = "atomic_constraints"


class AtomicConstraintSchema(BaseModel):
    value: List[bool] = Field(..., title="vector boolean 3d schema")
    """
    value of this entry
    """
    id: int
    """
    integer id of this entry
    """


class AtomicConstraintsPropertySchema(BaseModel):
    name: Name
    values: List[AtomicConstraintSchema] = Field(..., title="atomic constraints schema")
    """
    atomic constraints schema
    """
