CTRL_VAR_PREFIX = "ctrl__"
CONTROL_OPERATOR_NAME = "control"
SKIP_CONTROL_OPERATOR_NAME = "skip_control"
INVERT_OPERATOR_NAME = "invert"
REPEAT_OPERATOR_NAME = "iteration"
CLASSICAL_IF_OPERATOR_NAME = "classical_if"
POWER_OPERATOR_NAME = "power"
UNCOMPUTE_OPERATOR_NAME = "uncompute"
WITHIN_APPLY_NAME = "within_apply"
BLOCK_OPERATOR_NAME = "block"

All_BUILTINS_OPERATORS = {
    CONTROL_OPERATOR_NAME,
    INVERT_OPERATOR_NAME,
    REPEAT_OPERATOR_NAME,
    POWER_OPERATOR_NAME,
    UNCOMPUTE_OPERATOR_NAME,
    WITHIN_APPLY_NAME,
    BLOCK_OPERATOR_NAME,
}
