from collections.abc import Sequence
from typing import (
    Any,
    Final,
    Literal as L,
    Protocol,
    Self,
    SupportsIndex as _Index,
    TypeAlias,
    overload,
    type_check_only,
)
from typing_extensions import TypeVar, override

import _numtype as _nt
import numpy as np

from ._polybase import ABCPolyBase
from .polyutils import trimcoef as polytrim

__all__ = [
    "Polynomial",
    "polyadd",
    "polycompanion",
    "polyder",
    "polydiv",
    "polydomain",
    "polyfit",
    "polyfromroots",
    "polygrid2d",
    "polygrid3d",
    "polyint",
    "polyline",
    "polymul",
    "polymulx",
    "polyone",
    "polypow",
    "polyroots",
    "polysub",
    "polytrim",
    "polyval",
    "polyval2d",
    "polyval3d",
    "polyvalfromroots",
    "polyvander",
    "polyvander2d",
    "polyvander3d",
    "polyx",
    "polyzero",
]

###

_ScalarT = TypeVar("_ScalarT", bound=np.generic)
_InexactT = TypeVar("_InexactT", bound=np.inexact)

_Indices: TypeAlias = Sequence[_Index]
_ArrayAndFitResult: TypeAlias = tuple[_nt.Array[_ScalarT], Sequence[np.inexact | np.int32]]

_ToNumeric_0d: TypeAlias = _ToComplex | _nt.ToObject_0d | _SupportsCoefOps
_ToNumeric_1d: TypeAlias = _nt._ToArray2_1d[np.number | np.bool | np.object_, complex | _SupportsCoefOps]
_ToNumeric_nd: TypeAlias = _nt._ToArray2_nd[np.number | np.bool | np.object_, complex | _SupportsCoefOps]

_ToF64: TypeAlias = np.float64 | _nt.JustFloat
_ToComplex: TypeAlias = np.complexfloating | _nt.JustComplex
_CoInt: TypeAlias = _nt.co_integer | int
_CoF64: TypeAlias = _nt.co_float64 | float
_CoFloat: TypeAlias = _nt.co_float | float
_CoComplex: TypeAlias = _nt.co_complex | complex

_I64_1d: TypeAlias = _nt.Array1D[np.int64]
_F64_1d: TypeAlias = _nt.Array1D[np.float64]
_C128_1d: TypeAlias = _nt.Array1D[np.complex128]
_Float_1d: TypeAlias = _nt.Array1D[np.floating]
_Complex_1d: TypeAlias = _nt.Array1D[np.complexfloating]
_Inexact_1d: TypeAlias = _nt.Array1D[np.inexact]
_Object_1d: TypeAlias = _nt.Array1D[np.object_]

_F64_nd: TypeAlias = _nt.Array[np.float64]
_C128_nd: TypeAlias = _nt.Array[np.complex128]
_Object_nd: TypeAlias = _nt.Array[np.object_]
_Float_nd: TypeAlias = _nt.Array[np.floating]
_Complex_nd: TypeAlias = _nt.Array[np.complexfloating]
_Inexact_nd: TypeAlias = _nt.Array[np.inexact]

# compatible with e.g. int, float, complex, Decimal, Fraction, and ABCPolyBase
@type_check_only
class _SupportsCoefOps(Protocol):
    @override
    def __eq__(self, x: object, /) -> bool: ...
    @override
    def __ne__(self, x: object, /) -> bool: ...
    def __neg__(self, /) -> Self: ...
    def __pos__(self, /) -> Self: ...
    def __add__(self, x: Any, /) -> Self: ...
    def __sub__(self, x: Any, /) -> Self: ...
    def __mul__(self, x: Any, /) -> Self: ...
    def __pow__(self, x: Any, /) -> Self | float: ...
    def __radd__(self, x: Any, /) -> Self: ...
    def __rsub__(self, x: Any, /) -> Self: ...
    def __rmul__(self, x: Any, /) -> Self: ...

###

polydomain: Final[_F64_1d] = ...
polyzero: Final[_I64_1d] = ...
polyone: Final[_I64_1d] = ...
polyx: Final[_I64_1d] = ...

###

class Polynomial(ABCPolyBase):
    domain: _F64_1d = ...  # pyright: ignore[reportIncompatibleMethodOverride]
    window: _F64_1d = ...  # pyright: ignore[reportIncompatibleMethodOverride]
    basis_name: None = None  # pyright: ignore[reportIncompatibleMethodOverride]

###

#
@overload
def polyline(off: _nt.ToInt_0d, scl: _nt.CoInt64_0d) -> _I64_1d: ...
@overload
def polyline(off: _nt.CoInt64_0d, scl: _nt.ToInt_0d) -> _I64_1d: ...
@overload
def polyline(off: _CoInt, scl: _CoInt) -> _nt.Array1D[np.integer]: ...
@overload
def polyline(off: _ToF64, scl: _CoF64) -> _F64_1d: ...
@overload
def polyline(off: _CoF64, scl: _ToF64) -> _F64_1d: ...
@overload
def polyline(off: _nt.ToFloating_0d, scl: _CoFloat) -> _Float_1d: ...
@overload
def polyline(off: _CoFloat, scl: _nt.ToFloating_0d) -> _Float_1d: ...
@overload
def polyline(off: _nt.ToComplex128_0d, scl: _nt.CoComplex128_0d) -> _C128_1d: ...
@overload
def polyline(off: _nt.CoComplex128_0d, scl: _nt.ToComplex128_0d) -> _C128_1d: ...
@overload
def polyline(off: _ToComplex, scl: _CoComplex) -> _Complex_1d: ...
@overload
def polyline(off: _CoComplex, scl: _ToComplex) -> _Complex_1d: ...
@overload
def polyline(off: _CoComplex, scl: _CoComplex) -> _nt.Array1D[np.number]: ...
@overload
def polyline(off: _nt.ToObject_0d, scl: _nt.ToObject_0d) -> _Object_1d: ...

#
@overload
def polyfromroots(roots: _nt.ToFloat64_1d | _nt.CoInteger_1d) -> _F64_1d: ...
@overload
def polyfromroots(roots: _nt.CoFloating_1d) -> _Float_1d: ...
@overload
def polyfromroots(roots: _nt.ToComplex128_1d) -> _C128_1d: ...
@overload
def polyfromroots(roots: _nt.ToComplex_1d) -> _Complex_1d: ...
@overload
def polyfromroots(roots: _nt.CoComplex_1d) -> _Inexact_1d: ...
@overload
def polyfromroots(roots: _nt.ToObject_1d) -> _Object_1d: ...

#
@overload
def polyadd(c1: _nt.CoInteger_1d, c2: _nt.CoInteger_1d) -> _F64_1d: ...
@overload
def polyadd(c1: _nt.ToFloat64_1d, c2: _nt.CoFloat64_1d) -> _F64_1d: ...
@overload
def polyadd(c1: _nt.CoFloat64_1d, c2: _nt.ToFloat64_1d) -> _F64_1d: ...
@overload
def polyadd(c1: _nt.ToReal_1d, c2: _nt.CoFloating_1d) -> _Float_1d: ...
@overload
def polyadd(c1: _nt.CoFloating_1d, c2: _nt.ToReal_1d) -> _Float_1d: ...
@overload
def polyadd(c1: _nt.ToComplex128_1d, c2: _nt.CoComplex128_1d) -> _C128_1d: ...
@overload
def polyadd(c1: _nt.CoComplex128_1d, c2: _nt.ToComplex128_1d) -> _C128_1d: ...
@overload
def polyadd(c1: _nt.ToComplex_1d, c2: _nt.CoComplex_1d) -> _Complex_1d: ...
@overload
def polyadd(c1: _nt.CoComplex_1d, c2: _nt.ToComplex_1d) -> _Complex_1d: ...
@overload
def polyadd(c1: _nt.ToObject_1d, c2: _ToNumeric_1d) -> _Object_1d: ...
@overload
def polyadd(c1: _ToNumeric_1d, c2: _nt.ToObject_1d) -> _Object_1d: ...

#
@overload
def polysub(c1: _nt.CoInteger_1d, c2: _nt.CoInteger_1d) -> _F64_1d: ...
@overload
def polysub(c1: _nt.ToFloat64_1d, c2: _nt.CoFloat64_1d) -> _F64_1d: ...
@overload
def polysub(c1: _nt.CoFloat64_1d, c2: _nt.ToFloat64_1d) -> _F64_1d: ...
@overload
def polysub(c1: _nt.ToReal_1d, c2: _nt.CoFloating_1d) -> _Float_1d: ...
@overload
def polysub(c1: _nt.CoFloating_1d, c2: _nt.ToReal_1d) -> _Float_1d: ...
@overload
def polysub(c1: _nt.ToComplex128_1d, c2: _nt.CoComplex128_1d) -> _C128_1d: ...
@overload
def polysub(c1: _nt.CoComplex128_1d, c2: _nt.ToComplex128_1d) -> _C128_1d: ...
@overload
def polysub(c1: _nt.ToComplex_1d, c2: _nt.CoComplex_1d) -> _Complex_1d: ...
@overload
def polysub(c1: _nt.CoComplex_1d, c2: _nt.ToComplex_1d) -> _Complex_1d: ...
@overload
def polysub(c1: _nt.ToObject_1d, c2: _ToNumeric_1d) -> _Object_1d: ...
@overload
def polysub(c1: _ToNumeric_1d, c2: _nt.ToObject_1d) -> _Object_1d: ...

#
@overload
def polymulx(c: _nt.ToFloat64_1d | _nt.CoInteger_1d) -> _F64_1d: ...
@overload
def polymulx(c: _nt.CoFloating_1d) -> _Float_1d: ...
@overload
def polymulx(c: _nt.ToComplex128_1d) -> _C128_1d: ...
@overload
def polymulx(c: _nt.ToComplex_1d) -> _Complex_1d: ...
@overload
def polymulx(c: _nt.CoComplex_1d) -> _Inexact_1d: ...
@overload
def polymulx(c: _nt.ToObject_1d) -> _Object_1d: ...

#
@overload
def polymul(c1: _nt.CoInteger_1d, c2: _nt.CoInteger_1d) -> _F64_1d: ...
@overload
def polymul(c1: _nt.ToFloat64_1d, c2: _nt.CoFloat64_1d) -> _F64_1d: ...
@overload
def polymul(c1: _nt.CoFloat64_1d, c2: _nt.ToFloat64_1d) -> _F64_1d: ...
@overload
def polymul(c1: _nt.ToReal_1d, c2: _nt.CoFloating_1d) -> _Float_1d: ...
@overload
def polymul(c1: _nt.CoFloating_1d, c2: _nt.ToReal_1d) -> _Float_1d: ...
@overload
def polymul(c1: _nt.ToComplex128_1d, c2: _nt.CoComplex128_1d) -> _C128_1d: ...
@overload
def polymul(c1: _nt.CoComplex128_1d, c2: _nt.ToComplex128_1d) -> _C128_1d: ...
@overload
def polymul(c1: _nt.ToComplex_1d, c2: _nt.CoComplex_1d) -> _Complex_1d: ...
@overload
def polymul(c1: _nt.CoComplex_1d, c2: _nt.ToComplex_1d) -> _Complex_1d: ...
@overload
def polymul(c1: _nt.ToObject_1d, c2: _ToNumeric_1d) -> _Object_1d: ...
@overload
def polymul(c1: _ToNumeric_1d, c2: _nt.ToObject_1d) -> _Object_1d: ...

#
@overload
def polydiv(c1: _nt.CoInteger_1d, c2: _nt.CoInteger_1d) -> _F64_1d: ...
@overload
def polydiv(c1: _nt.ToFloat64_1d, c2: _nt.CoFloat64_1d) -> _F64_1d: ...
@overload
def polydiv(c1: _nt.CoFloat64_1d, c2: _nt.ToFloat64_1d) -> _F64_1d: ...
@overload
def polydiv(c1: _nt.ToReal_1d, c2: _nt.CoFloating_1d) -> _Float_1d: ...
@overload
def polydiv(c1: _nt.CoFloating_1d, c2: _nt.ToReal_1d) -> _Float_1d: ...
@overload
def polydiv(c1: _nt.ToComplex128_1d, c2: _nt.CoComplex128_1d) -> _C128_1d: ...
@overload
def polydiv(c1: _nt.CoComplex128_1d, c2: _nt.ToComplex128_1d) -> _C128_1d: ...
@overload
def polydiv(c1: _nt.ToComplex_1d, c2: _nt.CoComplex_1d) -> _Complex_1d: ...
@overload
def polydiv(c1: _nt.CoComplex_1d, c2: _nt.ToComplex_1d) -> _Complex_1d: ...
@overload
def polydiv(c1: _nt.ToObject_1d, c2: _ToNumeric_1d) -> _Object_1d: ...
@overload
def polydiv(c1: _ToNumeric_1d, c2: _nt.ToObject_1d) -> _Object_1d: ...

#
@overload
def polypow(c: _nt.CoInteger_nd, pow: _CoInt, maxpower: _CoInt | None = None) -> _F64_1d: ...
@overload
def polypow(c: _nt.ToFloat64_1d, pow: _CoInt, maxpower: _CoInt | None = None) -> _F64_1d: ...
@overload
def polypow(c: _nt.CoFloating_1d, pow: _CoInt, maxpower: _CoInt | None = None) -> _Float_1d: ...
@overload
def polypow(c: _nt.ToComplex128_1d, pow: _CoInt, maxpower: _CoInt | None = None) -> _C128_1d: ...
@overload
def polypow(c: _nt.ToComplex_1d, pow: _CoInt, maxpower: _CoInt | None = None) -> _Complex_1d: ...
@overload
def polypow(c: _nt.CoComplex_1d, pow: _CoInt, maxpower: _CoInt | None = None) -> _Inexact_1d: ...
@overload
def polypow(c: _nt.ToObject_1d, pow: _CoInt, maxpower: _CoInt | None = None) -> _Object_1d: ...

#
@overload
def polyder(c: _nt.CoInteger_nd, m: _Index = 1, scl: _CoFloat = 1, axis: _Index = 0) -> _F64_nd: ...
@overload
def polyder(c: _nt.ToFloat64_nd, m: _Index = 1, scl: _CoFloat = 1, axis: _Index = 0) -> _F64_nd: ...
@overload
def polyder(c: _nt.ToFloating_nd, m: _Index = 1, scl: _CoFloat = 1, axis: _Index = 0) -> _Float_nd: ...
@overload
def polyder(c: _nt.ToComplex128_nd, m: _Index = 1, scl: _CoComplex = 1, axis: _Index = 0) -> _C128_nd: ...
@overload
def polyder(c: _nt.ToComplex_nd, m: _Index = 1, scl: _CoComplex = 1, axis: _Index = 0) -> _Complex_nd: ...
@overload
def polyder(c: _nt.CoComplex_nd, m: _Index = 1, scl: _CoComplex = 1, axis: _Index = 0) -> _Inexact_nd: ...
@overload
def polyder(c: _nt.ToObject_nd, m: _Index = 1, scl: _ToNumeric_0d = 1, axis: _Index = 0) -> _Object_nd: ...

#
@overload
def polyint(
    c: _nt.CoInteger_nd,
    m: _Index = 1,
    k: _CoF64 | _nt.CoFloat64_1d = [],
    lbnd: _CoFloat = 0,
    scl: _CoFloat = 1,
    axis: _Index = 0,
) -> _F64_nd: ...
@overload
def polyint(
    c: _nt.ToFloat64_nd,
    m: _Index = 1,
    k: _CoF64 | _nt.CoFloat64_1d = [],
    lbnd: _CoFloat = 0,
    scl: _CoFloat = 1,
    axis: _Index = 0,
) -> _F64_nd: ...
@overload
def polyint(
    c: _nt.CoFloating_nd,
    m: _Index = 1,
    k: _CoFloat | _nt.CoFloating_1d = [],
    lbnd: _CoFloat = 0,
    scl: _CoFloat = 1,
    axis: _Index = 0,
) -> _Float_nd: ...
@overload
def polyint(
    c: _nt.ToComplex_nd,
    m: _Index = 1,
    k: _CoComplex | _nt.CoComplex_1d = [],
    lbnd: _CoComplex = 0,
    scl: _CoComplex = 1,
    axis: _Index = 0,
) -> _Complex_nd: ...
@overload
def polyint(
    c: _nt.CoComplex_nd,
    m: _Index,
    k: _ToComplex | _nt.ToComplex_1d,
    lbnd: _CoComplex = 0,
    scl: _CoComplex = 1,
    axis: _Index = 0,
) -> _Complex_nd: ...
@overload
def polyint(
    c: _nt.CoComplex_nd,
    m: _Index = 1,
    *,
    k: _ToComplex | _nt.ToComplex_1d,
    lbnd: _CoComplex = 0,
    scl: _CoComplex = 1,
    axis: _Index = 0,
) -> _Complex_nd: ...
@overload
def polyint(
    c: _nt.ToObject_nd,
    m: _Index = 1,
    k: _ToNumeric_0d | _ToNumeric_1d = [],
    lbnd: _ToNumeric_0d = 0,
    scl: _ToNumeric_0d = 1,
    axis: _Index = 0,
) -> _Object_nd: ...

#
@overload  # workaround for microsoft/pyright#10232
def polyvalfromroots(
    x: _nt._ToArray_nnd[_InexactT], r: _nt.CastsArray[_InexactT, _nt.NeitherShape], tensor: bool = True
) -> _nt.Array[_InexactT]: ...
@overload  # workaround for microsoft/pyright#10232
def polyvalfromroots(
    x: _nt.CastsArray[_InexactT, _nt.NeitherShape], r: _nt._ToArray_nnd[_InexactT], tensor: bool = True
) -> _nt.Array[_InexactT]: ...
@overload
def polyvalfromroots(x: _nt.CastsScalar[_InexactT], r: _InexactT, tensor: bool = True) -> _InexactT: ...
@overload
def polyvalfromroots(x: _InexactT, r: _nt.CastsScalar[_InexactT], tensor: bool = True) -> _InexactT: ...
@overload
def polyvalfromroots(x: _nt.CoFloat64_1nd, r: _nt.CoFloat64_nd, tensor: bool = True) -> _nt.Array[np.float64]: ...
@overload
def polyvalfromroots(x: _nt.CoFloat64_nd, r: _nt.CoFloat64_1nd, tensor: bool = True) -> _nt.Array[np.float64]: ...
@overload
def polyvalfromroots(x: _CoF64, r: _CoF64, tensor: bool = True) -> np.float64: ...
@overload
def polyvalfromroots(x: _nt.ToObject_1nd, r: _ToNumeric_nd, tensor: bool = True) -> _Object_nd: ...
@overload
def polyvalfromroots(x: _ToNumeric_nd, r: _nt.ToObject_1nd, tensor: bool = True) -> _Object_nd: ...

#
@overload
def polyval(x: _CoInt, c: _nt.CoInteger_1d, tensor: bool = True) -> np.float64: ...
@overload
def polyval(x: _ToF64, c: _nt.CoFloat64_1d, tensor: bool = True) -> np.float64: ...
@overload
def polyval(x: _CoF64, c: _nt.ToFloat64_1d, tensor: bool = True) -> np.float64: ...
@overload
def polyval(x: _CoFloat, c: _nt.CoFloating_1d, tensor: bool = True) -> np.floating: ...
@overload
def polyval(x: _ToComplex, c: _nt.CoComplex_1d, tensor: bool = True) -> np.complexfloating: ...
@overload
def polyval(x: _CoComplex, c: _nt.ToComplex_1d, tensor: bool = True) -> np.complexfloating: ...
@overload
def polyval(x: _nt.ToFloat64_1nd, c: _nt.CoFloat64_1nd, tensor: bool = True) -> _F64_nd: ...
@overload
def polyval(x: _nt.CoFloat64_1nd, c: _nt.ToFloat64_1nd, tensor: bool = True) -> _F64_nd: ...
@overload
def polyval(x: _nt.CoFloating_1nd, c: _nt.CoFloating_1nd, tensor: bool = True) -> _Float_nd: ...
@overload
def polyval(x: _nt.ToComplex_1nd, c: _nt.CoComplex_1nd, tensor: bool = True) -> _Complex_nd: ...
@overload
def polyval(x: _nt.CoComplex_1nd, c: _nt.ToComplex_1nd, tensor: bool = True) -> _Complex_nd: ...
@overload
def polyval(x: _nt.ToObject_1nd, c: _ToNumeric_nd, tensor: bool = True) -> _Object_nd: ...
@overload
def polyval(x: _ToNumeric_nd, c: _nt.ToObject_1nd, tensor: bool = True) -> _Object_nd: ...

#
@overload
def polyval2d(x: _CoInt, y: _CoInt, c: _nt.CoInteger_1d) -> np.float64: ...
@overload
def polyval2d(x: _ToF64, y: _CoF64, c: _nt.CoFloat64_1d) -> np.float64: ...
@overload
def polyval2d(x: _CoF64, y: _ToF64, c: _nt.CoFloat64_1d) -> np.float64: ...
@overload
def polyval2d(x: _CoF64, y: _CoF64, c: _nt.ToFloat64_1d) -> np.float64: ...
@overload
def polyval2d(x: _CoFloat, y: _CoFloat, c: _nt.CoFloating_1d) -> np.floating: ...
@overload
def polyval2d(x: _ToComplex, y: _CoComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polyval2d(x: _CoComplex, y: _ToComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polyval2d(x: _CoComplex, y: _CoComplex, c: _nt.ToComplex_1d) -> np.complexfloating: ...
@overload
def polyval2d(x: _nt.ToFloat64_1nd, y: _nt.CoFloat64_nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polyval2d(x: _nt.CoFloat64_1nd, y: _nt.ToFloat64_nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polyval2d(x: _nt.CoFloat64_1nd, y: _nt.CoFloat64_nd, c: _nt.ToFloat64_1nd) -> _F64_nd: ...
@overload
def polyval2d(x: _nt.ToFloat64_nd, y: _nt.CoFloat64_1nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polyval2d(x: _nt.CoFloat64_nd, y: _nt.ToFloat64_1nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polyval2d(x: _nt.CoFloat64_nd, y: _nt.CoFloat64_1nd, c: _nt.ToFloat64_1nd) -> _F64_nd: ...
@overload
def polyval2d(x: _nt.CoFloating_1nd, y: _nt.CoFloating_nd, c: _nt.CoFloating_1nd) -> _Float_nd: ...
@overload
def polyval2d(x: _nt.CoFloating_nd, y: _nt.CoFloating_1nd, c: _nt.CoFloating_1nd) -> _Float_nd: ...
@overload
def polyval2d(x: _nt.ToComplex_1nd, y: _nt.CoComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polyval2d(x: _nt.CoComplex_1nd, y: _nt.ToComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polyval2d(x: _nt.CoComplex_1nd, y: _nt.CoComplex_nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polyval2d(x: _nt.ToComplex_nd, y: _nt.CoComplex_1nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polyval2d(x: _nt.CoComplex_nd, y: _nt.ToComplex_1nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polyval2d(x: _nt.CoComplex_nd, y: _nt.CoComplex_1nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polyval2d(x: _nt.ToObject_1nd, y: _ToNumeric_nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polyval2d(x: _ToNumeric_nd, y: _nt.ToObject_1nd, c: _ToNumeric_nd) -> _Object_nd: ...

# keep in sync with *val2d
@overload
def polygrid2d(x: _CoInt, y: _CoInt, c: _nt.CoInteger_1d) -> np.float64: ...
@overload
def polygrid2d(x: _ToF64, y: _CoF64, c: _nt.CoFloat64_1d) -> np.float64: ...
@overload
def polygrid2d(x: _CoF64, y: _ToF64, c: _nt.CoFloat64_1d) -> np.float64: ...
@overload
def polygrid2d(x: _CoF64, y: _CoF64, c: _nt.ToFloat64_1d) -> np.float64: ...
@overload
def polygrid2d(x: _CoFloat, y: _CoFloat, c: _nt.CoFloating_1d) -> np.floating: ...
@overload
def polygrid2d(x: _ToComplex, y: _CoComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polygrid2d(x: _CoComplex, y: _ToComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polygrid2d(x: _CoComplex, y: _CoComplex, c: _nt.ToComplex_1d) -> np.complexfloating: ...
@overload
def polygrid2d(x: _nt.ToFloat64_1nd, y: _nt.CoFloat64_nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polygrid2d(x: _nt.CoFloat64_1nd, y: _nt.ToFloat64_nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polygrid2d(x: _nt.CoFloat64_1nd, y: _nt.CoFloat64_nd, c: _nt.ToFloat64_1nd) -> _F64_nd: ...
@overload
def polygrid2d(x: _nt.ToFloat64_nd, y: _nt.CoFloat64_1nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polygrid2d(x: _nt.CoFloat64_nd, y: _nt.ToFloat64_1nd, c: _nt.CoFloat64_1nd) -> _F64_nd: ...
@overload
def polygrid2d(x: _nt.CoFloat64_nd, y: _nt.CoFloat64_1nd, c: _nt.ToFloat64_1nd) -> _F64_nd: ...
@overload
def polygrid2d(x: _nt.CoFloating_1nd, y: _nt.CoFloating_nd, c: _nt.CoFloating_1nd) -> _Float_nd: ...
@overload
def polygrid2d(x: _nt.CoFloating_nd, y: _nt.CoFloating_1nd, c: _nt.CoFloating_1nd) -> _Float_nd: ...
@overload
def polygrid2d(x: _nt.ToComplex_1nd, y: _nt.CoComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid2d(x: _nt.CoComplex_1nd, y: _nt.ToComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid2d(x: _nt.CoComplex_1nd, y: _nt.CoComplex_nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid2d(x: _nt.ToComplex_nd, y: _nt.CoComplex_1nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid2d(x: _nt.CoComplex_nd, y: _nt.ToComplex_1nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid2d(x: _nt.CoComplex_nd, y: _nt.CoComplex_1nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid2d(x: _nt.ToObject_1nd, y: _ToNumeric_nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polygrid2d(x: _ToNumeric_nd, y: _nt.ToObject_1nd, c: _ToNumeric_nd) -> _Object_nd: ...

#
@overload
def polyval3d(x: _CoF64, y: _CoF64, z: _CoF64, c: _nt.CoFloating_1d) -> np.float64: ...
@overload
def polyval3d(x: _CoFloat, y: _CoFloat, z: _CoFloat, c: _nt.CoFloating_1d) -> np.floating: ...
@overload
def polyval3d(
    x: _nt.CoFloating_1nd, y: _nt.CoFloating_nd, z: _nt.CoFloating_nd, c: _nt.CoFloating_1nd
) -> _Float_nd: ...
@overload
def polyval3d(
    x: _nt.CoFloating_nd, y: _nt.CoFloating_1nd, z: _nt.CoFloating_nd, c: _nt.CoFloating_1nd
) -> _Float_nd: ...
@overload
def polyval3d(
    x: _nt.CoFloating_nd, y: _nt.CoFloating_nd, z: _nt.CoFloating_1nd, c: _nt.CoFloating_1nd
) -> _Float_nd: ...
@overload
def polyval3d(x: _ToComplex, y: _CoComplex, z: _CoComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polyval3d(x: _CoComplex, y: _ToComplex, z: _CoComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polyval3d(x: _CoComplex, y: _CoComplex, z: _ToComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polyval3d(x: _CoComplex, y: _CoComplex, z: _CoComplex, c: _nt.ToComplex_1d) -> np.complexfloating: ...
@overload
def polyval3d(x: _nt.ToComplex_1nd, y: _nt.CoComplex_nd, z: _nt.CoComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polyval3d(x: _nt.CoComplex_nd, y: _nt.ToComplex_1nd, z: _nt.CoComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polyval3d(x: _nt.CoComplex_nd, y: _nt.CoComplex_nd, z: _nt.ToComplex_1nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polyval3d(x: _nt.CoComplex_1nd, y: _nt.CoComplex_nd, z: _nt.CoComplex_nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polyval3d(x: _nt.CoComplex_nd, y: _nt.CoComplex_1nd, z: _nt.CoComplex_nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polyval3d(x: _nt.CoComplex_nd, y: _nt.CoComplex_nd, z: _nt.CoComplex_1nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polyval3d(x: _nt.ToObject_1nd, y: _ToNumeric_nd, z: _ToNumeric_nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polyval3d(x: _nt.ToObject_1nd, y: _nt.ToObject_1nd, z: _ToNumeric_nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polyval3d(x: _ToNumeric_nd, y: _ToNumeric_nd, z: _nt.ToObject_1nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polyval3d(x: _ToNumeric_nd, y: _ToNumeric_nd, z: _ToNumeric_nd, c: _nt.ToObject_1nd) -> _Object_nd: ...

# keep in sync with *val3d
@overload
def polygrid3d(x: _CoFloat, y: _CoFloat, z: _CoFloat, c: _nt.CoFloating_1d) -> np.floating: ...
@overload
def polygrid3d(
    x: _nt.CoFloating_1nd, y: _nt.CoFloating_nd, z: _nt.CoFloating_nd, c: _nt.CoFloating_1nd
) -> _Float_nd: ...
@overload
def polygrid3d(
    x: _nt.CoFloating_nd, y: _nt.CoFloating_1nd, z: _nt.CoFloating_nd, c: _nt.CoFloating_1nd
) -> _Float_nd: ...
@overload
def polygrid3d(
    x: _nt.CoFloating_nd, y: _nt.CoFloating_nd, z: _nt.CoFloating_1nd, c: _nt.CoFloating_1nd
) -> _Float_nd: ...
@overload
def polygrid3d(x: _ToComplex, y: _CoComplex, z: _CoComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polygrid3d(x: _CoComplex, y: _ToComplex, z: _CoComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polygrid3d(x: _CoComplex, y: _CoComplex, z: _ToComplex, c: _nt.CoComplex_1d) -> np.complexfloating: ...
@overload
def polygrid3d(x: _CoComplex, y: _CoComplex, z: _CoComplex, c: _nt.ToComplex_1d) -> np.complexfloating: ...
@overload
def polygrid3d(x: _nt.ToComplex_1nd, y: _nt.CoComplex_nd, z: _nt.CoComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid3d(x: _nt.CoComplex_nd, y: _nt.ToComplex_1nd, z: _nt.CoComplex_nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid3d(x: _nt.CoComplex_nd, y: _nt.CoComplex_nd, z: _nt.ToComplex_1nd, c: _nt.CoComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid3d(x: _nt.CoComplex_1nd, y: _nt.CoComplex_nd, z: _nt.CoComplex_nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid3d(x: _nt.CoComplex_nd, y: _nt.CoComplex_1nd, z: _nt.CoComplex_nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid3d(x: _nt.CoComplex_nd, y: _nt.CoComplex_nd, z: _nt.CoComplex_1nd, c: _nt.ToComplex_1nd) -> _Complex_nd: ...
@overload
def polygrid3d(x: _nt.ToObject_1nd, y: _ToNumeric_nd, z: _ToNumeric_nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polygrid3d(x: _nt.ToObject_1nd, y: _nt.ToObject_1nd, z: _ToNumeric_nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polygrid3d(x: _ToNumeric_nd, y: _ToNumeric_nd, z: _nt.ToObject_1nd, c: _ToNumeric_nd) -> _Object_nd: ...
@overload
def polygrid3d(x: _ToNumeric_nd, y: _ToNumeric_nd, z: _ToNumeric_nd, c: _nt.ToObject_1nd) -> _Object_nd: ...

#
@overload
def polyvander(x: _nt.ToFloat64_nd | _nt.CoInteger_nd, deg: _Index) -> _F64_nd: ...
@overload
def polyvander(x: _nt.CoFloating_nd, deg: _Index) -> _Float_nd: ...
@overload
def polyvander(x: _nt.ToComplex128_nd, deg: _Index) -> _C128_nd: ...
@overload
def polyvander(x: _nt.ToComplex_nd, deg: _Index) -> _Complex_nd: ...
@overload
def polyvander(x: _nt.CoComplex_nd, deg: _Index) -> _Inexact_nd: ...
@overload
def polyvander(x: _nt.ToObject_nd, deg: _Index) -> _Object_nd: ...
@overload
def polyvander(x: _ToNumeric_nd, deg: _Index) -> _nt.Array: ...

#
@overload
def polyvander2d(x: _nt.CoInteger_nd, y: _nt.CoInteger_nd, deg: _Indices) -> _F64_nd: ...
@overload
def polyvander2d(x: _nt.ToFloat64_nd, y: _nt.CoFloat64_nd, deg: _Indices) -> _F64_nd: ...
@overload
def polyvander2d(x: _nt.CoFloat64_nd, y: _nt.ToFloat64_nd, deg: _Indices) -> _F64_nd: ...
@overload
def polyvander2d(x: _nt.CoFloating_nd, y: _nt.CoFloating_nd, deg: _Indices) -> _Float_nd: ...
@overload
def polyvander2d(x: _nt.ToComplex_nd, y: _nt.CoComplex_nd, deg: _Indices) -> _Complex_nd: ...
@overload
def polyvander2d(x: _nt.CoComplex_nd, y: _nt.ToComplex_nd, deg: _Indices) -> _Complex_nd: ...
@overload
def polyvander2d(x: _nt.ToObject_nd, y: _ToNumeric_nd, deg: _Indices) -> _Object_nd: ...
@overload
def polyvander2d(x: _ToNumeric_nd, y: _nt.ToObject_nd, deg: _Indices) -> _Object_nd: ...
@overload
def polyvander2d(x: _ToNumeric_nd, y: _ToNumeric_nd, deg: _Indices) -> _nt.Array: ...

#
@overload
def polyvander3d(x: _nt.CoInteger_nd, y: _nt.CoInteger_nd, z: _nt.CoInteger_nd, deg: _Indices) -> _F64_nd: ...
@overload
def polyvander3d(x: _nt.ToFloat64_nd, y: _nt.CoFloat64_nd, z: _nt.CoFloat64_nd, deg: _Indices) -> _F64_nd: ...
@overload
def polyvander3d(x: _nt.CoFloat64_nd, y: _nt.ToFloat64_nd, z: _nt.CoFloat64_nd, deg: _Indices) -> _F64_nd: ...
@overload
def polyvander3d(x: _nt.CoFloat64_nd, y: _nt.CoFloat64_nd, z: _nt.ToFloat64_nd, deg: _Indices) -> _F64_nd: ...
@overload
def polyvander3d(x: _nt.CoFloating_nd, y: _nt.CoFloating_nd, z: _nt.CoFloating_nd, deg: _Indices) -> _Float_nd: ...
@overload
def polyvander3d(x: _nt.ToComplex_nd, y: _nt.CoComplex_nd, z: _nt.CoComplex_nd, deg: _Indices) -> _Complex_nd: ...
@overload
def polyvander3d(x: _nt.CoComplex_nd, y: _nt.ToComplex_nd, z: _nt.CoComplex_nd, deg: _Indices) -> _Complex_nd: ...
@overload
def polyvander3d(x: _nt.CoComplex_nd, y: _nt.CoComplex_nd, z: _nt.ToComplex_nd, deg: _Indices) -> _Complex_nd: ...
@overload
def polyvander3d(x: _nt.ToObject_nd, y: _ToNumeric_nd, z: _ToNumeric_nd, deg: _Indices) -> _Object_nd: ...
@overload
def polyvander3d(x: _ToNumeric_nd, y: _nt.ToObject_nd, z: _ToNumeric_nd, deg: _Indices) -> _Object_nd: ...
@overload
def polyvander3d(x: _ToNumeric_nd, y: _ToNumeric_nd, z: _nt.ToObject_nd, deg: _Indices) -> _Object_nd: ...
@overload
def polyvander3d(x: _ToNumeric_nd, y: _ToNumeric_nd, z: _ToNumeric_nd, deg: _Indices) -> _nt.Array: ...

#
@overload
def polyfit(
    x: _nt.ToFloat64_1d | _nt.CoInteger_1d,
    y: _nt.ToFloat64_nd | _nt.CoInteger_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    full: L[False] = False,
    w: _nt.ToFloating_1d | None = None,
) -> _F64_nd: ...
@overload
def polyfit(
    x: _nt.ToFloat64_1d | _nt.CoInteger_1d,
    y: _nt.ToFloat64_nd | _nt.CoInteger_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.float64]: ...
@overload
def polyfit(
    x: _nt.ToFloat64_1d | _nt.CoInteger_1d,
    y: _nt.ToFloat64_nd | _nt.CoInteger_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    *,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.float64]: ...
@overload
def polyfit(
    x: _nt.ToFloating_1d,
    y: _nt.CoFloating_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    full: L[False] = False,
    w: _nt.ToFloating_1d | None = None,
) -> _Float_nd: ...
@overload
def polyfit(
    x: _nt.ToFloating_1d,
    y: _nt.CoFloating_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.floating]: ...
@overload
def polyfit(
    x: _nt.ToFloating_1d,
    y: _nt.CoFloating_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    *,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.floating]: ...
@overload
def polyfit(
    x: _nt.ToComplex_1d,
    y: _nt.CoComplex_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    full: L[False] = False,
    w: _nt.ToFloating_1d | None = None,
) -> _Complex_nd: ...
@overload
def polyfit(
    x: _nt.CoComplex_1d,
    y: _nt.ToComplex_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    full: L[False] = False,
    w: _nt.ToFloating_1d | None = None,
) -> _Complex_nd: ...
@overload
def polyfit(
    x: _nt.ToComplex_1d,
    y: _nt.CoComplex_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.complexfloating]: ...
@overload
def polyfit(
    x: _nt.CoComplex_1d,
    y: _nt.ToComplex_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.complexfloating]: ...
@overload
def polyfit(
    x: _nt.CoComplex_1d,
    y: _nt.ToComplex_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    *,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.complexfloating]: ...
@overload
def polyfit(
    x: _nt.ToComplex_1d,
    y: _nt.CoComplex_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    *,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.complexfloating]: ...
@overload
def polyfit(
    x: _nt.ToObject_1d,
    y: _ToNumeric_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    full: L[False] = False,
    w: _nt.ToFloating_1d | None = None,
) -> _Object_nd: ...
@overload
def polyfit(
    x: _ToNumeric_1d,
    y: _nt.ToObject_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.object_]: ...
@overload
def polyfit(
    x: _nt.ToObject_1d,
    y: _ToNumeric_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    *,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.object_]: ...
@overload
def polyfit(
    x: _ToNumeric_1d,
    y: _nt.ToObject_nd,
    deg: int | _nt.CoInteger_1d,
    rcond: float | None = None,
    *,
    full: L[True],
    w: _nt.ToFloating_1d | None = None,
) -> _ArrayAndFitResult[np.object_]: ...

#
@overload
def polycompanion(c: _nt.CoFloating_1d) -> _nt.Array2D[np.float64]: ...
@overload
def polycompanion(c: _nt.ToComplex_1d) -> _nt.Array2D[np.complex128]: ...
@overload
def polycompanion(c: _nt.ToObject_1d) -> _nt.Array2D[np.object_]: ...

#
@overload
def polyroots(c: _nt.CoFloating_1d) -> _F64_1d: ...
@overload
def polyroots(c: _nt.ToComplex_1d) -> _C128_1d: ...
@overload
def polyroots(c: _nt.ToObject_1d) -> _Object_1d: ...
