from _typeshed import Incomplete

PRIMARY_PARTITION_KEY: str
SECONDARY_PARTITION_KEY: str
METADATA_TABLE: str
REFERENCE_TABLE: str
TRANSACTION_TABLE: str
OBJECT_TABLE: str
TABLE_SCHEMA_TABLE: str
METADATA_KEY: str
SCHEMA_TABLE_NAME_FIELD: str
SCHEMA_NAME_FIELD: str
SCHEMA_VERSION_FIELD: str
CLASS_OBJECT: str
CLASS_OBJECT_META: str
OBJECT_ID: str
OBJECT_VERSION: str
TABLE_SCHEMA__TABLE_NAME: str
TABLE_SCHEMA__TABLE_VERSION: str
TABLE_SCHEMA__CREATED_AT: str
TABLE_SCHEMA: Incomplete
