from __future__ import annotations

from typing import Any

def user_block_cleanup(user_id: str | int, tombstone_data: dict[str, Any]) -> None: ...
def user_restore_cleanup(user_id: str | int) -> None: ...
def delete_record(recid: str, tombstone_data: dict[str, Any]) -> None: ...
def restore_record(recid: str) -> None: ...
