from typing import Any, Callable

from flask_sqlalchemy import SQLAlchemy as FlaskSQLAlchemy
from invenio_db.shared import db as _db
from sqlalchemy.engine import Engine

def alembic_test_context() -> dict[str, bool | Callable[..., bool]]: ...
def create_alembic_version_table() -> None: ...
def drop_alembic_version_table() -> None: ...
def has_table(engine: Engine, table: str) -> bool: ...
def versioning_models_registered(manager: Any, base: Any) -> bool: ...
def versioning_model_classname(manager: Any, model: Any) -> str: ...
def rebuild_encrypted_properties(
    old_key: str, model: Any, properties: list[str], db: FlaskSQLAlchemy = _db
) -> None: ...
