from __future__ import annotations

from typing import Any

from invenio_records.systemfields import SystemField

class RecordStatisticsField(SystemField):
    def _get_record_stats(self, record): ...
    def __get__(self, record, owner=None): ...
    def pre_commit(self, record, **kwargs) -> None: ...
    def pre_dump(self, record, data, dumper: Any | None = ...) -> None: ...
