from __future__ import annotations

from typing import Any, List

class CommonFieldsMixin:
    def get_doi(self, obj: dict[str, Any]) -> Any: ...
    def get_locations(self, obj: dict[str, Any]) -> Any: ...
    def get_titles(self, obj: dict[str, Any]) -> Any: ...
    def get_identifiers(self, obj: dict[str, Any]) -> List[str] | Any: ...
    def get_creators(self, obj: dict[str, Any]) -> List[str] | Any: ...
    def get_publishers(self, obj: dict[str, Any]) -> List[str] | Any: ...
    def get_contributors(self, obj: dict[str, Any]) -> List[str] | Any: ...
