"""Constants for the Arrowhead alarm integration."""

DEF_ENCODING = "ascii"
DEF_READ_LENGTH = 1024

AUTH_WELCOME_MSG = "Welcome"
AUTH_LOGIN_MSG = "login: "
AUTH_PASSWORD_PROMPT = "password: "

COMMAND_OK_PREFIX = "OK"
COMMAND_ERROR_PREFIX = "ERR"

DEFAULT_PORT = 9000
DEFAULT_USER_ID = 1
DEFAULT_USER_PIN = 1234
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "admin"

DEFAULT_MAX_ZONES = 8
DEFAULT_MAX_USERS = 2000
DEFAULT_MAX_OUTPUTS = 4
DEFAULT_MAX_AREAS = 16

DEFAULT_VIRTUAL_KEYPAD_NUM = 32

ZONE_EXPANDER_COUNT = 32
OUTPUT_EXPANDER_COUNT = 8
PROX_EXPANDER_COUNT = 32
