# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.models.characters_character_id_skills_get_skills_inner import CharactersCharacterIdSkillsGetSkillsInner

class TestCharactersCharacterIdSkillsGetSkillsInner(unittest.TestCase):
    """CharactersCharacterIdSkillsGetSkillsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CharactersCharacterIdSkillsGetSkillsInner:
        """Test CharactersCharacterIdSkillsGetSkillsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CharactersCharacterIdSkillsGetSkillsInner`
        """
        model = CharactersCharacterIdSkillsGetSkillsInner()
        if include_optional:
            return CharactersCharacterIdSkillsGetSkillsInner(
                active_skill_level = 56,
                skill_id = 56,
                skillpoints_in_skill = 56,
                trained_skill_level = 56
            )
        else:
            return CharactersCharacterIdSkillsGetSkillsInner(
                active_skill_level = 56,
                skill_id = 56,
                skillpoints_in_skill = 56,
                trained_skill_level = 56,
        )
        """

    def testCharactersCharacterIdSkillsGetSkillsInner(self):
        """Test CharactersCharacterIdSkillsGetSkillsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
