# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_genoa_client.models.characters_character_id_orders_get_inner import CharactersCharacterIdOrdersGetInner

class TestCharactersCharacterIdOrdersGetInner(unittest.TestCase):
    """CharactersCharacterIdOrdersGetInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CharactersCharacterIdOrdersGetInner:
        """Test CharactersCharacterIdOrdersGetInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CharactersCharacterIdOrdersGetInner`
        """
        model = CharactersCharacterIdOrdersGetInner()
        if include_optional:
            return CharactersCharacterIdOrdersGetInner(
                duration = 56,
                escrow = 1.337,
                is_buy_order = True,
                is_corporation = True,
                issued = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location_id = 56,
                min_volume = 56,
                order_id = 56,
                price = 1.337,
                range = '1',
                region_id = 56,
                type_id = 56,
                volume_remain = 56,
                volume_total = 56
            )
        else:
            return CharactersCharacterIdOrdersGetInner(
                duration = 56,
                is_corporation = True,
                issued = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location_id = 56,
                order_id = 56,
                price = 1.337,
                range = '1',
                region_id = 56,
                type_id = 56,
                volume_remain = 56,
                volume_total = 56,
        )
        """

    def testCharactersCharacterIdOrdersGetInner(self):
        """Test CharactersCharacterIdOrdersGetInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
