# here is the package imports
from layerlearn.flexiblestacked import FlexibleStackedClassifier
from layerlearn.flexiblestacked import FlexibleStackedRegressor
from layerlearn.baseLinear import LinearForestRegressor
from layerlearn.baseLinear import LinearSupportRegressor
from layerlearn.baseLinear import LinearDecisionRegressor
from layerlearn.baseLinear import LinearKNNRegressor
from layerlearn.baseLinear import LinearXGBRegressor
from layerlearn.baseLinear import LinearCatRegressor
from layerlearn.baseLinear import LinearGradientRegressor
from layerlearn.baseLinear import LinearAdaRegressor
from layerlearn.baseLinear import LinearLightRegressor
from layerlearn.baseLightR import LightForestRegressor
from layerlearn.baseLightR import LightSupportRegressor
from layerlearn.baseLightR import LightDecisionRegressor
from layerlearn.baseLightR import LightKNNRegressor
from layerlearn.baseLightR import LightXGBRegressor
from layerlearn.baseLightR import LightCatRegressor
from layerlearn.baseLightR import LightGradientRegressor
from layerlearn.baseLightR import LightAdaRegressor
from layerlearn.baseLightR import LightLinearRegressor
from layerlearn.baseXGBR import XGBForestRegressor
from layerlearn.baseXGBR import XGBSupportRegressor
from layerlearn.baseXGBR import XGBDecisionRegressor
from layerlearn.baseXGBR import XGBKNNRegressor
from layerlearn.baseXGBR import XGBLightRegressor
from layerlearn.baseXGBR import XGBCatRegressor
from layerlearn.baseXGBR import XGBGradientRegressor
from layerlearn.baseXGBR import XGBAdaRegressor
from layerlearn.baseXGBR import XGBLinearRegressor
from layerlearn.baseCatR import CatForestRegressor
from layerlearn.baseCatR import CatSupportRegressor
from layerlearn.baseCatR import CatDecisionRegressor
from layerlearn.baseCatR import CatKNNRegressor
from layerlearn.baseCatR import CatLightRegressor
from layerlearn.baseCatR import CatXGBRegressor
from layerlearn.baseCatR import CatGradientRegressor
from layerlearn.baseCatR import CatAdaRegressor
from layerlearn.baseCatR import CatLinearRegressor
from layerlearn.baseGradientR import GradientForestRegressor
from layerlearn.baseGradientR import GradientSupportRegressor
from layerlearn.baseGradientR import GradientDecisionRegressor
from layerlearn.baseGradientR import GradientKNNRegressor
from layerlearn.baseGradientR import GradientLightRegressor
from layerlearn.baseGradientR import GradientXGBRegressor
from layerlearn.baseGradientR import GradientCatRegressor
from layerlearn.baseGradientR import GradientAdaRegressor
from layerlearn.baseGradientR import GradientLinearRegressor
from layerlearn.baseAdaR import AdaForestRegressor
from layerlearn.baseAdaR import AdaSupportRegressor
from layerlearn.baseAdaR import AdaDecisionRegressor
from layerlearn.baseAdaR import AdaKNNRegressor
from layerlearn.baseAdaR import AdaLightRegressor
from layerlearn.baseAdaR import AdaXGBRegressor
from layerlearn.baseAdaR import AdaCatRegressor
from layerlearn.baseAdaR import AdaGradientRegressor
from layerlearn.baseAdaR import AdaLinearRegressor
from layerlearn.baseForestR import ForestSupportRegressor
from layerlearn.baseForestR import ForestDecisionRegressor
from layerlearn.baseForestR import ForestKNNRegressor
from layerlearn.baseForestR import ForestLightRegressor
from layerlearn.baseForestR import ForestXGBRegressor
from layerlearn.baseForestR import ForestCatRegressor
from layerlearn.baseForestR import ForestGradientRegressor
from layerlearn.baseForestR import ForestAdaRegressor
from layerlearn.baseForestR import ForestLinearRegressor
from layerlearn.baseSupportR import SupportForestRegressor
from layerlearn.baseSupportR import SupportDecisionRegressor
from layerlearn.baseSupportR import SupportKNNRegressor
from layerlearn.baseSupportR import SupportLightRegressor
from layerlearn.baseSupportR import SupportXGBRegressor
from layerlearn.baseSupportR import SupportCatRegressor
from layerlearn.baseSupportR import SupportGradientRegressor
from layerlearn.baseSupportR import SupportAdaRegressor
from layerlearn.baseSupportR import SupportLinearRegressor
from layerlearn.baseDecisionR import DecisionForestRegressor
from layerlearn.baseDecisionR import DecisionSupportRegressor
from layerlearn.baseDecisionR import DecisionKNNRegressor
from layerlearn.baseDecisionR import DecisionLightRegressor
from layerlearn.baseDecisionR import DecisionXGBRegressor
from layerlearn.baseDecisionR import DecisionCatRegressor
from layerlearn.baseDecisionR import DecisionGradientRegressor
from layerlearn.baseDecisionR import DecisionAdaRegressor
from layerlearn.baseDecisionR import DecisionLinearRegressor
from layerlearn.baseKNNR import KNNForestRegressor
from layerlearn.baseKNNR import KNNSupportRegressor
from layerlearn.baseKNNR import KNNDecisionRegressor
from layerlearn.baseKNNR import KNNLightRegressor
from layerlearn.baseKNNR import KNNXGBRegressor
from layerlearn.baseKNNR import KNNCatRegressor
from layerlearn.baseKNNR import KNNGradientRegressor
from layerlearn.baseKNNR import KNNAdaRegressor
from layerlearn.baseKNNR import KNNLinearRegressor
from layerlearn.baseAdaC import AdaBoostClassifier
from layerlearn.baseAdaC import AdaCatClassifier
from layerlearn.baseAdaC import AdaGradientClassifier
from layerlearn.baseAdaC import AdaLightClassifier
from layerlearn.baseAdaC import AdaXGBClassifier
from layerlearn.baseAdaC import AdaForestClassifier
from layerlearn.baseAdaC import AdaSupportClassifier
from layerlearn.baseAdaC import AdaLinearClassifier
from layerlearn.baseAdaC import AdaKNNClassifier

# here is the version of the package
__version__ = "1.5.9"