### COLUMN NAMES ###
# Provided in this file are dicts to standardize column names as necessary #

def col_map():
    return {
        'schedule':{
            'season':'season',
            'id':'game_id',
            'game_title':'game_title',
            'game_date':'game_date',
            'gameType':'season_type',
            'neutralSite':'neutral_site',
            'startTimeUTC':'start_time_utc',
            'start_time_est':'start_time_est',
            'easternUTCOffset':'eastern_utc',
            'venueUTCOffset':'venue_utc',
            'venueTimezone':'venue_timezone',
            'gameState':'game_state',
            'gameScheduleState':'game_schedule_state',
            'tvBroadcasts':'tv_broadcasts',
            'threeMinRecap':'three_min_recap',
            'threeMinRecapFr':'three_min_recap_fr',
            'condensedGame':'condensed_game',
            'condensedGameFr':'condensed_game_fr',
            'gameCenterLink':'gamecenter_link',
            'venue.default':'venue',
            'awayTeam.id':'away_team_id',
            'homeTeam.id':'home_team_id',
            'awayTeam.abbrev':'away_team_abbr',
            'homeTeam.abbrev':'home_team_abbr',
            'awayTeam.logo':'away_team_logo',
            'homeTeam.logo':'home_team_logo',
            'awayTeam.awaySplitSquad':'away_team_split_squad',
            'homeTeam.homeSplitSquad':'home_team_split_squad',
            'awayTeam.score':'away_score',
            'homeTeam.score':'home_score',
            'periodDescriptor.number':'period',
            'periodDescriptor.maxRegulationPeriods':'period_max_regulation',
            'periodDescriptor.periodType':'period_type',
            'gameOutcome.lastPeriodType':'period_type_last',
            'gameOutcome.otPeriods':'ot_periods',
            'seriesUrl':'series_url',
            'seriesStatus.round':'series_round',
            'seriesStatus.seriesAbbrev':'series_abbr',
            'seriesStatus.seriesTitle':'series_name',
            'seriesStatus.seriesLetter':'series_letter',
            'seriesStatus.neededToWin':'series_games_needed_to_win',
            'seriesStatus.gameNumberOfSeries':'series_game_num',
            'seriesStatus.topSeedTeamAbbrev':'top_seed_team_abbr',
            'seriesStatus.bottomSeedTeamAbbrev':'bottom_seed_team_abbr',
            'seriesStatus.topSeedWins':'top_seed_wins',
            'seriesStatus.bottomSeedWins':'bottom_seed_wins',
            'clock.timeRemaining':'period_time_remaining',
            'clock.secondsRemaining':'period_seconds_remaining',
            'clock.running':'period_clock_running',
            'clock.inIntermission':'game_in_intermission'
        },
        'season_info':{
            'id':'season',
            'formattedSeasonId':'season_name',
            'seasonOrdinal':'season_ordinal',
            'startDate':'start_date',
            'endDate':'end_date',
            'numberOfGames':'games_num',
            'totalRegularSeasonGames':'regular_season_total_games_num',
            'totalPlayoffGames':'playoffs_total_games_num',
            'regularSeasonStartDate':'regular_season_start_date',
            'regularSeasonEndDate':'regular_season_end_date',
            'standingsStart':'standings_start_date',
            'standingsEnd':'standings_end_date',
            'allStarGameInUse':'all_star_game',
            'conferencesInUse':'conferences',
            'divisionsInUse':'divisions',
            'wildcardInUse':'wildcard',
            'entryDraftInUse':'entry_draft',
            'nhlStanleyCupOwner':'nhl_stanley_cup_owner',
            'olympicsParticipation':'olympic_participation',
            'tiesInUse':'ties',
            'pointForOTLossInUse':'ot_loss_point',
            'regulationWinsInUse':'reg_wins',
            'rowInUse':'row',
            'supplementalDraftInUse':'supplemental_draft'
        },
        'standings': {
            "clinchIndicator": "clinch_indicator",
            "conferenceAbbrev": "conference_abbr",
            "conferenceHomeSequence": "conference_home_sequence",
            "conferenceL10Sequence": "conference_last_ten_sequence",
            "conferenceName": "conference_name",
            "conferenceRoadSequence": "conference_road_sequence",
            "conferenceSequence": "conference_sequence",
            "date": "date",
            "divisionAbbrev": "division_abbr",
            "divisionHomeSequence": "division_home_sequence",
            "divisionL10Sequence": "division_last_ten_sequence",
            "divisionName": "division_name",
            "divisionRoadSequence": "division_road_sequence",
            "divisionSequence": "division_sequence",
            "gameTypeId": "game_type_id",
            "gamesPlayed": "games_played",
            "goalDifferential": "goal_differential",
            "goalDifferentialPctg": "goal_differential_percentage",
            "goalAgainst": "goals_against",
            "goalFor": "goals_for",
            "goalsForPctg": "goals_for_percentage",
            "homeGamesPlayed": "home_games_played",
            "homeGoalDifferential": "home_goal_differential",
            "homeGoalsAgainst": "home_goals_against",
            "homeGoalsFor": "home_goals_for",
            "homeLosses": "home_losses",
            "homeOtLosses": "home_overtime_losses",
            "homePoints": "home_points",
            "homeRegulationPlusOtWins": "home_regulation_overtime_wins",
            "homeRegulationWins": "home_regulation_wins",
            "homeTies": "home_ties",
            "homeWins": "home_wins",
            "l10GamesPlayed": "last_ten_games_played",
            "l10GoalDifferential": "last_ten_goal_differential",
            "l10GoalsAgainst": "last_ten_goals_against",
            "l10GoalsFor": "last_ten_goals_for",
            "l10Losses": "last_ten_losses",
            "l10OtLosses": "last_ten_overtime_losses",
            "l10Points": "last_ten_points",
            "l10RegulationPlusOtWins": "last_ten_regulation_overtime_wins",
            "l10RegulationWins": "last_ten_regulation_wins",
            "l10Ties": "last_ten_ties",
            "l10Wins": "last_ten_wins",
            "leagueHomeSequence": "league_home_sequence",
            "leagueL10Sequence": "league_last_ten_sequence",
            "leagueRoadSequence": "league_road_sequence",
            "leagueSequence": "league_sequence",
            "losses": "losses",
            "otLosses": "overtime_losses",
            "pointPctg": "points_percentage",
            "points": "points",
            "regulationPlusOtWinPctg": "regulation_overtime_win_percentage",
            "regulationPlusOtWins": "regulation_overtime_wins",
            "regulationWinPctg": "regulation_win_percentage",
            "regulationWins": "regulation_wins",
            "roadGamesPlayed": "road_games_played",
            "roadGoalDifferential": "road_goal_differential",
            "roadGoalsAgainst": "road_goals_against",
            "roadGoalsFor": "road_goals_for",
            "roadLosses": "road_losses",
            "roadOtLosses": "road_overtime_losses",
            "roadPoints": "road_points",
            "roadRegulationPlusOtWins": "road_regulation_overtime_wins",
            "roadRegulationWins": "road_regulation_wins",
            "roadTies": "road_ties",
            "roadWins": "road_wins",
            "seasonId": "season",
            "shootoutLosses": "shootout_losses",
            "shootoutWins": "shootout_wins",
            "streakCode": "streak_code",
            "streakCount": "streak_count",
            "teamLogo": "team_logo",
            "ties": "ties",
            "waiversSequence": "waivers_sequence",
            "wildcardSequence": "wildcard_sequence",
            "winPctg": "win_percentage",
            "wins": "wins",
            "placeName.default": "place_name",
            "teamName.default": "team_name",
            "teamCommonName.default": "team_common_name",
            "teamAbbrev.default": "team_abbr",
            "seriesUrl": "series_url",
            "seriesTitle": "series_title",
            "seriesAbbrev": "series_abbr",
            "seriesLetter": "series_letter",
            "playoffRound": "playoff_round",
            "topSeedRank": "top_seed_rank",
            "topSeedRankAbbrev": "top_seed_rank_abbr",
            "topSeedWins": "top_seed_wins",
            "bottomSeedRank": "bottom_seed_rank",
            "bottomSeedRankAbbrev": "bottom_seed_rank_abbr",
            "bottomSeedWins": "bottom_seed_wins",
            "winningTeamId": "winning_team_id",
            "losingTeamId": "losing_team_id",
            "topSeedTeam.id": "top_seed_team_id",
            "topSeedTeam.abbrev": "top_seed_team_abbr",
            "topSeedTeam.name.default": "top_seed_team_name",
            "topSeedTeam.commonName.default": "top_seed_team_common_name",
            "topSeedTeam.placeNameWithPreposition.default": "top_seed_team_place_name",
            "topSeedTeam.logo": "top_seed_team_logo",
            "topSeedTeam.darkLogo": "top_seed_team_dark_logo",
            "bottomSeedTeam.id": "bottom_seed_team_id",
            "bottomSeedTeam.abbrev": "bottom_seed_team_abbr",
            "bottomSeedTeam.name.default": "bottom_seed_team_name",
            "bottomSeedTeam.commonName.default": "bottom_seed_team_common_name",
            "bottomSeedTeam.placeNameWithPreposition.default": "bottom_seed_team_place_name",
            "bottomSeedTeam.logo": "bottom_seed_team_logo",
            "bottomSeedTeam.darkLogo": "bottom_seed_team_dark_logo",
            "seriesLogo": "series_logo",
            "wsba_id": "wsba_id"
        },
        'roster':{
            "id": "player_id",
            "team_abbr": "team_abbr",
            "season": "season",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "heading_position": "heading_position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCountry": "birth_country",
            "player_name":"player_name",
            "firstName.default": "player_first_name",
            "lastName.default": "player_last_name",
            "birthCity.default": "birth_city",
            "birthStateProvince.default": "birth_state_province"
            },
        'prospects':{
            "id": "player_id",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCountry": "birth_country",
            "player_name":"player_name",
            "firstName.default": "player_first_name",
            "lastName.default": "player_last_name",
            "birthCity.default": "birth_city",
            "birthStateProvince.default": "birth_state_province",
        },
        'player_info':{
            'playerId': 'player_id',
            'player_name': 'player_name',
            'isActive': 'is_active',
            'currentTeamId': 'current_team_id',
            'currentTeamAbbrev': 'current_team_abbr',
            'badges': 'badges',
            'teamLogo': 'team_logo',
            'sweaterNumber': 'sweater_number',
            'position': 'position',
            'headshot': 'headshot',
            'heroImage': 'hero_image',
            'heightInInches': 'height_in',
            'heightInCentimeters': 'height_cm',
            'weightInPounds': 'weight_lbs',
            'weightInKilograms': 'weight_kg',
            'birthDate': 'birth_date',
            'birthCountry': 'birth_country',
            'shootsCatches': 'handedness',
            'playerSlug': 'player_slug',
            'inTop100AllTime': 'in_top_100_all_time',
            'inHHOF': 'in_hhof',
            'shopLink': 'shop_link',
            'twitterLink': 'twitter_link',
            'watchLink': 'watch_link',
            'last5Games': 'last_5_games',
            'seasonTotals': 'season_totals',
            'awards': 'awards',
            'currentTeamRoster': 'current_team_roster',
            'fullTeamName.default': 'full_team_name',
            'teamCommonName.default': 'team_common_name',
            'teamPlaceNameWithPreposition.default': 'team_place_name_with_preposition',
            'firstName.default': 'player_first_name',
            'lastName.default': 'player_last_name',
            'birthCity.default': 'birth_city',
            'birthStateProvince.default': 'birth_state_province',
            'draftDetails.year': 'draft_year',
            'draftDetails.teamAbbrev': 'draft_team_abbr',
            'draftDetails.round': 'draft_round',
            'draftDetails.pickInRound': 'draft_pick_in_round',
            'draftDetails.overallPick': 'draft_overall_pick',
        },
        'team_info':{
            "id":"team_id",
            "franchiseId":"franchise_id",
            "fullName":"team_name",
            "leagueId":"league_id",
            "triCode":"team_abbr",
            "logo_light":"logo_light",
            "logo_dark":"logo_dark",
            "country3Code":"country_abbr",
            "countryCode":"country_abbr_2",
            "countryName":"country_name",
            "hasPlayerStats":"has_player_stats",
            "imageUrl":"country_flag_large",
            "isActive":"is_active",
            "nationalityName":"nationality",
            "olympicUrl":"olympic_url",
            "thumbnailUrl":"thumbnail_url"
        },
        'draft_rankings':{
            "id": "player_id",
            "player_name":"player_name",
            "firstName": "player_first_name",
            "lastName": "player_last_name",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCity": "birth_city",
            "birthCountry": "birth_country",
            "birthStateProvince": "birth_state_province",
            "lastAmateurClub": "last_amateur_club",
            "lastAmateurLeague": "last_amateur_league",
            "midtermRank":"midterm_rank",
            "finalRank":"final_rank"
        },
        'edge':{
            'player_name':'player_name',
            'season':'season',
            'wsba_id':'wsba_id',
            'seasonsWithEdgeStats':'seasons_with_edge_stats',
            'sogSummary':'sog_summary',
            'sogDetails':'sog_details',
            'player.id':'player_id',
            'player.firstName.default':'player_first_name',
            'player.lastName.default':'player_last_name',
            'player.birthDate':'player_birth_date',
            'player.shootsCatches':'handedness',
            'player.sweaterNumber':'sweater_number',
            'player.position':'position',
            'player.headshot':'headshot',
            'player.goals':'goals',
            'player.assists':'assists',
            'player.points':'points',
            'player.gamesPlayed':'games_played',
            'player.team.commonName.default':'team_name',
            'player.team.placeNameWithPreposition.default':'team_place_name',
            'player.team.abbrev':'team_abbr',
            'player.team.teamLogo.light':'team_logo_light',
            'player.team.teamLogo.dark':'team_logo_dark',
            'topShotSpeed.imperial':'top_shot_speed',
            'topShotSpeed.metric':'top_shot_speed_metric',
            'topShotSpeed.percentile':'top_shot_speed_percentile',
            'topShotSpeed.leagueAvg.imperial':'league_avg_top_shot_speed',
            'topShotSpeed.leagueAvg.metric':'league_avg_top_shot_speed_metric',
            'topShotSpeed.overlay.player.firstName.default':'top_shot_speed_overlay_player_first_name',
            'topShotSpeed.overlay.player.lastName.default':'top_shot_speed_overlay_player_last_name',
            'topShotSpeed.overlay.gameDate':'top_shot_speed_overlay_game_date',
            'topShotSpeed.overlay.awayTeam.abbrev':'top_shot_speed_overlay_away_team',
            'topShotSpeed.overlay.awayTeam.score':'top_shot_speed_overlay_away_score',
            'topShotSpeed.overlay.homeTeam.abbrev':'top_shot_speed_overlay_home_team',
            'topShotSpeed.overlay.homeTeam.score':'top_shot_speed_overlay_home_score',
            'topShotSpeed.overlay.gameOutcome.lastPeriodType':'top_shot_speed_overlay_last_period_type',
            'topShotSpeed.overlay.periodDescriptor.maxRegulationPeriods':'top_shot_speed_overlay_max_regulation_periods',
            'topShotSpeed.overlay.periodDescriptor.number':'top_shot_speed_overlay_period_number',
            'topShotSpeed.overlay.periodDescriptor.periodType':'top_shot_speed_overlay_period_type',
            'topShotSpeed.overlay.timeInPeriod':'top_shot_speed_overlay_time_in_period',
            'topShotSpeed.overlay.gameType':'top_shot_speed_overlay_game_type',
            'skatingSpeed.speedMax.imperial':'max_speed',
            'skatingSpeed.speedMax.metric':'max_speed_metric',
            'skatingSpeed.speedMax.percentile':'max_speed_percentile',
            'skatingSpeed.speedMax.leagueAvg.imperial':'league_avg_max_speed',
            'skatingSpeed.speedMax.leagueAvg.metric':'league_avg_max_speed_metric',
            'skatingSpeed.speedMax.overlay.player.firstName.default':'max_speed_overlay_player_first_name',
            'skatingSpeed.speedMax.overlay.player.lastName.default':'max_speed_overlay_player_last_name',
            'skatingSpeed.speedMax.overlay.gameDate':'max_speed_overlay_game_date',
            'skatingSpeed.speedMax.overlay.awayTeam.abbrev':'max_speed_overlay_away_team',
            'skatingSpeed.speedMax.overlay.awayTeam.score':'max_speed_overlay_away_score',
            'skatingSpeed.speedMax.overlay.homeTeam.abbrev':'max_speed_overlay_home_team',
            'skatingSpeed.speedMax.overlay.homeTeam.score':'max_speed_overlay_home_score',
            'skatingSpeed.speedMax.overlay.gameOutcome.lastPeriodType':'max_speed_overlay_last_period_type',
            'skatingSpeed.speedMax.overlay.periodDescriptor.maxRegulationPeriods':'max_speed_overlay_max_regulation_periods',
            'skatingSpeed.speedMax.overlay.periodDescriptor.number':'max_speed_overlay_period_number',
            'skatingSpeed.speedMax.overlay.periodDescriptor.periodType':'max_speed_overlay_period_type',
            'skatingSpeed.speedMax.overlay.timeInPeriod':'max_speed_overlay_time_in_period',
            'skatingSpeed.speedMax.overlay.gameType':'max_speed_overlay_game_type',
            'skatingSpeed.burstsOver20.value':'bursts_over_20',
            'skatingSpeed.burstsOver20.percentile':'bursts_over_20_percentile',
            'skatingSpeed.burstsOver20.leagueAvg.value':'league_avg_bursts_over_20',
            'totalDistanceSkated.imperial':'total_distance_skated',
            'totalDistanceSkated.metric':'total_distance_skated_metric',
            'totalDistanceSkated.percentile':'total_distance_skated_percentile',
            'totalDistanceSkated.leagueAvg.imperial':'league_avg_total_distance_skated',
            'totalDistanceSkated.leagueAvg.metric':'league_avg_total_distance_skated_metric',
            'zoneTimeDetails.offensiveZonePctg':'offensive_zone_percentage',
            'zoneTimeDetails.offensiveZonePercentile':'offensive_zone_percentile',
            'zoneTimeDetails.offensiveZoneLeagueAvg':'league_avg_offensive_zone',
            'zoneTimeDetails.neutralZonePctg':'neutral_zone_percentage',
            'zoneTimeDetails.neutralZonePercentile':'neutral_zone_percentile',
            'zoneTimeDetails.neutralZoneLeagueAvg':'league_avg_neutral_zone',
            'zoneTimeDetails.defensiveZonePctg':'defensive_zone_percentage',
            'zoneTimeDetails.defensiveZonePercentile':'defensive_zone_percentile',
            'zoneTimeDetails.defensiveZoneLeagueAvg':'league_avg_defensive_zone',
            'season_type':'season_type'
        },
        'stats':{
            "Player":"player_name",
            "Goalie":"player_name",
            "Season":"season",
            "Year":"season_year",
            "Team":"team_abbr",
            "ID":"player_id",
            "Game":"game_id",
            "WSBA":"wsba_id",
            "Headshot":"headshot",
            "Position":"position",
            "Handedness":"handedness",
            "Height (in)":"height_in",
            "Weight (lbs)":"weight_lbs",
            "Birthday":"birth_date",
            "Age":"age",
            "Nationality":"nationality",
            "GP":"games_played",
            "TOI":"time_on_ice",
            "GF":"goals_for",
            "SF":"shots_for",
            "FF":"fenwick_for",
            "xGF":"expected_goals_for",
            "xGF/FF":"expected_goals_per_fenwick_for",
            "GF/xGF":"goals_for_per_expected_goals_for",
            "ShF%":"shooting_percentage_for",
            "FshF%":"fenwick_shot_percentage_for",
            "GA":"goals_against",
            "SA":"shots_against",
            "FA":"fenwick_against",
            "xGA":"expected_goals_against",
            "xGA/FA":"expected_goals_per_fenwick_against",
            "GA/xGA":"goals_against_per_expected_goals_against",
            "ShA%":"shooting_percentage_against",
            "FshA%":"fenwick_shot_percentage_against",
            "CF":"corsi_for",
            "CA":"corsi_against",
            "CF%":"corsi_for_percentage",
            "FF%":"fenwick_for_percentage",
            "xGF%":"expected_goals_for_percentage",
            "GF%":"goals_for_percentage",
            "SF%":"shots_for_percentage",
            "HF":"hits_for",
            "HA":"hits_against",
            "HF%":"hits_for_percentage",
            "Penl":"penalties",
            "Penl2":"minor_penalties",
            "Penl5":"major_penalties",
            "PIM":"penalty_minutes",
            "Draw":"penalties_drawn",
            "PENL%":"penalties_drawn_percentage",
            "Give":"giveaways",
            "Take":"takeaways",
            "PM%":"puck_management_percentage",
            "Block":"blocked_shots",
            "RushF":"rush_attempts_for",
            "RushA":"rush_attempts_against",
            "RushFxG":"rush_expected_goals_for",
            "RushAxG":"rush_expected_goals_against",
            "RushFG":"rush_goals_for",
            "RushAG":"rush_goals_against",
            "Rush":"rush_attempts",
            "Rush xG":"rush_expected_goals",
            "Rush G":"rush_goals",
            "GSAx":"goals_saved_above_expected",
            "Gi":"goals",
            "A1":"primary_assists",
            "A2":"secondary_assists",
            "P1":"primary_points",
            "P":"points",
            "Si":"shots",
            "Ci":"corsi",
            "Shi%":"shooting_percentage",
            "Fi":"fenwick",
            "xGi":"expected_goals",
            "xGi/Fi":"expected_goals_per_fenwick",
            "Gi/xGi":"goals_per_expected_goals",
            "Fshi%":"fenwick_shot_percentage",
            "OZF":"offensive_zone_faceoffs",
            "NZF":"neutral_zone_faceoffs",
            "DZF":"defensive_zone_faceoffs",
            "OZF%":"offensive_zone_faceoffs_percentage",
            "NZF%":"neutral_zone_faceoffs_percentage",
            "DZF%":"defensive_zone_faceoffs_percentage",
            "GC%":"goals_contribution_percentage",
            "AC%":"assists_contribution_percentage",
            "GI%":"goal_involvement_percentage",
            "FC%":"fenwick_contribution_percentage",
            "xGC%":"expected_goals_contribution_percentage",
            "F":"faceoffs_taken",
            "FW":"faceoff_wins",
            "FL":"faceoff_losses",
            "F%":"faceoff_percentage",
            "OOFF-SR":"on_ice_offense_shot_rate_percentile",
            "OOFF-SQ":"on_ice_offense_shot_quality_percentile",
            "OOFF-FN":"on_ice_offense_finishing_percentile",
            "OOFF-SRI":"on_ice_offense_shot_rate_impact",
            "OOFF-SQI":"on_ice_offense_shot_quality_impact",
            "OOFF-FNI":"on_ice_offense_finishing_impact",
            "OOFF-SRI-T":"total_on_ice_offense_shot_rate_impact",
            "OOFF-SQI-T":"total_on_ice_offense_shot_quality_impact",
            "OOFF-FNI-T":"total_on_ice_offense_finishing_impact",
            "ODEF-SR":"on_ice_defense_shot_rate_percentile",
            "ODEF-SQ":"on_ice_defense_shot_quality_percentile",
            "ODEF-FN":"on_ice_defense_finishing_percentile",
            "ODEF-SRI":"on_ice_defense_shot_rate_impact",
            "ODEF-SQI":"on_ice_defense_shot_quality_impact",
            "ODEF-FNI":"on_ice_defense_finishing_impact",
            "ODEF-SRI-T":"total_on_ice_defense_shot_rate_impact",
            "ODEF-SQI-T":"total_on_ice_defense_shot_quality_impact",
            "ODEF-FNI-T":"total_on_ice_defense_finishing_impact",
            "EGF":"extraneous_goals_for",
            "ExGF":"extraneous_expected_goals_for",
            "EGA":"extraneous_goals_against",
            "ExGA":"extraneous_expected_goals_against",
            "EGF-P":"extraneous_goals_for_percentile",
            "ExGF-P":"extraneous_expected_goals_for_percentile",
            "EGA-P":"extraneous_goals_against_percentile",
            "ExGA-P":"extraneous_expected_goals_against_percentile",
            "EGF-T":"total_extraneous_goals_for",
            "ExGF-T":"total_extraneous_expected_goals_for",
            "EGA-T":"total_extraneous_goals_against",
            "ExGA-T":"total_extraneous_expected_goals_against",
            "Team-Adjusted-EGI":"team_adjusted_extraneous_expected_goals_impact",
            "GISAx":"goals_impact_saved_above_expected",
            "NetGI":"net_goal_impact",
            "NetxGI":"net_expected_goals_impact",
            "Team-Adjusted-EGI-P":"team_adjusted_extraneous_goals_impact_percentile",
            "GISAx-P":"goals_impact_saved_above_expected_percentile",
            "NetGI-P":"net_goal_impact_percentile",
            "NetxGI-P":"net_expected_goals_impact_percentile",
            "Team-Adjusted-EGI-T":"total_team_adjusted_extraneous_goals_impact",
            "GISAx-T":"total_goals_saved_above_expected_total",
            "RushF/60":"rush_attempts_for_per_sixty",
            "RushA/60":"rush_attempts_against_per_sixty",
            "RushesFF":"rush_attempts_for_percentile",
            "RushesFA":"rush_attempts_against_percentile",
            "RushFxG/60":"rush_expected_goals_for_per_sixty",
            "RushAxG/60":"rush_expected_goals_against_per_sixty",
            "RushesxGF":"rush_expected_goals_for_percentile",
            "RushesxGA":"rush_expected_goals_against_percentile",
            "RushFG/60":"rush_goals_for_per_sixty",
            "RushAG/60":"rush_goals_against_per_sixty",
            "RushesGF":"rush_goals_for_percentile",
            "RushesGA":"rush_goals_against_percentile",
            "EGi":"extraneous_goals",
            "ExGi":"extraneous_expected_goals",
            "EGi-P":"extraneous_goals_percentile",
            "ExGi-P":"extraneous_expected_goals_percentile",
            "EGi-T":"total_extraneous_goals",
            "ExGi-T":"total_extraneous_expected_goals",
            "LiEG":"linemate_extraneous_goals",
            "LiExG":"linemate_extraneous_expected_goals",
            "LiGIn":"linemate_goal_induction",
            "LixGIn":"linemate_expected_goal_induction",
            "ALiGIn":"adjusted_linemate_goal_involvement",
            "CompGI":"composite_goal_impact",
            "LiRelGI":"linemate_relative_goal_impact",
            "LiEG-P":"linemate_extraneous_goals_percentile",
            "LiExG-P":"linemate_extraneous_expected_goals_percentile",
            "LiGIn-P":"linemate_goal_induction_percentile",
            "LixGIn-P":"linemate_expected_goal_induction_percentile",
            "ALiGIn-P":"adjusted_linemate_goal_induction_percentile",
            "CompGI-P":"composite_goal_impact_percentile",
            "LiRelGI-P":"linemate_relative_goal_impact_percentile",
            "LiEG-T":"total_linemate_extraneous_goals",
            "LiExG-T":"total_linemate_extraneous_expected_goals",
            "LiGIn-T":"total_linemate_goal_induction",
            "LixGIn-T":"total_linemate_expected_goal_induction",
            "ALiGIn-T":"total_adjusted_linemate_goal_induction",
            "CompGI-T":"total_composite_goal_impact_total",
            "LiRelGI-T":"total_linemate_relative_goal_impact_total",
            "NetGI-T":"total_net_goal_impact",
            "NetxGI-T":"total_net_expected_goals_impact",
            "Fi/60":"fenwick_per_sixty",
            "xGi/60":"expected_goals_per_sixty",
            "Gi/60":"goals_per_sixty",
            "A1/60":"primary_assists_per_sixty",
            "A2/60":"secondary_assists_per_sixty",
            "P1/60":"primary_points_per_sixty",
            "P/60":"points_per_sixty",
            "Si/60":"shots_per_sixty",
            "OZF/60":"offensive_zone_faceoffs_per_sixty",
            "NZF/60":"neutral_zone_faceoffs_per_sixty",
            "DZF/60":"defensive_zone_faceoffs_per_sixty",
            "FF/60":"fenwick_for_per_sixty",
            "FA/60":"fenwick_against_per_sixty",
            "xGF/60":"expected_goals_for_per_sixty",
            "xGA/60":"expected_goals_against_per_sixty",
            "GF/60":"goals_for_per_sixty",
            "GA/60":"goals_against_per_sixty",
            "SF/60":"shots_for_per_sixty",
            "SA/60":"shots_against_per_sixty",
            "CF/60":"corsi_for_per_sixty",
            "CA/60":"corsi_against_per_sixty",
            "HF/60":"hits_for_per_sixty",
            "HA/60":"hits_against_per_sixty",
            "Give/60":"giveaways_per_sixty",
            "Take/60":"takeaways_per_sixty",
            "Penl/60":"penalties_per_sixty",
            "Penl2/60":"minor_penalties_per_sixty",
            "Penl5/60":"major_penalties_per_sixty",
            "Draw/60":"penalties_drawn_per_sixty",
            "PIM/60":"penalty_minutes_per_sixty",
            "Block/60":"blocked_shots_per_sixty",
            "GSAx/60":"goals_saved_above_expected_per_sixty",
            "WristFi":"wrist_fenwick",
            "WristxGi":"wrist_expected_goals",
            "WristGi":"wrist_goals",
            "DeflectedFi":"deflected_fenwick",
            "DeflectedxGi":"deflected_expected_goals",
            "DeflectedGi":"deflected_goals",
            "Tip-inFi":"tip_in_fenwick",
            "Tip-inxGi":"tip_in_expected_goals",
            "Tip-inGi":"tip_in_goals",
            "SlapFi":"slap_fenwick",
            "SlapxGi":"slap_expected_goals",
            "SlapGi":"slap_goals",
            "BackhandFi":"backhand_fenwick",
            "BackhandxGi":"backhand_expected_goals",
            "BackhandGi":"backhand_goals",
            "SnapFi":"snap_fenwick",
            "SnapxGi":"snap_expected_goals",
            "SnapGi":"snap_goals",
            "Wrap-aroundFi":"wrap_around_fenwick",
            "Wrap-aroundxGi":"wrap_around_expected_goals",
            "Wrap-aroundGi":"wrap_around_goals",
            "PokeFi":"poke_fenwick",
            "PokexGi":"poke_expected_goals",
            "PokeGi":"poke_goals",
            "BatFi":"bat_fenwick",
            "BatxGi":"bat_expected_goals",
            "BatGi":"bat_goals",
            "CradleFi":"cradle_fenwick",
            "CradlexGi":"cradle_expected_goals",
            "CradleGi":"cradle_goals",
            "Between-legsFi":"between_legs_fenwick",
            "Between-legsxGi":"between_legs_expected_goals",
            "Between-legsGi":"between_legs_goals",
            "GS":"game_score",
            "T-GD":"team_goal_differential",
            "EV_xGC%":"even_strength_expected_goals_contribution_percentage",
            "EV_xGF":"even_strength_expected_goals_for",
            "EV_xGA":"even_strength_expected_goals_against",
            "PP_xGC%":"power_play_expected_goals_contribution_percentage",
            "PP_xGF":"power_play_expected_goals_for",
            "PP_xGA":"power_play_expected_goals_against",
            "SH_xGC%":"short_handed_expected_goals_contribution_percentage",
            "SH_xGF":"short_handed_expected_goals_for",
            "SH_xGA":"short_handed_expected_goals_against",
            "P Score": "points_score",
            "PENL% Score": "penalties_drawn_percentage_score",
            "PM% Score": "puck_management_percentage_score",
            "F% Score": "faceoff_percentage_score",
            "EV_xGC% Score": "even_strength_expected_goals_contribution_percentage_score",
            "EV_xGF Score": "even_strength_expected_goals_for_score",
            "EV_xGA Score": "even_strength_expected_goals_against_score",
            "PP_xGC% Score": "power_play_expected_goals_contribution_percentage_score",
            "PP_xGF Score": "power_play_expected_goals_for_score",
            "PP_xGA Score": "power_play_expected_goals_against_score",
            "SH_xGC% Score": "short_handed_expected_goals_contribution_percentage_score",
            "SH_xGF Score": "short_handed_expected_goals_for_score",
            "SH_xGA Score": "short_handed_expected_goals_against_score",
            "xGF% Score": "expected_goals_for_percentage_score",
            "GA/xGA Score": "goals_against_per_expected_goals_against_score",
            "EV Score": "even_strength_score",
            "PP Score": "power_play_score",
            "SH Score": "short_handed_score",
            "Production Score": "production_score",
            "Play-Driving Score": "play_driving_score",
            "Offensive Score": "offensive_score",
            "Defensive Score": "defensive_score",
            "Workload Score": "workload_score",
            "Goaltending Score": "goaltending_score",
            "Misc Score": "misc_score",
            "Penalties Score": "penalties_score",
            "Puck Management Score": "puck_management_score",
            "Faceoffs Score": "faceoffs_score",
            "Strength": "strength_state",
            "Span": "season_type",
            "FC%-P": "fenwick_contribution_percentage_percentile",
            "xGC%-P": "expected_goals_contribution_percentage_percentile",
            "GI%-P": "goal_involvement_percentage_percentile",
            "GC%-P": "goals_contribution_percentage_percentile",
            "RushFi/60": "rush_fenwick_per_sixty",
            "RushxGi/60": "rush_expected_goals_per_sixty",
            "RushesxGi": "rush_expected_goals_percentile",
            "RushesFi": "rush_fenwick_percentile",
            "Fi/60-P": "fenwick_per_sixty_percentile",
            "xGi/60-P": "expected_goals_per_sixty_percentile",
            "Gi/60-P": "goals_per_sixty_percentile",
            "A1/60-P": "primary_assists_per_sixty_percentile",
            "A2/60-P": "secondary_assists_per_sixty_percentile",
            "P1/60-P": "primary_points_per_sixty_percentile",
            "P/60-P": "points_per_sixty_percentile",
            "Si/60-P": "shots_per_sixty_percentile",
            "OZF/60-P": "offensive_zone_faceoffs_per_sixty_percentile",
            "NZF/60-P": "neutral_zone_faceoffs_per_sixty_percentile",
            "DZF/60-P": "defensive_zone_faceoffs_per_sixty_percentile",
            "FF/60-P": "fenwick_for_per_sixty_percentile",
            "FA/60-P": "fenwick_against_per_sixty_percentile",
            "xGF/60-P": "expected_goals_for_per_sixty_percentile",
            "xGA/60-P": "expected_goals_against_per_sixty_percentile",
            "GF/60-P": "goals_for_per_sixty_percentile",
            "GA/60-P": "goals_against_per_sixty_percentile",
            "SF/60-P": "shots_for_per_sixty_percentile",
            "SA/60-P": "shots_against_per_sixty_percentile",
            "CF/60-P": "corsi_for_per_sixty_percentile",
            "CA/60-P": "corsi_against_per_sixty_percentile",
            "HF/60-P": "hits_for_per_sixty_percentile",
            "HA/60-P": "hits_against_per_sixty_percentile",
            "Give/60-P": "giveaways_per_sixty_percentile",
            "Take/60-P": "takeaways_per_sixty_percentile",
            "Penl/60-P": "penalties_per_sixty_percentile",
            "Penl2/60-P": "minor_penalties_per_sixty_percentile",
            "Penl5/60-P": "major_penalties_per_sixty_percentile",
            "Draw/60-P": "penalties_drawn_per_sixty_percentile",
            "PIM/60-P": "penalty_minutes_per_sixty_percentile",
            "Block/60-P": "blocked_shots_per_sixty_percentile",
            "GSAx/60-P": "goals_saved_above_expected_per_sixty_percentile",
            "INDV-SR": "individual_shot_rate_percentile",
            "INDV-SQ": "individual_shot_quality_percentile",
            "INDV-FN": "individual_finishing_percentile",
            "INDV-SRI": "individual_shot_rate_impact",
            "INDV-SQI": "individual_shot_quality_impact",
            "INDV-FNI": "individual_finishing_impact",
            "INDV-SRI-T": "total_individual_shot_rate_impact",
            "INDV-SQI-T": "total_individual_shot_quality_impact",
            "INDV-FNI-T": "total_individual_finishing_impact",
            "AC%-P": "assists_contribution_percentage_percentile",
            "GF%-P": "goals_for_percentage_percentile",
            "SF%-P": "shots_for_percentage_percentile",
            "xGF%-P": "expected_goals_for_percentage_percentile",
            "FF%-P": "fenwick_for_percentage_percentile",
            "CF%-P": "corsi_for_percentage_percentile"
        }
    }