from flask import Flask

def timestamp_suffix() -> str: ...
def prefix_index(
    index: str, prefix: str | None = ..., app: Flask | None = ...
) -> str: ...
def suffix_index(
    index: str, suffix: str | None = ..., app: Flask | None = ...
) -> str: ...
def build_index_from_parts(*parts: str) -> str: ...
def build_alias_name(
    index: str, prefix: str | None = ..., app: Flask | None = ...
) -> str: ...
def build_index_name(
    index: str | tuple[str, ...] | list[str],
    prefix: str | None = ...,
    suffix: str | None = ...,
    app: Flask | None = ...,
) -> str: ...
