from typing import Any

from flask_principal import Identity

class DummyResultList:
    hits: list[dict[str, Any]]
    def __init__(self, hits: list[dict[str, Any]]) -> None: ...

class DummyExpandingService:
    def __init__(self, type: str) -> None: ...
    def read(self, identity: Identity, id_: Any, **kwargs: Any) -> dict[str, Any]: ...
    def read_many(self, identity: Identity, ids: list[Any]) -> DummyResultList: ...
