from __future__ import annotations

from typing import Any, ClassVar

class ImageConverter:
    default_params: ClassVar[dict[str, Any]]
    def __init__(self, params: dict[str, Any] | None = ...) -> None: ...
    @property
    def params(self) -> dict[str, Any]: ...
    def convert(self, in_stream: Any, out_stream: Any) -> bool | None: ...

class PyVIPSImageConverter(ImageConverter):
    default_params: ClassVar[dict[str, Any]]
    @staticmethod
    def fp_source(input_file: Any) -> Any: ...
    @staticmethod
    def fp_target(output_file: Any) -> Any: ...
    def convert(self, in_stream: Any, out_stream: Any) -> bool | None: ...
