from __future__ import annotations

from typing import Any

class TilesStorage:
    def __init__(self, converter: Any | None = ...) -> None: ...
    def _converter(self) -> Any: ...
    def save(self, record_id: str, key: str, file_: Any) -> str: ...
    def open(self, record_id: str, key: str) -> Any: ...
    def update_access(self, record_id: str, key: str, visibility: str) -> None: ...
    def delete(self, record_id: str, key: str) -> None: ...

class LocalTilesStorage(TilesStorage):
    base_path: str

    def __init__(self, base_path: str, converter: Any | None = ...) -> None: ...
    def _directory(self, record_id: str, key: str) -> str: ...
    def save(self, record_id: str, key: str, file_: Any) -> str: ...
    def open(self, record_id: str, key: str) -> Any: ...
    def update_access(self, record_id: str, key: str, visibility: str) -> None: ...
    def delete(self, record_id: str, key: str) -> None: ...

tiles_storage: TilesStorage
