from __future__ import annotations

def generate_tiles(record_id: str, file_key: str, file_type: str) -> None: ...
def cleanup_tiles_file(
    record_id: str, tile_file_key: str, retry: bool = ...
) -> None: ...
