from politechie_core.validations.gender_validator import GenderValidator
from politechie_core.validations.dob_validator import DobValidator
from politechie_core.validations.email_validator import EmailValidator
from politechie_core.validations.phone_number_validator import PhoneNumberValidator
from politechie_core.validations.age_validator import AgeValidator