"""
This module provides reusable UI components.
All components extend ComponentModel and can be rendered asynchronously.
"""

# Base
from starlette_templates.components.base import ComponentModel

# Form Components
from starlette_templates.components.forms import (
    SelectOption,
    Input,
    Textarea,
    Select,
    Checkbox,
    Radio,
    Switch,
    FileInput,
    Range,
    ChoiceOption,
    ChoiceGroup,
    ChoicesSelect,
    DatePicker,
    TimePicker,
    DateTimePicker,
)

# Bootstrap Components
from starlette_templates.components.bootstrap import (
    Container,
    Row,
    Col,
    Grid,
    Card,
    NavLink,
    NavDropdown,
    Navbar,
    SidebarButton,
    Sidebar,
    BreadcrumbItem,
    Breadcrumb,
    SubNavLink,
    SubNav,
    Badge,
    ListGroupItem,
    ListGroup,
    CarouselItem,
    Carousel,
    Tag,
    Button,
    PageHeader,
    FilterItem,
    FilterBar,
    Alert,
    Toast,
    Modal,
    Tooltip,
    Popover,
    ProgressBar,
    Spinner,
    TabItem,
    Tabs,
    AccordionItem,
    Accordion,
    Pagination,
    DropdownItem,
    Dropdown,
    ButtonGroup,
    Collapse,
    ActivityItem,
    Timeline,
    Table,
    Icon,
    Avatar,
    Skeleton,
    EmptyState,
    Offcanvas,
    Divider,
    CopyButton,
)


__all__ = [
    # Base
    "ComponentModel",
    # Forms
    "SelectOption",
    "Input",
    "Textarea",
    "Select",
    "Checkbox",
    "Radio",
    "Switch",
    "FileInput",
    "Range",
    "ChoiceOption",
    "ChoiceGroup",
    "ChoicesSelect",
    "DatePicker",
    "TimePicker",
    "DateTimePicker",
    # Bootstrap Layout
    "Container",
    "Row",
    "Col",
    "Grid",
    # Bootstrap Components
    "Card",
    "NavLink",
    "NavDropdown",
    "Navbar",
    "SidebarButton",
    "Sidebar",
    "BreadcrumbItem",
    "Breadcrumb",
    "SubNavLink",
    "SubNav",
    "Badge",
    "ListGroupItem",
    "ListGroup",
    "CarouselItem",
    "Carousel",
    "Tag",
    "Button",
    "PageHeader",
    "FilterItem",
    "FilterBar",
    "Alert",
    "Toast",
    "Modal",
    "Tooltip",
    "Popover",
    "ProgressBar",
    "Spinner",
    "TabItem",
    "Tabs",
    "AccordionItem",
    "Accordion",
    "Pagination",
    "DropdownItem",
    "Dropdown",
    "ButtonGroup",
    "Collapse",
    "ActivityItem",
    "Timeline",
    "Table",
    "Icon",
    "Avatar",
    "Skeleton",
    "EmptyState",
    "Offcanvas",
    "Divider",
    "CopyButton",
]
