# generated by datamodel-codegen:
#   filename:  core/primitive/string.json
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel


class PrimitiveString(BaseModel):
    value: str
