"""Utility functions shared across the library.

This package contains foundational utilities that are backend-agnostic and
safe to import from any layer (core, db, api). Keep dependencies minimal.
"""

from .context import GlobalContext
from .decorators import (
    async_safe,
    log_calls,
    memoize,
    preserve_signature,
    retry,
    timeout,
    validate_args,
)
from .factory import PluginFactory
from .serialization import deserialize_datetime, serialize_datetime
from .types import (
    AnyDict,
    AnyList,
    APIResponse,
    CacheKey,
    CacheValue,
    ConfigData,
    ContextData,
    DatabaseUrl,
    EndpointPath,
    ErrorCode,
    ErrorDetails,
    ErrorMessage,
    EventData,
    EventHandler,
    EventName,
    FileContent,
    FileMetadata,
    FilePath,
    GraphData,
    HTTPMethod,
    HTTPStatus,
    JSONData,
    JSONDict,
    JSONList,
    NodeData,
    NodeId,
    ObjectId,
    OptionalBool,
    OptionalDict,
    OptionalFloat,
    OptionalInt,
    OptionalList,
    OptionalStr,
    StringDict,
    StringList,
    StringOrBool,
    StringOrFloat,
    StringOrInt,
    WalkerData,
    WalkerId,
    is_async_callable,
    is_boolean,
    is_callable,
    is_dict,
    is_float,
    is_integer,
    is_list,
    is_string,
    to_boolean,
    to_dict,
    to_float,
    to_integer,
    to_list,
    to_string,
)
from .validation import PathValidator

__all__ = [
    # Core utilities
    "PluginFactory",
    "GlobalContext",
    "PathValidator",
    # Serialization
    "serialize_datetime",
    "deserialize_datetime",
    # Decorators
    "preserve_signature",
    "async_safe",
    "memoize",
    "retry",
    "timeout",
    "validate_args",
    "log_calls",
    # Types
    "NodeId",
    "WalkerId",
    "ObjectId",
    "GraphData",
    "NodeData",
    "EdgeData",
    "WalkerData",
    "HTTPMethod",
    "HTTPStatus",
    "APIResponse",
    "EndpointPath",
    "DatabaseUrl",
    "CollectionName",
    "QueryFilter",
    "QueryOptions",
    "CacheKey",
    "CacheValue",
    "CacheTTL",
    "FilePath",
    "FileContent",
    "FileMetadata",
    "EventHandler",
    "EventData",
    "EventName",
    "ContextData",
    "ContextKey",
    "ContextValue",
    "ErrorCode",
    "ErrorMessage",
    "ErrorDetails",
    "ConfigValue",
    "ConfigSection",
    "ConfigData",
    "OptionalStr",
    "OptionalInt",
    "OptionalFloat",
    "OptionalBool",
    "OptionalList",
    "OptionalDict",
    "StringDict",
    "StringList",
    "AnyDict",
    "AnyList",
    "StringOrInt",
    "StringOrFloat",
    "StringOrBool",
    "IntOrFloat",
    "JSONData",
    "JSONDict",
    "JSONList",
    # Type guards
    "is_string",
    "is_integer",
    "is_float",
    "is_boolean",
    "is_dict",
    "is_list",
    "is_callable",
    "is_async_callable",
    # Conversion helpers
    "to_string",
    "to_integer",
    "to_float",
    "to_boolean",
    "to_dict",
    "to_list",
]
