# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-12-16
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from esi_genoa_client.models.route_connection import RouteConnection
from typing import Optional, Set
from typing_extensions import Self

class RouteRequestBody(BaseModel):
    """
    RouteRequestBody
    """ # noqa: E501
    avoid_systems: Optional[Annotated[List[StrictInt], Field(max_length=1000)]] = Field(default=None, description="Systems to avoid")
    connections: Optional[Annotated[List[RouteConnection], Field(max_length=1000)]] = Field(default=None, description="Additional one-way connections (like Jump Bridges) between systems")
    preference: Optional[StrictStr] = Field(default='Shorter', description="Preference for the route")
    security_penalty: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=50, description="Strictness of the path preference")
    __properties: ClassVar[List[str]] = ["avoid_systems", "connections", "preference", "security_penalty"]

    @field_validator('preference')
    def preference_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Shorter', 'Safer', 'LessSecure']):
            raise ValueError("must be one of enum values ('Shorter', 'Safer', 'LessSecure')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RouteRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in connections (list)
        _items = []
        if self.connections:
            for _item_connections in self.connections:
                if _item_connections:
                    _items.append(_item_connections.to_dict())
            _dict['connections'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RouteRequestBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "avoid_systems": obj.get("avoid_systems"),
            "connections": [RouteConnection.from_dict(_item) for _item in obj["connections"]] if obj.get("connections") is not None else None,
            "preference": obj.get("preference") if obj.get("preference") is not None else 'Shorter',
            "security_penalty": obj.get("security_penalty") if obj.get("security_penalty") is not None else 50
        })
        return _obj


