"""Pydantic models for IFPA API resources.

This package contains all Pydantic models used for request validation and
response deserialization throughout the SDK.
"""

from ifpa_api.models.calendar import CalendarEvent, CalendarResponse
from ifpa_api.models.common import (
    IfpaBaseModel,
    MajorTournament,
    RankingSystem,
    ResultType,
    StatsRankType,
    SystemCode,
    TimePeriod,
    TournamentType,
)
from ifpa_api.models.director import (
    CountryDirector,
    CountryDirectorsResponse,
    Director,
    DirectorSearchResponse,
    DirectorSearchResult,
    DirectorStats,
    DirectorTournament,
    DirectorTournamentsResponse,
    PlayerProfile,
)
from ifpa_api.models.player import (
    MultiPlayerResponse,
    Player,
    PlayerCard,
    PlayerRanking,
    PlayerResultsResponse,
    PlayerSearchResponse,
    PlayerSearchResult,
    PvpAllCompetitors,
    PvpComparison,
    PvpPlayer,
    PvpTournament,
    RankHistoryEntry,
    RankingHistory,
    RatingHistoryEntry,
    TournamentResult,
)
from ifpa_api.models.rankings import (
    CountryListEntry,
    CountryRankingsResponse,
    CustomRankingEntry,
    CustomRankingInfo,
    CustomRankingListResponse,
    CustomRankingsResponse,
    RankingEntry,
    RankingsCountryListResponse,
    RankingsResponse,
)
from ifpa_api.models.reference import (
    Country,
    CountryListResponse,
    CountryRegions,
    Region,
    StateProvListResponse,
)
from ifpa_api.models.series import (
    RegionOverview,
    RegionRepresentative,
    RegionRepsResponse,
    RegionStandingEntry,
    Series,
    SeriesListResponse,
    SeriesPlayerCard,
    SeriesPlayerEvent,
    SeriesRegion,
    SeriesRegionsResponse,
    SeriesRegionStandingsResponse,
    SeriesStandingEntry,
    SeriesStandingsResponse,
    SeriesStats,
    SeriesTournament,
    SeriesTournamentsResponse,
)
from ifpa_api.models.stats import (
    AgeGenderStats,
    CountryPlayersResponse,
    CountryPlayerStat,
    EventsAttendedPeriodResponse,
    EventsAttendedPeriodStat,
    EventsByYearResponse,
    EventsByYearStat,
    LargestTournamentsResponse,
    LargestTournamentStat,
    LucrativeTournamentsResponse,
    LucrativeTournamentStat,
    OverallStats,
    OverallStatsResponse,
    PlayersByYearResponse,
    PlayersByYearStat,
    PointsGivenPeriodResponse,
    PointsGivenPeriodStat,
    StatePlayersResponse,
    StatePlayerStat,
    StateTournamentsResponse,
    StateTournamentStat,
)
from ifpa_api.models.tournaments import (
    FormatDefinition,
    LeagueSession,
    RelatedTournament,
    RelatedTournamentsResponse,
    RelatedTournamentWinner,
    Tournament,
    TournamentFormat,
    TournamentFormatsListResponse,
    TournamentFormatsResponse,
    TournamentLeagueResponse,
    TournamentResultsResponse,
    TournamentSearchResponse,
    TournamentSearchResult,
    TournamentSubmission,
    TournamentSubmissionsResponse,
)
from ifpa_api.models.tournaments import (
    TournamentResult as TournamentResultDetail,
)

__all__ = [
    # Common
    "IfpaBaseModel",
    "TimePeriod",
    "RankingSystem",
    "ResultType",
    "TournamentType",
    "StatsRankType",
    "SystemCode",
    "MajorTournament",
    # Director
    "Director",
    "DirectorStats",
    "DirectorTournament",
    "DirectorTournamentsResponse",
    "DirectorSearchResult",
    "DirectorSearchResponse",
    "CountryDirector",
    "CountryDirectorsResponse",
    "PlayerProfile",
    # Player
    "Player",
    "PlayerRanking",
    "PlayerSearchResult",
    "PlayerSearchResponse",
    "MultiPlayerResponse",
    "TournamentResult",
    "PlayerResultsResponse",
    "RankHistoryEntry",
    "RankingHistory",
    "RatingHistoryEntry",
    "PvpAllCompetitors",
    "PvpComparison",
    "PvpPlayer",
    "PvpTournament",
    "PlayerCard",
    # Rankings
    "RankingEntry",
    "RankingsResponse",
    "CountryRankingsResponse",
    "CustomRankingEntry",
    "CustomRankingsResponse",
    "CountryListEntry",
    "RankingsCountryListResponse",
    "CustomRankingInfo",
    "CustomRankingListResponse",
    # Reference
    "Country",
    "CountryListResponse",
    "CountryRegions",
    "Region",
    "StateProvListResponse",
    # Tournaments
    "Tournament",
    "TournamentResultDetail",
    "TournamentResultsResponse",
    "TournamentFormat",
    "TournamentFormatsResponse",
    "TournamentFormatsListResponse",
    "FormatDefinition",
    "LeagueSession",
    "TournamentLeagueResponse",
    "TournamentSubmission",
    "TournamentSubmissionsResponse",
    "TournamentSearchResult",
    "TournamentSearchResponse",
    "RelatedTournament",
    "RelatedTournamentWinner",
    "RelatedTournamentsResponse",
    # Series
    "Series",
    "SeriesListResponse",
    "SeriesStandingEntry",
    "SeriesStandingsResponse",
    "SeriesPlayerEvent",
    "SeriesPlayerCard",
    "SeriesRegion",
    "SeriesRegionsResponse",
    "SeriesStats",
    "SeriesTournament",
    "SeriesTournamentsResponse",
    "RegionOverview",
    "RegionRepresentative",
    "RegionRepsResponse",
    "RegionStandingEntry",
    "SeriesRegionStandingsResponse",
    # Calendar
    "CalendarEvent",
    "CalendarResponse",
    # Stats
    "CountryPlayerStat",
    "CountryPlayersResponse",
    "StatePlayerStat",
    "StatePlayersResponse",
    "StateTournamentStat",
    "StateTournamentsResponse",
    "EventsByYearStat",
    "EventsByYearResponse",
    "PlayersByYearStat",
    "PlayersByYearResponse",
    "LargestTournamentStat",
    "LargestTournamentsResponse",
    "LucrativeTournamentStat",
    "LucrativeTournamentsResponse",
    "PointsGivenPeriodStat",
    "PointsGivenPeriodResponse",
    "EventsAttendedPeriodStat",
    "EventsAttendedPeriodResponse",
    "AgeGenderStats",
    "OverallStats",
    "OverallStatsResponse",
]
