# coding: utf-8

"""
    EVE Stable Infrastructure (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-12-16
    Contact: arcyfa_github@pm.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from esi_genoa_client.models.corporations_projects_detail_configurationdeliveritem_docking_locations_inner import CorporationsProjectsDetailConfigurationdeliveritemDockingLocationsInner
from esi_genoa_client.models.corporations_projects_detail_configurationdeliveritem_items_inner import CorporationsProjectsDetailConfigurationdeliveritemItemsInner
from typing import Optional, Set
from typing_extensions import Self

class CorporationsProjectsDetailConfigurationdeliveritem(BaseModel):
    """
    CorporationsProjectsDetailConfigurationdeliveritem
    """ # noqa: E501
    docking_locations: Optional[List[CorporationsProjectsDetailConfigurationdeliveritemDockingLocationsInner]] = Field(default=None, description="Docking location to deliver to")
    items: Optional[List[CorporationsProjectsDetailConfigurationdeliveritemItemsInner]] = Field(default=None, description="Item to deliver")
    office_id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["docking_locations", "items", "office_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CorporationsProjectsDetailConfigurationdeliveritem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in docking_locations (list)
        _items = []
        if self.docking_locations:
            for _item_docking_locations in self.docking_locations:
                if _item_docking_locations:
                    _items.append(_item_docking_locations.to_dict())
            _dict['docking_locations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CorporationsProjectsDetailConfigurationdeliveritem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "docking_locations": [CorporationsProjectsDetailConfigurationdeliveritemDockingLocationsInner.from_dict(_item) for _item in obj["docking_locations"]] if obj.get("docking_locations") is not None else None,
            "items": [CorporationsProjectsDetailConfigurationdeliveritemItemsInner.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "office_id": obj.get("office_id")
        })
        return _obj


