from flask import Flask
from flask.blueprints import Blueprint

def not_found_error(error: Exception) -> tuple[str, int]: ...
def record_tombstone_error(error: Exception) -> tuple[str, int]: ...
def record_permission_denied_error(error: Exception) -> tuple[str, int]: ...
def create_ui_blueprint(app: Flask) -> Blueprint: ...
