# coding: utf-8

"""
    Fyn-Tech API

    Schema for the REST API of fyn-api

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fyn_api_client.models.password_update_request import PasswordUpdateRequest

class TestPasswordUpdateRequest(unittest.TestCase):
    """PasswordUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasswordUpdateRequest:
        """Test PasswordUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasswordUpdateRequest`
        """
        model = PasswordUpdateRequest()
        if include_optional:
            return PasswordUpdateRequest(
                old_password = '0',
                new_password = '0'
            )
        else:
            return PasswordUpdateRequest(
                old_password = '0',
                new_password = '0',
        )
        """

    def testPasswordUpdateRequest(self):
        """Test PasswordUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
