from invenio_audit_logs.services import AuditLogAction
from invenio_drafts_resources.auditlog.context import RecordContext as RecordContext
from invenio_drafts_resources.auditlog.context import RequestContext as RequestContext
from invenio_drafts_resources.auditlog.context import UserContext as UserContext

class RecordBaseAuditLog(AuditLogAction): ...
class DraftCreateAuditLog(RecordBaseAuditLog): ...
class DraftEditAuditLog(RecordBaseAuditLog): ...
class RecordPublishAuditLog(RecordBaseAuditLog): ...
class DraftDeleteAuditLog(RecordBaseAuditLog): ...
class DraftNewVersionAuditLog(RecordBaseAuditLog): ...
