# Package Imports
from gmdkit.models.prop.list import IntList
from gmdkit.models.prop.gzip import ObjectString, ReplayString


LEVEL_DECODERS = {
    'k1': int,
    'k10': int,
    'k101': str,
    'k102': int,
    'k103': int,
    'k104': IntList.from_string,
    'k105': IntList.from_string,
    'k106': int,
    'k107': int,
    'k108': int,
    'k109': IntList.from_string,
    'k11': int,
    'k110': IntList.from_string,
    'k111': int,
    'k15': lambda x: bool(int(x)),
    'k16': int,
    'k17': int,
    'k18': int,
    'k19': int,
    'k2': str,
    'k20': int,
    'k21': int,
    'k22': int,
    'k23': int,
    'k24': int,
    'k26': int,
    'k27': int,
    'k3': str,
    'k34': ReplayString,
    'k36': int,
    'k37': int,
    'k4': ObjectString,
    'k41': int,
    'k42': int,
    'k45': int,
    'k46': int,
    'k48': int,
    'k5': str,
    'k50': int,
    'k6': int,
    'k60': int,
    'k64': int,
    'k66': int,
    'k67': str,
    'k7': int,
    'k71': int,
    'k74': int,
    'k75': int,
    'k76': int,
    'k8': int,
    'k80': int,
    'k81': int,
    'k83': int,
    'k84': int,
    'k85': int,
    'k86': int,
    'k87': str,
    'k88': IntList.from_string,
    'k9': int,
    'k90': int,
    'k91': IntList.from_string,
    'k95': int,
    'kCEK': int,
    'kI1': float,
    'kI2': float,
    'kI3': float,
    'kI4': int,
    'kI5': int,
    'kI7': float,
}


LEVEL_ENCODERS = {
    'k101': str,
    'k104': lambda x: x.to_string(),
    'k105': lambda x: x.to_string(),
    'k109': lambda x: x.to_string(),
    'k110': lambda x: x.to_string(),
    'k15': lambda x: str(int(x)),
    'k2': str,
    'k3': str,
    'k34': lambda x: x.save(),
    'k4': lambda x: x.save(),
    'k5': str,
    'k67': str,
    'k87': str,
    'k88': lambda x: x.to_string(),
    'k91': lambda x: x.to_string(),
    'kI1': float,
    'kI2': float,
    'kI3': float,
    'kI7': float,
}


LIST_DECODERS = {
    'k1': int,
    'k11': int,
    'k113': int,
    'k114': int,
    'k15': lambda x: bool(int(x)),
    'k16': int,
    'k2': str,
    'k21': int,
    'k22': int,
    'k3': str,
    'k42': int,
    'k46': int,
    'k5': str,
    'k60': int,
    'k7': int,
    'k83': int,
    'k84': int,
    'k96': IntList.from_string,
    'k98': int,
    'k99': int,
    'kCEK': int,
}


LIST_ENCODERS = {
    'k15': lambda x: str(int(x)),
    'k2': str,
    'k3': str,
    'k5': str,
    'k96': lambda x: x.to_string(),
}
