SITE_UI_URL: str
SITE_API_URL: str
RECORDS_RESOURCES_FILES_ALLOWED_DOMAINS: list[str]
RECORDS_RESOURCES_IMAGE_FORMATS: list[str]
RECORDS_RESOURCES_ALLOW_EMPTY_FILES: bool
RECORDS_RESOURCES_TRANSFERS: list[str]
RECORDS_RESOURCES_DEFAULT_TRANSFER_TYPE: str
