from typing import Any, Callable

from invenio_records_resources.services.base import Service

class ServiceRegistry:
    _services: dict[str, Service]

    def __init__(self) -> None: ...
    def register(
        self, service_instance: Service, service_id: str | None = ...
    ) -> None: ...
    def get(self, service_id: str) -> Service: ...
    def get_service_id(self, instance: Service) -> str: ...

class NotificationRegistry:
    _handlers: dict[str, list[Callable[..., Any]]]

    def __init__(self) -> None: ...
    def register(self, record_type: str, handler: Callable[..., Any]) -> None: ...
    def get(self, record_type: str) -> list[Callable[..., Any]]: ...
