from __future__ import annotations

from typing import Any

class RDMReleaseMetadata:
    rdm_release: Any
    def __init__(self, rdm_github_release: Any) -> None: ...
    @property
    def related_identifiers(self) -> dict[str, Any]: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def default_metadata(self) -> dict[str, Any]: ...
    @property
    def repo_license(self) -> str | None: ...
    @property
    def contributors(self) -> list[dict[str, Any]]: ...
    @property
    def citation_metadata(self) -> dict[str, Any]: ...
    @property
    def extra_metadata(self) -> dict[str, Any]: ...
    def load_extra_metadata(self) -> dict[str, Any]: ...
    def load_citation_file(
        self, citation_file_name: str | None
    ) -> dict[str, Any] | None: ...
    def load_citation_metadata(
        self, citation_data: dict[str, Any] | None
    ) -> dict[str, Any]: ...
