# generated by datamodel-codegen:
#   filename:  context_providers_directory/ml_settings_context_provider.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class ProblemCategory(Enum):
    regression = "regression"
    classification = "classification"
    clustering = "clustering"


class MLSettingsContextProviderSchema(BaseModel):
    target_column_name: Optional[str] = None
    problem_category: Optional[ProblemCategory] = None
