# DO NOT MODIFY -- This file is generated by type_spec
# ruff: noqa: E402 Q003
# fmt: off
# isort: skip_file
from __future__ import annotations
import typing  # noqa: F401
import datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from enum import StrEnum
from pkgs.serialization import serial_string_enum

__all__: list[str] = [
    "ASYNC_JOB_STATUS_FIELD_REF_NAME",
    "ASYNC_JOB_TYPE_FIELD_REF_NAME",
    "AsyncJobStatus",
    "AsyncJobType",
]


# DO NOT MODIFY -- This file is generated by type_spec
@serial_string_enum(
    labels={
        "async_batch_load": "Async Batch Load",
        "integration_server_run": "Integration Server Run",
    },
)
class AsyncJobType(StrEnum):
    ASYNC_BATCH_LOAD = "async_batch_load"
    INTEGRATION_SERVER_RUN = "integration_server_run"


# DO NOT MODIFY -- This file is generated by type_spec
@serial_string_enum(
    labels={
        "in_progress": "In Progress",
        "completed": "Completed",
        "error": "Error",
    },
)
class AsyncJobStatus(StrEnum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ERROR = "error"


# DO NOT MODIFY -- This file is generated by type_spec
ASYNC_JOB_TYPE_FIELD_REF_NAME = "core_async_job_jobType"


# DO NOT MODIFY -- This file is generated by type_spec
ASYNC_JOB_STATUS_FIELD_REF_NAME = "core_async_job_status"
# DO NOT MODIFY -- This file is generated by type_spec
