# DO NOT MODIFY -- This file is generated by type_spec
# ruff: noqa: E402 Q003
# fmt: off
# isort: skip_file
from __future__ import annotations
import typing  # noqa: F401
import datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
import dataclasses
from pkgs.serialization import serial_class
from pkgs.serialization import serial_alias_annotation
from . import base_t
from . import secret_retrieval_t

__all__: list[str] = [
    "Overrides",
    "SecretRetrievalOverride",
    "SecretRetrievalOverrides",
]


# DO NOT MODIFY -- This file is generated by type_spec
@serial_class(
    named_type_path="sdk.overrides.SecretRetrievalOverride",
)
@dataclasses.dataclass(slots=base_t.ENABLE_SLOTS, kw_only=True)  # type: ignore[literal-required]
class SecretRetrievalOverride:
    profile_name: str
    secret_retrieval: secret_retrieval_t.SecretRetrieval
    value: str


# DO NOT MODIFY -- This file is generated by type_spec
SecretRetrievalOverrides = typing.Annotated[
    list[SecretRetrievalOverride],
    serial_alias_annotation(
    named_type_path="sdk.overrides.SecretRetrievalOverrides",
    ),
]


# DO NOT MODIFY -- This file is generated by type_spec
@serial_class(
    named_type_path="sdk.overrides.Overrides",
)
@dataclasses.dataclass(slots=base_t.ENABLE_SLOTS, kw_only=True)  # type: ignore[literal-required]
class Overrides:
    secrets: SecretRetrievalOverrides
# DO NOT MODIFY -- This file is generated by type_spec
