from typing import Dict, Type, Union

from apmodel.types import ActivityPubModel

TYPE_MAPPING: Dict[str, Union[str, Type[ActivityPubModel]]] = {
    "https://www.w3.org/ns/activitystreams#Activity": "apmodel.core.activity.Activity",
    "https://www.w3.org/ns/activitystreams#IntransitiveActivity": "apmodel.core.activity.IntransitiveActivity",
    "https://www.w3.org/ns/activitystreams#Collection": "apmodel.core.collection.Collection",
    "https://www.w3.org/ns/activitystreams#CollectionPage": "apmodel.core.collection.CollectionPage",
    "https://www.w3.org/ns/activitystreams#OrderedCollection": "apmodel.core.collection.OrderedCollection",
    "https://www.w3.org/ns/activitystreams#OrderedCollectionPage": "apmodel.core.collection.OrderedCollectionPage",
    "https://www.w3.org/ns/activitystreams#Link": "apmodel.core.link.Link",
    "https://www.w3.org/ns/activitystreams#Object": "apmodel.core.object.Object",
    "http://joinmastodon.org/ns#Emoji": "apmodel.extra.emoji.Emoji",
    "https://www.w3.org/ns/activitystreams#Hashtag": "apmodel.extra.hashtag.Hashtag",
    "https://w3id.org/security#DataIntegrityProof": "apmodel.extra.cid.data_integrity_proof.DataIntegrityProof",
    "https://www.w3.org/ns/cid/v1#Multikey": "apmodel.extra.cid.multikey.Multikey",
    "https://w3id.org/security#Key": "apmodel.extra.security.cryptographickey.CryptographicKey",
    "https://www.w3.org/ns/activitystreams#Application": "apmodel.vocab.actor.Application",
    "https://www.w3.org/ns/activitystreams#Group": "apmodel.vocab.actor.Group",
    "https://www.w3.org/ns/activitystreams#Organization": "apmodel.vocab.actor.Organization",
    "https://www.w3.org/ns/activitystreams#Person": "apmodel.vocab.actor.Person",
    "https://www.w3.org/ns/activitystreams#Service": "apmodel.vocab.actor.Service",
    "https://www.w3.org/ns/activitystreams#Article": "apmodel.vocab.article.Article",
    "https://www.w3.org/ns/activitystreams#Document": "apmodel.vocab.document.Document",
    "https://www.w3.org/ns/activitystreams#Audio": "apmodel.vocab.document.Audio",
    "https://www.w3.org/ns/activitystreams#Image": "apmodel.vocab.document.Image",
    "https://www.w3.org/ns/activitystreams#Video": "apmodel.vocab.document.Video",
    "https://www.w3.org/ns/activitystreams#Page": "apmodel.vocab.document.Page",
    "https://www.w3.org/ns/activitystreams#Event": "apmodel.vocab.event.Event",
    "https://www.w3.org/ns/activitystreams#Place": "apmodel.vocab.event.Place",
    "https://www.w3.org/ns/activitystreams#Mention": "apmodel.vocab.mention.Mention",
    "https://www.w3.org/ns/activitystreams#Note": "apmodel.vocab.note.Note",
    "https://www.w3.org/ns/activitystreams#Profile": "apmodel.vocab.profile.Profile",
    "https://www.w3.org/ns/activitystreams#Tombstone": "apmodel.vocab.tombstone.Tombstone",
    "https://www.w3.org/ns/activitystreams#Accept": "apmodel.vocab.activity.accept.Accept",
    "https://www.w3.org/ns/activitystreams#TentativeAccept": "apmodel.vocab.activity.accept.TentativeAccept",
    "https://www.w3.org/ns/activitystreams#Add": "apmodel.vocab.activity.add.Add",
    "https://www.w3.org/ns/activitystreams#Announce": "apmodel.vocab.activity.announce.Announce",
    "https://www.w3.org/ns/activitystreams#Arrive": "apmodel.vocab.activity.arrive.Arrive",
    "https://www.w3.org/ns/activitystreams#Ignore": "apmodel.vocab.activity.ignore.Ignore",
    "https://www.w3.org/ns/activitystreams#Block": "apmodel.vocab.activity.block.Block",
    "https://www.w3.org/ns/activitystreams#Create": "apmodel.vocab.activity.create.Create",
    "https://www.w3.org/ns/activitystreams#Delete": "apmodel.vocab.activity.delete.Delete",
    "https://www.w3.org/ns/activitystreams#Dislike": "apmodel.vocab.activity.dislike.Dislike",
    "https://www.w3.org/ns/activitystreams#Flag": "apmodel.vocab.activity.flag.Flag",
    "https://www.w3.org/ns/activitystreams#Follow": "apmodel.vocab.activity.follow.Follow",
    "https://www.w3.org/ns/activitystreams#Offer": "apmodel.vocab.activity.offer.Offer",
    "https://www.w3.org/ns/activitystreams#Invite": "apmodel.vocab.activity.invite.Invite",
    "https://www.w3.org/ns/activitystreams#Join": "apmodel.vocab.activity.join.Join",
    "https://www.w3.org/ns/activitystreams#Leave": "apmodel.vocab.activity.leave.Leave",
    "https://www.w3.org/ns/activitystreams#Like": "apmodel.vocab.activity.like.Like",
    "https://www.w3.org/ns/activitystreams#Listen": "apmodel.vocab.activity.listen.Listen",
    "https://www.w3.org/ns/activitystreams#Move": "apmodel.vocab.activity.move.Move",
    "https://www.w3.org/ns/activitystreams#Question": "apmodel.vocab.activity.question.Question",
    "https://www.w3.org/ns/activitystreams#Read": "apmodel.vocab.activity.read.Read",
    "https://www.w3.org/ns/activitystreams#Reject": "apmodel.vocab.activity.reject.Reject",
    "https://www.w3.org/ns/activitystreams#TentativeReject": "apmodel.vocab.activity.reject.TentativeReject",
    "https://www.w3.org/ns/activitystreams#Remove": "apmodel.vocab.activity.remove.Remove",
    "https://www.w3.org/ns/activitystreams#Travel": "apmodel.vocab.activity.travel.Travel",
    "https://www.w3.org/ns/activitystreams#Undo": "apmodel.vocab.activity.undo.Undo",
    "https://www.w3.org/ns/activitystreams#Update": "apmodel.vocab.activity.update.Update",
    "https://www.w3.org/ns/activitystreams#View": "apmodel.vocab.activity.view.View",
    "http://litepub.social/ns#EmojiReact": "apmodel.extra.litepub.emoji_react.EmojiReact",
    "http://schema.org#PropertyValue": "apmodel.extra.schema.propertyvalue.PropertyValue",
}
