"""Shared types, enums, validators, and mixins for executor configurations."""

from .enums import (
    BodyType,
    CaptureMode,
    Combinator,
    ComparisonOperator,
    ConditionType,
    ExtractionMode,
    HtmlVariant,
    HttpMethod,
    LoopType,
    MCPProvider,
    ResponseFormat,
    SchemaFieldType,
    SearchProvider,
    SearchType,
    UserAgentMode,
    VariableType,
)
from .mixins import (
    OutputMixin,
    RetryMixin,
    TimeoutMixin,
    TimeoutRetryMixin,
)
from .types import (
    BingSearchConfig,
    ConditionDefinition,
    DuckDuckGoConfig,
    FormDataDefinition,
    GoogleSearchConfig,
    HeaderDefinition,
    SearchProviderConfig,
    SearchProviderDefinition,
    SearXNGConfig,
    SerpApiConfig,
    SerplyConfig,
    SimpleCondition,
    SwitchCase,
    TavilyConfig,
    VariableDefinition,
)
from .validators import (
    CommonValidators,
    FormKeyValidators,
    HeaderKeyValidators,
    validate_json_body,
)

__all__ = [
    # Enums
    "HttpMethod",
    "BodyType",
    "CaptureMode",
    "ResponseFormat",
    "ComparisonOperator",
    "ConditionType",
    "Combinator",
    "MCPProvider",
    "LoopType",
    "SearchProvider",
    "SearchType",
    "ExtractionMode",
    "HtmlVariant",
    "SchemaFieldType",
    "UserAgentMode",
    # Mixins
    "OutputMixin",
    "TimeoutMixin",
    "RetryMixin",
    "TimeoutRetryMixin",
    # Types
    "VariableDefinition",
    "HeaderDefinition",
    "FormDataDefinition",
    "SimpleCondition",
    "ConditionDefinition",
    "SwitchCase",
    "SearchProviderConfig",
    "GoogleSearchConfig",
    "BingSearchConfig",
    "SerpApiConfig",
    "SerplyConfig",
    "SearXNGConfig",
    "TavilyConfig",
    "DuckDuckGoConfig",
    "SearchProviderDefinition",
    # Validators
    "CommonValidators",
    "HeaderKeyValidators",
    "FormKeyValidators",
    "validate_json_body",
]
