# generated by datamodel-codegen:
#   filename:  core/primitive/array_of_3_numbers.json
#   version:   0.28.5

from __future__ import annotations

from typing import List

from pydantic import Field, RootModel


class ArrayOf3NumberElementsSchema(RootModel[List[float]]):
    root: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
