# DO NOT MODIFY -- This file is generated by type_spec
# ruff: noqa: E402 Q003
# fmt: off
# isort: skip_file
from __future__ import annotations
import typing  # noqa: F401
import datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
import dataclasses
from pkgs.serialization import serial_class
from ... import base_t

__all__: list[str] = [
    "Arguments",
    "ConditionParameterValueRecord",
    "ConditionRequest",
    "ConditionResponse",
    "Data",
    "ENDPOINT_METHOD",
    "ENDPOINT_PATH",
    "MAX_NUM_CONDITION_REQUESTS",
]

ENDPOINT_METHOD = "POST"
ENDPOINT_PATH = "api/external/outputs/external_resolve_output_conditions"


# DO NOT MODIFY -- This file is generated by type_spec
@serial_class(
    named_type_path="sdk.api.outputs.resolve_output_conditions.ConditionParameterValueRecord",
    to_string_values={"value_numeric"},
)
@dataclasses.dataclass(slots=base_t.ENABLE_SLOTS, kw_only=True)  # type: ignore[literal-required]
class ConditionParameterValueRecord:
    condition_parameter_id: base_t.ObjectId
    value_numeric: Decimal | None = None
    value_string: str | None = None


# DO NOT MODIFY -- This file is generated by type_spec
@serial_class(
    named_type_path="sdk.api.outputs.resolve_output_conditions.ConditionRequest",
)
@dataclasses.dataclass(slots=base_t.ENABLE_SLOTS, kw_only=True)  # type: ignore[literal-required]
class ConditionRequest:
    conditions: list[ConditionParameterValueRecord]


# DO NOT MODIFY -- This file is generated by type_spec
@serial_class(
    named_type_path="sdk.api.outputs.resolve_output_conditions.Arguments",
)
@dataclasses.dataclass(slots=base_t.ENABLE_SLOTS, kw_only=True)  # type: ignore[literal-required]
class Arguments:
    requested_conditions: list[ConditionRequest]


# DO NOT MODIFY -- This file is generated by type_spec
@serial_class(
    named_type_path="sdk.api.outputs.resolve_output_conditions.ConditionResponse",
)
@dataclasses.dataclass(slots=base_t.ENABLE_SLOTS, kw_only=True)  # type: ignore[literal-required]
class ConditionResponse:
    conditions: list[ConditionParameterValueRecord]
    output_condition_id: base_t.ObjectId


# DO NOT MODIFY -- This file is generated by type_spec
@serial_class(
    named_type_path="sdk.api.outputs.resolve_output_conditions.Data",
)
@dataclasses.dataclass(slots=base_t.ENABLE_SLOTS, kw_only=True)  # type: ignore[literal-required]
class Data:
    resolved_conditions: list[ConditionResponse]


# DO NOT MODIFY -- This file is generated by type_spec
MAX_NUM_CONDITION_REQUESTS = 100
# DO NOT MODIFY -- This file is generated by type_spec
