"""Gatsbie SDK - Official Python SDK for the Gatsbie Captcha API."""

from .client import Client
from .errors import (
    APIError,
    ERR_AUTH_FAILED,
    ERR_INSUFFICIENT_CREDITS,
    ERR_INTERNAL_ERROR,
    ERR_INVALID_REQUEST,
    ERR_SOLVE_FAILED,
    ERR_UPSTREAM_ERROR,
    GatsbieError,
    RequestError,
)
from .types import (
    AkamaiRequest,
    AkamaiSolution,
    CaptchaFoxCookies,
    CaptchaFoxRequest,
    CaptchaFoxSolution,
    CastleConfigJSON,
    CastleRequest,
    CastleSolution,
    CloudflareWAFRequest,
    CloudflareWAFSolution,
    DatadomeRequest,
    DatadomeSliderRequest,
    DatadomeSliderSolution,
    DatadomeSolution,
    ForterRequest,
    ForterSolution,
    FuncaptchaRequest,
    FuncaptchaSolution,
    HealthResponse,
    PerimeterXCookies,
    PerimeterXRequest,
    PerimeterXSolution,
    RecaptchaV3Request,
    RecaptchaV3Solution,
    Reese84Request,
    Reese84Solution,
    SBSDRequest,
    SBSDSolution,
    ShapeRequest,
    ShapeSolution,
    ShapeV2Request,
    ShapeV2Solution,
    SolveResponse,
    TurnstileRequest,
    TurnstileSolution,
    VercelRequest,
    VercelSolution,
)

__version__ = "1.0.3"

__all__ = [
    # Client
    "Client",
    # Errors
    "GatsbieError",
    "APIError",
    "RequestError",
    "ERR_AUTH_FAILED",
    "ERR_INSUFFICIENT_CREDITS",
    "ERR_INVALID_REQUEST",
    "ERR_UPSTREAM_ERROR",
    "ERR_SOLVE_FAILED",
    "ERR_INTERNAL_ERROR",
    # Types
    "HealthResponse",
    "SolveResponse",
    # Request types
    "DatadomeRequest",
    "RecaptchaV3Request",
    "AkamaiRequest",
    "VercelRequest",
    "ShapeRequest",
    "ShapeV2Request",
    "TurnstileRequest",
    "PerimeterXRequest",
    "CloudflareWAFRequest",
    "DatadomeSliderRequest",
    "CaptchaFoxRequest",
    "CastleConfigJSON",
    "CastleRequest",
    "Reese84Request",
    "ForterRequest",
    "FuncaptchaRequest",
    "SBSDRequest",
    # Solution types
    "DatadomeSolution",
    "RecaptchaV3Solution",
    "AkamaiSolution",
    "VercelSolution",
    "ShapeSolution",
    "ShapeV2Solution",
    "TurnstileSolution",
    "PerimeterXCookies",
    "PerimeterXSolution",
    "CloudflareWAFSolution",
    "DatadomeSliderSolution",
    "CaptchaFoxCookies",
    "CaptchaFoxSolution",
    "CastleSolution",
    "Reese84Solution",
    "ForterSolution",
    "FuncaptchaSolution",
    "SBSDSolution",
]
