# SoftFloatPy: A Python binding of Berkeley SoftFloat.
#
# Copyright (c) 2024-2025 Arihiro Yoshida. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from typing import Self
from enum import IntEnum, IntFlag


class TininessMode(IntEnum):
    BEFORE_ROUNDING = ...
    AFTER_ROUNDING = ...


class RoundingMode(IntEnum):
    NEAR_EVEN = ...
    MIN_MAG = ...
    MIN = ...
    MAX = ...
    NEAR_MAX_MAG = ...


class ExceptionFlag(IntFlag):
    INEXACT = ...
    UNDERFLOW = ...
    OVERFLOW = ...
    INFINITE = ...
    INVALID = ...


class UInt32:

    @classmethod
    def from_bytes(cls, src: bytes) -> UInt32: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_int(cls, src: int) -> UInt32: ...

    def to_int(self) -> int: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __invert__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lshift__(self, other: Self) -> Self: ...

    def __rshift__(self, other: Self) -> Self: ...

    def __and__(self, other: Self) -> Self: ...

    def __or__(self, other: Self) -> Self: ...

    def __xor__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...

    def __ilshift__(self, other: Self) -> Self: ...

    def __irshift__(self, other: Self) -> Self: ...

    def __iand__(self, other: Self) -> Self: ...

    def __ior__(self, other: Self) -> Self: ...

    def __ixor__(self, other: Self) -> Self: ...


class UInt64:

    @classmethod
    def from_bytes(cls, src: bytes) -> UInt64: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_int(cls, src: int) -> UInt64: ...

    def to_int(self) -> int: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __invert__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lshift__(self, other: Self) -> Self: ...

    def __rshift__(self, other: Self) -> Self: ...

    def __and__(self, other: Self) -> Self: ...

    def __or__(self, other: Self) -> Self: ...

    def __xor__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...

    def __ilshift__(self, other: Self) -> Self: ...

    def __irshift__(self, other: Self) -> Self: ...

    def __iand__(self, other: Self) -> Self: ...

    def __ior__(self, other: Self) -> Self: ...

    def __ixor__(self, other: Self) -> Self: ...


class Int32:

    @classmethod
    def from_bytes(cls, src: bytes) -> Int32: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_int(cls, src: int) -> Int32: ...

    def to_int(self) -> int: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __invert__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lshift__(self, other: Self) -> Self: ...

    def __rshift__(self, other: Self) -> Self: ...

    def __and__(self, other: Self) -> Self: ...

    def __or__(self, other: Self) -> Self: ...

    def __xor__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...

    def __ilshift__(self, other: Self) -> Self: ...

    def __irshift__(self, other: Self) -> Self: ...

    def __iand__(self, other: Self) -> Self: ...

    def __ior__(self, other: Self) -> Self: ...

    def __ixor__(self, other: Self) -> Self: ...


class Int64:

    @classmethod
    def from_bytes(cls, src: bytes) -> Int64: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_int(cls, src: int) -> Int64: ...

    def to_int(self) -> int: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __invert__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lshift__(self, other: Self) -> Self: ...

    def __rshift__(self, other: Self) -> Self: ...

    def __and__(self, other: Self) -> Self: ...

    def __or__(self, other: Self) -> Self: ...

    def __xor__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...

    def __ilshift__(self, other: Self) -> Self: ...

    def __irshift__(self, other: Self) -> Self: ...

    def __iand__(self, other: Self) -> Self: ...

    def __ior__(self, other: Self) -> Self: ...

    def __ixor__(self, other: Self) -> Self: ...


class BFloat16:

    @classmethod
    def from_bytes(cls, src: bytes) -> BFloat16: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_float(cls, src: float) -> BFloat16: ...

    def to_float(self) -> float: ...

    def __str__(self) -> str: ...


class Float16:

    @classmethod
    def from_bytes(cls, src: bytes) -> Float16: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_float(cls, src: float) -> Float16: ...

    def to_float(self) -> float: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __truediv__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __itruediv__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...


class Float32:

    @classmethod
    def from_bytes(cls, src: bytes) -> Float32: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_float(cls, src: float) -> Float32: ...

    def to_float(self) -> float: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __truediv__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __itruediv__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...


class Float64:

    @classmethod
    def from_bytes(cls, src: bytes) -> Float64: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_float(cls, src: float) -> Float64: ...

    def to_float(self) -> float: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __truediv__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __itruediv__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...


class Float128:

    @classmethod
    def from_bytes(cls, src: bytes) -> Float128: ...

    def to_bytes(self) -> bytes: ...

    @classmethod
    def from_float(cls, src: float) -> Float128: ...

    def to_float(self) -> float: ...

    def __str__(self) -> str: ...

    def __pos__(self) -> Self: ...

    def __neg__(self) -> Self: ...

    def __add__(self, other: Self) -> Self: ...

    def __sub__(self, other: Self) -> Self: ...

    def __mul__(self, other: Self) -> Self: ...

    def __truediv__(self, other: Self) -> Self: ...

    def __floordiv__(self, other: Self) -> Self: ...

    def __mod__(self, other: Self) -> Self: ...

    def __lt__(self, other: Self) -> bool: ...

    def __le__(self, other: Self) -> bool: ...

    def __gt__(self, other: Self) -> bool: ...

    def __ge__(self, other: Self) -> bool: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def __iadd__(self, other: Self) -> Self: ...

    def __isub__(self, other: Self) -> Self: ...

    def __imul__(self, other: Self) -> Self: ...

    def __itruediv__(self, other: Self) -> Self: ...

    def __ifloordiv__(self, other: Self) -> Self: ...

    def __imod__(self, other: Self) -> Self: ...


def set_tininess_mode(mode: TininessMode) -> None: ...

def get_tininess_mode() -> TininessMode: ...

def set_rounding_mode(mode: RoundingMode) -> None: ...

def get_rounding_mode() -> RoundingMode: ...

def set_exception_flags(flags: int) -> None: ...

def get_exception_flags() -> int: ...

def test_exception_flags(flags: int) -> bool: ...

def ui32_to_f16(x: UInt32) -> Float16: ...

def ui32_to_f32(x: UInt32) -> Float32: ...

def ui32_to_f64(x: UInt32) -> Float64: ...

def ui32_to_f128(x: UInt32) -> Float128: ...

def ui64_to_f16(x: UInt64) -> Float16: ...

def ui64_to_f32(x: UInt64) -> Float32: ...

def ui64_to_f64(x: UInt64) -> Float64: ...

def ui64_to_f128(x: UInt64) -> Float128: ...

def i32_to_f16(x: Int32) -> Float16: ...

def i32_to_f32(x: Int32) -> Float32: ...

def i32_to_f64(x: Int32) -> Float64: ...

def i32_to_f128(x: Int32) -> Float128: ...

def i64_to_f16(x: Int64) -> Float16: ...

def i64_to_f32(x: Int64) -> Float32: ...

def i64_to_f64(x: Int64) -> Float64: ...

def i64_to_f128(x: Int64) -> Float128: ...

def f16_to_ui32(
    x: Float16, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt32: ...

def f16_to_ui64(
    x: Float16, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt64: ...

def f16_to_i32(
    x: Float16, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int32: ...

def f16_to_i64(
    x: Float16, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int64: ...

def f16_to_f32(x: Float16) -> Float32: ...

def f16_to_f64(x: Float16) -> Float64: ...

def f16_to_f128(x: Float16) -> Float128: ...

def f16_round_to_int(
    x: Float16, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Float16: ...

def f16_add(x: Float16, y: Float16) -> Float16: ...

def f16_sub(x: Float16, y: Float16) -> Float16: ...

def f16_mul(x: Float16, y: Float16) -> Float16: ...

def f16_mul_add(x: Float16, y: Float16, z: Float16) -> Float16: ...

def f16_div(x: Float16, y: Float16) -> Float16: ...

def f16_rem(x: Float16, y: Float16) -> Float16: ...

def f16_sqrt(x: Float16) -> Float16: ...

def f16_eq(x: Float16, y: Float16) -> bool: ...

def f16_le(x: Float16, y: Float16) -> bool: ...

def f16_lt(x: Float16, y: Float16) -> bool: ...

def f16_eq_signaling(x: Float16, y: Float16) -> bool: ...

def f16_le_quiet(x: Float16, y: Float16) -> bool: ...

def f16_lt_quiet(x: Float16, y: Float16) -> bool: ...

def f16_is_signaling_nan(x: Float16) -> bool: ...

def bf16_to_f32(x: BFloat16) -> Float32: ...

def f32_to_bf16(x: Float32) -> BFloat16: ...

def bf16_is_signaling_nan(x: BFloat16) -> bool: ...

def f32_to_ui32(
    x: Float32, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt32: ...

def f32_to_ui64(
    x: Float32, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt64: ...

def f32_to_i32(
    x: Float32, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int32: ...

def f32_to_i64(
    x: Float32, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int64: ...

def f32_to_f16(x: Float32) -> Float16: ...

def f32_to_f64(x: Float32) -> Float64: ...

def f32_to_f128(x: Float32) -> Float128: ...

def f32_round_to_int(
    x: Float32, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Float32: ...

def f32_add(x: Float32, y: Float32) -> Float32: ...

def f32_sub(x: Float32, y: Float32) -> Float32: ...

def f32_mul(x: Float32, y: Float32) -> Float32: ...

def f32_mul_add(x: Float32, y: Float32, z: Float32) -> Float32: ...

def f32_div(x: Float32, y: Float32) -> Float32: ...

def f32_rem(x: Float32, y: Float32) -> Float32: ...

def f32_sqrt(x: Float32) -> Float32: ...

def f32_eq(x: Float32, y: Float32) -> bool: ...

def f32_le(x: Float32, y: Float32) -> bool: ...

def f32_lt(x: Float32, y: Float32) -> bool: ...

def f32_eq_signaling(x: Float32, y: Float32) -> bool: ...

def f32_le_quiet(x: Float32, y: Float32) -> bool: ...

def f32_lt_quiet(x: Float32, y: Float32) -> bool: ...

def f32_is_signaling_nan(x: Float32) -> bool: ...

def f64_to_ui32(
    x: Float64, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt32: ...

def f64_to_ui64(
    x: Float64, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt64: ...

def f64_to_i32(
    x: Float64, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int32: ...

def f64_to_i64(
    x: Float64, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int64: ...

def f64_to_f16(x: Float64) -> Float16: ...

def f64_to_f32(x: Float64) -> Float32: ...

def f64_to_f128(x: Float64) -> Float128: ...

def f64_round_to_int(
    x: Float64, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Float64: ...

def f64_add(x: Float64, y: Float64) -> Float64: ...

def f64_sub(x: Float64, y: Float64) -> Float64: ...

def f64_mul(x: Float64, y: Float64) -> Float64: ...

def f64_mul_add(x: Float64, y: Float64, z: Float64) -> Float64: ...

def f64_div(x: Float64, y: Float64) -> Float64: ...

def f64_rem(x: Float64, y: Float64) -> Float64: ...

def f64_sqrt(x: Float64) -> Float64: ...

def f64_eq(x: Float64, y: Float64) -> bool: ...

def f64_le(x: Float64, y: Float64) -> bool: ...

def f64_lt(x: Float64, y: Float64) -> bool: ...

def f64_eq_signaling(x: Float64, y: Float64) -> bool: ...

def f64_le_quiet(x: Float64, y: Float64) -> bool: ...

def f64_lt_quiet(x: Float64, y: Float64) -> bool: ...

def f64_is_signaling_nan(x: Float64) -> bool: ...

def f128_to_ui32(
    x: Float128, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt32: ...

def f128_to_ui64(
    x: Float128, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> UInt64: ...

def f128_to_i32(
    x: Float128, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int32: ...

def f128_to_i64(
    x: Float128, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Int64: ...

def f128_to_f16(x: Float128) -> Float16: ...

def f128_to_f32(x: Float128) -> Float32: ...

def f128_to_f64(x: Float128) -> Float64: ...

def f128_round_to_int(
    x: Float128, rounding_mode: RoundingMode = get_rounding_mode(), exact: bool = True
) -> Float128: ...

def f128_add(x: Float128, y: Float128) -> Float128: ...

def f128_sub(x: Float128, y: Float128) -> Float128: ...

def f128_mul(x: Float128, y: Float128) -> Float128: ...

def f128_mul_add(x: Float128, y: Float128, z: Float128) -> Float128: ...

def f128_div(x: Float128, y: Float128) -> Float128: ...

def f128_rem(x: Float128, y: Float128) -> Float128: ...

def f128_sqrt(x: Float128) -> Float128: ...

def f128_eq(x: Float128, y: Float128) -> bool: ...

def f128_le(x: Float128, y: Float128) -> bool: ...

def f128_lt(x: Float128, y: Float128) -> bool: ...

def f128_eq_signaling(x: Float128, y: Float128) -> bool: ...

def f128_le_quiet(x: Float128, y: Float128) -> bool: ...

def f128_lt_quiet(x: Float128, y: Float128) -> bool: ...

def f128_is_signaling_nan(x: Float128) -> bool: ...
