from enum import Enum


class ServiceType(str, Enum):
    TEXT_GEN = "TextGen"
    ACTION_INFERENCE = "ActionInference"
    SUMMARIZATION = "Summarization"
    TTS = "TextToSpeech"
    STT = "SpeechToText"
    AUDIO_INPUT = "AudioInput"
    AUDIO_OUTPUT = "AudioOutput"
    AUDIO_PIPELINE = "AudioPipeline"
    WAKE_WORD = "WakeWord"
    VISION_CAPTURE = "VisionCapture"
    COMPUTER_VISION = "ComputerVision"
    CHAT_AUGMENTATIONS = "ChatAugmentations"
    MEMORY = "Memory"
    IMAGE_GEN = "ImageGen"
    NONE = "None"


class EventType:
    # Server Messages (SignalR Invocation Target: ReceiveMessage)
    WELCOME = "welcome"
    CHAT_STARTED = "chatStarted"
    CHATS_SESSIONS_UPDATED = "chatsSessionsUpdated"
    MESSAGE = "message"
    UPDATE = "update"
    REPLY_GENERATING = "replyGenerating"
    REPLY_START = "replyStart"
    REPLY_CHUNK = "replyChunk"
    REPLY_END = "replyEnd"
    SPEECH_PLAYBACK_START = "speechPlaybackStart"
    SPEECH_PLAYBACK_COMPLETE = "speechPlaybackComplete"
    INTERRUPT_SPEECH = "interruptSpeech"
    ERROR = "error"
    ACTION = "action"
    CONTEXT_UPDATED = "contextUpdated"
    MEMORY_UPDATED = "memoryUpdated"
    APP_TRIGGER = "appTrigger"

    # New Server Messages
    AUTHENTICATION_REQUIRED = "authenticationRequired"
    CHAT_SESSION_ERROR = "chatSessionError"
    CHARACTERS_LIST_LOADED = "charactersListLoaded"
    SCENARIOS_LIST_LOADED = "scenariosListLoaded"
    CHATS_LIST_LOADED = "chatsListLoaded"
    CHAT_STARTING = "chatStarting"
    CHAT_LOADING = "chatLoading"
    CHAT_CLOSED = "chatClosed"
    CHAT_UPDATED = "chatUpdated"
    CHAT_PAUSED = "chatPaused"
    CHAT_FLOW = "chatFlow"
    CHAT_PARTICIPANTS_UPDATED = "chatParticipantsUpdated"
    REPLY_CANCELLED = "replyCancelled"
    SPEECH_RECOGNITION_START = "speechRecognitionStart"
    SPEECH_RECOGNITION_PARTIAL = "speechRecognitionPartial"
    SPEECH_RECOGNITION_END = "speechRecognitionEnd"
    RECORDING_REQUEST = "recordingRequest"
    RECORDING_STATUS = "recordingStatus"
    UPDATED = "updated"
    DOCUMENT_UPDATED = "documentUpdated"
    MODULE_RUNTIME_INSTANCES = "moduleRuntimeInstances"
    CONFIGURATION = "configuration"
    CHAT_CONFIGURATION = "chatConfiguration"
    SUGGESTIONS = "suggestions"
    USER_INTERACTION_REQUEST = "userInteractionRequest"
    CLOSE_USER_INTERACTION_REQUEST = "closeUserInteractionRequest"
    VISION_CAPTURE_REQUEST = "visionCaptureRequest"
    WAKE_WORD_STATUS = "wakeWordStatus"
    DOWNLOAD_PROGRESS = "downloadProgress"
    INSPECTOR = "inspector"
    INSPECTOR_ENABLED = "inspectorEnabled"
    INSPECTOR_ACTION_EXECUTED = "inspectorActionExecuted"
    INSPECTOR_SCRIPT_EXECUTED = "inspectorScriptExecuted"
    INSPECTOR_SCENARIO_EVENT_EXECUTED = "inspectorScenarioEventExecuted"
    LIST_RESOURCES_RESULT = "listResourcesResult"
    DEPLOY_RESOURCE_RESULT = "deployResourceResult"
    MISSING_RESOURCES_ERROR = "missingResourcesError"
    AUDIO_FRAME = "audioFrame"

    # Internal / Meta Events
    READY = "ready"
